### ISSUE TITLE
Personalization substitution and section tag is not working for version 5.3.0

### ISSUE THREAD

**Issue by thaodc** [sendgrid/sendgrid-php#1002]
### Issue Summary
Since 2018 I have one problem with Substitution `You are limited to 10,000 substitutions.`, I have already fixed it by combine with Section Tag together like this https://sendgrid.com/docs/API_Reference/SMTP_API/section_tags.html, And it worked fine until last week(21/08/2020).

Now it is not working and I don't know why. The email still was sent, but the content is not correct because it is not replace Substitutions on my email.

Email result look like:
```
Hi %FirstName% %LastName%,

Something here...
```

### Code Snippet
```php
# paste code here
    /**
     * @inheritDoc
     */
    public function send(RecipientEmail $to, SenderEmail $from, $subject, $body, array $variables = [])
    {
        $from = new Email($from->getFullName(), $from->getEmail());
        $to = new Email($to->getFullName(), $to->getEmail());

        $personalization = new Personalization();
        $personalization->addTo($to);

        $mail = new Mail();
        $mail->setFrom($from);
        $mail->setTemplateId($body);

        /**
         * When you have the $variables too big, SendGrid will reject the message because
         * SendGrid's Substitution is limited(10000 bytes)
         *
         * Before that, the format of substitution as below:
         *
         * {
         *    "to": [
         *       "example@example.com"
         *    ],
         *    "sub": {
         *       "%FirstName%": "This string maybe too long",
         *       "%LastName%": "This string maybe too long",
         *       ....
         *       ....
         *       more and limited
         *    }
         * }
         *
         * To resolved this problem we will use the Section with Substitution as below:
         *
         * {
         *    "to": [
         *       "example@example.com"
         *    ],
         *    "sub": {
         *       "%FirstName%": "%FirstName%",
         *       "%LastName%": "%LastName%",
         *       ....
         *       ....
         *       more and more
         *    },
         *    "section": {
         *       "%FirstName%": "This string maybe too long",
         *       "%LastName%": "This string maybe too long",
         *       ....
         *       ....
         *     }
         * }
         *
         * We will optimize the strings in Substitutions and let Section in SendGrid to contain that strings.
         */
        foreach ($variables as $variableName => $variableValue) {
            $personalization->addSubstitution('%' . $variableName . '%', '%' . $variableName . '%');

            $mail->addSection('%' . $variableName . '%', (string)$variableValue);
        }

        $mail->addPersonalization($personalization);

        return $this->sendRequest($mail);
    }
```

### Exception/Log
```
No error.
```

### Technical details:
* sendgrid-php version: 5.3.0
* php version: 7.1

**Comment by eshanholtz** [comment]
As seen at the top of the [documentation you linked](https://sendgrid.com/docs/API_Reference/SMTP_API/section_tags.html), section tags have been deprecated, you will have to migrate to transactional templates for similar functionality. Furthermore, substitutions cannot be used with transactional templates. Please see this [related issue](https://github.com/sendgrid/sendgrid-nodejs/issues/676) for some additional guidance on the proper usage.

**Comment by thaodc** [comment]
> As seen at the top of the [documentation you linked](https://sendgrid.com/docs/API_Reference/SMTP_API/section_tags.html), section tags have been deprecated, you will have to migrate to transactional templates for similar functionality. Furthermore, substitutions cannot be used with transactional templates. Please see this [related issue](https://github.com/sendgrid/sendgrid-nodejs/issues/676) for some additional guidance on the proper usage.

Why substitutions can not use with transaction template? exact is we can not use with dynamic transaction template, before that I still use it with section tag in Legacy Transaction Template.

Futhermore, if SendGrid is deprecated it then they should remove it completely, because some their customers might still not upgrade the package dependency to latest version.

**Comment by eshanholtz** [comment]
> Why substitutions can not use with transaction template?

Dynamic Transactional templates use [handlebar substitution](https://sendgrid.com/docs/for-developers/sending-email/using-handlebars/#personalizing-email-with-handlebars) to provide the data substitution. 
[The Section Tags capability was fully removed from the API on 07/30/2020](https://sendgrid.com/docs/for-developers/sending-email/section-tags/). We do not maintain or provide updates to older versions of our libraries. To get API updates and library improvements, we recommend upgrading to the latest version.
