### ISSUE TITLE
Hello I got error 406 Not Acceptable

### ISSUE THREAD

**Issue by jajamoks** [sendgrid/sendgrid-php#1003]
### Issue Summary
Im using the sendgrid for a years now and today I got error says '406 Not Acceptable'

### Code Snippet
```php

        $path = base_path('vendor/sendgrid-php/vendor/autoload.php');
        if(file_exists($path)){
            require $path;
        }

        $apiKey = getenv('SENDGRID_API_KEY');
        $sg = new \SendGrid($apiKey);

        $template_id = "d-0ec99b8ce8594dad8549244c7a6a7be5";

        try {
            $response = $sg->client->templates()->_($template_id)->get();

          $newGet = json_decode($response->body(), true);
          $bodyContent =  $newGet['versions'][0]['html_content'];

        } catch (Exception $e) {
 
            $bodyContent = "";
   
        }
```

**Comment by thinkingserious** [comment]
Hello @jajamoks,

This error occurs when you are [missing the `Accept` header](https://sendgrid.com/docs/API_Reference/Web_API_v3/How_To_Use_The_Web_API_v3/responses.html#-Status-Codes). 

Has anything changed with your server? Perhaps the header is getting over-written?

Could you please let us know what version of this helper library you are using?

With best regards,

Elmer

**Comment by rajatmasih-web4realty** [comment]
Hello,
I am using php CURL method to use sendgrid V3 api's.
Me also getting the same error but not all the time.
API : https://api.sendgrid.com/v3/user/webhooks/event/settings
I am sending these values in header.
`
"authorization: key",
"on-behalf-of: my-sub-username"
"content-type : application/json"
"accept : application/json"
`
And Some times i got the response and some time i just got the
HTML response : Not acceptable
Refer screen shot : https://prnt.sc/uiq6kq

Please help me in this

**Comment by eshanholtz** [comment]
@rajatmasih-web4realty 

Please reply with the version of the `sendgrid-php` helper library you are using so we can help you troubleshoot. Will you use our troubleshooting guide to help you [log the request body](https://github.com/sendgrid/sendgrid-php/blob/main/TROUBLESHOOTING.md#viewing-the-request-body) and [log the full SendGrid error output](https://github.com/sendgrid/sendgrid-php/blob/main/TROUBLESHOOTING.md#error-messages) and post both outputs here?

**Comment by rajatmasih-web4realty** [comment]
I am using PHP CURL method.And here is the response and Response Header info.

Response : https://prnt.sc/uiq6kq
Header : https://prnt.sc/uiq6yq

I am sending these values in header.
"authorization: key", "on-behalf-of: my-sub-username","content-type : application/json","accept : application/json"

**Comment by eshanholtz** [comment]
@rajatmasih-web4realty This GitHub page is intended to provide support for customers utilizing our `sendgrid-php` helper library. Since it does not appear you are using the helper library, I suggest you [reach out to support](https://support.sendgrid.com/hc/en-us) for further assistance.

**Comment by antoineazar** [comment]
I'm having the same issue. Using sendgrid php library through Google App Engine, getting the exact same response randomly, this is a stable codebase that has not changed in months.

**Comment by thinkingserious** [comment]
Hi @antoineazar,

This looks to be an issue not related to this helper library (assuming you have not made any updates/changes to the library), please reach out to our [support team](https://support.sendgrid.com/hc/en-us) for further assistance. Thanks!
