### ISSUE TITLE
include plugin as library to 3rd party plugin

### ISSUE THREAD

**Issue by loretoparisi** [sendgrid/sendgrid-php#1005]
### Issue Summary
When included `sendgrid-php` plugin within another plugin as a library, a `Cannot declare class` error comes out.

### Steps to Reproduce
1. Install the `sendgrid-php` plugin
2. Include the plugin in a new plugin folder and upload zip to WordPress

### Code Snippet
To avoid the error, I'm currently using this check:
```php
// include sendgrid sdk
if( class_exists('\\SendGrid\\Email') === false ) {
	// when used globally \\SendGrid\\Email
	// when importing with "use" Sendgrid
	require_once dirname(__FILE__) . "/sendgrid-php/sendgrid-php.php";
}
```

### Exception/Log
```
Fatal error: Cannot declare class SendGrid\Email, because the name is already in use in /home/loretoparisi/staging/3/wp-content/plugins/sendgrid-email-delivery-simplified/vendor/sendgrid-php/SendGrid/Email.php on line 5
There has been a critical error on your website. Please check your site admin email inbox for instructions.
```

### Technical details:
* sendgrid-php version:  1.11.8
* php version: 7.1

I have posted more details on SF [here](https://stackoverflow.com/questions/63858968/how-to-include-sendgrid-email-plugin-as-library-in-wordpress-avoiding-namespace).

**Comment by loretoparisi** [comment]
**[UPDATE]**
I have successfully renamed the `SendGrid` class and namespace to `SendGridSDK`, thus the "external" (i.e. directly installed from Wordpress) plugin works fine. The problem is the "internal" (ie. the one used as a library in my plugin) has an error, related to `Composer` I assume. Let's consider that I have already installed of `Composer` requirements locally, so my directory looks like:

```
.
├── lib
│   ├── SendGridSDK.php
│   └── helpers
│       └── mail
│           ├── Mail.php
│           └── README.md
├── sendgrid-php.php
└── vendor
    ├── autoload.php
    ├── bin
    ├── composer
    │   ├── ClassLoader.php
    │   ├── LICENSE
    │   ├── autoload_classmap.php
    │   ├── autoload_files.php
    │   ├── autoload_namespaces.php
    │   ├── autoload_psr4.php
    │   ├── autoload_real.php
    │   ├── autoload_static.php
    │   └── installed.json
    └── sendgrid
        └── php-http-client
            ├── CHANGELOG.md
            ├── CONTRIBUTING.md
            ├── LICENSE.txt
            ├── README.md
            ├── examples
            │   └── example.php
            └── lib
                ├── Client.php
                └── Response.php
```

The error is `Fatal error: Uncaught Error: Class 'SendGridSDK\Client' not found in` thrown in /home/loretoparisi/staging/2/wp-content/plugins/loretoparisi_admin/sendgrid-php/lib/SendGridSDK.php on line 53, where the `Client` is called:

```php
    $this->client = new \SendGridSDK\Client($host, $headers, '/v3', null, $curlOptions);
```

Since I have all files locally, why The AutoLoader cannot import the class `SendGridSDK\Client`?

**Comment by childish-sambino** [comment]
Recommend upgrading to a later, supported version of this library which may resolve the issue you're seeing. Latest is `7.8.3`.

**Comment by loretoparisi** [comment]
@childish-sambino thank you.
By the way, in the meantime I have fixed the old one just removing `Composer` and including libraries manually:


```bash
.
├── Wrapper
│   ├── Php.php
│   ├── Wordpress.php
│   └── WordpressCli.php
├── sendgrid-php
│   ├── lib
│   │   ├── Client.php
│   │   ├── Mail.php
│   │   ├── Response.php
│   │   └── SendGridSDK.php
│   └── sendgrid-php.php
├── test.php
```

where `sendgrid-php.php` looks like:

```php
<?php
require __DIR__ ."/lib/Client.php";
require __DIR__ ."/lib/Response.php";
require __DIR__ ."/lib/Mail.php";
require __DIR__ ."/lib/SendGridSDK.php";
?>
```
