### ISSUE TITLE
Bug fix for addTo() recipients with commas in their name

### ISSUE THREAD

**Issue by japhy-** [sendgrid/sendgrid-php#101]
sendgrid/vendor/sendgrid/smtpapi/lib/Smtpapi/Header.php

If there is a comma in the value of $name, addTo() will not escape or quote it, leading to a faulty To: header.

I recommend changing line 16 to:

$this->to[] = ($name ? '"' . preg_replace('{"}', '&amp;quot;', $name) . '" ' : $email);

**Comment by eddiezane** [comment]
Moved to https://github.com/sendgrid/smtpapi-php/issues/7
