### ISSUE TITLE
Can't send a campaign

### ISSUE THREAD

**Issue by quentint** [sendgrid/sendgrid-php#1016]
### Issue Summary
Sending a campaign using the "sendgrid/sendgrid ^7.8" PHP API.

### Steps to Reproduce
I tried lots of variations of API calls, including:
- `$sg->client->campaigns()->_($campaignId)->schedules()->post();`
- `$sg->client->marketing()->campaigns()->_($campaignId)->schedules()->now()->post();`

But none of them worked.

### Technical details:
* sendgrid-php version: 7.8.4
* php version: 7.3.23

Also: I noticed I can't use your docs because everything seems off (different method chaining, different parameters). Where can I find the proper docs (for ^7.8)?

Thanks in advance.

Note: I opened a support request on support.sendgrid.com (#5288817) but got no answer 🙁

**Comment by childish-sambino** [comment]
The first example was close, but it needs to include a time to send at value (UNIX timestamp for the date and time you would like your campaign to be sent out). E.g.,:
```
$sg->client->campaigns()->_($campaignId)->schedules()->post(['send_at' => 1489771528]);
```

Or just send _now_:
```
$sg->client->campaigns()->_($campaignId)->schedules()->now()->post();
```

**Comment by quentint** [comment]
Thanks @childish-sambino,
I've tried your second snippet (I'm trying to send *now*), but I get a 403 with `{"errors":[{"field":null,"message":"access forbidden"}]}`. All my other calls are OK (so I guess the API key is good).

The other places in my code where I successfully use the campaigns API is by using `$this->sg->client->marketing()->campaigns()->post($request)` (note the extra `->marketing()`).

Of course I tried `$this->sg->client->marketing()->campaigns()->_($campaignId)->schedules()->now()->post();` bot got a 404 🙁

Any idea? Could my API key (or account) be insufficient for sending/scheduling campaigns?

**Comment by childish-sambino** [comment]
Docs there may help: https://sendgrid.api-docs.io/v3.0/single-sends

Example:
```
$response = $sg->client->marketing()->singlesends()->_($campaignId)->schedule()->put(['send_at' => 'now']);
```

**Comment by quentint** [comment]
Wow, it works! Thanks very much!

I have two questions:
- (this one is for me) how come I didn't find that documentation link? I searched a lot and never stumbled upon it 🤔 
- my API sources do not list `schedule()` in its `@method` PHPDOC comments, so I never knew it existed. Is that something that requires a PR?

**Comment by childish-sambino** [comment]
* I frequently just google _"sendgrid api docs"_ and the API ref is near the top. Best one to use: https://sendgrid.com/docs/API_Reference/api_v3.html
* We have not sync'd the source yet with the latest API version. Not sure when we'll do that, but PRs are welcome in the meantime.
