### ISSUE TITLE
Missing function setToName

### ISSUE THREAD

**Issue by markengelhardt** [sendgrid/sendgrid-php#102]
Hello,

I can't see how to send a name along with the "to" email address, so it generates and email header like this:   

  To: 'Joe Cool' <joe@cool.com>

It seams like there should be a function called setToName which would be similar to setFromName

Am I missing something? Is there another way to do this?

Mark

**Comment by eddiezane** [comment]
Hi Mark,

Sorry for the delay on this. 

You can accomplish what you are looking for in the `addTo` method. It takes a second optional parameter for the 'to name'.

```php
$email = new SendGrid\Email();
$email->addTo('foo@bar.com', 'Mike Bar');
```
