### ISSUE TITLE
Recoverable fatal error: Object of class SendGrid\Mail\Mail could not be converted to string

### ISSUE THREAD

**Issue by burabil** [sendgrid/sendgrid-php#1020]
### Issue Summary
Just updated to the latest version of SendGrid to use apikey for authentication. Installed via the zip file provided using the link "latest packaged release of the library as a zip". When calling the code below via a webpage, I get the error below.

I googled this error but couldn't find anything similar.

### Code Snippet
```php

    require_once './sendgrid-php/sendgrid-php.php';

    $sendgrid = new \SendGrid("APIKEY-HERE");
    $email = new \SendGrid\Mail\Mail();
    $email->setFrom("myemail", "My Name");
    $email->setSubject($subject);
    $email->addTo($email, $email);
    $email->addContent("text/html", $message);
        
    try {
        $response = $sendgrid->send($email);
        print $response->statusCode() . "\n";
        print_r($response->headers());
        print $response->body() . "\n";
    } catch (Exception $e) {
        echo 'Caught exception: '.  $e->getMessage(). "\n";
    }
```

### Exception/Log
```
Recoverable fatal error: Object of class SendGrid\Mail\Mail could not be converted to string in sendgrid-php/lib/helper/Assert.php on line 28.

```

### Technical details

SendGrid version: 7.9.0

**Comment by eshanholtz** [comment]
Hey @burabil 

It appears you're incorrectly adding the data to your `\SendGrid\Mail\Mail()` object, specifically the line `$email->addTo($email, $email)`. That `addTo` function is [expecting either a `string` or a `To` object as the first argument](https://github.com/sendgrid/sendgrid-php/blob/main/lib/mail/Mail.php#L366), representing the desired email address, and a `string` for the second argument, representing the desired recipient's name. Note that your `$email` variable is of type `\Sendgrid\Mail\Mail`, which you are passing in for both arguments in that `addTo` function.

**Comment by burabil** [comment]
@eshanholtz Thank you for the feedback, Elise. This solved my problem.
