### ISSUE TITLE
Sending Mail from Godaddy PHP server returns HTTP ERROR 500

### ISSUE THREAD

**Issue by harshamv** [sendgrid/sendgrid-php#1024]
I am trying to integrate PHP for sending mail on my server. This is my code:

    <?php
    
    require("sendgrid-php/sendgrid-php.php");
    
    $email = new \SendGrid\Mail\Mail();
    $email->setFrom("support@exmaple.com", "SSupport");
    $email->setSubject("Sending with SendGrid is Fun");
    $email->addTo("harsha@example.com", "Harsha MV");
    
    $email->addContent(
        "text/plain", "and easy to do anywhere, even with PHP"
    );
    
    $email->addContent(
        "text/html", "<strong>and easy to do anywhere, even with PHP</strong>"
    );
    
    $sendgrid = new \SendGrid("SG.mTUjeGGYTsu9FB_bw#####q9nw.nR%%%%%%%%%%%%Kmm7pylP_xTrac$$$$$ElpN4");
    try {
        $response = $sendgrid->send($email);
        print $response->statusCode() . "\n";
        print_r($response->headers());
        print $response->body() . "\n";
    } catch (Exception $e) {
        echo 'Caught exception: ',  $e->getMessage(), "\n";
    }
    
    ?>

Error:

> Its returning 500 Server Error.

**Comment by redbrad0** [comment]
I am having the same problem which the error is Class 'SendGrid' not found. The problem is in one of the downloads the "vendor" directory was not found. I uploaded this director and the script ran.

![image](https://user-images.githubusercontent.com/2215598/100785504-5959b000-33d6-11eb-911e-d6ec4e8e6b40.png)

**Comment by JenniferMah** [comment]
Could you provide some more details like which version of the library you are using and which version of php you are running?
