### ISSUE TITLE
Adding authorization header to PHP file v2 Mailsend 

### ISSUE THREAD

**Issue by 1stnamewalker** [sendgrid/sendgrid-php#1027]
### Issue Summary
When replacing basic authentication with API key, it's resulting in a "Bad username/ password error". Unable to successfully add authorization header to PHP file (per support ticket 5279587) and require help configuring. See below code snippet currently used. Thank you.

### Steps to Reproduce
1. Updated user / password with API credentials
2. Resulted in Bad Username / Password

### Code Snippet
        $user='XXXX'; //sendgrid user
	$pass='XXXX'; //sendgrid password

	$url="https://api.sendgrid.com/api/mail.send.json";

	$subject=urlencode($subject);
	$body=urlencode($body);
	
	$tos=vmail_mailparts($to);
	$to=$tos['email'];
	$toname=urlencode($tos['name']);
	
	$froms=vmail_mailparts($from);
	$from=$froms['email'];
	$fromname=$froms['name'];

	$data="api_user=$user&api_key=$pass&to=$to&subject=$subject&html=$body&from=$from";
	
	if ($returnpath!='') $data.="&replyto=$returnpath";
	if ($toname!='') $data.="&toname=$toname";
	if ($fromname!='') $data.="&fromname=$fromname";

	$curl=curl_init($url);
	curl_setopt($curl,CURLOPT_RETURNTRANSFER,1);
	curl_setopt($curl,CURLOPT_SSL_VERIFYHOST,0);
	curl_setopt($curl,CURLOPT_SSL_VERIFYPEER,0);
	curl_setopt($curl,CURLOPT_POST,1);
	curl_setopt($curl,CURLOPT_POSTFIELDS,$data);
	$res=curl_exec($curl);

	$obj=json_decode($res,1);

	return $obj['message'];

### Technical details:
* sendgrid-php version: v2 mailsend
* php version:

**Comment by thinkingserious** [comment]
Hello @1stnamewalker,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by 1stnamewalker** [comment]
@thinkingserious I did reach out to support and they directed me here — can you please assist?
