### ISSUE TITLE
Since upgrading to v3 & using API can no longer send with 50+ BCC recipients

### ISSUE THREAD

**Issue by jiska78** [sendgrid/sendgrid-php#1029]
Everything has worked fine for years. After upgrading to V3 with API key I just can't get the code working. Below, "I am starting" gets echoed out to the screen and then the first 56 email addresses of 280 odd then nothing - it's as if the code breaks and the page stops.

If I comment out the line $email->addBcc($emailaddy->email); then I get all 280 odd email addresses on the screen and it echos "I made it" on to the screen, so it looks like the SendGrid option bombs out after 56 email addresses. Additionally, if I change the SQL query to only produce 10 email addresses, everything works fine as well

### Code Snippet
```php
    $email = new \SendGrid\Mail\Mail();

    $email->addTo($toemail, $fromname);

    $email->setFrom($fromemail, $fromname);

    $email->setSubject($subject);

    $email->addContent('text/plain','Your browser does not support HTML E-Mails.');

    $email->addContent("text/html", $body);


    if ($filename != "") {

      $file_encoded = base64_encode(file_get_contents($filename));

      $email->addAttachment(

          $file_encoded,

          "application/octet-stream",

          basename($filename),

          "attachment"

      );

    }                        

    
    echo "I'm starting"

    $qid = db_query($sql);          

    while ($emailaddy = db_fetch_object($qid)) {

      echo $emailaddy->email;

      $email->addBcc($emailaddy->email);

    }                                         

    $sendgrid = new \SendGrid(<API KEY>);

    echo "I made it";

    die;

    try {
        $response = $sendgrid->send($email);
        print $response->statusCode() . "\n";
        print_r($response->headers());
        print $response->body() . "\n";
    } catch (Exception $e) {
        echo 'Caught exception: '.  $e->getMessage(). "\n";
    }     

```

I've even tried creating a personalization, and the same issue occurs.

```php
    $personalization0 = new Personalization();
    $qid = db_query($sql);          
    while ($emailaddy = db_fetch_object($qid)) {
      $personalization0->addBcc(new Bcc($emailaddy->email));
    }    
    $mail->addPersonalization($personalization0);    
```

**Comment by shwetha-manvinkurke** [comment]
Hi @jiska78, 

Thank you for reporting the issue! 

Would you be able to add some exception handling/logging to your code to get more clarity on what's going on after sending your 56 emails and report back your findings here?

Thanks,
Shwetha

**Comment by jiska78** [comment]
> 
> 
> Hi @jiska78,
> 
> Thank you for reporting the issue!
> 
> Would you be able to add some exception handling/logging to your code to get more clarity on what's going on after sending your 56 emails and report back your findings here?
> 
> Thanks,
> Shwetha

I can't - it never gets to the point of sending the email. As per the code above it flakes out in the middle of this loop

```
 while ($emailaddy = db_fetch_object($qid)) {

      echo $emailaddy->email;

      **$email->addBcc($emailaddy->email);**

    }            
```

**Comment by jiska78** [comment]
Please help.

Since upgrading to V3 it has broken my website.

**Comment by shwetha-manvinkurke** [comment]
Hmm, I tried reproducing this issue by sending 116 emails each with a bcc but I did not see the same issue that you did. Are the `bcc` addresses different from the `to` and `from` address in each case?

**Comment by jiska78** [comment]
Yes the email addresses are different.

The code is not trying to send 116 emails. It is trying to send one email with 300 BCC recipients attached.

Is there a verbose logging I can enable with Sendgrid to see what is happening.

**Comment by jiska78** [comment]
I feel a little embarrassed now. My post made me think perhaps I should turn PHP verbose logging on, and then the error showed.

[25-Jan-2021 09:20:04] PHP Fatal error:  Uncaught SendGrid\Mail\TypeException: "$emailAddress" must be a valid email address. Got: *****@hotmail.com  in ....../sendgrid-php/lib/helper/Assert.php:61
Stack trace:

It seems that the email address had a blank space at the end of the address. I assume v2 of Sendgrid ignored this and just worked but v3 of Sendgrid is more literal. Once running a TRIM on the field in SQL, everything is working again.

Thanks for your help
