### ISSUE TITLE
Inline CID Images

### ISSUE THREAD

**Issue by matreltub** [sendgrid/sendgrid-php#103]
Hi,

Could you provide the ability to send inline CID images.

Thanks

M

**Comment by kunal732** [comment]
You can tag files for use as inline HTML content. It will mark the file for inline disposition using the specified "cid".

```php
$email = new SendGrid\Email();
$email->addTo('foo@bar.com')
      ->setHtml('<div>Our logo:<img src="cid:file-cid"></div>')
      ->addAttachment("../path/to/file.txt", "super_file.txt", "file-cid");
```
