### ISSUE TITLE
Can I send custom arguments with the singlesend API?

### ISSUE THREAD

**Issue by centurianii** [sendgrid/sendgrid-php#1033]
### Issue Summary
Hi, I'm sending to a list with members that have custom fields.
When I use a webhook to examine the events I don't see anything about member's custom fields.
Is this behavior implemented or looking in vain?

### Steps to Reproduce
Single send endpoint is described [there](https://sendgrid.api-docs.io/v3.0/single-sends/create-single-send).
I use php-curl and my own library (most connection with v3 API is implemented already) as I want to create a common interface with other APIs.

### Code Snippet
One of the events I receive.
```php
(
    [0] => Array
        (
            [asm_group_id] => 15836
            [category] => Array
                (
                    [0] => newsletter
                    [1] => issue 1
                    [2] => 2020
                )

            [email] => xxxxxxxxx@yahoo.co.uk
            [event] => open
            [ip] => 212.82.108.34
            [mc_stats] => singlesend
            [phase_id] => send
            [send_at] => 1612870575
            [sg_content_type] => html
            [sg_event_id] => 9oxFgxqRSgy342JPEsogSg
            [sg_message_id] => IzK6C2A_QB276G6kjc9LlA.filterdrecv-p3iad2-558d65d586-6r2qt-18-602273ED-1D.1
            [sg_template_id] => d-2f7b3de9b8ab42c0bd9dd41c0685bad5
            [sg_template_name] => 77d144ba-43ff-452d-9570-22fcc015868a
            [singlesend_id] => 03ffa8c4-6acb-11eb-8bd5-165a1a07e88a
            [singlesend_name] => 2021-02-09 11:36:05 GMT
            [template_hash] => 5d11418bab3ba9921036282b805b1fee0d2e8726330ecf740ad31b837622904c
            [template_id] => d-2f7b3de9b8ab42c0bd9dd41c0685bad5
            [template_version_id] => a90c0f4e-49c5-4f1a-a26b-11a306446be1
            [timestamp] => 1612870846
            [useragent] => YahooMailProxy; https://help.yahoo.com/kb/yahoo-mail-proxy-SLN28749.html
        )

)
```

### Technical details:
* sendgrid-php version: my own with php-curl
* php version: 7

**Comment by thinkingserious** [comment]
Hello @centurianii,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
