### ISSUE TITLE
How to get sender id 

### ISSUE THREAD

**Issue by hiteshSonagra** [sendgrid/sendgrid-php#1036]
### Issue Summary
I am registering sender using below API

$sg->client->senders()->post($request_body); 

Its response me 400"  statusCode":protected]=> int(400) ["body":protected]=> string(105) "{"errors":[{"message":"You already have a sender identity with the same nickname.","field":"nickname"}]}

Now I want that user sender id
I used the below API but getting an empty response.

https://api.sendgrid.com/v3/senders

I know I have senders but still getting an empty responses.

### Technical details:
* sendgrid-php version: V3
* php version: 7

**Comment by shwetha-manvinkurke** [comment]
Have you addressed this issue you see?
`You already have a sender identity with the same nickname`

Also, have you tried doing the api call without using the helper library?

**Comment by hiteshSonagra** [comment]
how can I get the sender id from SendGrid if the sender already registers?

**Comment by thinkingserious** [comment]
Hello @hiteshSonagra,

I believe [this API call](https://sendgrid.api-docs.io/v3.0/sender-identities-api/get-all-sender-identities) might be what you need.

With best regards,

Elmer
