### ISSUE TITLE
Querying endpoints that require an ID using fluent interface

### ISSUE THREAD

**Issue by callum-ez** [sendgrid/sendgrid-php#1037]
This is quite a simple question but I couldn't see it mentioned in the docs and playing around in the code to find something hasn't proven successful. Is it possible to make a request to e.g. the "/asm/groups/{group_id}/suppressions" endpoint using the fluent interface? Or for such endpoints are we forced to use the classical interface?

**Comment by thinkingserious** [comment]
Hello @callum-ez,

Yes you can :) Please see the documentation [here](https://github.com/sendgrid/sendgrid-php/blob/main/USAGE.md#post-asmgroupsgroup_idsuppressions). Thank you!

With best regards,

Elmer
