### ISSUE TITLE
I don't receive my email subject when sending email using dynamic template data

### ISSUE THREAD

**Issue by cindyadonia** [sendgrid/sendgrid-php#1039]
### Issue Summary
I'm trying to send email with dynamic template data, and It works fine, I can receive my email. 
But, I don't see the email subject that I have set.

I'm developing this with Laravel 7
### Here is how I send the email
```
$email = new \SendGrid\Mail\Mail(); 
$email->setFrom(env('MAIL_FROM_ADDRESS'), env('MAIL_FROM_NAME'));
$email->setSubject($subject);
$email->setTemplateId($templateId);
$email->addDynamicTemplateDatas($data);
$email->addTo("someone_email@email.com");

$sendgrid = new \SendGrid(env('MAIL_PASSWORD'));
$response = $sendgrid->send($email);
```
I tried to dump the data : ```dd($email);```
And this is what I got
![image](https://user-images.githubusercontent.com/48086081/111431097-ea5a5a00-872d-11eb-925d-7b06bf4eeda1.png)

Can someone tell me, what went wrong? Because this is only happened when I try to send the mail using the dynamic template 
### Technical details:
* sendgrid-php version: 7.9
* php version: 7.4.8

**Comment by shwetha-manvinkurke** [comment]
@cindyadonia Have you actually set the subject in your template?

![image](https://user-images.githubusercontent.com/6811347/111695951-e4797d00-87f0-11eb-8807-24e571164c63.png)

**Comment by cindyadonia** [comment]
> @cindyadonia Have you actually set the subject in your template?
> 
> ![image](https://user-images.githubusercontent.com/6811347/111695951-e4797d00-87f0-11eb-8807-24e571164c63.png)

Hello,
No I didn't, because I want to set my subject dynamically from the server.

I managed to solve my problem by sending the subject into the `dynamicTemplateData` array as suggested on this [disccussion](https://github.com/sendgrid/sendgrid-nodejs/issues/843#issue-378166341)

Looks like SendGrid it self hasn't mention anything about this problem until today, because I cannot find any documentation saying that we have to send the subject into the `dynamicTemplateData` (if you are using dynamic template to send the mail)
