### ISSUE TITLE
Unable to get campaign stat by id API

### ISSUE THREAD

**Issue by stvfactory** [sendgrid/sendgrid-php#1048]
https://sendgrid.api-docs.io/v3.0/marketing-campaigns-stats/get-singlesend-stat

I am trying to get marketing campaign stats from a singlesend id using the API v3 but only get a 404 status.

I tried to get all marketing campaign stats using the API v3 and it works fine.

Am I missing something ?

### Code Snippet
```php
$sg = new SendGrid("ThisIsMyApiKey");

$all = $sg->client->marketing()->stats()->singlesends()->get();

$single = $sg->client->marketing()->stats()->singlesends()->_("ThisIsMySingleSendId")->get();
```

### Exception/Log
```
$all = ["results"];

$single = Return HTTP/1.1 404 Not Found
```

### Technical details:
"name": "sendgrid/php-http-client",
"version": "3.13.0",

"name": "sendgrid/sendgrid",
"version": "7.9.1"

PHP 7.3.12

**Comment by eshanholtz** [comment]
I'm not seeing anything in your code that looks incorrect. You're seeing the ID you're passing to the second function call in the results from the first?

**Comment by stvfactory** [comment]
Yes, the $all do give me all the results, included the one I'm looking for in the $single call.
Actually, because of the 404, I have to call the all stats campaigns and parse it to filter out the stats I need by matching the stats id with the singlesend_id I use in the single call.
Not actually the best way but still working...

**Comment by thinkingserious** [comment]
Hello @stvfactory,

What happens if you run the second call here: https://sendgrid.api-docs.io/v3.0/marketing-campaigns-stats/get-singlesend-stat (on the "Try it out" tab)?

Thanks!

With best regards,

Elmer

**Comment by stvfactory** [comment]
Hello @thinkingserious !

I have filled the "Try it out" tab with my API Key and my single send ID but every time I send the request, it returns me results which aren't mine.
By the way, even without filling anything, the send request returns something.

I have tried to use call the api only using curl example provided

```
$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => "https://api.sendgrid.com/v3/marketing/stats/singlesends/SINGLESEND_ID?page_size=50&timezone=UTC&aggregated_by=total",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "GET",
  CURLOPT_POSTFIELDS => "{}",
  CURLOPT_HTTPHEADER => array(
    "authorization: Bearer <<API_KEY>>"
  ),
));

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
  echo "cURL Error #:" . $err;
} else {
  echo $response;
}
```

And it returns me this :

```
{"errors":[{"field":null,"message":"unauthorized"}]}
```

I tried to get all stats (as it was working with the SendGrid client) but it returns an unathorized message too.

**Comment by shwetha-manvinkurke** [comment]
@stvfactory I recommend you reach out to support as this points to an access issue.

**Comment by stvfactory** [comment]
Thank you for your help.
As strange as it is, this error must have been corrected because it works fine now (no change of code on my side).
