### ISSUE TITLE
SendGrid test send mail => "errors":[{"message":"Permission denied, wrong credentials","field":null,"help":null

### ISSUE THREAD

**Issue by PyroxFyre** [sendgrid/sendgrid-php#1052]
I'm trying to send an email with the test code given in this doc, but when I run it, I got this error : 

![SendGrid_Issue](https://user-images.githubusercontent.com/58972345/127452701-5eea15fc-671a-40b4-b532-2943034d5b38.png)

And here is my code in test.php

### Code Snippet
```php
<?php

use SendGrid\Mail\Mail;

require 'vendor/autoload.php';

$email = new Mail();
$email->setFrom("test@example.com", "Example User");
$email->setSubject("Sending with Twilio SendGrid is Fun");
$email->addTo("test@example.com", "Example User");
$email->addContent("text/plain", "and easy to do anywhere, even with PHP");
$email->addContent(
    "text/html", "<strong>and easy to do anywhere, even with PHP</strong>"
);

$file_encoded = base64_encode(file_get_contents('my_file.txt'));
$email->addAttachment(
    $file_encoded,
    "application/text",
    "my_file.txt",
    "attachment"
);

$sendgrid = new SendGrid(getenv('SENDGRID_API_KEY'));
try {
    $response = $sendgrid->send($email);
    print $response->statusCode() . "\n";
    print_r($response->headers());
    print $response->body() . "\n";
} catch (Exception $e) {
    echo 'Caught exception: '.  $e->getMessage(). "\n";
}
```

**Comment by JenniferMah** [comment]
Hi @PyroxFyre! This looks like a problem with your API key. Did you set up an [environment variable](https://github.com/sendgrid/sendgrid-php#setup-environment-variables) named `SENDGRID_API_KEY` with the value of your Sendgrid API key?

**Comment by PyroxFyre** [comment]
Hi, I finally get the problem in the evening, it's look like the file I've created is at the root of the project I'm working on, but the .env file was not loading at the root, so I'd to write API Key in this file, but I got another error, and after searching for a resolve, I found that the key I'm using is not the API Key, but the API Key ID, so it may be the reason of this error. I'll check this morning if I'm right, then I'll update or close this issue whatever happen ^^

**Comment by JenniferMah** [comment]
Hi @PyroxFyre!
Thanks for the update. Please reach out to [support](https://support.sendgrid.com/hc/en-us) if you need more help debugging your API key.
