### ISSUE TITLE
How to specify a custom sender?

### ISSUE THREAD

**Issue by cod3rshotout** [sendgrid/sendgrid-php#1058]
I'm using the `$email->setFrom('no-reply@example.com');` method and it's working fine for email delivered to the registered sender. However, the email is delivered as `no-reply@example.com`.  
How can I include the email of the customer that has filled the form? Eh: `mario@gmail.com`?

If I replace `$email->setFrom('mario@gmail.com');` I will get 403. Is there a way to use setaFrom using a custom email?

**Comment by JenniferMah** [comment]
Hi @cod3rshotout! Have you gone through the [sender verification](https://docs.sendgrid.com/ui/sending-email/sender-verification) process?

**Comment by cod3rshotout** [comment]
Solution:

    $email->setReplyTo("mario@gmail.com");
