### ISSUE TITLE
charset issue, emails displayed in Chinese for some recipients

### ISSUE THREAD

**Issue by SteveJay7** [sendgrid/sendgrid-php#1059]
### Issue Summary
We are sending emails using the PHP API this way:

```php
$email = new \SendGrid\Mail\Mail(); 
$email->setFrom($emailFiliale, $absender);
$email->setSubject("Rechnung ".$rechnungNummerText);
$email->addTo($toEmails[0]);
$email->addContent("text/html", $bodyHtml);
$email->addAttachment(base64_encode($pdf), "application/pdf", $rechnungNummerText.".pdf", "attachment");
$sendgrid = new \SendGrid($sendgridMasterKey);
```

Everything works fine but we just got reports from clients opening the email in their iphone mail app that they see only a block of Chinese characters.

![image](https://user-images.githubusercontent.com/30262418/135644420-532726c5-3bf4-4974-88b2-9412fbe33663.png)

I tried to add a charset to the addContent method like "text/html; charset=utf-8" instead of "text/html" but your API doesn't accept that.

Is there any other way to pass the charset or solve this issue?

### Technical details:
* sendgrid-php version: 7.2.1
* php version: 7.4.3

**Comment by SteveJay7** [comment]
any news on this issue?
I think if the addContent method would accept the charset like "text/html; charset=utf-8" and you would pass it to the emails source it would solve the issue. can you please implement that?

Thanks,
Stefan

**Comment by beebzz** [comment]
Hi @SteveJay7! Per [this issue's](https://github.com/sendgrid/sendgrid-php/issues/826) response [here](https://github.com/sendgrid/sendgrid-php/issues/826#issuecomment-484598550), this is a limitation of the API. Feel free to contact [SendGrid customer support](https://support.sendgrid.com/hc/en-us) to raise visibility.
