### ISSUE TITLE
Subscribe to email notifications link broken/dx.sendgrid.com not working

### ISSUE THREAD

**Issue by mbtreetime** [sendgrid/sendgrid-php#1078]
### Issue Summary
The link and the entire dx.sendgrid.com domain just give Heroku error pages

https://github.com/sendgrid/sendgrid-php/blob/main/README.md?plain=1#L15

- Subscribe to email [notifications](https://dx.sendgrid.com/newsletter/php) for releases and breaking changes.

https://dx.sendgrid.com/newsletter/php

second example:
https://dx.sendgrid.com/newsletter/nodejs

![image](https://user-images.githubusercontent.com/90357002/152010089-8cf7500c-941f-48d7-be7d-24296f89c8fe.png)

**Comment by JenniferMah** [comment]
Hi @mbtreetime! Thanks for bringing this to our attention. I've gone ahead and updated the `read.me` to remove these links. We no longer run that Heroku application. As an alternative you can use the `watch` feature on this Github repo to get notified when there is a new release. Click on the watch button in the upper right hand corner, select custom, and select releases. More information for how to setup Github notifications can be found [here](https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications#configuring-your-watch-settings-for-an-individual-repository).
