### ISSUE TITLE
ensure sendgrid-php does not use sslv3

### ISSUE THREAD

**Issue by nquinlan** [sendgrid/sendgrid-php#111]
PHP automatically tries to use SSLv3 when connecting to SendGrid however that no longer works as we disabled support for SSLv3 due to [POODLE](http://en.wikipedia.org/wiki/POODLE) this can result is failures. We should ensure we don't try to use SSLv3 with this lib.

**Comment by eddiezane** [comment]
We do not support sslv3 on the API anymore, so this should no longer be an issue.
