### ISSUE TITLE
Uncaught exception 'Exception' with message 'SSL certificate problem: self signed certificate in certificate chain'  

### ISSUE THREAD

**Issue by sgentile** [sendgrid/sendgrid-php#112]
Getting this error  - any ideas?

Fatal error: Uncaught exception 'Exception' with message 'SSL certificate problem: self signed certificate in certificate chain' in D:\home\site\wwwroot\sendgrid-php\vendor\mashape\unirest-php\lib\Unirest\Unirest.php:219
Stack trace:
#0 D:\home\site\wwwroot\sendgrid-php\vendor\mashape\unirest-php\lib\Unirest\Unirest.php(74): Unirest::request('POST', 'https://api.sen...', Array, Array, NULL, NULL)
#1 D:\home\site\wwwroot\sendgrid-php\lib\SendGrid.php(45): Unirest::post('https://api.sen...', Array, Array)
#2 D:\home\site\wwwroot\contact.php(99): SendGrid->send(Object(SendGrid\Email))
#3 {main}
  thrown in D:\home\site\wwwroot\sendgrid-php\vendor\mashape\unirest-php\lib\Unirest\Unirest.php on line 219

**Comment by blade93ny** [comment]
change your params during SendGrid instantiation to something like this:

***$sendgrid = new SendGrid($sendgrid_username, $sendgrid_password, array("turn_off_ssl_verification" => true));

**Comment by eddiezane** [comment]
I just released a new version of the library that removed unirest and used native cURL. Please let me know if this issue continues to pop up. Also, please post what version of PHP you are running.

**Comment by blade93ny** [comment]
the SSL issue resurfaced:
Uncaught exception 'Exception' with message 'SSL certificate problem: self signed certificate in certificate chain'
---
im specifying in the options array to turn off ssl verification --- array('turn_off_ssl_verification' => true, /*'protocol' => 'http'*/)
---
Any suggestions?

**Comment by eddiezane** [comment]
@blade93ny what version of PHP are you on?

**Comment by blade93ny** [comment]
5.5.15

**Comment by eddiezane** [comment]
@blade93ny the call would indeed be

```php
$sendgrid = new SendGrid('foo', 'bar', array('turn_off_ssl_verification' => true));
```

This is definitely not recommended though as you are vulnerable to a MITM attack.

Are you on Windows? Which version? What version of cURL? Can you update PHP if possible? Do you have any OS updates available?

What I think is happening is that you have an old cert somewhere in your chain. Can you please check this out? http://php.net/manual/en/function.curl-setopt.php#110457

**Comment by blade93ny** [comment]
Im testing this locally...
Im on Win7x64 using XAMPP...
Not using any certificates...
