### ISSUE TITLE
Failure detection

### ISSUE THREAD

**Issue by ilithium** [sendgrid/sendgrid-php#115]
When I use the library, I've found that there's no clear way to detect a failure - specifically, when an email isn't sent through the API. Looking through the source code tells me that the send() method only returns the message body.

Is there a way to retrieve a response code/status via this package and the API, in the same way as SMTP returns a message ID?

Actually - if there's a way to retrieve the message ID, that'd be great!

**Comment by kunal732** [comment]
@ilithium this is something we're working on 346c90ab856214fcd5f939483065de8a7457dc4e , its on the v3.0 branch.
