### ISSUE TITLE
method getTos() is deprecated

### ISSUE THREAD

**Issue by ocesaroliveira** [sendgrid/sendgrid-php#118]
Hello devs, we are using the API on 1.1 version, but we updating to 2.1 disappears the method getTos. Why?

**Comment by kunal732** [comment]
Hey @cesaroliveiraa, you can still get an array of the current setTos by using 

```php
$tos = $email->smtpapi->to;
```
If you find you still require the function, can you describe how you were using it and your use case.

**Comment by taz77** [comment]
I'm the maintainer of the Drupal module for Sendgrid and I just ran into this as well building more debugging into the module. I want/need to extract the To addresses that is in the email message object as it is being built. 
```
 $tos = $email->smtpapi->to;
```
This returns an empty array while preparing a message.

Being I am using a forked version of the official SendGrid API for the module (Guzzle 6.x and PHP 5.4+ support), I just added the method back to the API. I just thought I would addd this comment for anyone else that may happen upon this issue.

**Comment by thinkingserious** [comment]
Thanks for the feedback @taz77, we have flagged this ticket to take a deeper look.

**Comment by taz77** [comment]
You can take a look at what I am doing here. I am using another Drupal module called Maillog that is specifically designed for mail system debugging and troubleshooting. I extract everything out of the Sendgrid email object and send it off to this logging untility before the email gets actually processed.

Around line 156
https://github.com/taz77/drupal-sendgrid_integration/blob/7.x-1.x/inc/sendgrid.mail.inc

**Comment by thinkingserious** [comment]
Awesome, thanks @taz77!

**Comment by thinkingserious** [comment]
Hello @ocesaroliveira @taz,

We have revamped our mail send endpoint such that it integrates the functionality of the SMTPAPI header. Check it out here: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

This library will be updated shortly with complete support for the new v3 /mail/send endpoint as well as the remaining v3 Web API endpoints. You can check out the beta branch here: https://github.com/sendgrid/sendgrid-php/tree/v3beta

Thanks!

With Best Regards,

Elmer
