### ISSUE TITLE
CURLOPT_FOLLOWLOCATION

### ISSUE THREAD

**Issue by nextexile** [sendgrid/sendgrid-php#119]
I'm on MediaTemple Grid. Email does get sent but all I see on the next page is:

Message: curl_setopt() [function.curl-setopt]: CURLOPT_FOLLOWLOCATION cannot be activated when safe_mode is enabled or an open_basedir is set

Filename: Unirest/Unirest.php

Line Number: 203

Safe mode is off, basedir is set because it's shared hosting. What's the best course of action here? Can / should I just comment out that one line that calls for CURLOPT_FOLLOWLOCATION?

**Comment by kunal732** [comment]
Can you update the library to the latest version and try again. Unirest has been removed.

**Comment by nextexile** [comment]
Ok, so I tried adding the new library and unless I'm missing something, it's even worse.

I include SendGrid.php, it's missing Email.php.
I then include Email.php, it's missing Smtpapi\Header.

What's the proper installation method for 2.2.0 if I'm doing manual install from a zip?

**Comment by eddiezane** [comment]
@nextexile that zip needs to be updated. Sorry about that. I'll respond once it is.

For the mean time, composer is the best way to test it.

**Comment by nextexile** [comment]
Ah thanks, I'll just wait. I appreciate the quick response.

**Comment by eddiezane** [comment]
@nextexile Ok should be good. Had to square away S3 keys. 

The latest version should be package and ready for download [here](https://sendgrid-open-source.s3.amazonaws.com/sendgrid-php/sendgrid-php.zip)

Thanks for your patience and helping us get it all squared away!

**Comment by nextexile** [comment]
Awesome, not sure if I should open a new issue but now I occasionally get:

Severity: Notice
Message: Array to string conversion
Filename: lib/SendGrid.php
Line Number: 51

**Comment by eddiezane** [comment]
Interesting. Is it just a notice or does it cease to work?

Could you please share what you might be passing an array into?

**Comment by nextexile** [comment]
It looks something like this. To note, I'm using your API and methods, nothing hacky nor am I assembling my own headers.

var dump on $form:

array(11) { ["to"]=> string(23) "xxx@xxx.com" ["from"]=> string(23) "xxx@xxx.com" ["x-smtpapi"]=> string(30) "{"to":["xxx@xxx.com"]}" ["subject"]=> string(55) "subject" ["text"]=> NULL ["html"]=> string(17169) "" ["headers"]=> string(2) "{}" ["bcc"]=> array(2) { [0]=> string(20) "xxx@xxx.com" [1]=> string(22) "xxx@xxx.com" } ["fromname"]=> string(11) "name" ["api_user"]=> string(6) "user" ["api_key"]=> string(25) "mykey" }

**Comment by nextexile** [comment]
I think CURLOPT_POSTFIELDS expects a string and you're passing an array?

**Comment by eddiezane** [comment]
> This parameter can either be passed as a urlencoded string like 'para1=val1&para2=val2&...' or as an array with the field name as key and field data as value. If value is an array, the Content-Type header will be set to multipart/form-data. 

http://php.net/manual/en/function.curl-setopt.php

Maybe it's the `Content-Type` bit. I'll play with it more tonight or tomorrow.

Thanks for the help!

**Comment by nextexile** [comment]
This got rid of the warning for me. Changing content-type did not.

`curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($form));`

**Comment by nextexile** [comment]
I'm still waiting to hear from anyone else on this issue but please beware that the http_build_query solution mentioned in this thread may break attachments. Mine were still getting attached but all files were completely blank.

**Comment by pulse00** [comment]
`http_build-query` causes `Missing destination email` response error here (php 5.5.9).

**Comment by nextexile** [comment]
So, if I use http_build_query no more Array to string conversion issues, which seems to be tied to CC, but that breaks attachments. To be precise, attachments work and arrive with email BUT theyre empty every single time.

**Comment by eddiezane** [comment]
I have figured this out thanks to [this](http://stackoverflow.com/questions/3772096/posting-multidimensional-array-with-php-and-curl). I am going to be building the post body manually in toWebFormat.
