### ISSUE TITLE
Array To String Conversion Issue

### ISSUE THREAD

**Issue by digitsoft** [sendgrid/sendgrid-php#128]
I found the solution from this issue: https://github.com/sendgrid/sendgrid-php/issues/119

The fix works for me, but it's not in the current release.
curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($form));

Edit line 51 of:
sendgrid-php/lib/SendGrid.php

**Comment by eddiezane** [comment]
The problem is that `curl_setopt($ch, CURLOPT_POSTFIELDS,` expects a single dimension array. Working on a fix for the v3 branch now.
