### ISSUE TITLE
Call to undefined method Smtpapi\Header::setCategory()

### ISSUE THREAD

**Issue by christianscharr** [sendgrid/sendgrid-php#129]
Using latest version (2.2.1) in packaged zip-version on Ubuntu server with PHP 5.3.10 installed.

sendgrid-php-2.2.1/lib/SendGrid/Email.php line 244:

243: public function setCategory($category) {
244:     $this->smtpapi->setCategory($category);
245:     return $this;
246: }

**Comment by eddiezane** [comment]
Fixed in v0.4.0 of https://github.com/sendgrid/smtpapi-php
