### ISSUE TITLE
Scoping issues preventing emails from being sent

### ISSUE THREAD

**Issue by gmox** [sendgrid/sendgrid-php#130]
If you have something like (in laravel 4.2)

		$sendgrid = new SendGrid( 'username','password');

		$mail = new SendGrid\Email();

                Emails::chunk(1000, function($emails) use ($sendgrid, $mail) {
                        $_emails = [];
                        foreach( $emails as $email ) {
                               $_emails[] = $email->email;
                         }
                        $send = $mail->setTos($_emails);
                        $sendgrid->send($send);
                });

It stores the emails in the $mail object. Eventually, when this gets to 10,000 emails, all emails you send afterward that mark will no longer send. Changing the scope and putting both $sendgrid and $mail within the closure will allow you to continue sending past the 10,000 mark.

**Comment by gmox** [comment]
Additionally, it's strange that, even tho the request was not successful, the API returns {"message":"successful"}

**Comment by eddiezane** [comment]
Not clear on the issue you're experiencing.
