### ISSUE TITLE
Bug in sendgrid client library

### ISSUE THREAD

**Issue by hhminh** [sendgrid/sendgrid-php#131]
It appears that something change on sendgrid server side, it now suddenly send to recipient like this:

to: john, Array

I look into the client library into the file lib/SendGrid.php line 51

curl_setopt($ch, CURLOPT_POSTFIELDS, $form);

I put http_build_query around the $form variable and that seems to stop sendgrid server side from putting Array into the recipient list

curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($form));

I think this is also a more proper way to deal with curl.

Could you investigate and incorporate the fix into the version 1.0 of the API

**Comment by VictorAcatrinei** [comment]
Indeed this seems to be causing issues. Do we have any kind of update on the problem? Thanks!

**Comment by nextexile** [comment]
Hey guys, I have a suspicion that while this fixes the issue, it breaks attachments. Can someone verify on their end? My attachments appear but are empty.

**Comment by nextexile** [comment]
I have just confirmed this on my end. Still would love to hear from someone else but in the meantime please beware.

**Comment by eddiezane** [comment]
I have a pre-release up of v3.0.0 that should fix all of these issues. Would love some testers to provide feedback. 

I need to write up the changes and a better README, but [here's a primer](https://github.com/sendgrid/sendgrid-php/tree/v3.0.0#please-read-this).

`"sendgrid/sendgrid": "3.0.0-RC1"` in composer.

https://github.com/sendgrid/sendgrid-php/releases/tag/v3.0.0-RC1

**Comment by nextexile** [comment]
I just quickly tried this out and its complaining about Guzzle not being present. Is this some new dependency?

**Comment by eddiezane** [comment]
Yea I wound up going with Guzzle3. I tried pretty hard to stick to native curl. I even started working on another [library](https://github.com/eddiezane/TinyHttp) but in the end I would have had to manually handle form/multipart encoding... That's when I realized that these big HTTP libraries exist for a reason.

The issue everyone was getting about the Array to string conversion was because curl requires a single dimension array and we are building a nested one. As people realized, `http_build_query` broke attachments.

**Comment by nextexile** [comment]
So, this also bumps up your required PHP version to 5.4, correct?

**Comment by eddiezane** [comment]
Nah thankfully Guzzle3 supports PHP 5.3 still.

On Saturday, April 4, 2015, Serg Chernata <notifications@github.com> wrote:

> So, this also bumps up your required PHP version to 5.4, correct?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sendgrid/sendgrid-php/issues/131#issuecomment-89610910>
> .
>


-- 
Eddie Zaneski
{"device": "mobile"}

**Comment by nextexile** [comment]
Hmm, installing via composer Guzzle is refusing to work with PHP under 5.4. Should I be suppressing that warning and ignoring it?

**Comment by eddiezane** [comment]
Yea the docs for Guzzle3 are [here](http://guzzle3.readthedocs.org/en/latest/). 

I'll do some testing getting everything installed on PHP 5.3. Maybe I botched a config somewhere.

https://github.com/guzzle/guzzle3
