### ISSUE TITLE
Unable to send html emails using templates

### ISSUE THREAD

**Issue by pulse00** [sendgrid/sendgrid-php#134]
i'm unable to send html emails using templates with this library. Here's what i've tried so far:

```php
        $email
            ->addTo($user->getEmail())
            ->setFrom('support@example.com')
            ->setFromName('support')
            ->setSubject('Subject goes here')
            ->setText('Hello!')
            ->addCategory('Welcome Mail')
            ->addFilter('templates', 'enabled', 1)
            ->addFilter('templates', 'template_id', $this->welcomeTemplateID)
        ;
```

The resulting email seems to be a multipart email containing `text/html`, but there is no styling applied whatsoever. Here's the relevant html part of the received email:

```
Content-Type: text/html; charset="utf-8"
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable

<html><body>
<p><strong>|SUBJECT|</strong></p>
<p>Use this area to offer a short preview of your email's content.</p>
<p>View this email in your browser (*|ARCHIVE|*)</p>
<p>Designing Your Email</p>
<p>Creating an elegant email is simple=C2=A0 <strong>|FOO|</strong></p>
<p>Now that you=E2=80=99ve selected a template to work with, drag in conten=
t blocks to define the structure of your message. Don=E2=80=99t worry, you =
can always delete or rearrange blocks as needed. Then click =E2=80=9CDesign=
=E2=80=9D to define fonts, colors, and styles.</p>
<p>So <strong>|OAS|</strong> !</p>
<p>Need inspiration for your design? Here=E2=80=99s what other MailChimp us=
ers are doing.</p>
<p>Sign Up (wWtm0fP--k3--ltZpxVT3tPL6XEpGhLoqnHRpjheh2A)</p>
<p>Hello!</p>
<p>Copyright =C2=A9 <strong>|CURRENT_YEAR|</strong> <strong>|LIST:COMPANY|<=
/strong>, All rights reserved.</p>
<p><strong>|IFNOT:ARCHIVE_PAGE|</strong> <strong>|LIST:DESCRIPTION|</strong=
></p>
<p>Our mailing address is:</p>
<p><strong>|HTML:LIST_ADDRESS_HTML|</strong> <strong>|END:IF|</strong></p>
<p>unsubscribe from this list (*|UNSUB|*)=C2=A0=C2=A0=C2=A0 update subscrip=
tion preferences (*|UPDATE_PROFILE|*)=C2=A0</p>
<p><strong>|IF:REWARDS|</strong> <strong>|HTML:REWARDS|</strong> <strong>|E=
ND:IF|</strong></p>
</body></html>
```

If i send the template using the test-button in the sendgrid interface, the html is styled properly.

It seems when using the php library, all styles are stripped away. Anything wrong with the api calls above?

**Comment by eddiezane** [comment]
You need to use `->setHtml('Hello!')` instead of `->setText('Hello!')`.

This cause the html version to get sent as opposed to the plain text one.

**Comment by pulse00** [comment]
this worked, thanks. i still don't get why i need to call `setText()` or `setHtml()` when using templates. Isn't the whole point of templates not to have to specify the body of the email, but use replacement tags only?

**Comment by eddiezane** [comment]
Thanks for the great feedback! This is something many others have suggested and I'm pretty sure it's planned; not sure for when though.

**Comment by pulse00** [comment]
ah ok, i see. so for now simply using `->setHtml(" ");` works fine, which replaces `<%body%>` with an empty space. thanks for the fast response.

**Comment by justaserr** [comment]
Using `$content = new Content('text/html', ' ');` instead of `$content = new Content('text/plain', ' ');` as stated in example https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#with-mail-helper-class allowed sending templates as HTML.

**Comment by deenlord** [comment]
apiV3 equivalent?

**Comment by thinkingserious** [comment]
[Here](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#transactional-templates) you go @deenlord. Thanks!
