### ISSUE TITLE
`CC` and `BCC` Not Working

### ISSUE THREAD

**Issue by mdavis1982** [sendgrid/sendgrid-php#136]
Given the following code:

```php
$client = new SendGrid('user', 'password');

$email = new SendGrid\Email();
$email->setFrom('example@example.com');
$email->setFromName('Example');
$email->addTo('username@example.com', 'Name');
$email->setText('Hello, world');
$email->setSubject('Test Subject');
$email->addCc('foo@example.com');

var_dump($client->send($email));
```

I get the following exception:

```
ErrorException in SendGrid.php line 51:
Array to string conversion
```

This also happens when trying to use `BCC`. 

I'm using the following in my `composer.json`:

```json
{
    "require": {
        "sendgrid/sendgrid": "~2.2"
    }
}
```

How do I fix this?

**Comment by mdavis1982** [comment]
No reply to this yet? This seems like a pretty important feature for an e-mail provider and their associated client library...

**Comment by eddiezane** [comment]
Thanks for the report. We are aware of the problem and are working on it.

**Comment by eddiezane** [comment]
I have a pre-release up of v3.0.0 that should fix all of these issues. Would love some testers to provide feedback. 

I need to write up the changes and a better README, but [here's a primer](https://github.com/sendgrid/sendgrid-php/tree/v3.0.0#please-read-this).

`"sendgrid/sendgrid": "3.0.0-RC1"` in composer.

https://github.com/sendgrid/sendgrid-php/releases/tag/v3.0.0-RC1
