### ISSUE TITLE
Passwords starting with "@" cause deprecation warning and exception

### ISSUE THREAD

**Issue by yemble** [sendgrid/sendgrid-php#137]
In php 5.5:

If password begins with an @ character, it is treated as a filename and raises a warning due to deprecation, and an exception due to the file not existing. Should probably figure out a way to disable the @filename "API" or prevent people from choosing passwords starting with that character.

I spent two hours chasing red herrings about CURLFile and the like before realising it was the password data (since changed, obvs).

```
    ..
    [api_key] => @xxxxyyyyzzzz
    ..

PHP Deprecated:  curl_setopt(): The usage of the @filename API for file uploading is deprecated. Please use the CURLFile class instead in vendor/sendgrid/sendgrid/lib/SendGrid.php on line 51

PHP Fatal error:  Uncaught exception 'Exception' with message 'couldn't open file "xxxxyyyyzzzz"' in vendor/sendgrid/sendgrid/lib/SendGrid.php:60
```

**Comment by eddiezane** [comment]
Appologies that this was a hunt for you.

The next release of the repo is using Guzzle, which also uses `@` to identify files (it eventually wraps them in CurlFile for PHP >=5.5)

Since we need to maintain support for PHP >=5.3, we will still need to utilize this.
