### ISSUE TITLE
Using unique arguments for multiple recipient e-mail,

### ISSUE THREAD

**Issue by MrRoyce** [sendgrid/sendgrid-php#139]
Can we create a unique argument when sending a multiple recipient e-mail?  We send 1000 emails at a time and we would like to pass multiple unique arguments for each email (user_id, mail_code, etc).  

What is the syntax for doing that with the PHP smtp api?

regards,
Royce

**Comment by eddiezane** [comment]
You would need to call `addUniqueArg` 1000 times or call `setUniqueArgs` with an array of all of the unique args.

Please see https://github.com/sendgrid/sendgrid-php#unique-arguments for examples.

Let me know if you require further assistance or please reach out to our [support team](https://support.sendgrid.com/hc/en-us/articles/203979566-How-do-I-contact-Support-).

**Comment by MrRoyce** [comment]
Hi there, thanks for your response.  I tried with an array of 1000 arguments, but the calls failed with:

`A message was received from this address by our systems that had errors in the smtpapi header, and cannot be processed.
The error detected was: The unique_args variable must be less than 10000 bytes
If you require assistance in working with the SMTP API, please contact us at support@sendgrid.com`

I tried reducing the array to 250, but I got the exact same message.

I know the code works with just 1 element in the array, but I can't keep testing until I find the magic number.  Can you help with this issue?

Also, can you change the API to truncate the headers to under 72 characters as described in:

https://sendgrid.com/docs/API_Reference/SMTP_API/using_the_smtp_api.html#-Requirements-and-Limitations


regards,
Royce

**Comment by eddiezane** [comment]
The 72 character limit only applies when the SMTP API Header is used with SMTP as a transport. This library uses HTTP as opposed to SMTP, so that restraint shouldn't apply. We should make that more clear in the docs.

As for the other issue, I'd reach out to our support team to see if they can help so you aren't waiting on me to dig into this.

**Comment by MrRoyce** [comment]
I posted a question to the SendGrid support.

https://community.sendgrid.com/sendgrid/topics/using-unique-arguments-for-multiple-recipient-e-mail-with-sendgrid-php?rfm=1&topic_submit=true

**Comment by MrRoyce** [comment]
This is the reply from Seth Ammons:

*Hi Royce! I double checked our code. We check the lengths in bytes of the unique_args value. If it is greater than 10,000 bytes, we kick out that error. 

In your code, you do not need to binary search for a number of elements in your unique args list, you should instead check for the byte length of the string representation that will be in the json header. I hope this helps!*

Eddie, would it be possible for the API to do this check and then throw an exception if the length is > 10,000?

**Comment by eddiezane** [comment]
This is something we can definitely consider adding.

For the time being, you should be able to check the length of the string before passing an email into the `send` function by doing

```php
if (mb_strlen($myEmail->smtpapi->jsonString(), 'UTF-8') > 10000) {
    // throw Exception
}
```

**Comment by scottkawai** [comment]
Hey guys - just throwing this in here.  Are you looking to have unique arguments where each of the 1000 recipients have a different value for a given unique argument key?  If so, that would probably require combining substitution tags with unique arguments:

```php
$sendgrid = new SendGrid( $sg_username, $sg_password );
$mail = new SendGrid\Email();
$emails = array (
    "New Person 1 <new1@email.none>",
    "New Person 2 <new2@email.none>",
    "New Person 3 <new3@email.none>"
);

$mail->setSmtpapiTos($emails);

$mail->addUniqueArgument( "user_id", "%user_id%" )
$mail->addUniqueArgument( "mail_code", "%mail_code%" )

$mail->addSubstitution( "%user_id%" , array("12345", "67890", "2468") );
$mail->addSubstitution( "%mail_code%" , array("abcde", "fghij", "klmnop") );
```

**Comment by thinkingserious** [comment]
Thanks to all that have contributed to this thread.

I have clarified the documentation: https://github.com/sendgrid/sendgrid-php/commit/a3992e7f800d4aa87da6b1e1cce6e6b6679cc62f

It is possible we may add this check to the library, but not at this time.
