### ISSUE TITLE
setTos doesn't work with array with empty values

### ISSUE THREAD

**Issue by gemal** [sendgrid/sendgrid-php#140]
if you have an array like this
$to = array(
  0 => 'bla@bla.com',
  3 => 'bla2@bla.com',
)

and do:
$email->setTos($to);

the sendgrid is reporting that the email is sent but nothing is sent!

The array is coming from using array_unique

If I do:
$to = array(
  0 => 'bla@bla.com',
  1 => 'bla2@bla.com',
)

it works!

using 2.2.1 php

**Comment by eddiezane** [comment]
Thanks for reporting this. I think it's fixed in the upcoming v3.0.0 release since we're using Guzzle3.

For the time being, please call `array_values()` on the array before passing it to `setTos()`.

`$email->setTos(array_values(array_unique($to)));`
