### ISSUE TITLE
Change SMTP Ports

### ISSUE THREAD

**Issue by BrainBuzzer** [sendgrid/sendgrid-php#141]
Hey, I am wanted to change the SMTP ports to 587 as Google cloud does not support port 25. How can I do that?

**Comment by eddiezane** [comment]
This library actually uses HTTP over port 443 via our [Web API](https://sendgrid.com/docs/API_Reference/Web_API/mail.html) as opposed to SMTP so you won't have to worry about that.

Please let us know if you need further clarification.
