### ISSUE TITLE
Question about documentation

### ISSUE THREAD

**Issue by gsaqui** [sendgrid/sendgrid-php#142]
In the readme you mention that you can send to 1000 email addresses at a time and you have the following bit of code:
```
$sendgrid = new SendGrid(SENDGRID_USERNAME, SENDGRID_PASSWORD);
$email = new SendGrid\Email();

$recipients = array(
    "alpha@mailinator.com", 
    "beta@mailinator.com", 
    "zeta@mailinator.com"
);
$names = array("Alpha", "Beta", "Zeta");

$email
    ->setFrom("from@mailinator.com")
    ->setSubject('[sendgrid-php-batch-email]')
    ->setTos($recipients)
    ->addSubstitution("%name%", $names)
    ->setText("Hey %name, we have an email for you")
    ->setHtml("<h1>Hey %name%, we have an email for you</h1>")
;
```

I was wondering if the setText("Hey %name......") should be setText("Hey %name%.......)?

Also is recommended to have both setText and setHtml?

**Comment by eddiezane** [comment]
Great catch; I'll update it!

It is indeed recommended to have both text and html content. It's generally gets you a better spam score.

**Comment by gsaqui** [comment]
@eddiezane thanks for answering the questions so quickly
