### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by hyldmar** [sendgrid/sendgrid-php#143]
I want to use [Sourcegraph](https://sourcegraph.com) for sendgrid-php code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/sendgrid/sendgrid-php. (It should only take 30 seconds.)

Thank you!

**Comment by eddiezane** [comment]
When I tried to enable it:
> PHP is not supported. Sourcegraph's advanced code search, browsing, and usage examples are only available for supported languages. If the language was detected incorrectly, or to use only basic repository operations, you can proceed anyway.
