### ISSUE TITLE
SMTP-Id with RESTful Api

### ISSUE THREAD

**Issue by zang** [sendgrid/sendgrid-php#144]
we are using the api to send emails, and we'd like to implement the webhooks to track events and parse incoming emails. My questions are:

1) we don't seem to get SMTP-Id in the initial api response. Is there a way to get it?
2) what's the recommended method for us to map the hooks to the exact email since we can't rely on email address ? Is there a php code example you can point me to?

Thanks in advance,
Lucy

**Comment by eddiezane** [comment]
Hi Lucy,

There isn't a way to get the SMTP-ID in the initial api response. The response is to just let you know that SendGrid accepted your request.

We recommend using [unique args](https://sendgrid.com/docs/API_Reference/SMTP_API/unique_arguments.html) to track the lifecycle of emails. 

Using unique args with [PHP](https://github.com/sendgrid/sendgrid-php#unique-arguments).

Please reach out to SendGrid support if you require further assistance.
