### ISSUE TITLE
Sending Marketing Email through SMTP API 

### ISSUE THREAD

**Issue by woody101** [sendgrid/sendgrid-php#146]
Hi Guys

I am new to SMTP API, and I'm not even sure SMTP API can do what I'm trying to achieve, so please be patient.

I have created an email in the 'Marketing Email' section of the newsletter app - https://sendgrid.com/newsletter.

I have created a couple of variations through the GUI so we can split test this email.

It's currently in 'draft' status and has no recipient list applied. This is because we want to use SMTP API  in code to send this, yet I do not see a method to send newsletters? I guess I'm looking for the equivalent to this:

$json_string = array(
	'to' => array(
		'email1@domain.com', 'email2@domain.com'
	),
	'addSubstitution' => array(
		'-name-', array('kev', 'joe'),
		'-age-', array('37', '29')
	),
	'filters' => array(
		'opentrack' => array(
			'settings' => array(
				'enable' => '1'
			)
		)
	)
);

$params = array(
    'api_user'  => $username,
    'api_key'   => $password,
	'x-smtpapi' => json_encode($json_string),
	'name'		=> 'Annual inactives test 1',
  );

$request =  'https://api.sendgrid.com/api/newsletter/send.json';

// Generate curl request
$session = curl_init($request);
// Tell curl to use HTTP POST
curl_setopt ($session, CURLOPT_POST, true);
// Tell curl that this is the body of the POST
curl_setopt ($session, CURLOPT_POSTFIELDS, $params);
// Tell curl not to return headers, but do return the response
curl_setopt($session, CURLOPT_HEADER, false);
// Tell PHP not to use SSLv3 (instead opting for TLS)
curl_setopt($session, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_2);
curl_setopt($session, CURLOPT_RETURNTRANSFER, true);

// obtain response
$response = curl_exec($session);
curl_close($session);

// print everything out
print_r($response);

The reason we need to send this as a newsletter is because we need access to the statistics after it's been sent (http://gyazo.com/7df97db8806ec6076c4f66bb830eb03b).

Perhaps there's a very simple solution here, in fact I'm pretty sure there is.... I'm still learning :)
 
I have also just discovered the Apps(Filters) section, perhaps this will record all the open, click data and stats I require without using the newsletter GUI at all?

Can you help?

Thanks

**Comment by eddiezane** [comment]
Hi @woody101,

This library only has support for our [regular mail endpoint](https://sendgrid.com/docs/API_Reference/Web_API/mail.html), not our [marketing email endpoints](https://sendgrid.com/docs/API_Reference/Marketing_Emails_API/index.html).

Please reach out to our [support team](https://support.sendgrid.com/hc/en-us/articles/203979566-How-do-I-contact-Support-) for assistance.

**Comment by woody101** [comment]
Ok thanks Eddie,
Will do that.
