### ISSUE TITLE
Setting Multiple From Names

### ISSUE THREAD

**Issue by sokser** [sendgrid/sendgrid-php#147]
I've been using the sendgrid api with great success so far but have encountered one issue. I use the function setTos() to send to approximately 50 subscribers at a time. However we need to set a different from name for particular subscribers (e.g. NAME New York, Name SF, Name Miami, etc). Is there any equivalent to setFroms() in the API, or any other way to do this?

**Comment by eddiezane** [comment]
Presently the only way to achieve this is to make individual api calls.

Please let me know if I can explain further.

**Comment by sokser** [comment]
Understood. However, in your documentation you show and example with multiple "->from(email)->fromName(name)' in a single call. This doesn't seem to work in practice. Should the documentation be updated? https://github.com/sendgrid/sendgrid-php#setfromname

**Comment by eddiezane** [comment]
Great catch! I think that is supposed to be demonstrating you can replace it with multiple calls but is definitely confusing.

If you want to open a pull request to change it you'll get sent a SendGrid t-shirt :smile: otherwise I'll make the change.
