### ISSUE TITLE
Multiple attachments with the same filename

### ISSUE THREAD

**Issue by davidbehler** [sendgrid/sendgrid-php#151]
Right now it's not possible to add multiple attachments with the same filename to an email. Or rather you can add them, but when you send them only one of them (the last one added I guess) gets sent.

That's because in the `toWebFormat` method of the `Email` class the form data is set using the `$full_filename`: `$web['files['.$full_filename.']'] = $contents;`. 

If you use custom filenames (which we do to have nice looking email attachments), the custom filename is used as `$full_filename`. And that's where the problem comes from. Our users can have multiple files with the same name and attach them to emails. Each email can have multiple attachments.

I'd fix the code myself, but there is no use in changing the `toWebFormat` method without changing the API that's called using the data...because I guess it expects the data to be in a certain format, the filename as array key and the value being the file's content.

**Comment by thinkingserious** [comment]
Hello @davidbehler,

Thanks for the feedback!

We have changed the way we handle attachments in the new version of this library (example): https://github.com/sendgrid/sendgrid-php/blob/v3beta/examples/helpers/mail/example.php#L83 

To learn more about the new v3 /mail/send endpoint, please check out: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

If your request requires a change to the API itself, then please direct your suggestion to https://support.sendgrid.com and/or https://community.sendgrid.com

With Best Regards,

Elmer

**Comment by davidbehler** [comment]
Looks good to me. Thanks! 

Any idea when v3 will be merged into master?

**Comment by thinkingserious** [comment]
We are planning for no more than a few weeks, thanks for checking in!
