### ISSUE TITLE
Poor diagnostic message upon curl error

### ISSUE THREAD

**Issue by caraffa** [sendgrid/sendgrid-php#152]
Good day.
Consider this piece of code of your SndGrid.php file: 
```php
class SendGrid {
.
.
.
  private function makeRequest($form) {
    $ch = curl_init();
.
.
.
    $response = curl_exec($ch);
    $error = curl_error($ch);
    if ($error) {
      throw new Exception($error);
    }
    curl_close($ch);
    return json_decode($response);
  }
.
.
.
}
```
... and consider this scenario:
Let's suppose for a moment that for whatever reason your servers at SendGrig.com are unreachable. Curl_exec will fail and the $error variable will contain a meaningful description of the error (such as "host unreachable", or so). This is because it is curl itself that is handling the error.
Now please consider this second scenario:
Your servers at SendGrid.com are perfectly functional AND reachable so that I decide to send an e-mai using your service. But, let's suppose, I've typed a wrong username and/or password in my php code. Curl_exec will fail and your code will throw an exception with the value of the variable $error as human readable message. In this case I'm left with absolutely no hint about what really did happen because the variable $error contains simply the word "error" and nothing else.
De facto, the real source of information, the $response variable, which is containing valuable diagnostic information, is discarded.
My suggestion is to modify the code as follow:
Instead of 
```php
    $error = curl_error($ch);
    if ($error) {
      throw new Exception($error);
    }
```
we can use 
```php
    $error = curl_error($ch);
    if ($error && empty($response) ) {
        $response = json_encode((object)array( 'message' => $error ));
    }
```
In this way the call to makeRequest will return a $response that contain the word "success" or "error", along with additional error info, if any, while at the same time, handling the case of a "pure" curl error.
Regards

**Comment by thinkingserious** [comment]
This is no longer an issue with the current version of the library.

Thank you for taking the time to report this with such detail, we appreciate it!
