### ISSUE TITLE
Templates already contain a subject, why do I need to pass one?

### ISSUE THREAD

**Issue by christhomas** [sendgrid/sendgrid-php#154]
Since when creating a template I set the subject.  Why is the subject required when I'm sending an email?

Shouldn't it pick it up from the template, isn't that the whole point of using templates in the first place, I just set the substitution parameters.

However, if I set no subject, or a blank space, no subject is used and I am told it's missing subject.

**Comment by eddiezane** [comment]
Definitely on our roadmap of improvements. Thanks for the feedback and apologies for any issues this has caused you.

**Comment by christhomas** [comment]
why did you close the issue? is it fixed?

**Comment by eddiezane** [comment]
This needs to be changed at our API/Template Engine level. It isn't an issue with the library.

**Comment by christhomas** [comment]
I hate to say this, but if this wasn't obvious to the people who wrote the api/template engine, then I have little faith in their ability to write API's....It seems such an glaringly obvious oversight to make.

But ok, I have forked the repository and I'm making a much improved client library, you're free to check it out, I think I've started something pretty interesting, comments are appreciated
