### ISSUE TITLE
Guzzle 3.x is EOL. Any plans to upgrade to at least 5.x

### ISSUE THREAD

**Issue by taz77** [sendgrid/sendgrid-php#156]
Guzzle 3.x and 4.x are now EOL. Any plans to update?

https://github.com/guzzle/guzzle

**Comment by afrowuk** [comment]
Guzzle 6 would be ideal.

**Comment by taz77** [comment]
If you are interested. I have forked this repo to work on upgrading to Guzzle v6.x

https://github.com/taz77/sendgrid-php

**Comment by taz77** [comment]
In working on this, I am starting to ask "why on earth is this using an external library". You could just as easily wrote this with simple cURL statements.

**Comment by brandonmwest** [comment]
Feel free to review the project history for context.

**Comment by taz77** [comment]
Where? I looked in the commit history and only found where Guzzle 3.x was added on 3 April 2015. Commit message was "Add guzzle3"

**Comment by taz77** [comment]
Guess I should frame why I been working on this today. Because I keep getting nothing but 503 errors from Sendgrid when using this API. I was hoping upgrading to Guzzle6.x would give me more than just "it's broken" error.

**Comment by taz77** [comment]
Come to think of it. First commit was 3 April 2015 that included Guzzle 3 which at that time was already deprecated?.?.? That makes zero sense to me.

**Comment by brandonmwest** [comment]
Search the issues for "curl", "guzzle" etc. I understand that it's often hard for people that look at a legacy code base to understand the reasons certain decisions were made but I assure you that things that don't make sense to you on the surface were done for good reasons.

**Comment by taz77** [comment]
I went looking there too. So far everything I have read is because of PHP 5.3. Sorry, but PHP 5.3.x went EOL 10 months ago. And since Guzzle 6.x requires PHP 5.5.x I assume that is why it was not used here. I was really excited about Sendgrid, but supporting antiquated end-of-life software isn't something I can do as a developer.

**Comment by eddiezane** [comment]
What is the actual issue you are having @taz77?

I'd have loved to drop support for PHP 5.3, but until this [graph](http://w3techs.com/technologies/details/pl-php/5/all) and our usage reporting says differently, PHP 5.3 will be supported for the rest of our customers.

**Comment by taz77** [comment]
The only way to progress is sometimes to force change. You make appropriate notifications to customers and move forward. If <a href="https://developer.atlassian.com/jiradev/jira-apis/jira-api-status/jira-rpc-services/jira-xml-rpc-overview/soap-and-xml-rpc-api-deprecation-notice">Atlassian</a> can do it, so can you guys :-) No offense, I am sure their customer base is far greater.

PHP 5.3 went end-of-life <a href="https://secure.php.net/eol.php">10 months ago</a>. Do your part and drop it. On a smaller scale, it could be equated to the life support that IE got for years. We all have to do our part to not foster bad behavior.

I was trying to update the Drupal <a href="https://www.drupal.org/project/sendgrid_integration">Sendgrid module</a> for the V3 API to use the new API Keys. In working on the code and using composer for dependencies, I get nothing but 503 errors with no real explanation of why. Even with a try{} catch{}, I get nothing.

**Comment by taz77** [comment]
Found my source of 503 errors. cURL cacert issue.

**Comment by taz77** [comment]
Hey guys. Well I finally got around to doing more work and I forked your repository to start updgrading to Guzzle 6.0.x.

Could you guys take a look at this? Maybe this could represent a larger version change to jump from Guzzle 3 to 6.

https://github.com/taz77/sendgrid-php

**Comment by thinkingserious** [comment]
Please see the comments here: https://github.com/sendgrid/sendgrid-php/pull/161
