### ISSUE TITLE
Update Readme file

### ISSUE THREAD

**Issue by mbernier** [sendgrid/sendgrid-php#159]
https://github.com/sendgrid/sendgrid-php/commit/12d24853ca617b0aa27031a12e886e6a0c4d2190#commitcomment-12727681

From @hadifarnoud: 

> please update the readme. it's old and has wrong info (e.g. https://sendgrid.com/beta/settings/api_key link).
> 
> please add a short description of what addSomething setSomething mean and what is the difference. your docs are really incomplete. this readme helped me more actually. just needs to be better

**Comment by thinkingserious** [comment]
https://github.com/sendgrid/sendgrid-php/commit/bf5c94f2fe679efb88d0d8f8974c4db3d29c33b9
