### ISSUE TITLE
A feature to remove unsubscribed user

### ISSUE THREAD

**Issue by akshit-sharma** [sendgrid/sendgrid-php#160]
https://sendgrid.com/docs/API_Reference/Web_API/unsubscribes.html#-delete

A feature to remove an unsubscribed user, so he may get mail again.

**Comment by thinkingserious** [comment]
We will be implementing [Advanced Suppression Management](https://sendgrid.com/docs/API_Reference/Web_API_v3/Suppression_Management/index.html) in the next version of this API, which you may track here: [https://github.com/sendgrid/sendgrid-php/tree/v3_beta](https://github.com/sendgrid/sendgrid-php/tree/v3_beta)

Thanks!
