### ISSUE TITLE
"The requested package sendgrid could not be found in any version" error on composer update

### ISSUE THREAD

**Issue by benjaminfleet** [sendgrid/sendgrid-php#172]
Per the readme file, I added the following to my composer.json file:
```
{  
  "require": {
    "sendgrid/sendgrid": "~3.2"
  }
}
```

I am receiving this error when I run "php composer.phar update":
"Problem 1
    - The requested package sendgrid could not be found in any version, there may be a typo in the package name."

**Comment by thinkingserious** [comment]
Can you try changing 3.2 to 4.0?

**Comment by thinkingserious** [comment]
Hello @benjaminfleet,

If you are still having issues, please feel free to re-open this issue.

Also, note that this library is moving to version 5.0 shortly, you can get a preview here: https://github.com/sendgrid/sendgrid-php/tree/v3beta

With Best Regards,

Elmer
