### ISSUE TITLE
Fatal Error: Guzzle cURL Error 7 Fail to Connect to Sendgrid

### ISSUE THREAD

**Issue by elevatednetwork** [sendgrid/sendgrid-php#173]
Today (04-Nov-2015) at 09:02 I noticed a fatal PHP error in my error logs. After a bit of research I believe I figured out exactly what happened. While attempting to send an email to sendgrid the connection timed out or simply failed to connect to api.sendgrid.com. I use the highly suggested exception catching (try/catch) when sending ($sendgrid->send($email);) an email. However, the fatal error was produced by Guzzle. I'm assuming api.sendgrid.com was under a lot of load when this fatal error occurred and that is why the connection failed.

Here is the error message I received:
> PHP Fatal error: Uncaught exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 7: Failed to connect to api.sendgrid.com port 443: Connection timed out [url] https://api.sendgrid.com/api/mail.send.json' in /sendgrid-php/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php:359

The error also produced a long stack trace, which I'll leave out for now because I feel it's unnecessary. What I found in the stack trace was that the error occurred in /sendgrid-php/lib/SendGrid.php on line 138, which the line simply reads: $res = $req->send();

I found [this StackOverflow question](http://stackoverflow.com/questions/29617480/how-to-handle-fatal-error-curl-error-7-failed-to-connect-to-xxxx-port-443) related to the error. I believe the line the error occurred on which I mentioned above (line 138 of /sendgrid-php/lib/SendGrid.php) should be wrapped in a try/catch block, but I'm unsure if I'm right about this and that's why I'm posting this issue.

Preferably I'd like it if the failed to connect error was identifiable in the response when sending ($sendgrid->send($email);) an email, so that I can have the script try to send again later instead of marking the email as failed to send. I am unsure of how to go about doing this though.

Thank you for any support!

**Comment by thinkingserious** [comment]
Thanks for taking the time to explain, we appreciate it!

First, have you tried turning on guzzle_exceptions? https://github.com/sendgrid/sendgrid-php/blob/master/lib/SendGrid.php#L66

Second, it looks like we should be catching the exception here: https://github.com/sendgrid/sendgrid-php/blob/master/lib/SendGrid.php#L119, but if Guzzle exceptions are turned off, maybe that particular error slips through.

I have not tested any of the above, but it will be some time before I can, so I thought I'd offer some pointers :)

**Comment by elevatednetwork** [comment]
Ahh, I see, thank you so much! 

I'm assuming guzzle exceptions are turned off by default? I'm using all default options.
I'll turn it on now, is there any way to emulate a timeout for me to test it?

**Comment by thinkingserious** [comment]
I don't know the default for the exceptions. 

Try adding 10.255.255.1 api.sendgrid.com into /etc/hosts to simulate the timeout.

**Comment by elevatednetwork** [comment]
Today (06-Nov-2015) at 17:25 an error exception occurred with Guzzler, 
**35: Unknown SSL protocol error in connection to api.sendgrid.com:443**.

This was after I set enable_guzzle_exceptions to true in the sendgrid class options.
Here is a snippet of the code I used:
```
$sendgrid_options = array(
	'enable_guzzle_exceptions' => true
);

$sendgrid = new SendGrid($sendgrid_account_user, $sendgrid_account_pass, $sendgrid_options);

$email = new SendGrid\Email();

... Setting all necessary $email values (ex. $email->addTo($email_to);) ...

try {
	$return = $sendgrid->send($email);
}catch(\SendGrid\Exception $e) {
	$err[] = 'Error Code: ' . $e->getCode();
	foreach($e->getErrors() as $er) {
		$err[] = $er;
	}
}
```

I'm unsure why this exception wouldn't have been caught. Possibly I messed something up? Should I also be setting the sendgrid class option *verify*?

Here is copy of the error log report with the stack trace:
```
[06-Nov-2015 17:25:02 America/Los_Angeles] PHP Fatal error:  Uncaught exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 35: Unknown SSL protocol error in connection to api.sendgrid.com:443  [url] https://api.sendgrid.com/api/mail.send.json' in /sendgrid/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php:359
Stack trace:
#0 /sendgrid/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(292): Guzzle\Http\Curl\CurlMulti->isCurlException(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
#1 /sendgrid/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(257): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
#2 /sendgrid/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(240): Guzzle\Http\Curl\CurlMulti->processMessages()
#3 /sendgrid/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(224): Guzzle\Http\Curl\CurlMulti->executeHandles()
#4 /sendgrid/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(111): Guzzle\Http\Curl\CurlMulti->perform()
#5 /sendgrid/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMultiProxy.php(94): Guzzle\Http\Curl\CurlMulti->send()
#6 /sendgrid/vendor/guzzle/guzzle/src/Guzzle/Http/Client.php(284): Guzzle\Http\Curl\CurlMultiProxy->send()
#7 /sendgrid/vendor/guzzle/guzzle/src/Guzzle/Http/Message/Request.php(198): Guzzle\Http\Client->send(Object(Guzzle\Http\Message\EntityEnclosingRequest))
#8 /sendgrid/lib/SendGrid.php(138): Guzzle\Http\Message\Request->send()
#9 /sendgrid/lib/SendGrid.php(117): SendGrid->postRequest('/api/mail.send....', Array)
#10 {main} thrown in /sendgrid/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php on line 359
```

Thank you!

**Comment by thinkingserious** [comment]
I'm thinking you might have "turn_off_ssl_verification" set to true. Can you verify?

Otherwise, this might point you in the right direction: http://stackoverflow.com/questions/19171475/goutte-tlsv1-protocol-version-error

Thanks for the follow up!

**Comment by elevatednetwork** [comment]
I hadn't set "turn_off_ssl_verification" at all, so in the options I set "turn_off_ssl_verification" to false. I also have "enable_guzzle_exceptions" set to true, along with a try/catch around $sendgrid->send() as I previously mentioned. However I am still getting the same exact issue.

I noticed in the source code there is also a "raise_exceptions" option. Should I set this to true just be make sure it throwing exceptions?

**Comment by thinkingserious** [comment]
You can also try catching the exception directly from Guzzle, like this: http://stackoverflow.com/a/19007337

Either way, please let me know what your testing reveals. Thanks!

**Comment by elevatednetwork** [comment]
First of all, I noticed there have been some updated to this library so I went ahead and updated it on my end. The same error was still occurring after update.

As for the SO question you linked, the answer accepted I had already tried to no avail. I also tried the answer posted by "Dado" and again the same exact error is occurring. However, I was only able to implement the first code block that "Dado" posted, I had some issues trying to get the other two code blocks implemented but I didn't think it was that important because he mentioned that those 2 code blocks were for trying to catch the Guzzle errors. I'm just trying to stop them from causing a fatal error on my script.

Something new happened today, this error is now occurring almost every single time I try to use $sendgrid->send(). The key part is "almost every single time" because every once in a while a request goes through successfully. It seems to be completely random, so I think it truly does have something to do with the script timing out when requesting https://api.sendgrid.com/api/mail.send.json.

I can also verify it has nothing to do with the content I'm sending because on the first request it will timeout on a specific email send, but on second request the email send it timed out on before goes through perfectly and then it times out on a different email send.

To clarify about the error occurring, every single time it occurs even after this library update, it says exactly the same thing, including which lines it occurred on, as the error log report I posted above on Nov 6.

Thanks for everything.

**Comment by elevatednetwork** [comment]
Also, I wanted to say that the script I'm sending the request from is not on SSL. This seems to have something to do with SSL. Even if I am able to prevent these errors from crashing my script, it still means that this timeout is occurring causing an email send to not get sent. I want to prevent the script from experiencing this timeout.

**Comment by thinkingserious** [comment]
Thanks for the update @elevatednetwork. It sounds like you are indeed having a server mis-configuration problem. Could you provide more details about your server? What happens when you run your code locally or on another server?

With regards to "Dado"'s solution, by implementing the code blocks to catch the errors, that should allow you to avoid the fatal error. But that does not solve the root problem.

**Comment by elevatednetwork** [comment]
I haven't tried to run it locally or from another server yet, I will as soon as I can though. However, I found a sort of temporary solution for the moment though. Since we've been sending email to SendGrid to send out we've always had an internal "email queue" table which out clients emails are put into, then there is a CRON job that sends X amount of emails from the queue to SendGrid. This CRON job was set to run every other minute (*/2 * * * *) and I thought that maybe the timeout was caused because we are sending emails to the SendGrid API too often. I changed the CRON job to run every 5 minutes and I haven't had the error occur since. 

Is it possible that sending requests to the SendGrid API too often may cause this timeout problem? I looked through some documentation and didn't see anything related mentioned anywhere.

**Comment by idimensionz** [comment]
According to the SendGrid API documentation, there are rate limits (see https://sendgrid.com/docs/API_Reference/Web_API_v3/index.html#-Rate-Limits).  I'm not sure that this PHP API client currently checks the response from the API to see if the limit has been reached.  For the PHP API client I'm writing, I do capture that information and make it available.

**Comment by elevatednetwork** [comment]
So after a week of no more errors occurring I can confidently say that the problem I was having was caused by SendGrids Web API rate limits. I was sending requests to the API too quickly. After changing my CRON job, which sends a request to the API, from once every two minutes to once every five minutes I haven;'t experienced the issue.

Thank you @idimensionz for the tip.
Thank you @thinkingserious for your support.

My only question would be as to why this library doesn't check the response from the API to see if the limit has been reached?

**Comment by idimensionz** [comment]
@elevatednetwork You're welcome!  Glad I could help.  The Rate Limit info is only made available in the headers of the HTTP response of calls to **v3** of the SendGrid API.  It can be a bit messy to grab that info however, I've built my PHP API client from the ground up to make that info available in each response to an API call.  My response object contains the HTTP status code, the content type, the rate limit info (limit, remaining and reset date/time), errors, and the actual content of the response.
