### ISSUE TITLE
problem class not found

### ISSUE THREAD

**Issue by andrezhu97** [sendgrid/sendgrid-php#174]
Fatal error: Class 'Guzzle\Http\Client' not found in /membri/handbag3600/SendGrid.php on line 85 
what problem it could be?

**Comment by dufoli** [comment]
I have exactly the same issue. Do you find why ?

**Comment by andrezhu97** [comment]
you have to read with attention the istruction on the home because the files that we are using wasn't correct. i resolved in this way, watch the istrution on the home
