### ISSUE TITLE
HTTP 406 Not Acceptable Errors

### ISSUE THREAD

**Issue by gsaqui** [sendgrid/sendgrid-php#177]
When extending the the Client to send GET requests to `/v3/suppression/bounces` I am getting `406 Not Acceptable` as a response.  I see that the python library has added an Accept header.  When I've done this to my local copy it seems to fix the problem.  If this is the correct solution can you please add it to the lib\Client.php file please?

**Comment by brandonmwest** [comment]
Hi, are you using Google App Engine? We had an issue but it should be resolved now.

**Comment by gsaqui** [comment]
No I was running locally and only had the issue when I hit `/v3/suppression/bounces`.  I was able to fix the issue locally with the following line in lib\Client.php:
```
        $guzzleOption['request.options']['headers'] = array('Authorization' => 'Bearer ' . $this->apiKey, 'Content-Type' => 'application/json', 'Accept' => '*/*');
```

Notice I added ` 'Accept' => '*/*'` as a header.  This seemed to fix the problem.

**Comment by brandonmwest** [comment]
Ah, gotcha, thanks. We will get that header added.

**Comment by thinkingserious** [comment]
@gsaqui Fixed with this release [v4.0.1](https://github.com/sendgrid/sendgrid-php/releases/tag/v4.0.1)

Thanks for bringing this to our attention and providing your fix!

**Comment by rajatmasih-web4realty** [comment]
I am using Php CURL method and tried by added Accept header but it won't work at all.I am getting this in response with 406 http status and Sometime it works and sometimes not.
Response : <html>\r\n<head><title>406 Not Acceptable</title></head>\r\n<body bgcolor="white">\r\n<center><h1>406 Not Acceptable</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n

**Comment by childish-sambino** [comment]
@rajatmasih-web4realty Please open a new issue.
