### ISSUE TITLE
Support for batch_id in scheduled sends.

### ISSUE THREAD

**Issue by notsentient** [sendgrid/sendgrid-php#180]
Hi, I've looked through the documentation and the repo code and couldn't find any references to the batch_id smtpapi header parameter as described [here](https://sendgrid.com/docs/API_Reference/SMTP_API/scheduling_parameters.html).
This is a pretty useful feature for being able to cancelled a scheduled email batch!

Is there a time-frame on when this might be implemented or am I better off fork it and having a go myself?

**Comment by nolan-interactive** [comment]
I agree with @notsentient, would indeed be useful to set the batch_id when calling the setSendAt method.

**Comment by thinkingserious** [comment]
@notsentient you would be better off to fork it as of right now. Thanks for offering to do so!

**Comment by elevatednetwork** [comment]
@notsentient If you do happen to get it working please let me know. I've been trying to tackle this myself with no luck.

**Comment by thinkingserious** [comment]
Hello @notsentient and @tyler-hughes,

We have added the ability to set a batch_id in our new v3 /mail/send endpoint. Here is an example: https://github.com/sendgrid/sendgrid-php/blob/v3beta/examples/helpers/mail/example.php#L101

Please let me know if you need further help.

With Best Regards,

Elmer
