### ISSUE TITLE
Authentication issue with the sendgrid-php packaged library (v3.2.0)

### ISSUE THREAD

**Issue by omodica** [sendgrid/sendgrid-php#181]
Starting sometime today (2015/12/07) we are seeing authentication issues using our API keys.

We've made no changes to our account settings or API key settings, and what used to work now returns: 

```json
{
  "errors": ["Authenticated user is not authorized to send mail"],
  "message": "error"
}
```

We are currently using the latest available packaged library, which is based off v3.2.0. I haven't yet tried with the newest release (v4.0.1).

Note that this user is also experiencing the issue: https://community.sendgrid.com/sendgrid/topics/authenticated-user-is-not-authorized-to-send-mail

Thanks!
Olivier.

**Comment by mbernier** [comment]
Can you please check the API Key permissions for the Key that you are using to send mail?  

https://app.sendgrid.com/settings/api_keys Then click the gear icon and choose "Edit details". The mail.send permission should be turned on for your mail sending key.

**Comment by omodica** [comment]
Hi,

I've verified that all permissions are set to the most permissive values, however I'm not seeing a permission that seems specific to mail.send. To be clear we've made so account or API key settings changes.

Thanks.

**Comment by mbernier** [comment]
![sendgrid](https://cloud.githubusercontent.com/assets/169448/11646938/ec6df2a0-9d1f-11e5-9fa0-7866dc2540a5.jpg)

Are you seeing this permissions value?

**Comment by omodica** [comment]
No, it's not there. It's not available whether I update an existing API key (which used to work) or when I choose to create a new General API key. Let me know what I can provide publicly or privately to identify our account.

**Comment by mbernier** [comment]
hey, the easiest way to verify yourself and to get someone on this ASAFP - is to email support@sendgrid.com. Tell them you were talking to me and reference this github issue so they have the history.

**Comment by omodica** [comment]
Thanks Matt, I sent the email. I'll close this issue once it's resolved, I guess it has nothing to do with the PHP SDK.

**Comment by mbernier** [comment]
Nope, but thanks for letting us know. I have hit up the support folks and they are looking forward to helping out!

**Comment by omodica** [comment]
Support was able to resolve the issue on our account; thanks again.

**Comment by mbernier** [comment]
No problem. Sorry for the trouble!!
