### ISSUE TITLE
Chatroom for questions and discussions related to SendGrid PHP API

### ISSUE THREAD

**Issue by idimensionz** [sendgrid/sendgrid-php#182]
Hey everyone!  This isn't really an issue but wasn't sure the proper place to post this. I thought it might be helpful to have a chat room where contributors (and those interested in the SendGrid PHP API developement) could get together to ask coding questions and have discussions related to the SendGrid PHP API.  I created a chatroom on HipChat.  You can use the following link to sign up for a free account and join the chatroom https://www.hipchat.com/invite/499355/712a407d35f5389b5a76ed97d819444f?utm_campaign=company_room_link . If there's a better place to post this info, let me know and I'll move it.

**Comment by mbernier** [comment]
Hey, this is really interesting! I will talk to our people and see what they want to do. Thanks!!

**Comment by thinkingserious** [comment]
We have this on our roadmap. Thanks again for the idea!
