### ISSUE TITLE
Guzzle 3 package is deprecated but still used by SendGrid

### ISSUE THREAD

**Issue by achraf52** [sendgrid/sendgrid-php#184]
While installing sendgrid-php via Composer, I have received a notice that the guzzle/guzzle dependency is Guzzle 3 which is deprecated and has moved to a new name.

The notice:
guzzle/guzzle suggests installing guzzlehttp/guzzle (Guzzle 5 has moved to a new package name. The package you have installed, Guzzle 3, is deprecated.)

Please check this out and take action.

**Comment by idimensionz** [comment]
Hi @achraf52 , this issue was raised previously in issue https://github.com/sendgrid/sendgrid-php/issues/156 .  You may also wish to review the comments on pull request https://github.com/sendgrid/sendgrid-php/pull/161.

**Comment by thinkingserious** [comment]
@achraf52 Thank you for the additional feedback. We have this modification currently under consideration as we work through updating all of our libraries for our Web API v3 endpoints. Keep an eye on this repo for updates.

@idimensionz Thanks for pointing @achraf52 in the right direction :)

**Comment by achraf52** [comment]
Thanks everyone, I have been unable to find open issues in sendgrid-php on Guzzle 3 being deprecated, so that's why I've raised this issue here. I'll have a look at the pull request comments.
