### ISSUE TITLE
Are there plans for Symfony 3 support?

### ISSUE THREAD

**Issue by n1cklarosa** [sendgrid/sendgrid-php#185]
We use Google Cloud Engine and you can't connect to Sendgrids STMP servers due to their policy. 
Thanks!

**Comment by thinkingserious** [comment]
You should be able to use SendGrid within Symfony 3 by including this library in the vendor folder. 

Otherwise, we don't have any specific plans for further integration. What did you have in mind?

**Comment by n1cklarosa** [comment]
I see, thanks for this. I have been trying to install using Composer (and
more than likely just dont know what I am doing) as my app has quite a few
productions environments, and we try to employ package management where we
can.

Here are the results I get when attempting to install this package using
'composer require sendgrid/sendgrid'

    - don't install symfony/event-dispatcher v2.7.7|don't install
symfony/symfony v3.0.1
    - don't install symfony/event-dispatcher v2.7.8|don't install
symfony/symfony v3.0.1
    - don't install symfony/event-dispatcher v2.8.0|don't install
symfony/symfony v3.0.1
    - don't install symfony/event-dispatcher v2.8.1|don't install
symfony/symfony v3.0.1
    - Installation request for symfony/symfony == 3.0.1.0 -> satisfiable by
symfony/symfony[v3.0.1].
    - Installation request for sendgrid/sendgrid ^4.0 -> satisfiable by
sendgrid/sendgrid[4.0.0, 4.0.1, 4.0.2].

I will use the suggested method for the time being. thank you !

On Wed, Jan 13, 2016 at 3:38 AM, Elmer Thomas <notifications@github.com>
wrote:

> You should be able to use SendGrid within Symfony 3 by including this
> library in the vendor folder.
>
> Otherwise, we don't have any specific plans for further integration. What
> did you have in mind?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sendgrid/sendgrid-php/issues/185#issuecomment-170968467>
> .
>



-- 
-- 
Nick La Rosa
0413 735 610 - nick@nicklarosa.net - @nick_la_rosa
<http://twitter.com/nick_la_rosa>
Artist Management nlrmgmt.com

**Comment by pedrocasado** [comment]
Related topic (https://github.com/sendgrid/sendgrid-php/issues/194) which has a working solution.
