### ISSUE TITLE
Templates and v3

### ISSUE THREAD

**Issue by austinh** [sendgrid/sendgrid-php#186]
Templates are frustrating to use because you have to set the subject and the body, even though those are already being used in the template.
Are there any plans to improve the sendgrid api for v3? I looked back into the past issues and it looks like there were plans several months ago but no movement, and using templates is quite frustrating.

Thanks

**Comment by mbernier** [comment]
We are currently working on the v3 endpoint for sending mail. This is one of the things we have looked at for a feature on that endpoint.
