### ISSUE TITLE
Guzzle not found?

### ISSUE THREAD

**Issue by jeromeramone** [sendgrid/sendgrid-php#191]
I've been using sendgrid-php with no problems for a year or more.  Suddenly a few days ago, every page that sends email is giving this error:

Fatal error: Class 'Guzzle\Http\Client' not found in /var/www/vhosts/thebumbershoot.com/httpdocs/sendgrid/lib/SendGrid.php on line 71

I'm an oldschool, self-taught programmer and am confused about what's going on!  Is Guzzle supposed to actually exist in the files of sendgrid-php?  Because I can't find it anywhere...

Or is Guzzle some sort of module that's installed on the server.  I am just using an old linux shared hosting account, so I don't handle server updates myself.  I certainly never installed Guzzle when I first set up sendgrid-php a year ago.

Can anyone explain this to me?

Thanks in advance.

**Comment by trousers** [comment]
Guzzle is a dependency of sendgrid. 'Guzzle\Http\Client' is the namespace which is registered by composer which then autoloads it when the application is run. Guzzle is installed in the vendors directory which should be in the root of your project. Have a look there. Any guzzle in there? IF not run composer install (or php composer.phar install) in the same directory as composer.json (should be in the root)

**Comment by thinkingserious** [comment]
Thanks for the answer @trousers!

@jeromeramone does that solve your issue?

**Comment by dufoli** [comment]
I got the same error. 
On my side, I have guzzle in lib/vendor.sendgrid-php/vendor.guzzle
I have another version which I use for other needs in vendor/guzzlehttp

The second one is a version 6.1

whereas sendgrid one is a 3.9.
Can it be a conflict? Because up to now I have never do composer install for our project and sendgrid was integrate with a zip which contain ever the guzzle

**Comment by trousers** [comment]
They need to upgrade to guzzle 6. If they want to continue supporting old php then keep version ~4.0 guzzle 3  and make 5.0 guzzle 6.

Side note: I installed fastglass/send-grid which has implemented guzzle 6 but it doesn't support username/password auth

**Comment by thinkingserious** [comment]
Thanks again for the answer @trousers 

Is there anything else we can help with @dufoli? If so, please re-open this ticket.
