### ISSUE TITLE
Undefined property: SendGrid\Response::$message

### ISSUE THREAD

**Issue by m-menon** [sendgrid/sendgrid-php#192]
I am using the latest version of sendgrid php and I encounter the below problem when using this code
```
$response = $sendgrid->send($sendgrid_email);
//
if (!$response) {
 throw new Exception("Did not receive response.");
} else if ($response->message && $response->message == "error") {
 throw new Exception("Received error: ".join(", ", $response->errors));
```

The line that's throwing the error is:
```
} else if ($response->message && $response->message == "error") {
```

And the error is:
**Notice: Undefined property: SendGrid\Response::$message in /app-root/repo/register.php on line...**

Strangely it had been working before and suddenly this error started to show up. Any pointers will be greatly helpful. Thanks

**Comment by m-menon** [comment]
any comments?

**Comment by idimensionz** [comment]
You could try `($response->getBody())['message']`

**Comment by m-menon** [comment]
ok cool thanks, will try it out :-)

**Comment by thinkingserious** [comment]
Thanks for jumping in and helping @idimensionz!

@m-menon please let us know if you need further help and thanks for supporting SendGrid!

**Comment by m-menon** [comment]
Thanks a lot @idimensionz and @thinkingserious :+1:
