### ISSUE TITLE
Call to a member function toWebFormat()

### ISSUE THREAD

**Issue by helloarpitgshah** [sendgrid/sendgrid-php#199]
Hey,

Hope you are doing good...

I have integrate the SendGrid PHP API Library and whenever I am going to call the Sendgrid from the Model then I got the following error,

<b>Fatal error</b>:  Call to a member function toWebFormat() on a non-object in 

Can you please help me out?

Thanks,

**Comment by Dreyer** [comment]
It sounds like the `$email` variable you might be passing to `$sendgrid->send($email);` is not of the type `SendGrid\Email`, however it's a little difficult to diagnose your issue without a code snippet.

**Comment by thinkingserious** [comment]
Hello @helloarpitgshah,

@Dreyer is correct, please provide us with a code snippet so we can further assist.

Thanks!

**Comment by helloarpitgshah** [comment]
We have resolved the issues, Thanks for your response.

**Comment by thinkingserious** [comment]
@helloarpitgshah awesome, thanks for the follow up!
