### ISSUE TITLE
Confused in implementation

### ISSUE THREAD

**Issue by Ibad021** [sendgrid/sendgrid-php#205]
Hi,
  I have read all documentation but I am so much confused what to use. Currently I have created templates in sendgrid I want to send emails using that templates. Please tell me which library I should install ? which code to use? Please guide me step by step

Thanks,

**Comment by thinkingserious** [comment]
Hello @Ibad021,

If you use this library, here is the documentation for sending templates: https://github.com/sendgrid/sendgrid-php#templates

If you just want to use curl, here is an example: https://github.com/sendgrid/sendgrid-php/blob/master/example_v2_template.php

If you would like additional options or support, please reach out to support@sendgrid.com.

Thanks!

With Best Regards,

Elmer

**Comment by Ibad021** [comment]
Thank you Elmer, You were so helpfull

On Thu, Mar 3, 2016 at 9:51 PM, Elmer Thomas <notifications@github.com>
wrote:

> Closed #205 <https://github.com/sendgrid/sendgrid-php/issues/205>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sendgrid/sendgrid-php/issues/205#event-576521662>.
>



-- 








*Regards,*
* Ibad ur Rehman Khan*
