### ISSUE TITLE
Call to a member function get() on null

### ISSUE THREAD

**Issue by patrickomeara** [sendgrid/sendgrid-php#206]
I have just updated to the latest SDK 4.0.4 Mail is sending fine but api_keys and asm_groups is not working as the documentation states.

```php
$client->api_keys->get();
```
also happening for
```php
$client->asm_groups->get();
```

```
Call to a member function get() on null
```

**Comment by thinkingserious** [comment]
@patrickomeara I need some further context to solve this issue. Could you please provide the surrounding code, redacting your credentials?

Also, this library will shortly replaced with this one: https://github.com/sendgrid/sendgrid-php/tree/v3beta

In the new library, that call would be executed as follows: https://github.com/sendgrid/sendgrid-php/blob/v3beta/examples/example.php#L37
