### ISSUE TITLE
Fatal error: Class 'Guzzle\Http\Client' not found in SendGrid.php on line 85

### ISSUE THREAD

**Issue by kheme** [sendgrid/sendgrid-php#207]
I installed sendgrid-php from .zip, and when I run it, I get the following error:

> Fatal error: Class 'Guzzle\Http\Client' not found in SendGrid.php on line 85

I've looked all over and I cannot figure out how to resolve this.

Please help. Thanks

**Comment by idimensionz** [comment]
Guzzle is a dependency that is managed by the dependency manager named composer.  So, you will need to make sure the server where you unzipped your zip file has composer installed.  See https://getcomposer.org/doc/00-intro.md#installation-linux-unix-osx for details on installing composer.

Once composer is installed, you'll need to run `composer install` in the directory where you unzipped the files.  This will evaluate the composer.lock or composer.json file and install all the dependencies defined in those files including guzzle.

**Comment by thinkingserious** [comment]
Thanks @idimensionz!

If this does not solve your issue @kheme, please feel free to re-open this issue.
