### ISSUE TITLE
File attachments only result in a one line file

### ISSUE THREAD

**Issue by sdclee** [sendgrid/sendgrid-php#210]
Hi there.
I have tried every which way to get a simple php API script working with the single file attachment example.
Either of these two lines (one with full path the other without a path, implying current directory) results in a flat file the contents of which are the 'at' symbol and filename:

**'files['.$fileName.']' => '@'.dirname(__FILE__).'/'.$fileName**
or
**'files['.$fileName.']' => '@'.$fileName,**

So the actual file itself never gets attached. This is the same behaviour on both windows and linux platforms.

I tried using the class example instead but it just falls over with an exception due to missing "Guzzle"  (there's also a syntax error which I corrected). I'd prefer to stick with the simple API if possible.
After trawling the net (and here) I can't find any references to it failing for others.

Any clues gratefully received.

Thanks in advance.
Lee

**Comment by thinkingserious** [comment]
Hello @sdclee,

We are in the process of rewriting this library to support all Web API v3 endpoints. The new library will no longer depend on Guzzle. Here is the client we will be using: https://github.com/sendgrid/php-http-client

For now, if you don't want to use Guzzle, you might try using curl directly: https://sendgrid.com/docs/Integrate/Code_Examples/php.html

Thanks!

**Comment by sdclee** [comment]
Thanks for the reply. If you look at the code fragment I posted you will see that it is from the curl example but the attachment fails. It always attaches a file as a one line test contains the '@' symbol and the filename itself.
Maybe you could offer an explanation for this errant behaviour?
Thanks in advance.
L
ee

**Comment by thinkingserious** [comment]
I don't see what is going wrong in those two lines of code. Would you mind sharing the rest of the relevant code for additional context? Thanks!

**Comment by sdclee** [comment]
Ok I'll re-state the issue originally described.
Whichever option I use (current directory or full path) the file that becomes the attachment looks at first as it is correct in the email client (say for example a PDF document) but on loser inspection the file's content comprises a single line describing the path/filename preceeded by the '@' symbol, e.g.:
@pslp_PTR_0074860.pdf
This is the content of the attachment I fot when trying to send the test script itself (sendgridfoo2.php):
@sendgridfoo2.php
I emphasise here that it doesn't make any difference whether the path + filename is used or just filename. Here's the results after sanitising the path for Windows:
@D:\SDC\sendgrid-php-master\sendgridfoo2.php

So in both cases the file attachment contains only the line "@whateverTheFileNameIs"
I hope you are able to spot what might be wrong.

**Comment by mbernier** [comment]
Please let me ask another way: You are getting the filename as the content of the file attached to the resulting email, rather than the contents of the file you are expecting?

**Comment by sdclee** [comment]
That's correct.
Thanks

**Comment by thinkingserious** [comment]
I could not get the example here working either: https://sendgrid.com/docs/Integrate/Code_Examples/php.html - I will add this to our backlog to troubleshoot.

In the mean time, I was able to get success using our current library with this code:
```
sendgrid-php-example.php
<?php
require 'vendor/autoload.php';
Dotenv::load(__DIR__);

$sendgrid_username = $_ENV['SENDGRID_USERNAME'];
$sendgrid_password = $_ENV['SENDGRID_PASSWORD'];
$to  = $_ENV['TO'];

$sendgrid = new SendGrid($sendgrid_username, $sendgrid_password, array("turn_off_ssl_verification" => true));
$email    = new SendGrid\Email();
$email->addTo($to)->
       setFrom($to)->
       setSubject('[sendgrid-php-example] Owl named %yourname%')->
       setText('Owl are you doing?')->
       setHtml('<strong>%how% are you doing?</strong>')->
       addSubstitution("%yourname%", array("Mr. Owl"))->
       addSubstitution("%how%", array("Owl"))->
       addHeader('X-Sent-Using', 'SendGrid-API')->
       addHeader('X-Transport', 'web')->
       addAttachment('./gif.gif', 'owl.gif');

$response = $sendgrid->send($email);
var_dump($response);
```

Here is what's in my composer.json file:
```
{
  "name": "sendgrid-php-example",
  "description": "Example of using the SendGrid php library.",
  "version": "0.1.1",
  "homepage": "http://github.com/scottmotte/sendgrid-php-example",
  "license": "MIT",
  "keywords": ["SendGrid", "sendgrid", "email", "send", "grid", "php"],
  "require": {
    "sendgrid/sendgrid": "~4.0",
    "sendgrid/smtpapi": "~0.5",
    "vlucas/phpdotenv": "1.0.*"
  }
}
```
And the .env:
```
SENDGRID_USERNAME=xxxxx
SENDGRID_PASSWORD=xxxxx
TO=elmer@sendgrid.com
```
Also, I've not tried this using our [new HTTP Client](https://github.com/sendgrid/php-http-client), but that might be worth a try too.

**Comment by thinkingserious** [comment]
@sdclee Our new library is nearly out of beta and here is an example of how it handles attachements: https://github.com/sendgrid/sendgrid-php/blob/v3beta/examples/helpers/mail/example.php#L83

Thanks for your support!

**Comment by jsolc** [comment]
In case you're still searching for answers and not alternative solutions: the problem is updated curl behavior (php >= 5.6) see: [https://binfalse.de/2016/06/21/forget-the-at-use-curl-file-create/](url)

**Comment by thinkingserious** [comment]
Thank you @jsolc!
