### ISSUE TITLE
PHP Fatal error due to lack of namespace on new Client class

### ISSUE THREAD

**Issue by ziemkowski** [sendgrid/sendgrid-php#211]
Version 4 added a top level `Client` class without a namespace, causing any project that already defines a `Client` class of their own to encounter:

```
PHP Fatal error:  Cannot redeclare class Client
```

Please add the class to the `SendGrid` namespace already used for the `Email` class.

CC: @jpirkey

**Comment by thinkingserious** [comment]
This library is being completely rewritten right now and it will include namespaces for all the things :)

Here is a preview (this is the client the library will use): https://github.com/sendgrid/php-http-client
