### ISSUE TITLE
Empty from email address (required) even though it's provided

### ISSUE THREAD

**Issue by wernight** [sendgrid/sendgrid-php#212]
I get the error: `Empty from email address (required)` however this is the email object being sent:

```
bcc: null
bccName: null
cc: null
ccName: null
content: null
date: null
from: "do-not-reply@example.com"
fromName: "Foo's Example"
headers: null
html: "<html>↵<body>...</body>↵</html>↵"
replyTo: false
smtpapi: Object
subject: "[Example] on 21-03-2016"
text: null
to: Array[1]
toName: null
```

Running [latest `sendgrid/sendgrid` release](https://packagist.org/packages/sendgrid/sendgrid) (version 4.0.4) which uses latest `sendgrid/smtpapi` (version 0.5.0).

Similar to issues:
  - https://github.com/sendgrid/sendgrid-nodejs/issues/178
  - https://github.com/sendgrid/sendgrid-nodejs/issues/204
  - https://github.com/nodemailer/nodemailer/issues/336

**Comment by wernight** [comment]
It seems that this issue also happens if one didn't *whitelabel* the domain used in `from`.

**Comment by wernight** [comment]
Here is the `$email->toWebFormat()` generated:

 - `from`: `do-not-reply@example.com`
 - `fromname`: `Foo's Example`
 - `x-smtpapi`: {}
 - ...

**Comment by thinkingserious** [comment]
Thanks for letting us know. I've added this to our backlog.

Could you provide the relevant code snippet?

**Comment by wernight** [comment]
Note that `example@example.com` is just an example as trying different values including whitelabeled domains doesn't change the outcome:

```
<?php
require('vendor/autoload.php');

$email = new \SendGrid\Email();
$email
    ->addTo('example@example.com', 'Foo Bar')
    ->setFrom('example@example.com')
    ->setSubject('test')
    ->setText('test');

$sendgrid = new \SendGrid(\file_get_contents('/mnt/sendgrid/api-key'));
$sendgrid->send($email);
```

```
$ php snippet.php
Fatal error: Uncaught exception 'SendGrid\Exception' with message '{"errors":["Empty from email address (required)"],"message":"error"}' in /srv/vendor/sendgrid/sendgrid/lib/SendGrid.php:120
Stack trace:
#0 /srv/snippet.php(12): SendGrid->send(Object(SendGrid\Email))
#1 {main}
  thrown in /srv/vendor/sendgrid/sendgrid/lib/SendGrid.php on line 120
```

**Comment by wernight** [comment]
I did notice that my key has a line return at the end. May be those are not properly handled/escaped.

**Comment by thinkingserious** [comment]
Hmm, I think I had  a similar issue, that I fixed with this: https://github.com/sendgrid/php-http-client/blob/master/lib/SendGrid/config.php#L31

Are you saying that once you added the trim() to your api key, it now works?

**Comment by wernight** [comment]
Yes

However I think it should be fixed as the error really is misleading

**Comment by thinkingserious** [comment]
Agreed, we'll get that into our backlog. Thanks!

**Comment by thinkingserious** [comment]
@wernight We have completely revamped our error messaging. Check out our new docs for details: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html

Thanks for your continued support!

**Comment by wizvs** [comment]
@thinkingserious I am getting the same error [Error: Empty from email address (required)]
when using nodejs sendgrid module.
Here is my code.:

sendgrid.send({
    to: 'nitefoodie@gmail.com ',
    from: 'talk@aircountr.com',
    subject: 'Report Export',
    text: 'Please find the attached exported report.',
    files: [
        {
            filename:     '',           // required only if file.content is used.
            contentType:  '',           // optional
            cid:          '',           // optional, used to specify cid for inline content
            path:         '',           //
            url:          './file.csv',           // == One of these three options is required
            content:      ('' | Buffer) //
        }
    ]
},function(err, json) {
  if (err) { return console.error(err); }
        
  console.log(json);
        res.json("Mail sent successfully");
    });

**Comment by thinkingserious** [comment]
@wizvs Please follow this issue over in the nodejs repo: https://github.com/sendgrid/sendgrid-nodejs/issues/228

I'll be responding to that ticket soon.

**Comment by ndo360** [comment]
I am now having this issue and this link now points to a 404: https://github.com/sendgrid/php-http-client/blob/master/lib/SendGrid/config.php#L31

**Comment by thinkingserious** [comment]
Hello @ndo360,

Could you please provide some further detail so that I can try and reproduce? 

Specifically:

1. Sample source code
2. Version of the SDK you are using

Thank you!

Elmer

**Comment by ndo360** [comment]
@thinkingserious Thank you for replying fast, here is the source code referenced in the error:
[sendgrid.js]
`      if (json.message !== 'success') {
        var error = 'sendgrid error';
        if (json.errors) { error = json.errors.shift(); }
        return callback(new Error(error), null);
      }`
[request.js]
`  // Protect against double callback
  if (!self._callback && self.callback) {
    self._callback = self.callback
    self.callback = function () {
      if (self._callbackCalled) {
        return // Print a warning maybe?
      }
      self._callbackCalled = true
      self._callback.apply(self, arguments)
    }`

`    if (self._json) {
      try {
        response.body = JSON.parse(response.body, self._jsonReviver)
      } catch (e) {
        debug('invalid JSON received', self.uri.href)
      }
    }
    debug('emitting complete', self.uri.href)
    if (typeof response.body === 'undefined' && !self._json) {
      response.body = self.encoding === null ? new Buffer(0) : ''
    }
    self.emit('complete', response, response.body)
  })
}`

`    responseContent.on('end', function (chunk) {
      self.emit('end', chunk)
    })`

Also I have attached the screenshot of the error displayed
![error screenshot](https://cloud.githubusercontent.com/assets/13690264/25511529/4a83fe02-2b95-11e7-80e9-728cd03d1985.PNG)

**Comment by thinkingserious** [comment]
@ndo360,

What version of the [SendGrid Node.js library](https://github.com/sendgrid/sendgrid-nodejs) are you using?

**Comment by ndo360** [comment]
@thinkingserious I manged to fix it as it turned out I missed a step, thanks for everything though!

**Comment by Sachin-Suresh** [comment]
what step had u missed...please post ur working code!

**Comment by thinkingserious** [comment]
Hi @Sachin-Suresh,

I'd be happy to try and help. Could you please post the code you are having trouble with and the error message?

Thanks!

With Best Regards,

Elmer
