### ISSUE TITLE
Move to from deprecated guzzle/guzzle to new guzzlehttp/guzzle ? 

### ISSUE THREAD

**Issue by jdespatis** [sendgrid/sendgrid-php#219]
Hello

Is there a point in the roadmap to replace guzzle/guzzle by guzzlehttp/guzzle in sendgrid php ?

The fact is I just can't install this sendgrid php in my composer with Symfony 3
(sendgrid needs guzzle/guzzle which needs symfony/event-dispatcher ~2.1, which is no more provided by Symfony 3)

As a result, sendgrid can't be used in Symfony 3 project by now
It would be nice to be able to use sendgrid !

**Comment by jdespatis** [comment]
https://packagist.org/packages/fastglass/sendgrid might be an option though

**Comment by thinkingserious** [comment]
@jdespatis yes, we are working on that now. Here is the new client we will be using (it has no dependencies): https://github.com/sendgrid/php-http-client

Please follow this repo for update. Thanks!

**Comment by jdespatis** [comment]
@thinkingserious thanks for your feedback

Do you know roughly when the new client will be released ? (in terms of months)

**Comment by thinkingserious** [comment]
The best estimate I can give you right now, is a "couple" of months.

We definitely appreciate your patience in the mean time and please let us
know if you have any feedback on our updated client.

Thanks!

On Friday, March 25, 2016, Jerome Despatis <notifications@github.com> wrote:

> @thinkingserious <https://github.com/thinkingserious> thanks for your
> feedback
>
> Do you know roughly when the new client will be released ? (in terms of
> months)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/sendgrid/sendgrid-php/issues/219#issuecomment-201349181>
>


-- 
<http://www.sendgrid.com>
Elmer Thomas
Developer Experience Engineer | Product
