### ISSUE TITLE
Strangeness: Fatal error: Class 'Guzzle\Http\Client' not found - Read before Reply

### ISSUE THREAD

**Issue by foghladha** [sendgrid/sendgrid-php#220]
I know this has been mentioned over and over again, however this is a unique case and can not find anyone that's had the same result. I'm mainly wondering if there is a list of reserved words or places you can't use sendgrid that might cause conflicts.

Function

function sendgrid($to, $from, $subject, $body) {
  require("/var/www/sendgrid-php/sendgrid-php.php");
  $sendgrid = new SendGrid("MYAPIKEY");
  $email    = new SendGrid\Email();
  $email->addTo($to)
        ->setFrom($from)
        ->setSubject($subject)
        ->setHtml($body);
  $sendgrid->send($email);
}

Now if I call this on my test_sendgrid.php file it works without a problem

$body = "My Body Text";
$subject = "Testing SendGrid";
$to      = "Foghladha <my@email.com>";
$from    = "Foghladha <my@email.com>";
 sendgrid($to, $from, $subject, $body) ;`

However if I execute this code on my live script for site registrations I get:

PHP Fatal error: Class 'Guzzle\Http\Client' not found in /var/www/sendgrid-php/lib/SendGrid.php on line 85

Here's where it gets really strange. When I put the file in the root directory it breaks. When I put it in a subfolder it works. I'm using full paths for includes. 

  require("/var/www/sendgrid-php/sendgrid-php.php");

Is anything inside sendgrid not using full paths where it needs to be in a subdirectory to work?

*confused*

**Comment by foghladha** [comment]
Found the problem. In:
/var/www/sendgrid-php/sendgrid-php.php

both of the requireds we're set to a variable path:
<?php
require 'vendor/autoload.php';
require 'lib/SendGrid.php';
?>

I changed that to: 
<?php
require '/var/www/sendgrid-php/vendor/autoload.php';
require '/var/www/sendgrid-php/lib/SendGrid.php';
?>

and it worked.

**Comment by foghladha** [comment]
You can close this if you like now that I figured out what was causing the weirdness.

Root Directory = PHP Fatal error: Class 'Guzzle\Http\Client' not found in /var/www/sendgrid-php/lib/SendGrid.php on line 85

Sub Directory = No Error

Changing the _sendgrid-php.php_ to reflect full paths fixed the problem

**Comment by thinkingserious** [comment]
Thank you for sharing the solution with us!
