### ISSUE TITLE
Can't attach a file

### ISSUE THREAD

**Issue by renoirfaria** [sendgrid/sendgrid-php#222]
Hello guys, i want to attach a file but i am receiving the following error:

> Fatal error: Uncaught Guzzle\Common\Exception\InvalidArgumentException: Unable to open proposta.pdf for reading in C:\xampp\htdocs\phi\sistemas\sendgrid\vendor\guzzle\guzzle\src\Guzzle\Http\Message\PostFile.php:53 Stack trace: #0 C:\xampp\htdocs\phi\sistemas\sendgrid\vendor\guzzle\guzzle\src\Guzzle\Http\Message\PostFile.php(28): Guzzle\Http\Message\PostFile->setFilename('proposta.pdf') #1 C:\xampp\htdocs\phi\sistemas\sendgrid\vendor\guzzle\guzzle\src\Guzzle\Http\Message\EntityEnclosingRequest.php(199): Guzzle\Http\Message\PostFile->__construct('files[proposta....', '@proposta.pdf', NULL, NULL) #2 C:\xampp\htdocs\phi\sistemas\sendgrid\vendor\guzzle\guzzle\src\Guzzle\Http\Message\RequestFactory.php(106): Guzzle\Http\Message\EntityEnclosingRequest->addPostFile('files[proposta....', '@proposta.pdf') #3 C:\xampp\htdocs\phi\sistemas\sendgrid\vendor\guzzle\guzzle\src\Guzzle\Http\Client.php(201): Guzzle\Http\Message\RequestFactory->create('POST', 'https://api.sen...', NULL, Array) #4 C:\xampp\htdocs\phi\sistemas\sendgrid\vendor\g in C:\xampp\htdocs\phi\sistemas\sendgrid\vendor\guzzle\guzzle\src\Guzzle\Http\Message\PostFile.php on line 53

```
<?php
//sendgrid entrando em ação
$sendgrid = new SendGrid(':D');
$email = new SendGrid\Email();
$email
    ->addTo('.$_POST["email"].')
    ->setFrom('contato@renoir.com')
    ->setSubject('Proposta Phishing')
    ->setText('Hello World!')
    ->setHtml('<strong>Chegou!</strong>')
    ->addAttachment("proposta.pdf")
;

$sendgrid->send($email);

// Or catch the error

try {
    $sendgrid->send($email);
} catch(\SendGrid\Exception $e) {
    echo $e->getCode();
    foreach($e->getErrors() as $er) {
        echo $er;
    }
}
?>

```

**Comment by thinkingserious** [comment]
I believe the filename must be in the format @/path/to/proposta.pdf

**Comment by thinkingserious** [comment]
I will assume that since you thumbs up my answer, you are good to go :)

BTW, this library will be replaced with this version very soon: https://github.com/sendgrid/sendgrid-php/tree/v3beta

Check out how our new v3 /mail/send beta endpoint handled attachments here: https://github.com/sendgrid/sendgrid-php/blob/v3beta/examples/helpers/mail/example.php#L83

Thanks!

**Comment by renoirfaria** [comment]
@thinkingserious Yes, your answer enlightened me, thank you!
