### ISSUE TITLE
Namespace 'Client' class.

### ISSUE THREAD

**Issue by patricknelson** [sendgrid/sendgrid-php#223]
Is there any particular reason why the `Client` class was not namespaced? This seems like a common class name (very generic) and shouldn't exist in the global namespace like this. Would it be alright to refactor this so that it is setup in the `SendGrid\` namespace instead starting with the next minor release, e.g. `4.1`?

**Comment by patricknelson** [comment]
While I'm at it, out of curiosity: Is there any particular reason why the `Client` class exists? It seems to have functionality duplicated from the `SendGrid` but adds a few extra HTTP verbs to the REST'ful implementation. Would it make more sense to refactor this to unify it under a single API and have it properly namespaced? It's a little bit confusing coming into it with fresh eyes, that's all :smile:

**Comment by thinkingserious** [comment]
The new version, which is under development and near release, of this library has proper namespacing. The client has been extracted to it's own repo and is already available here: https://github.com/sendgrid/php-http-client

Originally, that new `Client` class was to support the v3 version of our API.

**Comment by patricknelson** [comment]
Aw it's already at `v1`! I was going to submit a ninja PR or two, just because I wanted to get in early before it's "stable". At any rate, what is offered by the `Client` library that's not already easily available in other libraries like `Guzzle`? That library, for example, already provides an OOP interface to `curl` without necessarily tightly binding you to the actual implementation (i.e. instead of `curl` you could be using PHP's stream wrapper or even sockets).

It looks like the concept there is just to allow URI construction via method chaining. However, is that simpler than just using native strings and interpolation in PHP? e.g. `$curl->put("/your/api/$param", $data)`???

**Comment by patricknelson** [comment]
What I noticed chiefly was the primary difference between your v3 and v2 api's was the switch between `/api/*` in the URI prefix to simply using `/v3/*` instead. Everything else is just an abstraction on top of standard REST.

In my mind, both API's can be easily interacted with using a standard library like `Guzzle` with maybe some extra sugar on top of that to automatically prefix requests (e.g. protocol, domain and maybe the `/v3/*` prefix) and then setting up complex data structures as explicit types for both input/output, like your collection of `APIKeys` or `ASMGroups` and other objects under the `Resources` namespace. Also maybe the manual footwork required in creating a real PHP API which simply is a list of methods or objects which actually are a PHP implementation of those requests going to your REST'ful API. Otherwise, if you make it magical (i.e. use of magic methods) it's no different than me simply typing the string/URI to the REST'ful endpoint. Otherwise, it's nice to have a library which actually exposes an actual chain of methods like:


```php
<?php
$response = $sendGrid->contactdb()->lists($listId)->recipients()->post([ /* my array of recipients */]); 
```

Or similar. Then, since those methods are real methods which then return actual classes with more methods on them, my IDE can then automatically suggest. Otherwise, I can simply reference the standard API documentation here (https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/contactdb.html#Add-Multiple-Recipients-to-a-List-POST) and make my requests using a typical HTTP client like `curl_*` or whatever.

**Comment by thinkingserious** [comment]
Thank you for the great feedback!

We moved away from Guzzle because supporting the various versions became troublesome. We currently have several tickets where people continue to get tripped up on that dependency.

The goal of this next release (see our [Python library](https://github.com/sendgrid/sendgrid-python) for a taste of what it will look like at) was to prepare the base infrastructure, and keep that infrastructure as light as we could using the standard library whenever we could.

What you describe in your second comment will be supported in the following version of the library via "helpers". 

Please feel free to submit pull request. We love ninja PRs!

Also, your continued feedback is welcome and appreciated.

Thanks again!

**Comment by thinkingserious** [comment]
@patricknelson the namespace issue is now resolved and the new v3beta branch of this library is available for testing (it included support for the new v3 /mail/send endpoint too!): https://github.com/sendgrid/sendgrid-php/tree/v3beta

We will include the ability to pass in your own preferred HTTP client in a future version.

Thanks!
