### ISSUE TITLE
undefined method (setPsr4)

### ISSUE THREAD

**Issue by smockensturm** [sendgrid/sendgrid-php#224]
Hi. Can you help me track down why we are getting this error?

> Fatal error: Call to undefined method Composer\Autoload\ClassLoader::setPsr4() in /home/ottawahi/public_html/sendgrid-php/vendor/composer/autoload_real.php on line 33

We are **not** using composer (sorry) using the packaged library like so...

> require("sendgrid-php/sendgrid-php.php");

PHP 5.4.45
A Small Orange Server

**Comment by thinkingserious** [comment]
Hello @smockensturm,

Can you please provide the full stack trace?

If you are not using composer, I'm not sure why that function is getting called.

**Comment by Dreyer** [comment]
As mentioned above you shouldn't really be seeing those error messages if you're not using composer. I would suspect that something else in your environment might be attempting to call that method or load the contents of the vendor directory.

To diagnose, you're going to have to provide more information on your setup or a full stack trace.

I just tried downloading a fresh copy of the packaged library [sendgrid-php/sendgrid-php.zip](https://sendgrid-open-source.s3.amazonaws.com/sendgrid-php/sendgrid-php.zip) and ran the following 'test.php' in the directory:

```php
<?php
require 'sendgrid-php.php';

$sendgrid = new SendGrid('YOUR_SENDGRID_APIKEY');
$email = (new SendGrid\Email())
    ->addTo('dreyer@github.com')
    ->setFrom('test@example.com')
    ->setSubject('This is only a test')
    ->setText('Hello World!')
    ->setHtml('<strong>Hello World!</strong>');

$sendgrid->send($email);

try {
    $response = $sendgrid->send($email);
    var_dump($response->getCode(), $response->getBody());
} catch(\SendGrid\Exception $e) {
    echo $e->getCode();
    foreach($e->getErrors() as $er) {
        echo $er;
    }
}
```

The result after running it on the command line:

```
md@mac:~/Downloads/sendgrid-php$ php --version
PHP 5.6.2 (cli) (built: Nov 11 2014 16:47:39) (DEBUG)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
md@mac:~/Downloads/sendgrid-php$ php test.php 
int(200)
array(1) {
  ["message"]=>
  string(7) "success"
}
```

**Comment by smockensturm** [comment]
Thanks for staying on this. We could test this locally no problem. But I don't know if we have the resources to run it in run it on a command line on the host server. I'll tell you what we did in the meantime though, commented out line 33 of /vendor/composer/autoload_real.php

**Comment by Dreyer** [comment]
@smockensturm what is the name of the company providing your hosting? You mentioned 'A Small Orange' is that the name of the company?

**Comment by thinkingserious** [comment]
@smockensturm thanks for sharing your fix!

@Dreyer thanks for jumping in with some support!

Note that we will no longer be supporting this library in favor of our updated v3beta version: https://github.com/sendgrid/sendgrid-php/tree/v3beta which includes support for all v3 Web API endpoints including the newly released (beta) v3 /mail/send endpoint.
