### ISSUE TITLE
How to send 2 emails from a form (PHP)

### ISSUE THREAD

**Issue by pbengani** [sendgrid/sendgrid-php#225]
I am facing an issue. I have a form and I want to send 2 emails -
1. to the admin with all the data 
2. to the user who fills the form as a confirmation email

now i am able to send email to admin but stuck how to send email to user simultaneously. 

Using Sendgrid with PHP cURL.

**Comment by thinkingserious** [comment]
Hi @pbengani,

Please report this issue to our support team at: https://support.sendgrid.com

Thanks!
