### ISSUE TITLE
can't use symfony3 with guzzle/guzzle 3.9 required by sendgrid

### ISSUE THREAD

**Issue by yassine-ah** [sendgrid/sendgrid-php#226]
Please update the dependency, guzzle/guzzle 3.9 require symfony/event-dispatcher: ~2.1 how has conflict with symfony/event-dispatcher: ~3.0

**Comment by romainbriand** [comment]
:+1: I have the very same problem.

**Comment by thinkingserious** [comment]
@yassine-ah @romainbriand 

The new version of this library (coming very soon) will no longer depend on Guzzle, it will use this client, which has no dependencies: https://github.com/sendgrid/php-http-client
