### ISSUE TITLE
Substitution not working with setTos and setSmtpapiTos

### ISSUE THREAD

**Issue by kumarbalap** [sendgrid/sendgrid-php#228]
Hi,

I have a template with substitutions. (example: **#product_name#**).

When I send to individual person, the substitutions working fine, but not with array of mail ids.
I have tested with both setTos and setSmtpapiTos.

Here is my code.
```

if ( is_array($to) ) {
	$email->setTos( $to );
	//$email->setSmtpapiTos( $to );
} else {
	$email->addTo( $to );
}

$email
	->setFrom('donotreply@test.com')
	->setFromName('Test From')
	->setSubject(' ')
	->setHtml(' ')
	->setText(' ')
	->setTemplateId($templateId);

if ( count($mailData) != 0 ) {
	foreach ( $mailData as $dataKey => $dataVal ) {
		$name = '#' .$dataKey. '#';
		$email->addSubstitution( $name, array( $dataVal ) );
	}
}

if ( count($categories) != 0 ) {
	$email->setCategories( $categories );
}

try {
	$sendgrid->send($email);
} catch(\SendGrid\Exception $e) {
	Log::error( 'Mail not sent. Template: ' . $template . $e->getCode() );
}
```
Please don't look at the variables, its all working fine. I have tested many times with single email id.

Thanks,
Bala

**Comment by thinkingserious** [comment]
Hello @kumarbalap,

Please open a ticket with our support team at https://support.sendgrid.com so that we can dig deeper.

Thanks!

**Comment by kumarbalap** [comment]
Hi @thinkingserious 

I have opened a support ticket for the same, so far no reply.
[https://community.sendgrid.com/sendgrid/topics/substitution-not-working-with-settos-and-setsmtpapitos](https://community.sendgrid.com/sendgrid/topics/substitution-not-working-with-settos-and-setsmtpapitos)

Can you please help me on this, I'm evaluating for one of my application. 

Thanks,
Bala

**Comment by dangerdm** [comment]
I'm having the same problem I believe. The first email is intact with all the substitutions and the second email shows up, HOWEVER, there is no substitution data within the email, only the blank template arrives. 

I've tried 'addTo', 'addSmtpapiTo', 'setTos', and  'setSmtpapiTos'    - all with the same outcome of sending to two different emails.

**Comment by themao** [comment]
So far I understood that substitutions don't work this way: they suppose to have one substitution item per email address.

Example:

We have recipients 'mail1@gmail.com', 'mail2@gmail.com' and 'mail3@gmail.com'. Therefore we can NOT have a substitution array just with `[ 'key' => 'value1' ]`, it should be `[ 'key' => 'value1', 'value2', 'value3']`

The other way is to use Unique Arguments, I suppose.

**Comment by thinkingserious** [comment]
Hello @kumarbalap, @dangerdm, @themao,

We have released the beta of our new v3 /mail/send endpoint which handles substitutions slightly different, please check out the documentation here: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

Then, you can explore an example here: https://github.com/sendgrid/sendgrid-php/blob/v3beta/examples/helpers/mail/example.php

If you continue to have issues, please feel free to re-open this issue.

Thanks!

With Best Regards,

Elmer

**Comment by cesarhfborges** [comment]
i dont understand this API, very complicated, i using code in this format and substituitions doesn't work substituitions

// $emails = explode(',', $destinatario);
        $curl = curl_init();

        $email = new \SendGrid\Mail\Mail();
        $email->setFrom("no-reply@sdredes.com.br", "SdManager");
        $email->setSubject("Teste Ticket");
        $email->setTemplateId(
            new \SendGrid\Mail\TemplateId("d-811fb0388b2d48b587e23fb9ac8a81d9")
        );
        for ($i = 0; $i < count($destinatarios); $i++){
            $email->addTo($destinatarios[$i]);
        }
        $email->addDynamicTemplateDatas( [
            '[%USBSDREDES%]'     => 'Some stuff',
            'templatesRock' => 'They sure do!'
        ] );
        //$email->addSubstitution('[%USBSDREDES%]', 'Teste');

        $email->addContent("text/plain", $mensagem);
        $email->addContent("text/html", "<strong>".$mensagem."</strong>");

        $sendgrid = new \SendGrid($this->apiKey);
        $response = $sendgrid->send($email);

        return $response->statusCode();
