### ISSUE TITLE
Assign metadata to each recipient

### ISSUE THREAD

**Issue by Dreyer** [sendgrid/sendgrid-php#229]
I'm one of the Mandrill refugees that had to switch to SendGrid. So far the switch has been mostly painless.

One handy aspect of the Mandrill API which we're missing right now allowed us to assign additional metadata to each recipient. We would use this to include their `AccountID` so from within the Dashboard / Control Panel logs we could inspect a recipient and there directly connect an email address to a particular account (as email addresses may not be entirely unique).

I can see the library provides a method for adding [Unique Arguments](https://github.com/sendgrid/sendgrid-php#unique-arguments) to a particular email only. Effectively where multiple recipients are involved, I would need to perform some kind of mapping here (email:AccountID) which is less than ideal.

Are there alternative approaches for achieving this with SendGrid?

**Comment by thinkingserious** [comment]
Hi @Dreyer,

Welcome to SendGrid, we are happy to have you!

Our new v3 /mail/send endpoint allows you to set custom arguments for a group of emails using personalizations. You can see a code example here: https://github.com/sendgrid/sendgrid-php/blob/v3beta/examples/helpers/mail/example.php#L50

Please check out our new documentation for further details: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

With Best Regards,

Elmer
