### ISSUE TITLE
addTo() and addBcc() not working correctly when using addAttachment()

### ISSUE THREAD

**Issue by andreistangacianu** [sendgrid/sendgrid-php#23]
Hey there,

I've been trying to use the addTo() and addBcc() functions together with adding an attachment - > addAttachment("./file.php"), but I can't seem to get it to work.

Basically when I use  

addTo('andrei@sendgrid.com')->
setBcc('someotheraddress@sendgrid.com')->

in the mail object - it works perfect and the emails get delivered.

However, when I add the addAttachment("./file.php") function in the same object - the email goes out to only the addTo() address. 

Thanks,
Andrei

**Comment by chnadrakala** [comment]
how can i send mails to dynamic emails in the 'to' filed using mail() in php
(or)
how can i send mails to emails fetched from database

**Comment by thinkingserious** [comment]
@chnadrakala please open up a support ticket at https://support.sendgrid.com

Thanksl

**Comment by vinuf666** [comment]
I got it working this way though it does not fix the issue with the underlying PHP library issue.Sharing code in case anyone gets stuck trying to add BCC with a mail having attachment.

`
<?php
$url = 'https://api.sendgrid.com/';
$user = 'yourusername'; //replace with sendgrid username
$pass = 'password'; //replace with sendgrid pass
$fileName = 'license.txt'; //the file to attach
$filePath = dirname(__FILE__); //assuming file is in script folder(replace with whatever path)

$params = array(
    'api_user'  => $user,
    'api_key'   => $pass,
    'to'        => 'toaddress@domain.com', //replace with your To: address
    'subject'   => 'Sendgrid Test of File sends',
    'html'      => '<p> the HTML </p>',
    'from'      => 'fromaddress@domain.com', //replace with your From: address
    'bcc'       => 'bccaddress@domain.com', //replace with your Bcc: address
    'files['.$fileName.']' => '@'.$filePath.'/'.$fileName
  );

print_r($params);

$request =  $url.'api/mail.send.json';

// Generate curl request
$session = curl_init($request);

// Tell curl to use HTTP POST
curl_setopt ($session, CURLOPT_POST, true);

// Tell curl that this is the body of the POST
curl_setopt ($session, CURLOPT_POSTFIELDS, $params);

// Tell curl not to return headers, but do return the response
curl_setopt($session, CURLOPT_HEADER, false);
// Tell PHP not to use SSLv3 (instead opting for TLS)
curl_setopt($session, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_2);
curl_setopt($session, CURLOPT_RETURNTRANSFER, true);

// obtain response
$response = curl_exec($session);
curl_close($session);

// print everything out
print_r($response); //{"message":"success"}
?>
`
Code was derived from one of the basic examples given in sendgrid documentation.
