### ISSUE TITLE
getting the sent message id

### ISSUE THREAD

**Issue by hackzilla** [sendgrid/sendgrid-php#230]
It'd be nice when you call send, that the message id was returned in the response.

Then I could match back to unsubscribes in my system.

**Comment by idimensionz** [comment]
Hi Daniel,

You can call addUniqueArg() on the SendGrid Email object to add a unique
identifier to the email.  This can be used to link the email back to a
specific account.  We do this for iDimensionz's Communiqué email marketing
system to track all statistics (via the web hooks).

Best regards,
Jim Mullen

**Comment by thinkingserious** [comment]
@hackzilla 

@idimensionz solution is correct (thanks Jim!)

Here is how you would add a custom argument using our new v3 /mail/send endpoint: https://github.com/sendgrid/sendgrid-php/blob/v3beta/examples/helpers/mail/example.php#L50
