### ISSUE TITLE
Fatal error when using the packaged version.

### ISSUE THREAD

**Issue by fabdrol** [sendgrid/sendgrid-php#232]
```
Fatal error: Class 'Guzzle\Http\RedirectPlugin' not found in /home/users/staryftp/starting-point.nl/B2S/sendgrid-php/lib/SendGrid.php on line 85
```

- I copied the entire zipfile into my project dir
- I require the `sendgrid-php.php` file as instructed
- Autoloader issue?

**Comment by fabdrol** [comment]
Turned out it was my mistake.

**Comment by techheads** [comment]
Are you able to please include what you did to fix your mistake? I've come across the same error and it may help others. Thanks for your time.

**Comment by fabdrol** [comment]
Something had gone wrong during upload, causing one or more files to be corrupt. Re-uploading fixed the issue.
