### ISSUE TITLE
Legacy template wrapping around Transactional Template

### ISSUE THREAD

**Issue by justinbeatz** [sendgrid/sendgrid-php#233]
Hi, I have a legacy template and created a new Transactional Template, created a new API key with Legacy Templates set to "No Access", and when I ran a test i got an email with the Transactional Template inside the Legacy one.

This is the code i'm using:

$template_id = 'my_template_id';
$sendgrid = new SendGrid($sendgrid_api_key);

$email = new SendGrid\Email();

$email
	->addTo($toEmail)
	->setFrom($fromEmail)
	->setFromName($fromName)
	->setSubject('Testing sendgrid')
	->setHtml('<strong>Hello World!</strong>')
	->setTemplateId($template_id);

$response = $sendgrid->send($email);

I'm using the latest version (4) installed via composer.

**Comment by thinkingserious** [comment]
Hello @justinbeatz,

It looks like you are having a permissions issue with your API key. Please reach out to https://support.sendgrid.com so we can help you further.

Thanks!

With Best Regards,

Elmer
