### ISSUE TITLE
 Class 'Guzzle\Http\Client' not found 

### ISSUE THREAD

**Issue by maxwassler** [sendgrid/sendgrid-php#234]
Hello when I want to send an email with the API, thats always return me
`Fatal error :  Class 'Guzzle\Http\Client' not found in /var/www/html/mail/lib/SendGrid.php on line 85`
What can I do for fix that ? 
Thank you

**Comment by maxwassler** [comment]
Resolved

**Comment by zeeshan4971** [comment]
how did you resolved it

**Comment by thinkingserious** [comment]
@zeeshan4971 the new version of this library no longer requires the Guzzle dependency.

**Comment by maxwassler** [comment]
Yep and if you need to use another version, try to remove the line, it worked fine for me

**Comment by thinkingserious** [comment]
Thanks for the follow up @maxwassler

**Comment by zeeshan4971** [comment]
please can you provide the link for the latest api

**Comment by thinkingserious** [comment]
@zeeshan4971 the documentation for the v3 /mail/send is here: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

This repo contains the latest version of the API client: https://github.com/sendgrid/sendgrid-php

Example: https://github.com/sendgrid/sendgrid-php/blob/master/examples/mail/mail.php#L28 (note the link to the helper)

General usage, including installation of this library is included on the README: https://github.com/sendgrid/sendgrid-php

Thanks!

**Comment by zeeshan4971** [comment]
Yeap this error is gone thanks now can u tell me how to add authentication to the contactdb  example i have the user and pass

**Comment by thinkingserious** [comment]
Awesome, thanks for the follow up!

You will need your API Key, not user/pass.

Here is an example of how to set the API Key https://github.com/sendgrid/sendgrid-php/blob/master/examples/contactdb/contactdb.php#L6

This assumes you have the API Key in an environment variable as described here: https://github.com/sendgrid/sendgrid-php/blob/master/CONTRIBUTING.md#environment-variables
