### ISSUE TITLE
How do I include the helpers using composer

### ISSUE THREAD

**Issue by Petah** [sendgrid/sendgrid-php#238]
How do I include the helpers using composer?

I added `"sendgrid/sendgrid": "dev-v3beta"` to my composer.json file, but when I try to do `new \SendGrid\Mail()` it fails because it cannot find the class. 

If I include the `vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php` file it fails because that file tries to require `__DIR__ . '/../../../vendor/autoload.php'`.

If I remove that line it works fine.

**Comment by thinkingserious** [comment]
Hello @Petah,

First, thanks for giving the new API library a try!

I have not tested or expect composer to work until we bring this library out of beta (which should be very soon!). 

For now, this is the method of testing I recommend: https://github.com/sendgrid/sendgrid-php/tree/v3beta#trying-out-the-v3-beta-mail-send

With Best Regards,

Elmer

**Comment by Petah** [comment]
Do you have a better time frame apart from "very soon"?

Im have been using the old version, but I now need to access the transactional template API which requires this version afaics.

**Comment by thinkingserious** [comment]
Unfortunately, I can not commit to a time frame today. 

I can say that it is my own belief that we are weeks, not months away.
