### ISSUE TITLE
The provided authorization grant is invalid, expired, or revoked

### ISSUE THREAD

**Issue by frechina** [sendgrid/sendgrid-php#239]
Hi,
I'm getting this error when sending. I've tried with several api keys and always get this error. Any idea?
Help please.

Thanks

**Comment by thinkingserious** [comment]
Hello @frechina,

Could you please contact https://support.sendgrid.com? Thanks!

**Comment by frechina** [comment]
support.sendgrid.com told be to write here

**Comment by frechina** [comment]
any help? @thinkingserious

**Comment by thinkingserious** [comment]
@frechina could you please provide me with your support ticket number?

**Comment by frechina** [comment]
@thinkingserious here the ticket number 663637

**Comment by frechina** [comment]
any update about this?

**Comment by thinkingserious** [comment]
Hello @frechina,

It looks like you are not using the API Key, but rather your API Key ID. The API Key is only displayed once, when you create it. It has the format (Note that is starts with SG): SG.akawjndajkwhasdfasdfkhbawkbawkhjdbkahwd.kuahwdjkabwkuydbawkjydbhailuwhdliafdsfawiludh

Please verify.

Thanks!

**Comment by frechina** [comment]
Thank you for your replo @thinkingserious 
However, I tried with an API Key with such format and still not working

**Comment by thinkingserious** [comment]
@frechina Do you get the same error?

With the same API key, can you make the API call with a standard cURL request?

**Comment by frechina** [comment]
I made a POST to https://api.sendgrid.com/api/mail.send.json with params 

api_user=MY_USER&api_key=MY_KEY&to=ANY&toname=Destination&subject=Example_Subject&text=testingtextbody&from=OTHER 

and I get

{
  "errors": [
    "Permission denied, wrong credentials"
  ],
  "message": "error"
}

**Comment by thinkingserious** [comment]
OK, then the issue is definitely with your key. In that case our support team will need to further assist. Please add this information to your support ticket. Thanks!

**Comment by frechina** [comment]
Hi @thinkingserious 
Seems that I found a way to call the API with username/password created from "credentials" instead of using API Key.

If I make a POST to https://api.sendgrid.com/api/mail.send.json?api_user=MY_USER&api_key=MY_PASSWD&to=SOME_MAIL&toname=Destination&subject=Example_Subject&text=testingtextbody&from=SOME_OTHER_MAIL

I get

{
  "message": "success"
}

and I receive the email

I tried with your library:

```
$sendgrid = new SendGrid('MY_USER', 'MY_PASSWD');
```

and it does not work, could you please help me to use your library by using user/password?

**Comment by thinkingserious** [comment]
Hello @frechina,

We do not support using your username and password credentials through our libraries. 

According to the support ticket it looks like the issues with your API key has been resolved. If not, please let our support team know.

Thanks!

**Comment by frechina** [comment]
Hi @thinkingserious 
My issue is not resolved at all, the support ticket tell me that I need to use api_user and api_key and you tell me that this sendgrid library does not support username and password credentials.

What should I do to use this library? I just need to know what steps should I take to do it work

**Comment by thinkingserious** [comment]
Hello @frechina,

I do not see in the ticket where it was suggested that you use the api_user. The response I see from Fatma and Ron are to use a API Key. 

Using this library (v2): https://github.com/sendgrid/sendgrid-php/blob/master/example_v2.php#L8 You can either pass your API Key directly or put it in your environment (recommended).

Using the new library (v3): https://github.com/sendgrid/sendgrid-php/blob/v3beta/examples/helpers/mail/example.php#L183 (if using the v3 library, please make sure to read the README: https://github.com/sendgrid/sendgrid-php/blob/v3beta/README.md

Whichever you choose, if you still have difficulty, please post the code and redact your API Key. Thank you!

**Comment by frechina** [comment]
Hi @thinkingserious 

I saw api_user in this capture from Fatma:

http://screencast.com/t/606B2Au3O2U

which shows me the way to use the library v2

**Comment by thinkingserious** [comment]
Could you please explain the steps you have taken to use this library (e.g.
Installed via Composer) and provide the code that is returning the error
(with your credentials redacted)?

On Thursday, June 2, 2016, frechina <notifications@github.com> wrote:

> Hi @thinkingserious <https://github.com/thinkingserious>
>
> I saw api_user in this capture from Fatma:
>
> http://screencast.com/t/606B2Au3O2U
>
> which shows me the way to use the library v2
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sendgrid/sendgrid-php/issues/239#issuecomment-223341674>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAI9B5gfLB7uN71thxgmGHjuiuxT1JJCks5qHwEYgaJpZM4Iqr1F>
> .
>


-- 
<http://www.sendgrid.com>
Elmer Thomas
Developer Experience Engineer | Product

**Comment by frechina** [comment]
it seems that sendgrid technical team did something with my API key and now it is working. I hope it still working in the future. Thank you for your help @thinkingserious

**Comment by thinkingserious** [comment]
Excellent! Thank you for following up!
