### ISSUE TITLE
Sendgrid integration giving 500 internal error

### ISSUE THREAD

**Issue by subhana000** [sendgrid/sendgrid-php#242]
I have placed my code exactly like this and its not working giving me 500 internal error. Please I need a quick solution. Any help !!
$sendgrid = new SendGrid('my_api_key');
$email = new SendGrid\Email();
$email
    ->addTo('subhana.nisar@tossdown.com')
    ->setFrom('me@bar.com')
    ->setSubject('Subject goes here')
    ->setText('Hello World!')
    ->setHtml('<strong>Hello World!</strong>')
;

$sendgrid->send($email);

// Or catch the error

try {
    $sendgrid->send($email);
} catch(\SendGrid\Exception $e) {
    echo $e->getCode();
    foreach($e->getErrors() as $er) {
        echo $er;
    }
}

**Comment by thinkingserious** [comment]
Hello @subhana000,

I have a few follow questions:

1. Did you get the error message that came with the internal error?
2. How did you install the library? https://github.com/sendgrid/sendgrid-php#installation

Thanks!

- Elmer

**Comment by subhana000** [comment]
Yes I am getting message that coming like this "500 internal error"
downloaded the php library and place in my application.

Everything was working fine and suddenly yesterday an error start appearing

On Sat, Jun 4, 2016 at 7:50 PM, Elmer Thomas <notifications@github.com>
wrote:

> Hello @subhana000 <https://github.com/subhana000>,
>
> I have a few follow questions:
>
>    1. Did you get the error message that came with the internal error?
>    2. How did you install the library?
>    https://github.com/sendgrid/sendgrid-php#installation
>
> Thanks!
>
>    - Elmer
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sendgrid/sendgrid-php/issues/242#issuecomment-223759626>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AS1FRoEDkDaLXtejOHHe1ldHGWPjjNwHks5qIZCmgaJpZM4IuE1M>
> .
>



-- 
Regards,
Subhana Nisar Khan
Development

http://tossdown.com
subhana.nisar@tossdown.com <omair.bangash@tossdown.com>

**Comment by thinkingserious** [comment]
How did you install the library? Are you using composer or did you download and add the files directly? 

What version of this library are you using?

Also, please note that if you are using the code as pasted above, there are a few issues 1) you are calling $sendgrid->send($email) twice, which would result in duplicate emails and 2) there is an extra trailing }

**Comment by subhana000** [comment]
Downloaded the library and then placed the folder and I tried the api too
even thats not working

On Sat, Jun 4, 2016 at 8:23 PM, Elmer Thomas <notifications@github.com>
wrote:

> How did you install the library? Are you using composer or did you
> download and add the files directly?
>
> What version of this library are you using?
>
> Also, please note that if you are using the code as pasted above, there
> are a few issues 1) you are calling $sendgrid->send($email) twice, which
> would result in duplicate emails and 2) there is an extra trailing }
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sendgrid/sendgrid-php/issues/242#issuecomment-223761404>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AS1FRsNpmaoZGJaBYjZJsiMMjzR9Uz8bks5qIZiPgaJpZM4IuE1M>
> .
>



-- 
Regards,
Subhana Nisar Khan
Development

http://tossdown.com
subhana.nisar@tossdown.com <omair.bangash@tossdown.com>

**Comment by thinkingserious** [comment]
What do you mean by "tried the api too"? Do you mean a cURL request?

What changed in your code or environment from when it was working to now?

**Comment by thinkingserious** [comment]
Also, could you provide the complete code (you can email it to dx@sendgrid.com if you prefer)? Since the code you have posted is not working code. Thanks!

**Comment by subhana000** [comment]
This is php code and thats what your support team provided to try.

function checkemails(){

//require_once("application/libraries/sendgrid-php/sendgrid-php.php");

$sendgrid = new SendGrid('KSH6gvLfRaaLUuFFiTeTuw');

$email = new SendGrid\Email();

$email

    ->addTo('subhana.nisar@tossdown.com')

    ->setFrom('me@bar.com')

    ->setSubject('Subject goes here')

    ->setText('Hello World!')

    ->setHtml('<strong>Hello World!</strong>')

;


$sendgrid->send($email);


// Or catch the error


try {

    $sendgrid->send($email);

} catch(\SendGrid\Exception $e) {

    echo $e->getCode();

    foreach($e->getErrors() as $er) {

        echo $er;

    }

}

}

On Sat, Jun 4, 2016 at 8:29 PM, Elmer Thomas <notifications@github.com>
wrote:

> Also, could you provide the complete code (you can email it to
> dx@sendgrid.com if you prefer)? Since the code you have posted is not
> working code. Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sendgrid/sendgrid-php/issues/242#issuecomment-223761661>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AS1FRhX77_9vwW1ERSFpdpzSAugOalygks5qIZnigaJpZM4IuE1M>
> .
>



-- 
Regards,
Subhana Nisar Khan
Development

http://tossdown.com
subhana.nisar@tossdown.com <omair.bangash@tossdown.com>

**Comment by thinkingserious** [comment]
Please do not post your credentials to public forums. Fortunately, these are not correct credentials. Your API Key should be in the form: SG.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX. Can you verify that in your production code you are using the proper key?

```
$sendgrid->send($email);
// Or catch the error
try {
    $sendgrid->send($email);
} catch(\SendGrid\Exception $e) {
    echo $e->getCode();
    foreach($e->getErrors() as $er) {
        echo $er;
    }
}
```

This means that in your code only include:
```
$sendgrid->send($email);
```
**OR**
```
try {
    $sendgrid->send($email);
} catch(\SendGrid\Exception $e) {
    echo $e->getCode();
    foreach($e->getErrors() as $er) {
        echo $er;
    }
}
```
but not both. 

I recommend you delete the first occurrence of $sendgrid->send($email);

**Comment by subhana000** [comment]
*Fatal error*: Class 'Guzzle\Http\Client' not found in
*/Volumes/Data/localhost/work/tossdown/application/libraries/sendgrid-php/lib/SendGrid.php*
on
line *79*
*error*

On Sat, Jun 4, 2016 at 8:35 PM, Elmer Thomas <notifications@github.com>
wrote:

> Please do not post your credentials to public forums. Fortunately, these
> are not correct credentials. Your API Key should be in the form:
> SG.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX. Can you verify that in your
> production code you are using the proper key?
>
> $sendgrid->send($email);
> // Or catch the error
> try {
>     $sendgrid->send($email);
> } catch(\SendGrid\Exception $e) {
>     echo $e->getCode();
>     foreach($e->getErrors() as $er) {
>         echo $er;
>     }
> }
>
> This means that in your code only include:
>
> $sendgrid->send($email);
>
> *OR*
>
> try {
>     $sendgrid->send($email);
> } catch(\SendGrid\Exception $e) {
>     echo $e->getCode();
>     foreach($e->getErrors() as $er) {
>         echo $er;
>     }
> }
>
> but not both.
>
> I recommend you delete the first occurrence of $sendgrid->send($email);
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sendgrid/sendgrid-php/issues/242#issuecomment-223762009>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AS1FRrbmQyhFr38ncG5_Ul0Hm4keceIqks5qIZtegaJpZM4IuE1M>
> .
>



-- 
Regards,
Subhana Nisar Khan
Development

http://tossdown.com
subhana.nisar@tossdown.com <omair.bangash@tossdown.com>

**Comment by thinkingserious** [comment]
This v2 library requires a dependency on the Guzzle library; note that the new version of this library that will replace this current version in a few weeks (see the v3beta branch) will not require this dependency.

If you install this library with Conposer (recommended), this decency is installed automatically. Since you have downloaded this library directly, you will need to include the dependency manually, please see this link for instructions: https://github.com/guzzle/guzzle3

Thank you!

**Comment by subhana000** [comment]
Thank you for the help :)

On Sat, Jun 4, 2016 at 11:02 PM, Elmer Thomas <notifications@github.com>
wrote:

> This v2 library requires a dependency on the Guzzle library; note that the
> new version of this library that will replace this current version in a few
> weeks (see the v3beta branch) will not require this dependency.
>
> If you install this library with Conposer (recommended), this decency is
> installed automatically. Since you have downloaded this library directly,
> you will need to include the dependency manually, please see this link for
> instructions: https://github.com/guzzle/guzzle3
>
> Thank you!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sendgrid/sendgrid-php/issues/242#issuecomment-223769452>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AS1FRpPj12G1fUodGBcU06-ZxRgqN14Mks5qIb2ngaJpZM4IuE1M>
> .
>



-- 
Regards,
Subhana Nisar Khan
Development

http://tossdown.com
subhana.nisar@tossdown.com <omair.bangash@tossdown.com>
