### ISSUE TITLE
Contacts API support?

### ISSUE THREAD

**Issue by Niek** [sendgrid/sendgrid-php#243]
Any plans to add support for https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/contactdb.html?

**Comment by thinkingserious** [comment]
Yes, those endpoints are supported in the new version of this library, which should come out of beta in a few weeks. You can check it out here: https://github.com/sendgrid/sendgrid-php/tree/v3beta. Specifically, here are the contactdb examples: https://github.com/sendgrid/sendgrid-php/blob/v3beta/examples/contactdb/contactdb.php

Thanks!

**Comment by Niek** [comment]
Whoops, I missed that! Good to see!
