### ISSUE TITLE
Updated README.md with link to new packed release (zip)

### ISSUE THREAD

**Issue by beltofte** [sendgrid/sendgrid-php#244]
The README.md file contain a link to a packed release (zip) for people not using composer. This zip-file contains a version that is more than a year old (version 3.20).

Time to create a new packed release?

**Comment by thinkingserious** [comment]
Thanks @beltofte!

We will investigate.

**Comment by thinkingserious** [comment]
This is resolved in our latest release. Thanks again for the heads up!
