### ISSUE TITLE
Use of short array syntax contradicts min PHP required version in composer.json

### ISSUE THREAD

**Issue by ajbonner** [sendgrid/sendgrid-php#245]
This commentary is with respect to the v3beta branch.

I just want to point out that PHP short array syntax ($foo = [1, 2, 3] vs $foo = array(1, 2, 3)) isn't supported on PHP 5.3.

For example see its use here: https://github.com/sendgrid/sendgrid-php/blob/v3beta/lib/helpers/mail/Mail.php#L37

In composer.json the PHP min required version is still only 5.3 - https://github.com/sendgrid/sendgrid-php/blob/v3beta/composer.json#L9

PHP 5.3/4 are both end of life, and 5.5 is end of life in one month, so it would make sense to make the minimum required version at least 5.6.

More info on support / EOL status is at: http://php.net/supported-versions.php

Thanks for your work here, I've actually got a slightly earlier version of this beta api running well in production under PHP 7.

**Comment by thinkingserious** [comment]
Hello @ajbonner,

Thank you for your feedback. I will look into removing support for 5.3/5.4 and 5.5.

**Comment by hobailey** [comment]
Hey, I just did a PR (#257) with the required updates as I had the same problem :-)

**Comment by thinkingserious** [comment]
Hello @ajbonner,

You are correct, we will be making those adjustments. Thanks for the heads up!
