### ISSUE TITLE
Upgrade Guzzle 3 to maintained version // Symfony 3 compability

### ISSUE THREAD

**Issue by johanwilfer** [sendgrid/sendgrid-php#246]
As sendgrid-php depends on guzzle v.3 that isn't maintained and guzzle v.3 requires an old version of symfony/event-dispatcher (2.x) it isn't possible to upgrade to symfony 3.

Can you please upgrade to a maintained version, like 5 or 6. Or even to 4 that still isn't maintained but doesn't have this dependency.

Thanks!

**Comment by markbijl** [comment]
I agree with this request, experiencing the same situation with symfony 3. It also doesn't help that we have a few internal libraries that are already using guzzle 6.

**Comment by thinkingserious** [comment]
@johanwilfer @markbijl,

The new version of this library no longer requires Guzzle. You can check it out here: https://github.com/sendgrid/sendgrid-php/tree/v3beta

It comes out of beta shortly.

Thanks!

**Comment by johanwilfer** [comment]
Cool. You have a big scary warning about using the beta. Is it safe thought?

**Comment by thinkingserious** [comment]
@johanwilfer I believe it's safe, but you may want to wait until we are officially out of beta.
