### ISSUE TITLE
Update examples and usage to use associative arrays vs. JSON strings

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-php#254]
#### Issue Summary

Please see this thread: https://github.com/sendgrid/sendgrid-php/issues/253
#### Steps to Reproduce

https://github.com/sendgrid/sendgrid-php/blob/master/examples/apikeys/apikeys.php#L13
#### Technical details:
- sendgrid-php 5.X.X
- PHP Version: 5.x

**Comment by gavrichards** [comment]
Is there likely to be any improvements to the docs soon? I'm finding them really difficult to navigate and find information that corresponds to my current code from the previous SDK. I'm sure I recall the previous docs were really simple, with explanation of each method. This seems to have vanished with v5.

One example of the poor documentation here is on the homepage of this repo, under the Announcements, the first link is to 'SendGrid Documentation'. I [click this](https://sendgrid.com/docs/API_Reference/Web_API_v3/index.html) hoping to get some great docs for the SDK, but instead it's all about the API. I have no interest in the API, that's why I want to use this SDK in the first place.
Then I see a list of 7 different libraries, one of which is PHP. Click that and you're straight back to where you came from, so I'm just going around in circles.

Here's an example of some code I built using the old SDK and the easy docs that were provided. If anyone can point me in the direction of docs to create the equivalent in v5 (not just a code example which doesn't explain what each bit does) that would be super.

```
$email = new SendGrid\Email();
                        $email
                            ->setFrom($from)
                            ->setFromName($arrPack["packFrom"])
                            ->setSmtpapiTos($arrTo)
                            ->setSubject($arrPack["packSubject"])
                            ->setCategory("marketing-" . $arrPack["packType"])
                            ->setHtml($arrPack["packHtml"])
                            ->setText($arrPack["packText"])
                            ->setUniqueArgs([
                                "siteId" => $siteId,
                                "packId" => $arrPack["packId"],
                                "memberId" => "{MEM_ID}",
                            ])
                            ->addSubstitution('{MEM_ID}', $arrMemId)
                            ->addSubstitution('{MEM_FNAME}', $arrMemFname)
                            ->addSubstitution('{MEM_EMAIL}', $arrMemEmail);
```

**Comment by thinkingserious** [comment]
Hello @gavrichards,

Yes, we are working on docs improvements and your vote helps push that up in the priority queue. Thanks!

With regards to the mapping from v2 to v3, I think this is a helpful doc: https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/how_to_migrate_from_v2_to_v3_mail_send.html

Then, here is a kitchen sink example using the Mail Helper: https://github.com/sendgrid/sendgrid-php/blob/master/examples/helpers/mail/example.php#L22

And here is a kitchen sink example without the Mail Helper: https://github.com/sendgrid/sendgrid-php/blob/master/examples/mail/mail.php#L33

Finally, you may find documentation on the mail/send endpoint here: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

If you are still having issues, I'm happy to help. If you provide me with the new migrated code I can help troubleshoot any issues you run into.

**Comment by gavrichards** [comment]
Hi @thinkingserious 

Thanks for the response.
I think your links highlight the issue I have raised with the docs at the moment.

The first and last links are pages about the API, not the PHP SDK. If this is an effective SDK, I should have no reason to have an understanding of the API, as it is a wrapper that I interact with, and *it* takes care of the API. Hope this makes sense.

The kitchen sink examples don't have any comments, or for example an explanation of why `new Email()` now has 2 parameters, or what these are, when the old SDK didn't have any parameters for `new Email()`

I hope you can understand my frustrations :)
Gav

**Comment by thinkingserious** [comment]
@gavrichards,

I understand your frustrations. We took a few steps back building this library from scratch to support all the v3 Web APIs (this was a major change across all our sdks). Now, we are iterating based on feedback from this community to get the library back up to par and beyond. So your feedback is greatly appreciated!

An upgrade to the Mail Helper and its documentation is definitely coming and your feedback will be considered during that process. When we begin development on that, we'll create an issue here on GitHub detailing our plan. If you have time, we would love for you to continue contributing your feedback.

For the Email object, the first parameter is the Name and the second is the Email Address.

**Comment by gavrichards** [comment]
So do `setFrom()` and `setFromName()` still exist? They seemed like really convenient methods. Now you have to pass null to the first parameter if you don't want it? It seems a bit backwards, so I would be really interested to understand the decision process here.

Thanks for your time.

**Comment by thinkingserious** [comment]
@gavrichards,

This first version of the helper, simply tries to build [this object](https://github.com/sendgrid/sendgrid-php/blob/master/examples/mail/mail.php#L33) for you: Thus, the [Email object](https://github.com/sendgrid/sendgrid-php/blob/master/lib/helpers/mail/Mail.php#L845). I personally don't like having to pass that null in either (yuck!).

The Email object does have methods to set the name and email already, but what you want is to be able to set those without creating that object. Future iterations of the helper will include convenience methods, and that would address this particular issue. Thanks for providing some input on which ones are valuable. We want to cover all the common use cases first.

**Comment by stevenmunro** [comment]
I'm also finding the documentation extremely frustrating. 

How is ->addSubstitution supposed to work now?

I get PHP Fatal error:  Uncaught Error: Call to undefined method SendGrid\Mail::addSubstitution()

**Comment by thinkingserious** [comment]
Hi @stevenmunro,

Could you please provide the following information?

1. How did you install the library? 
2. Could you provide the rest of the relevant source code? If not publicaly, please email dx@sendgrid.com
3. What documentation did you look at so far?

Thanks!

**Comment by thinkingserious** [comment]
This has been moved [here](https://github.com/sendgrid/sendgrid-php/issues/434).
