### ISSUE TITLE
Unable to send multiple emails

### ISSUE THREAD

**Issue by videotiledarren** [sendgrid/sendgrid-php#255]
#### Issue Summary

Using the SendGrid PHP Library, I wish to send an email to a user on registration, followed by an email to the admin to inform them of this.  Only one email is ever sent.  I notice somebody has reported this issue previously #225 and it was closed with a suggestion that the user should contact SendGrid Support.  Having discussed this issue for several weeks now with SendGrid Support, the most recent reply (after NINE days of waiting) was...

"Sorry for the late update.
Due to the fact that I can't assist you for code review please direct this issue to our [PHP library issue](https://github.com/sendgrid/sendgrid-php/issues) and our developer team could further assist you on your case."

Here is my function:

```PHP
function sendanEmail($emailTo, $emailToName, $emailFrom, $emailFromName, $emailSubject, $emailHTMLBody, $emailTextBody, $emailBCC){
global $client;
require '../../common/hs4/vendor/autoload.php';
require '../../common/hs4/lib/SendGrid.php';
$sendgrid = new SendGrid("REMOVED");
$email    = new SendGrid\Email();
$email->addTo($emailTo, $emailToName)
          ->setFrom('email@example.com') 
          ->setFromName($emailFromName)
          ->setReplyTo($emailFrom)
            ->setSubject($emailSubject)
            ->setText($emailTextBody)
            ->setHtml($emailHTMLBody)
            ->addCategory($client);
$sendgrid->send($email);
}
```

And then I'm running the following to send the two emails when the new account has been processed:

`sendanEmail($email, $fullName, $clientEmail, $clientName, $courseType.' Training', $emailMessageHTML, $emailMessageText, '');`

`sendanEmail($clientEmail, $clientContact, 'no-reply@domain.com', 'Training Accounts', 'New Trial Account', $emailMessageHTML, $emailMessageText, '');`

No matter the order I put the two calls to sendanEmail(), only the first one is ever sent.

#### Technical details:

* sendgrid-php Version: 3.2.0

**Comment by thinkingserious** [comment]
Hello @videotiledarren,

We no longer support that version of the library and we recommend you update to version 5.X.X.

That said, I have a few suggestions:

1. Add some print statements and print out the values of the function parameters and the $email object before you call $sendgrid->send. 
2. You might try only creating one $email and $sendgrid object.

Please let me know your results.

Thanks!
