### ISSUE TITLE
Non 7bit-String as content for mail subject (f.e. German umlauts)

### ISSUE THREAD

**Issue by mercredo** [sendgrid/sendgrid-php#256]
#### Issue Summary

Im trying to include special characters into the mail subject, as there are for example German umlauts (ä, ö, ü). I had no problems regarding this matter in sendgrid-php 4.0.4.

SendGrid BOUNCES and keeps saying: "550 Subject contains invalid characters.".

#### Steps to Reproduce

NEW CODE (v. 5.0):

```
$sendgrid = new \SendGrid("MYAPIKEY");

$mail = new \SendGrid\Mail();
$email = new \SendGrid\Email(null, 'sender@example.com');
$mail->setFrom($email);

$personalization = new \SendGrid\Personalization();
$email = new \SendGrid\Email('Some Name', 'recipient@example.com');
$personalization->addTo($email);
$personalization->setSubject("Please print out the ä, ö, and ü");
$personalization->addSubstitution("%brand%", 'some brand');
$mail->addPersonalization($personalization);

$sendgrid->client->mail()->send()->post($mail);
```

DEPRECATED CODE (v. 4.0.4):

```
$sendgrid = new \SendGrid("MYAPIKEY");

$mail = new \SendGrid\Email();
$mail->setFrom("sender@example.com");
$mail->setSubject("Please print out the ä, ö, and ü");
$mail->addTo("recipient@example.com", "Some Recipient");
$mail->addSubstitution("%brand%", array("Some brand"));

$sendgrid->send($mail);
```

I have no idea how to get UTF-8 characters to work as expected using this library (version).

#### Technical details:

* sendgrid-php Version: master
* PHP Version: 5.0
* Similar Problems: https://github.com/sendgrid/sendgrid-php/issues/162

####

**Comment by mercredo** [comment]
maybe I am a victim of this bug:

https://github.com/sendgrid/sendgrid-php/issues/162

**Comment by thinkingserious** [comment]
@mercredo I think so, please follow that issue. Thanks!

**Comment by mercredo** [comment]
I found out, that, if I remove the 'addSubstitution'-method from the personalization, it works flawlessly. Problem is, that I need those substitutions.

**Comment by thinkingserious** [comment]
@mercredo,

Can you please provide the value of `$mail` before you pass it to the `mail()->send()` function?

Try: `echo json_encode($mail, JSON_PRETTY_PRINT), "\n";`

I tested your code and found that the content block was missing:
```php
$content = new \SendGrid\Content("text/plain", "some text here");
$mail->addContent($content);
```

When I added that, the email sent as expected. Here is an example of a minimal email: https://github.com/sendgrid/sendgrid-php/blob/master/examples/helpers/mail/example.php#L8

Thanks!

**Comment by mercredo** [comment]
hi, thanks for your response. I forgot to mention that I of course have added content for both plain and html. I'm using my own hosted templates, and those will be rendered and afterwards added via
`$mail->addContent(new \SendGrid\Content("text/html", $redneredHTML));`

The value of $mail contains invalid JSON:

`{ "from": { "email": "somemail@example.com" }, "personalizations": [ { "to": [ { "name": "Me", "email": "me@example.com" } ], "subject": "Account noch nicht best\u00e4tigt. Ihre Registrierung", "substitutions": { "%brand%": "mybrand" } } ], "content": [ { "type": "text\/plain", "value": "Account noch nicht best\u00e4tigt\r\n\nGuten Tag Me,\r\nVor 2 Tagen haben Sie sich bei mybrand registriert. Die Best\u00e4tigung Ihrer E-Mail-Adresse test@example.com steht noch aus.\r\nKlicken Sie bitte auf den folgenden Link, um Ihre Registrierung abzuschlie\u00dfen\r\n" }, { "type": "text\/html", "value": "\n \n \n \n \n `

**Comment by thinkingserious** [comment]
@mercredo,

Can you please provide the value of $mail before you pass it to the mail()->send() function?

Try: `echo json_encode($mail, JSON_PRETTY_PRINT), "\n";`

Then you can paste here using 

```json
Your JSON here.
```

Thanks!

**Comment by thinkingserious** [comment]
Hi @mercredo,

I'm asking for the JSON, because in my tests I can not reproduce the error. I'm trying to find out where the problem exists in the JSON.

The JSON you have provided above is incomplete. If you prefer, it might be easier to put in paste bin, or you can email us at dx@sendgrid.com.

One other thing, can you please add a try/catch block to your code like so:
```php
try {
  $response = $sendgrid->client->mail()->send()->post($mail);
  echo $response->statusCode();
  echo $response->headers();
  echo $response->body();
} catch (Exception $e) {
  echo 'Caught exception: ',  $e->getMessage(), "\n";
}
```
and please let me know the exception returned?

Thanks!

**Comment by mercredo** [comment]
hi, there is no exception to be catched. 

The output for a BOUNCE with added substitution is:
`202HTTP/1.1 100 Continue HTTP/1.1 202 Accepted Server: nginx Date: Tue, 05 Jul 2016 14:59:00 GMT Content-Type: text/plain; charset=utf-8 Content-Length: 0 Connection: keep-alive X-Message-Id: HQAOLwNnSnCVd3fqhADGhQ X-Frame-Options: DENY`

The output for a SUCCESSFUL delivery without added substitution is:
`202HTTP/1.1 100 Continue HTTP/1.1 202 Accepted Server: nginx Date: Tue, 05 Jul 2016 15:07:48 GMT Content-Type: text/plain; charset=utf-8 Content-Length: 0 Connection: keep-alive X-Message-Id: pJeVY_ygS7acvAUE85glRA X-Frame-Options: DENY `

**Comment by thinkingserious** [comment]
@mercredo,

OK, thanks. Can you provide me with the complete JSON?

**Comment by mercredo** [comment]
hi,

that took some time to hopefully hide sensitive content:
http://paste.ofcode.org/DeXGe9GfvnDZaunEqfTNhQ

the JSON is valid.

**Comment by thinkingserious** [comment]
Hi @mercredo,

I think what is happening is that we are double encoding the html content.

If you try this, it should work:

`$mail->addContent(new \SendGrid\Content("text/html", stripslashes($htmlContent)));`

**Comment by mercredo** [comment]
I found that out 15 minutes again, that I single-quotedly ran the subject string through my translator.
Beginners fault, but sometimes we are all thrown back to basics :p.
Still thanks again for your response.

**Comment by thinkingserious** [comment]
Thanks for the follow up @mercredo!

**Comment by mercredo** [comment]
It still doesnt seem to be solved completely. I finally found out, that I additionally need to add some substitution tag ("$something%") into the subject for it to not throw a BOUNCE.

I solved the issue temporarily:
```
$personalization->setSubject($this->_translate("Some fancy words with ä and ü and ö") . " / " . "somestring" . " / " . "somestring" . "%SGFIX%");
$personalization->addSubstitution("%SGFIX%", "");
```

**Comment by thinkingserious** [comment]
Hello @mercredo,

I will not call you diabolic ;)

This behavior is strange. Can you give me the specific bounce message you are receiving?

**Comment by mercredo** [comment]
See above:
--> SendGrid BOUNCES and keeps saying: "550 Subject contains invalid characters.".

**Comment by thinkingserious** [comment]
@mercredo,

Can you please provide the JSON that is causing the 550 error? And also the JSON of the fixed version? Thanks!
