### ISSUE TITLE
 Parse error: syntax error, unexpected '[', expecting ')' in /sendgrid-php/lib/helpers/mail/Mail.php on line 38

### ISSUE THREAD

**Issue by christiaank** [sendgrid/sendgrid-php#258]
#### Issue Summary

Just started integrating sendgrid-php but get the following error.

Parse error: syntax error, unexpected '[', expecting ')' in **my-path-to**/sendgrid-php/lib/helpers/mail/Mail.php on line 38

#### Steps to Reproduce

Installed sendgrid-php and trying to test using the basic demo example.

#### Technical details:

* sendgrid-php Version: 5.0.1
* PHP Version: 5.3.29 FastCGI (also tried regular CGI)
* MediaTemple host

**Comment by thinkingserious** [comment]
Thanks for letting us know!

I have a couple follow up questions:

1. How did you install? Composer?
2. Can you paste the relevant code here?

Thanks!

**Comment by christiaank** [comment]
Not using composer - downloaded the packaged files and installed directly.  Code as per below (removed API key)

```
<?php

require "$_SERVER[DOCUMENT_ROOT]/inc/php/sendgrid-php/sendgrid-php.php";

$from = new SendGrid\Email("chef.com.au Orders", "orders.cc@chef.com.au");
$subject = "Test email with SendGrid";
$to = new SendGrid\Email("Christiaan Knol", "christiaan@studio6digital.com.au");
$content = new SendGrid\Content("text/plain", "Test message content.");
$mail = new SendGrid\Mail($from, $subject, $to, $content);
$apiKey = getenv('API-KEY');
$sg = new \SendGrid($apiKey);
$response = $sg->client->mail()->send()->post($mail);

echo $response->statusCode();
echo $response->headers();
echo $response->body();

```

**Comment by thinkingserious** [comment]
Ah, you are using an unsupported version of PHP (or rather, MediaTemple is): https://github.com/sendgrid/sendgrid-php/issues/245. Is it possible to get an upgraded version, at least 5.6? Perhaps you can convince them with this: http://php.net/supported-versions.php

As a work around, you can try using the v3 /mail/send endpoint without the helper: https://github.com/sendgrid/sendgrid-php/blob/master/examples/mail/mail.php#L28

Also, on this line:
```
$apiKey = getenv('API-KEY');
```

Is API-KEY your SendGrid API Key? If so, then that is not correct. That line of code assumes you are storing your SendGrid API Key in an environment variable named API-KEY.

If you are not using environment variables (not recommended), you would do:

```
$apiKey = 'API-KEY';
```

Thanks!

**Comment by christiaank** [comment]
OK, thanks – I'll see what's involved in using a later version of PHP - latest they're offering at this stage is 5.5.35

Otherwise I'll look at alternatives like the SMTP option.

Thanks.

**Comment by thinkingserious** [comment]
Awesome, thanks for the follow up!
