### ISSUE TITLE
[Feature Request] Bulk mail sending

### ISSUE THREAD

**Issue by a2nt** [sendgrid/sendgrid-php#259]
Can you add bulk sending option to API using curl_multi_\* functions?

**Comment by thinkingserious** [comment]
Hello @a2nt,

I'm not quite sure what you are asking for, could you please provide more details? Thanks!

**Comment by a2nt** [comment]
Hello @thinkingserious,
it allows you to send few request simultaneuosly here's some details: http://www.phpied.com/simultaneuos-http-requests-in-php-with-curl/
It will be useful to send few messages at the same time and will make PHP processing faster.

**Comment by thinkingserious** [comment]
Thanks for the elaboration @a2nt, we have added this request to our backlog for consideration.

**Comment by mbernier** [comment]
Similar to #485
