### ISSUE TITLE
Problem when using {key} as a substitution

### ISSUE THREAD

**Issue by LewisTheobald** [sendgrid/sendgrid-php#264]
#### Issue Summary

We've been using the { and } symbol as the wrapper around our substitution tags. When migrating to v3, these come back with a '400 Bad Request'. Though the request works fine if I remove the substitutions section.
#### Steps to Reproduce

The JSON payload for the personalistion section is:

```
"personalizations": [{
    "to": [{
        "email": "lewistheobald@github.com"
    }],
    "substitutions": {
        "{id}": 1,
        "{name}": "Lewis Theobald",
        "{forename}": "Lewis",
        "{surname}": "Theobald"
    }
}]
```

The response is:

```
{
  "errors": [
    {
      "message": "Bad Request",
      "field": null,
      "help": null
    }
  ]
}
```

If I remove the substitutions block or change it to another symbol, we receive '202 Accepted'.
#### Technical details:
- sendgrid-php Version: master (latest commit: [commit number])
- PHP Version: 5.x

**Comment by LewisTheobald** [comment]
Actually, it spanned from only the single item

```
"{id}": 1
```

Should actually be

```
"{id}":"1"
```

Requires all parameters to be sent over as string enclosed in quotes. Should make this aware somewhere in the [Personalizations](https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/personalizations.html) section

**Comment by thinkingserious** [comment]
Thank you @LewisTheobald!

I will leave this ticket open until we update the docs and code to clarify.

**Comment by csaroff** [comment]
> I will leave this ticket open until we update the docs and code to clarify.

Can you update the the error object that is sent back to include more information than 

```javascript
{"errors":[{"message":"Bad Request","field":null,"help":null}]}
```

I didn't find this to be very useful in diagnosing the problem

**Comment by thinkingserious** [comment]
@csaroff,

Yes, that will be part of the update. 

Thanks for taking the time to provide feedback!

**Comment by ejames17** [comment]
@LewisTheobald  thanks saved me a few hours of debugging.

**Comment by thinkingserious** [comment]
@LewisTheobald,

Please take a moment to [fill out this form](https://dx.sendgrid.com/swag) so we can send you some swag :)

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
This has been moved [here](https://github.com/sendgrid/sendgrid-php/issues/434).
