### ISSUE TITLE
Email cubject length for personalisation

### ISSUE THREAD

**Issue by birdy247** [sendgrid/sendgrid-php#265]
When attempting to send a subject with a length > 78, I receive a response indicating the subject must be less than 78 chars.

Is this intended?  If so, perhaps there should be something in the docs to indicate this.

**Comment by thinkingserious** [comment]
@birdy247,

This issue was fixed on the API side a few weeks ago. We have removed this limit. 

I just tried to reproduce this error and I could not. 

Could you please give me your step by step to help reproduce?
