### ISSUE TITLE
PHP Version Compatibility

### ISSUE THREAD

**Issue by ilithium** [sendgrid/sendgrid-php#267]
#### Issue Summary

In your documentation, you don't seem to state anywhere (that I've seen) which version of PHP is required to use this library and, unfortunately, I have a client who is using an old version of PHP (5.3.3) which doesn't support the new PHP Array short form [ 'email' => $this->getEmail() ] (Mail.php:39 in your 5.0.4 release).

Please can you at least either (a) document the minimum required PHP version for the library to work or (b) not use backwards-incompatible code? I'm happy to create a PR if you'd like me to fix these issues.

#### Steps to Reproduce

1. Install SendGrid PHP API r5.0.4
2. Create a simple file which executes $sg = new \SendGrid($apiKey);
3. Execute the file

This is a bit disappointing on both the documentation front and on the build side: I appreciate that we all want nice, tidy and efficient code but, so far, I'm finding this unusable without a bunch of work and I'd _like_ to use your library but you've explicitly excluded a whole bunch of users.

#### Technical details:

* sendgrid-php Version: 5.0.4
* PHP Version: 5.3.3

**Comment by ilithium** [comment]
Turns out the reason for this issue is simply usage of the new Array form _and_ that your composer.json file is incorrect in regard to the version of PHP that is required to use this library.

I will attempt to correct this on 5.0.3 (as your composer.json says it requires PHP >= 5.3) and see if I can get it working and create PR if required/desired.

**Comment by thinkingserious** [comment]
Hello @ilithium,

Thanks for the feedback and offer to assist!

This library will only support versions that are not [end of life](http://php.net/supported-versions.php). Currently, that means versions 5.6 and above.

That said, I'm sure this community would appreciate a fork that supports older versions and we would be happy to link to it.

I will be adding the version requirement to the README under the dependencies section for better visibility.
