### ISSUE TITLE
Where is SendGrid/Email defined?

### ISSUE THREAD

**Issue by markmclaren2** [sendgrid/sendgrid-php#271]
I've downloaded sendgrid-php-5.0.7 and php-http-client-3.1.0 but when I try to send an email via SendGrid I get an error saying "Class 'SendGrid\\Email' not found..."

This might be a stupid question, but where is this class defined?

Thanks

Mark

For reference, here's the script I'm trying to run

<?php
require("sendgrid-lib/SendGrid.php");

$from = new SendGrid\Email(null, "support@solaraccounts.co.uk");
$subject = "Hello World from the SendGrid PHP Library!";
$to = new SendGrid\Email(null, "mark.mclaren@solaraccounts.co.uk");
$content = new SendGrid\Content("text/plain", "Hello, Email!");
$mail = new SendGrid\Mail($from, $subject, $to, $content);

$apiKey = "[removed]";
$sg = new \SendGrid($apiKey);

try {
    $response = $sendgrid->client->mail()->send()->post($mail);
} catch (Exception $e) {
    echo 'Caught exception: ',  $e->getMessage(), "\n";
}

echo $response->statusCode();
echo $response->headers();
echo $response->body();
?>

**Comment by mikegreen** [comment]
What line do you get the error? Line 4 or the $response?

**Comment by markmclaren2** [comment]
The error is on line 4.

I'm not too familiar with PHP, but shouldn't there be a Email.php file somewhere in the sendgrid-php-5.0.7.zip file I downloaded?

**Comment by mikegreen** [comment]
I think you want
require("/sendgrid-php/sendgrid-php.php");

You are downloading the packaged zip from here - https://github.com/sendgrid/sendgrid-php ?

**Comment by thinkingserious** [comment]
@markmclaren2,

Mike's last comment is what I would have added. I'm assuming you downloaded from here: https://github.com/sendgrid/sendgrid-php#alternative-install-package-from-zip (there is no need to download php-http-client separately)

Thanks @mikegreen!

**Comment by markmclaren2** [comment]
OK I've now downloaded and am using this .zip file instead:
https://sendgrid-open-source.s3.amazonaws.com/sendgrid-php/sendgrid-php.zip

(this is the link that is on page https://github.com/sendgrid/sendgrid-php#alternative-install-package-from-zip )

But now the error message is "Call to undefined function SendGrid\\curl_init() in [marks-sendgrid-root]/vendor/sendgrid/php-http-client/lib/SendGrid/Client.php on line 163"

Where is curl_init() defined?

**Comment by markmclaren2** [comment]
Whoops I hadn't installed curl.  When I ran "sudo apt-get install php5-curl" and restarted apache, everything worked fine!

Thanks for your help guys :)

**Comment by thinkingserious** [comment]
Awesome! Thanks for following up!
