### ISSUE TITLE
Attachment not base64 encoded error

### ISSUE THREAD

**Issue by arkoe** [sendgrid/sendgrid-php#272]
I have built an webapp that combines two uploaded photos into one, with watermark. Nothing special and works fine. However, when sending as an attachment with the Sendgrid API, sometimes the e-mail is not being sent due this error: The attachment content must be base64 encoded.

This is the code for the attachment:

`$resultphoto = new SendGrid\Attachment;
		$resultphoto->setFilename(str_replace('images/', '', $resultfilename));
		$resultphoto_base64 = chunk_split(base64_encode(file_get_contents($resultfilename)));
		$resultphoto->setContent($resultphoto_base64);
		$mail->addAttachment($resultphoto);`

When I encode the file that the Sendgrid API gives an error with, and copy it to a file or string or whatever, and decode it using PHP, the image does show up.

**Comment by arkoe** [comment]
Update: I have done 50 more tests from 5 different devices, sometimes they send, sometimes they don't. Exact same process, exact same photos.

**Comment by thinkingserious** [comment]
What happens when you don't do the chunk_split?

**Comment by arkoe** [comment]
Removing the chunk_split resolves the issue

**Comment by thinkingserious** [comment]
Thanks for the follow up!
