### ISSUE TITLE
Why does ended support to PHP 5.5?

### ISSUE THREAD

**Issue by fernandoval** [sendgrid/sendgrid-php#273]
This is not an issue. Only a question.

I still using Ubuntu Server 14.04 LTS with PHP 5.5.9.
There is no official upgrade to 16.04 LTS until 16.04.1 be lauched.
There is no official Ubuntu 16.04 LTS AMI in AWS.

There is a real reason to break support to PHP 5.5?

So I am freezed in sendgrid-php 5.0.4.

**Comment by thinkingserious** [comment]
Hello @fernandoval,

PHP 5.5 is end of life: http://php.net/eol.php

We are not intentionally breaking the library with respect to php 5.5, we are just no longer officially supporting it. AFAIK, the library should still work in php 5.5.

If there are library changes that must be made to specifically support 5.5, I suggest you fork this library.

I hope that helps!

**Comment by fernandoval** [comment]
It's ok.

But the Composer (based on the requirement of the minimum version of PHP) by default does not update or install a newer version of php-sendgrid than 5.0.4.

I am forced to use --ignore-platform-reqs option and this is not so good.

However, thanks for the explanation.

**Comment by thinkingserious** [comment]
@fernandoval,

Sorry for the extra pain. 

The other option is: https://github.com/sendgrid/sendgrid-php#alternative-install-package-from-zip
