### ISSUE TITLE
Add phpdoc and style fixes

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-php#276]
#### Issue Summary

Reference: https://github.com/sendgrid/sendgrid-php/pull/252/files

#### Technical details:

* sendgrid-php Version: 5.x
* PHP Version: 5.x

**Comment by aautar** [comment]
Seemed low-hanging, so I took a stab at it:
https://github.com/sendgrid/sendgrid-php/pull/307

I'll send the CLA soon.
