### ISSUE TITLE
Does not contain a valid address

### ISSUE THREAD

**Issue by the-dagger** [sendgrid/sendgrid-php#277]
I am trying to call the php script to send email using sendgrid by passing to/from email address and API key as a parameter. <br>
It throws an error saying  <br>```{"errors":[{"message":"Does not contain a valid address.","field":"personalizations.0.to.0.email","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.personalizations.to"}]}```

And on hard-coding the to address, it works flawlessly.

I have also used the same technique in setting the from address and API key which works without any problem, the only error seems to be in the from address.

Code : 
```<?php

require 'vendor/autoload.php';

$from = new SendGrid\Email(null,$argv[2]);  //No issues here
$subject = "Hello World from the SendGrid PHP Library!";
$to = new SendGrid\Email(null, $argv[5]);  //Throws the above mentioned error
$content = new SendGrid\Content("text/plain","Hello"); //I get the same error on replacing the content too with a variable passed to the script
$mail = new SendGrid\Mail($from, $subject, $to, $content);

$apiKey = $argv[1];
$sg = new \SendGrid($apiKey);

$response = $sg->client->mail()->send()->post($mail);
echo $response->statusCode();
echo $response->headers();
echo $response->body();``

My PHP version is `PHP 5.6.23-1`

**Comment by thinkingserious** [comment]
Hello @the-dagger,

Could you please print the value of $argv[5] and let me know the result? Also, please check the type: http://php.net/manual/en/function.gettype.php

My guess is that the argument is not being converted to a string.

Thanks!

**Comment by the-dagger** [comment]
@thinkingserious 
```
string
string
400HTTP/1.1 400 Bad Request
Server: nginx
Date: Mon, 08 Aug 2016 15:24:19 GMT
Content-Type: application/json
Content-Length: 204
Connection: keep-alive
X-Frame-Options: DENY

{"errors":[{"message":"Does not contain a valid address.","field":"personalizations.0.to.0.email","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.personalizations.to"}]}Script End
```
This is the output when i ran the script again.
The first 2 lines are the result of 
```echo gettype($argv[5]), "\n";
echo gettype($argv[2]), "\n";```

**Comment by thinkingserious** [comment]
@the-dagger,

What are the values of those strings?

**Comment by thinkingserious** [comment]
Can you also print out the value of `$mail`?

**Comment by the-dagger** [comment]
Hey @thinkingserious.
Apparently the variables passed to the php file was a string with spaces and hence each word was being read as a separate argument.
So, fixing that fixed the error.
Also one more thing, I wanted to upload a file whose location is varying according to the argument passed in to the script.
I had a look at the following method for adding an attachment 
``` $attachment1 = new Attachment();
    $attachment2->setContent("BwdW");
    $attachment2->setType("image/png");
    $attachment2->setFilename("banner.png");
    $attachment2->setDisposition("inline");
    $attachment2->setContentId("Banner");
    $mail->addAttachment($attachment1);```

But this method call doesn't seem to work for me.
It gives
 ```Fatal error:  Class 'SendGrid\SendGrid\Email' not found in /var/www/html/api/email.php on line 11```
Could you guide me towards the method that I should use?

**Comment by thinkingserious** [comment]
@the-dagger,

That is the correct method.

What is line 11 in email.php?

**Comment by the-dagger** [comment]
@thinkingserious 
it's this ```$from = new SendGrid\Email(null, $jsonData['sender']);```

My entire php file is [http://hastebin.com/ijecixoqex.php](http://hastebin.com/ijecixoqex.php)

**Comment by thinkingserious** [comment]
@the-dagger,

Can you try `Email` instead of `SendGrid\Email`?

**Comment by the-dagger** [comment]
@thinkingserious Thanks ! Upon removing all the occurrence of SendGrid\, there are no more such errors but I'm getting an error about base64 encoding.
```{"errors":[{"message":"The attachment content must be base64 encoded.","field":"attachments.0.content","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.attachments.content"}]}```
I read up a bit in the previous issues wherein it said to check if my attachment's size was not large than the upper limit.
But that's not the case the attachment is only 2.4mb in size.

**Comment by thinkingserious** [comment]
Yes, you need to encode the data with this function: http://php.net/manual/en/function.base64-encode.php

Example:
```php
$attachment->setContent(base64_encode("/var/www/html/release".$uid."/releaseapk.apk"));
```

**Comment by the-dagger** [comment]
Ok, this works and email is being sent.
But the size of attachment is just 1 kb now.

**Comment by thinkingserious** [comment]
@the-dagger,

I think you need to read the zip file as a string first, then pass that string to base64_encode: http://php.net/manual/en/function.fread.php

**Comment by the-dagger** [comment]
Ok, I'll check it out and let you know.
Thanks :+1:

**Comment by the-dagger** [comment]
@thinkingserious fread doesn't seem to do the trick.
Also I am sending a signed android app as attachment, so reading it as string and then repacking will corrupt it.
Is there any alternative approach to this problem?

**Comment by thinkingserious** [comment]
@the-dagger,

Do you mind sending us the file so we can troubleshoot on our side? 

dx@sendgrid.com

**Comment by the-dagger** [comment]
Hey @thinkingserious File as in the .apk file?

**Comment by thinkingserious** [comment]
@the-dagger,

Yes. I want to see if I can duplicate your error.

**Comment by the-dagger** [comment]
Sure, emailing it rn

**Comment by thinkingserious** [comment]
@the-dagger,

This code worked for me:

```php
<?php
// If you are using Composer
require 'vendor/autoload.php';

$sg = new \SendGrid(getenv("SENDGRID_API_KEY"));

$from = new SendGrid\Email(null, "dx@sendgrid.com");  //No issues here
$subject = "Hello World from the SendGrid PHP Library!";
$to = new SendGrid\Email(null, "elmer@sendgrid.com");  //Throws the above mentioned error
$content = new SendGrid\Content("text/plain", "Hello"); //I get the same error on replacing the content too with a variable passed to the script
$mail = new SendGrid\Mail($from, $subject, $to, $content);

$path = '/Users/thinkingserious/Workspace/sendgrid/sendgrid-php/releaseapk.apk';
$type = pathinfo($path, PATHINFO_EXTENSION);
$data = file_get_contents($path);

$attachment = new SendGrid\Attachment();
$attachment->setContent(base64_encode($data));
$attachment->setType($type);
$attachment->setFilename("releaseapk.apk");
$attachment->setDisposition("attachment");
$attachment->setContentId("releaseapk");
$mail->addAttachment($attachment);

$response = $sg->client->mail()->send()->post($mail);
echo $response->statusCode();
echo $response->headers();
echo $response->body();
```

**Comment by the-dagger** [comment]
@thinkingserious Thanks, this works as a charm.
I believe the issue was there because i was missing `$attachment->setType($type);`

**Comment by thinkingserious** [comment]
@the-dagger Awesome, thanks for following up!

**Comment by the-dagger** [comment]
No issues, 
Thank you for being so patient and helping me out :)
Cheers.
