### ISSUE TITLE
where is file sendgrid-php.php ?

### ISSUE THREAD

**Issue by sonyarianto** [sendgrid/sendgrid-php#279]
#### Issue Summary

A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, code examples.

#### Steps to Reproduce

1. This is the first step
2. This is the second step
3. Further steps, etc.

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* sendgrid-php Version: master (latest commit: [commit number])
* PHP Version: 5.x

**Comment by mikegreen** [comment]
Read the Install Package area here:
https://github.com/sendgrid/sendgrid-php

If you aren't using composer, download the zip file there and use that...

**Comment by thinkingserious** [comment]
@mikegreen is correct, that file is included in the downloadable package only, located here: https://github.com/sendgrid/sendgrid-php#alternative-install-package-from-zip

Thanks for providing the answer @mikegreen!
