### ISSUE TITLE
"emails and delete_all cannot both be set" error when deleting spam_reports

### ISSUE THREAD

**Issue by mcmillenb** [sendgrid/sendgrid-php#281]
#### Issue Summary

I'm trying to delete spam reports following the example in the README:

```
$request_body = json_decode('{
  "delete_all": false, 
  "emails": [
    "example1@example.com", 
    "example2@example.com"
  ]
}');
$response = $sg->client->suppression()->spam_reports()->delete($request_body);
echo $response->statusCode();
echo $response->body();
echo $response->headers();
```

But when I execute this code I get this error in the response:

> emails and delete_all cannot both be set

#### Steps to Reproduce

1. Create a valid SendGrid object ($sg = new SendGrid(API_KEY))
2. Execute the above code from the README

Not sure if this functionality is broken, or if the documentation is wrong, but one or the other should be fixed.

#### Technical details:

* sendgrid-php Version: 5.0.4
* PHP Version: 5.4

**Comment by thinkingserious** [comment]
@mcmillenb,

Apologies for the confusion.

This should work if you just remove the "delete_all" field. 

Thanks!
