### ISSUE TITLE
emails not being delievered

### ISSUE THREAD

**Issue by ruchisharma123** [sendgrid/sendgrid-php#282]
#### Issue Summary

Emails are not going since today morning. Please review the code below:
	$url = 'https://api.sendgrid.com/';
	$user = '';
	$pass = '';

	$message='test message';
$subject='test subject';
$toemail= '';
$fromemail='';
$fromname'='';

        $json_string = array( 'unique_args' => array( 'subject' => $subject ));
	
	$params = array(
	    'api_user'  => $user,
	    'api_key'   => $pass,
	    'to'        => $toemail,
	    'subject'   => $subject,
	    'html'      => $message,
	    'from'      => $fromemail,
	    'fromname'  => $fromname,
		'x-smtpapi' => json_encode($json_string),
	  );
	
	echo '<pre>';
	print_r($params);
	echo '</pre>';

	$request =  $url.'api/mail.send.json';
	//$request =  $url.'mail.send.json';
	
	// Generate curl request
	$session = curl_init($request);
	// Tell curl to use HTTP POST
	curl_setopt ($session, CURLOPT_POST, true);
	// Tell curl that this is the body of the POST
	curl_setopt ($session, CURLOPT_POSTFIELDS, $params);
	// Tell curl not to return headers, but do return the response
	curl_setopt($session, CURLOPT_HEADER, false);
	curl_setopt($session, CURLOPT_RETURNTRANSFER, true);

	// obtain response
	$response = curl_exec($session);
	curl_close($session);

please help through it as it is very urgent expecting for the best help from you as soon as possible.

#### Steps to Reproduce

1. This is the first step
2. This is the second step
3. Further steps, etc.

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* sendgrid-php Version: master (latest commit: [commit number])
* PHP Version: 5.x

**Comment by thinkingserious** [comment]
Hello @ruchisharma123,

This is not code from this library, could you please reach out to https://support.sendgrid.com? They will be happy to help.

Thanks!
