### ISSUE TITLE
Error sending one mail to many users

### ISSUE THREAD

**Issue by asantisan** [sendgrid/sendgrid-php#283]
I'm running this script for sending an email to many users. I want it to be, 1 to 1 without others users being copied in the headers.
this is the error i'm having:

`400HTTP/1.1 400 Bad Request Server: nginx Date: Tue, 30 Aug 2016 13:31:02 GMT Content-Type: application/json Content-Length: 216 Connection: keep-alive X-Frame-Options: DENY {"errors":[{"message":"Invalid type. Expected: string, given: array.","field":"personalizations.0.to.0.email","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.personalizations.to"...}`

This is the script i'm running for v3,

`<?php
require("sendgrid-php/sendgrid-php.php");

// query the users 
$resultado = mysqli_query($dbc,"SELECT email, hash FROM newsletter WHERE enviado = '0' AND newsletter = '1'");
$totalRows = mysqli_num_rows($resultado);
if ($totalRows == 0){ 
    echo "<p>No results</p>";
}

$all_users = array(); // intialzie array
while ($usuario = mysqli_fetch_array($resultado, MYSQLI_ASSOC)) {
    $usermail = $usuario['email']; 
    $hash = $usuario['hash'];
    mysqli_query($dbc, "UPDATE newsletter SET enviado = '1' WHERE email='$usermail' "); 
    $all_users[] = $usermail; // push all emails first
}

$apiKey = 'myapikey';
$sg = new \SendGrid($apiKey);

 try {
    $from = new SendGrid\Email(null, "no_responder@test.ar");
    $subject = "Convocatorias Semanales";
    $to = new SendGrid\Email(null, $all_users);
    $content = new SendGrid\Content("text/html", "Test");
    $mail = new SendGrid\Mail($from, $subject, $to, $content);
    $response = $sg->client->mail()->send()->post($mail);
    echo 'Ok!';
   
} catch (Exception $e) {
    echo 'Caught exception: ',  $e->getMessage(), "\n";
}
echo $response->statusCode();
echo $response->headers();
echo $response->body();
?>`

I can't send the array of users in "to". My purpose is to send one mail to each users individually without others users being copied in the headers.

* sendgrid-php Version: 3
* PHP Version:  5.5.9

**Comment by thinkingserious** [comment]
Hello @asantisan,

Here is an example:

```php
<?php
function exampleMultipleTos()
{
    $mail = new Mail();
    $email = new Email("DX", "test@example.com");
    $mail->setFrom($email);
    $mail->setSubject("Hello World from the SendGrid PHP Library");
    
    // Here is where you would loop through for each To email. Each To email needs its own Personalization
    $personalization1 = new Personalization();
    $email1 = new Email("Example User", "test1@example.com");
    $personalization1->addTo($email1);
    $mail->addPersonalization($personalization1);
    
    $personalization2 = new Personalization();
    $email2 = new Email("Example User", "test2@example.com");
    $personalization2->addTo($email2);
    $mail->addPersonalization($personalization2);
    
    $content = new Content("text/html", "<html><body>some text here</body></html>");
    $mail->addContent($content);
    $reply_to = new ReplyTo("test@example.com");
    $mail->setReplyTo($reply_to);
    return $mail;
}

function sendEmail()
{
    $apiKey = getenv('SENDGRID_API_KEY');
    $sg = new \SendGrid($apiKey);
    $request_body = exampleMultipleTos();
    $response = $sg->client->mail()->send()->post($request_body);
    echo $response->statusCode();
    echo $response->body();
    echo $response->headers();
}

sendEmail(); 
```

Source: https://github.com/sendgrid/sendgrid-php/blob/master/examples/helpers/mail/example.php#L22

**Comment by asantisan** [comment]
Thank you. Any other option to do it?

**Comment by thinkingserious** [comment]
@asantisan,

You could build the json object yourself, like this: https://github.com/sendgrid/sendgrid-php/blob/master/examples/mail/mail.php#L28

**Comment by Vahanerevan** [comment]
Maybe you need to add this example in readme.md.

**Comment by thinkingserious** [comment]
@Vahanerevan,

Thank you for taking the time to provide additional feedback!

We already have the basic version [here in the README](https://github.com/sendgrid/sendgrid-php#without-mail-helper-class) with a link to that code in the paragraph, right under the header. Do you have a suggestion on how I can make that more obvious?

Also, we are building out a [Use Cases section](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md) (that is linked from the README) and your use case will definitely be included. Hopefully that will help make things easier too.

With Best Regards,

Elmer

**Comment by lafod** [comment]
Hello ,
Am getting this response 

{"errors":[{"message":"Invalid type. Expected: object, given: array.","field":"personalizations.0.to.0","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.personalizations.to"}]}

this is my request body

{"from":{"name":"ERP","email":"dev@gmail.com"},"personalizations":[{"to":[[{"email":"user@gmail.com"}]]}],"subject":"New User Created ","content":

**Comment by thinkingserious** [comment]
Hi @lafod,

It looks like your request body was truncated, could you please repost.

But from what I see, `[[{"email":"user@gmail.com"}]]` should be `[{"email":"user@gmail.com"}]`

**Comment by trainoasis** [comment]
This error appears to me on WP plugin, what can I do ?! array cannot be passed to wp_mail function as usual?
