### ISSUE TITLE
There is no way to send a templated mail without content.

### ISSUE THREAD

**Issue by vitya1** [sendgrid/sendgrid-php#285]
Currently developers to send an email have to set content, even when this is actually no need. For example, in case when there is template includes all required content or template with user variables only.
#### Steps to Reproduce

See this https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#with-mail-helper-class
No way to avoid Content() object initialisation.

I think it would be useful to make it possible.
#### Technical details:
- sendgrid-php Version: master (364f693c2cf4cc6eae4afc4efd2b031fb3f41d50: 474)
- PHP Version: 5.6

**UPD**: Subject is required field for templating mails as well. Even when they have its own subjects

**Comment by thinkingserious** [comment]
Hello @vitya1,

If you don't use the Mail constructor, [like this](https://github.com/sendgrid/sendgrid-php/blob/master/examples/helpers/mail/example.php#L22), you don't need to include the content object. I'll investigate the subject.

Thanks!

**Comment by vitya1** [comment]
Hello @thinkingserious ,
Thank you for your answer. So maybe create a special method for templated mail sending, which would encapsulate personalization logic creation (like the Mail constructor). I guess it can cover pretty big number of cases.

**Comment by thinkingserious** [comment]
Hello @vitya1,

I have verified that when you have a template ID set, you don't need to include the subject or the content.

Here are some new examples that I hope will help: https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#transactional_templates

We do plan to make a template helper. Right now, the order of priority is to improve the Mail Helper, then create a template Helper followed by an attachment helper.

Thanks!
