### ISSUE TITLE
Subject encode problem using templates

### ISSUE THREAD

**Issue by littlewall** [sendgrid/sendgrid-php#286]
#### Issue Summary

There's a problem with subject encoding while using templates variables.
#### Steps to Reproduce

```
$from = new SendGrid\Email("CoffeeBay", "***@coffeebay.cz");
$subject = "Just because it cant be empty";
$to = new SendGrid\Email(null, "***@coffeebay.cz");
$content = new SendGrid\Content("text/html", "Just because it cant be empty");
$mail = new SendGrid\Mail($from, $subject, $to, $content);
$mail->personalization[0]->addSubstitution(":email_year", "***");
// ... a few more substitution
$mail->setTemplateId("***");
```

Real subject "Přišla nová objednávka z CoffeeBay" is saved in template.
The bottom email is what the wrong subject looks like:
![wrong subject](https://cloud.githubusercontent.com/assets/16668308/18228492/f569cc2e-7250-11e6-8786-65dfac09d79c.png)

Raw:
`Subject: Přišla nová objednávka z CoffeeBay`

I tried utf_encode() but doesnt help.  (#162)

When I remove template:

```
$from = new SendGrid\Email("CoffeeBay", "***@coffeebay.cz");
$subject = "Just because it cant be empty";
$to = new SendGrid\Email(null, "***@coffeebay.cz");
$content = new SendGrid\Content("text/html", "Just because it cant be empty");
$mail = new SendGrid\Mail($from, $subject, $to, $content);
```

everything works just fine (top email on picture).

Raw:
`Subject: =?UTF-8?B?UMWZacWhbGEgbm92w6Egb2JqZWRuw6F2a2EgeiBDb2ZmZWVCYXk=?=`

Any ideas? Thank.

**Comment by thinkingserious** [comment]
Hello @milanzitka,

Have you tried using this sample code? https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#with-mail-helper-class

When I tried it, both with setting the `$subject` and storing the subject in the template, I did not see the wrong subject.

**Comment by milanzitka** [comment]
Hello @thinkingserious,
thank you for your reply. And yes, i tried it. But i tried again today, and it seems like there's problem only when I add some substitution.

**This is okay:**
![right](https://cloud.githubusercontent.com/assets/16668308/18306950/75c9d7d4-74ee-11e6-810f-b75dc391cf36.png)
```
$from = new SendGrid\Email(null, "emailfrom");
$to = new SendGrid\Email(null, "emailto");
$subject = "Something";
$content = new SendGrid\Content("text/html", "Something");
$mail = new SendGrid\Mail($from, $subject, $to, $content);
$mail->setTemplateId("***");
```

**This not:**
![wrong](https://cloud.githubusercontent.com/assets/16668308/18306991/a84a9aae-74ee-11e6-8fd2-299032a3b7fe.png)
```
$from = new SendGrid\Email(null, "emailfrom");
$to = new SendGrid\Email(null, "emailto");
$subject = "Something";
$content = new SendGrid\Content("text/html", "Something");
$mail = new SendGrid\Mail($from, $subject, $to, $content);
$mail->setTemplateId("***");
$mail->personalization[0]->addSubstitution("::email_year", "2016");
```

**Comment by thinkingserious** [comment]
Thanks for the follow up @milanzitka,

It looks like we are going to have to dig further on this one. That is strange behavior indeed.

**Comment by Nightzer** [comment]
Is this issue still unresolved? 
im having the same problems

**Comment by thinkingserious** [comment]
Hello @Nightzer,

This issue is still on our backlog pending investigation. I've just now added your vote to help move it up the queue. 

Thanks!

**Comment by rh78** [comment]
I have the same Problem. I went with sendgrid Support and exchanged lots of messages but at the end i have up because Support was not able to help me. Thinking about moving from transactional Templates to own stuff because of this. But the Templates was one of the main reasons i wanted to go with sendgrid...

**Comment by thinkingserious** [comment]
@rh78,

Our engineers are now working on a fix and I'll update this thread when it goes live.

My apologies for the inconvenience and we appreciate your patience.

With Best Regards,

Elmer

**Comment by rh78** [comment]
Thanks. Can you give us some timeframe when to expect a fix? We want to go live by end of January.

**Comment by rh78** [comment]
Ps: for me its not PHP but .net API but it seems to be a cross API Problem.

**Comment by thinkingserious** [comment]
@rh78,

Yes, it's an API level problem. 

Unfortunately, I do not have deep insight into the engineering timeline. But the fact that the issue is in development now, leads me to believe it should be pushed live by the end of January, but I can not guarantee that.

**Comment by thinkingserious** [comment]
Hello @littlewall @Nightzer @rh78,

My apologies for allowing this to fall between the cracks. I should have updated you regarding [the fix back in August](https://github.com/sendgrid/sendgrid-python/issues/302).

Please let me know if you continue to experience this issue.

With Best Regards,

Elmer
