### ISSUE TITLE
How to add Bcc to the current README.md example?

### ISSUE THREAD

**Issue by josephernest** [sendgrid/sendgrid-php#288]
This fails: 

```
<?php require("path/to/sendgrid-php/sendgrid-php.php");

$from = new SendGrid\Email(null, "test@example.com");
$subject = "Hello World from the SendGrid PHP Library!";
$to = new SendGrid\Email(null, "test@example.com");
$content = new SendGrid\Content("text/plain", "Hello, Email!");
$mail = new SendGrid\Mail($from, $subject, $to, $content);

$mail->addBcc('foo@bar.com');   // !! FAILURE HERE !!

$apiKey = getenv('SENDGRID_API_KEY');
$sg = new \SendGrid($apiKey);

$response = $sg->client->mail()->send()->post($mail);
echo $response->statusCode();
echo $response->headers();
echo $response->body();
?>
```

How to do it properly?

**Comment by thinkingserious** [comment]
Hello @josephernest,

Because you are using the Mail constructor, we create an initial personalizations object for you behind the scenes. So to add the BCC, you need to do something like: https://github.com/sendgrid/sendgrid-php/blob/master/examples/helpers/mail/example.php#L16

Thanks!

**Comment by josephernest** [comment]
@thinkingserious I don't understand: why would this `$mail->personalization[0]->addTo($to);` be equivalent to a regular BCC in a email header ?

**Comment by thinkingserious** [comment]
Hi @josephernest,

We are trying to build an object similar to [this](https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/personalizations.html#-Sending-a-Single-Email-to-a-Single-Recipient-With-a-CC-and-a-BCC). Since we already create that personalization object with the constructor, we need to add the BCC to it. 

When you do `$mail->addBcc`, you are adding it to the mail object, when it really needs to go inside of the personalization object.

Here is what your code would look like:

```php
<?php require("path/to/sendgrid-php/sendgrid-php.php");

$from = new SendGrid\Email(null, "test@example.com");
$subject = "Hello World from the SendGrid PHP Library!";
$to = new SendGrid\Email(null, "test@example.com");
$content = new SendGrid\Content("text/plain", "Hello, Email!");
$mail = new SendGrid\Mail($from, $subject, $to, $content);
$mail->personalization[0]->addBcc('foo@bar.com');

$apiKey = getenv('SENDGRID_API_KEY');
$sg = new \SendGrid($apiKey);

$response = $sg->client->mail()->send()->post($mail);
echo $response->statusCode();
echo $response->headers();
echo $response->body();
?>
```

But you are correct, it makes sense that you should be able to simply do `$mail->addBcc('foo@bar.com');`. We are going to figure out the best way to do that in the next iteration of the Mail Helper. I hope that when we create the issue to do that, you will chime in with your feedback :)

Thanks!

**Comment by josephernest** [comment]
Thanks a lot for this! I have to confess that, after discovering this
library, and spending 2 hours digging, without finding what I needed
(simply sending an email with a bcc), I moved to another solution that is
now running on production... But maybe one day I'll come back again! I wish
you the best for your library.

**Comment by thinkingserious** [comment]
Hi @josephernest,

Thanks for the follow up! Though I am sad that you have left us, I'm greatly appreciative for your feedback, which will help others avoid this issue in the future.

Best of luck!

With Best Regards,

Elmer

**Comment by josephernest** [comment]
Hi @thinkingserious,

I tried your last code with: 

    $mail->personalization[0]->addBcc('test@example.com');

but I get this response:

    400Array ( [0] => HTTP/1.1 400 Bad Request [1] => Server: nginx [2] => Date: Fri, 08 Sep 2017 17:41:50 GMT [3] => Content-Type: application/json [4] => Content-Length: 213 [5] => Connection: keep-alive [6] => X-Frame-Options: DENY [7] => Access-Control-Allow-Origin: https://sendgrid.api-docs.io [8] => Access-Control-Allow-Methods: POST [9] => Access-Control-Allow-Headers: Authorization, Content-Type, On-behalf-of, x-sg-elas-acl [10] => Access-Control-Max-Age: 600 [11] => X-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html [12] => [13] => )

In particular this error:

     {"errors":[{"message":"Invalid type. Expected: object, given: string.","field":"personalizations.0.bcc.0","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.personalizations.bcc"}]}

What's the problem?

Thanks in advance.

**Comment by josephernest** [comment]
There is a little mistake in your previous code @thinkingserious. Please replace:

    $mail->personalization[0]->addBcc('foo@bar.com');

by

    $bcc = new SendGrid\Email(null, "foo@bar.com");
    $mail->personalization[0]->addBcc($bcc);

**Comment by thinkingserious** [comment]
Thanks @josephernest!

Have you had a chance to look at the [new SDK design](https://github.com/sendgrid/sendgrid-php/issues/413)? Your feedback would be greatly appreciated.

**Comment by chrisarusso** [comment]
Hmmm, the implementation that actually just worked for me was: 

```
$bcc = new SendGrid\Email("Example Name", "email@example.com");
$mail->personalization[0]->addBcc($bcc);
```

**Comment by thinkingserious** [comment]
Hi @chrisarusso,

Thanks for the confirmation!

Do you have any thoughts on the [new interface](https://github.com/sendgrid/sendgrid-php/issues/413)?

Thanks!

With Best Regards,

Elmer

**Comment by FlaviuRadulescu** [comment]
Hello @thinkingserious 

when I use the code to send to BCC addresses as you suggested ($mail->personalization[0]->addBcc($bcc);)  , I see in the email header the BCC: name added under the Subject. Also, Outlook displays the BCC in the header of the email 
![sendgrid bcc](https://user-images.githubusercontent.com/31763056/37880789-992edfc2-3085-11e8-8ca8-41dc36acb3d1.JPG)
. This is the first time when I see the BCC added to the email header.

How can I remove this before sending the email? Please see below a snippet from the email header.

Thank you,
Flaviu



To: Email Name <email@addresss>
Message-ID: <voP-PTBRS3qJM4TJ3_yNuA@ismtpd0005p1lon1.sendgrid.net>
Cc: Email Name <email@addresss>
Subject: Subject de email - trimit bcc la gmail 11:26
Bcc: Email Name <email@addresss>

**Comment by thinkingserious** [comment]
Hello @FlaviuRadulescu,

Are you saying that you can see the bcc field when receiving the email in Outlook?

With Best Regards,

Elmer

**Comment by FlaviuRadulescu** [comment]
Yes, I have attached a picture. Can you see it?

**Comment by thinkingserious** [comment]
Hello @FlaviuRadulescu,

I'm not sure what the issue is here. Could you please open up a new issue so that I may add this to my backlog for further review and also possibly get some insight from our PHP community?

Thanks!

Elmer
