### ISSUE TITLE
BREAKING CHANGES

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-php#290]
As a result of your feedback and as a continuation of the execution of our long term roadmap, there will be breaking changes coming soon. The last time we had a major breaking change, it was for the implementation of v3 Web API support. We announced those changes here on GitHub along with some instructions on how to test and provide feedback. 

The feedback we got was amazing, but we didn't quite get the amount or thoroughness of feedback we were hoping for.

We want to continue improving this iterative process, so we are reaching out to you for feedback in order to determine the optimum way to move forward as this library is designed to be community driven, SendGrid led.

**Please take a moment to share your thoughts with us.** 

Following are some ideas we are considering, we will likely choose one from Execution and one from Communication, but not all of the items below.

Execution (for large changes):
1. Utilize the [pre-release functionality](https://help.github.com/articles/creating-releases/) in GitHub to gather feedback and contributions to a specific branch
2. Communicate through a dedicated GitHub issue that references that pre-release branch (e.g [C# Dynamic Update](https://github.com/sendgrid/sendgrid-csharp/issues/303))

Communication:
1. Continue using GitHub issues
2. Opt-in email newsletter for announcements
3. Opt-in email mailing list
4. Dedicated social media account (e.g. @sendgrid_libraries)

How do you prefer to get these announcements? Is this too much? Too little? Please let us know!! 

As always, we are listening carefully and are looking forward to working with you.

**Note: We will always follow the semver.org convention of using major point releases to signify breaking changes. Please DO NOT auto-update your dependencies. It is important to take a look at the CHANGELOG or releases to find out how the breaking changes will impact your code.**

**Comment by ninsuo** [comment]
As far as I can see in 5.0.4, we cannot set any curl option in the client.
This is a big lack of flexibility.
This broken #149 and #157

**Comment by thinkingserious** [comment]
@ninsuo,

Thanks, that is great feedback!

I'm thinking the change would go here: https://github.com/sendgrid/php-http-client/blob/master/lib/Client.php#L42

Would you like to give it a shot with a PR, or would you like us to create a ticket for a fix?

With Best Regards,

Elmer

**Comment by ninsuo** [comment]
Yep, we need this quickly and your implementation is quite simple, so I will open a PR tomorrow.

Thanks,

**Comment by thinkingserious** [comment]
Awesome, thank you @ninsuo!

**Comment by lode** [comment]
I would like Execution 2 (although I prefer 1 but GitHub notifications don't work well along with that) and Communication 2.

Is that the kind of feedback you're looking for?

**Comment by thinkingserious** [comment]
Yes, thanks @lode!
