### ISSUE TITLE
Mail Class Constructor is counter intuitive

### ISSUE THREAD

**Issue by tstrijdhorst** [sendgrid/sendgrid-php#291]
The constructor of the mail utility class only does something when all parameters are provided yet all parameters seem optional in the method signature:
https://github.com/sendgrid/sendgrid-php/blob/master/lib/helpers/mail/Mail.php#L917-L929

I discovered this when I didn't provide all the values and it didn't work as expected. The only way you can see it needs all the values is by looking at the library code which isn't the most user friendly thing to do.

Either remove the defaults or make it so that you can use it without filling in all the arguments.

**Comment by thinkingserious** [comment]
Great idea, I'm going to leave this open for implementation.

Note, that you don't have to use that constructor. It was created for the simple hello world type use case. Here are alternatives:

- https://github.com/sendgrid/sendgrid-php#without-mail-helper-class
- https://github.com/sendgrid/sendgrid-php/blob/master/examples/helpers/mail/example.php#L22

Thanks again!

**Comment by thinkingserious** [comment]
Please follow [this issue](https://github.com/sendgrid/sendgrid-php/issues/300) to track progress on this.

Thanks!
