### ISSUE TITLE
Prism file in sendgrid-php.zip

### ISSUE THREAD

**Issue by adrianjones1** [sendgrid/sendgrid-php#292]
I just download the Packaged Library for the V3 API from https://sendgrid-open-source.s3.amazonaws.com/sendgrid-php/sendgrid-php.zip and found an odd 15.9MB file called Prism in the zip. Can you confirm what this is for as it appears to be a Unix executable which could be dangerous.

**Comment by thinkingserious** [comment]
@adrianjones1,

Thanks for the heads up! That file should be excluded in the upload. I'll leave this ticket open to fix that.

It's safe for you to delete it. We use it for our unit tests. You can find out about prism here: https://stoplight.io/prism

**Comment by adrianjones1** [comment]
Thanks for confirming that and glad its nothing to worry about anyway. The API is working great for our needs :-)

**Comment by moparlakci** [comment]
is it some kinda NSA thing?

**Comment by brandonmwest** [comment]
https://stoplight.io/platform/prism/

**Comment by Veve2** [comment]
FYI, This file is still in the zip.

**Comment by thinkingserious** [comment]
Thanks for the heads up @Veve2.

I think I need to exclude the prism directory here: https://github.com/sendgrid/sendgrid-php/blob/master/scripts/s3upload.sh#L12

I will add your vote to this item in our backlog. It's not that high of priority, but the priority can be raised if others vote on the issue or if someone submits a PR.

With Best Regards,

Elmer
