### ISSUE TITLE
Sending all emails to a specified address in local environment

### ISSUE THREAD

**Issue by pdoreau** [sendgrid/sendgrid-php#293]
Hello.
I'm thinking about using sendgrid-php instead of swiftmailer.
With swiftmailer, an option is available to avoid sending email to real users when I work in my local environment : [delivery_address](http://symfony.com/doc/current/email/dev_environment.html#sending-to-a-specified-address).

Is there something similar with sendgrid-php or do I have to code it myself ?

**Comment by thinkingserious** [comment]
Hi @pdoreau,

Yes, we have a [sandbox mode](https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/sandbox_mode.html). 

Here is some [example code](https://github.com/sendgrid/sendgrid-php/blob/master/examples/helpers/mail/example.php#L129).

Thanks!
