### ISSUE TITLE
how to know invalid emails?

### ISSUE THREAD

**Issue by franklynsd** [sendgrid/sendgrid-php#305]
Hi, we'd like to know which emails in our system are invalid addresses.
Do you think we can use the bounces API or the bounce webhook event?
Would this be accurate? If so, how can we do this with the php library?

**Comment by thinkingserious** [comment]
Hello @franklynsd,

You can interact with this emails like this: https://github.com/sendgrid/sendgrid-php/blob/master/examples/suppression/suppression.php#L102
