### ISSUE TITLE
File Attachment not sending correctly

### ISSUE THREAD

**Issue by NullPatrol** [sendgrid/sendgrid-php#306]
#### Issue Summary

FIle attachment content not being sent correctly
  $filename="information.csv";
  $filePath = dirname(**FILE**);
  if(count($return)>0) {
    $params = array(
      'api_user'  => $user,
      'api_key'   => $pass,
      'to'        => $email,
      'subject'   => 'Subject',
      'html'      => $html,
      'text'      => "Dear blablabla text",
      'from'      => 'notifications@email.com',
      'files['.$filename.']' => '@'.$filePath.'/'.$filename
    );
    $request =  $url.'api/mail.send.json';
    $session = curl_init($request);
    curl_setopt ($session, CURLOPT_POST, true);
    curl_setopt ($session, CURLOPT_POSTFIELDS, $params);
    curl_setopt($session, CURLOPT_HEADER, false);
    curl_setopt($session, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_2);
    curl_setopt($session, CURLOPT_RETURNTRANSFER, true);
    curl_exec($session);
    curl_close($session);

the file sent to me is information.csv with the contents: "/var/www/html/notifications/information.csv"
**FILE** (dir the files are both in) is (obviously) /var/www/html/notifications.

issue is that the thing sent as an attachment is the text and not the contents of the referred file. 
Is this a bug or am I doing something wrong? Couldn't find anything online.

**Comment by thinkingserious** [comment]
Hello @NullPatrol,

Here is an example of sending an attachment with this library: https://github.com/sendgrid/sendgrid-php/blob/master/examples/helpers/mail/example.php#L82 (note that the contents must be base64 encoded)

In the above example, you are using the v2 mail endpoint directly, it's documentation is here: https://sendgrid.com/docs/API_Reference/Web_API/mail.html#-Send-a-test-with-attachment

This may also be helpful to you: http://stackoverflow.com/questions/25769429/sendgrid-curl-php-external-file-attachment-broken

**Comment by NullPatrol** [comment]
I'm unable to use the vendor loader class.
as for the v2 mail API, that is exactly what I did as far as I am concerned.
The stackoverflow suggestion seems to have no effect on the given output

https://gyazo.com/08fce8a8df8aaba8a6cff2fdd7c206ad.png

**Comment by thinkingserious** [comment]
@NullPatrol,

Can you please elaborate on "I'm unable to use the vendor loader class."? 

Are you installing via Composer or direct download?

If you want to use cURL and still have issues, please contact our support team at https://support.sendgrid.com. This issue tracker relates to the sendgrid-php library.

Thanks!

**Comment by thinkingserious** [comment]
Hello @NullPatrol, here is the latest example on how to use attachments with this library: https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#attachments

I hope that helps!
