### ISSUE TITLE
Unique arguments with substitution tags

### ISSUE THREAD

**Issue by drawmyattention** [sendgrid/sendgrid-php#308]
Is it possible to set a unique argument for each e-mail I send, when sending to multiple recipients and when using substitution tags?

Currently using the following code which works fine to send to multiple users, with substitution tags:

    $mail = new SendGrid\Mail();
    $mail->setFrom($email)
        ->setFromName($from)
        ->setSubject($subject)
        ->setHtml($body)
        ->setTos($recipients)
        ->addSubstitution("__recipientid__", $replacementIDS)
        ->addSubstitution("__recipient__", $replacementNames);

I'd like to be able to also add something like: ```->addUniqueArgumentSubstitution('my_unique_key', $arrayOfValues);```

**Comment by thinkingserious** [comment]
Hi @drawmyattention,

Do you mean something like this? https://github.com/sendgrid/sendgrid-php/blob/master/examples/helpers/mail/example.php#L72

**Comment by drawmyattention** [comment]
Perfect. I was using an old version of the package, which did not have the ```Personalization``` class.

Was there a way to do this without that class?

**Comment by thinkingserious** [comment]
@drawmyattention,

No, the personalization class is fundamental to the new v3 design. 

You can dig deeper here: https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/personalizations.html

Thanks!
