### ISSUE TITLE
Attachment file is corrupted 

### ISSUE THREAD

**Issue by mohiolmis** [sendgrid/sendgrid-php#310]
#### Issue Summary

When I send a mail its send with attachment but attachment file is corrupted .I use 2 code . Please help me .
#### Steps to Reproduce
1. This is the first Code
   <?php

//
// SendGrid PHP Library Example
//
// This example shows how to send email through SendGrid
// using the SendGrid PHP Library.  For more information
// on the SendGrid PHP Library, visit:
//
//     https://github.com/sendgrid/sendgrid-php
//

require 'vendor/autoload.php';

/\* USER CREDENTIALS
/  Fill in the variables below with your SendGrid
/  username and password.
====================================================*/
$sg_username = "###";
$sg_password = "###";

/\* CREATE THE SENDGRID MAIL OBJECT
====================================================*/
$sendgrid = new SendGrid( $sg_username, $sg_password );
$mail = new SendGrid\Email();

/\* ADD THE ATTACHMENT
/  For the purposes of this demo, the file being
/  attached resides in the same folder as this
/  example.php file
====================================================*/
$mail->setAttachment('sendgrid_logo.jpg');

/\* SMTP API
====================================================*/
// ADD THE RECIPIENTS
$emails = array (
    "mohiolmis@gmail.com"
);
foreach($emails as $recipient) {
    $mail->addTo($recipient);
}

// ADD THE CATEGORIES
$categories = array (
    "test_attachment"
);
foreach($categories as $category) {
    $mail->addCategory($category);
}

// ADD THE UNIQUE ARGUMENTS
$unique_args = array (
    "action" => "test_attachment"
);
foreach ( $unique_args as $key => $value ) {
    $mail->addUniqueArgument( $key, $value );
}

// ADD THE APP FILTERS
$filters = array (
    "clicktrack" => array (
        "settings" => array (
            "enabled" => 1
        )
    ),
    "opentrack" => array (
        "settings" => array (
            "enabled" => 1
        )
    ),
    "subscriptiontrack" => array (
        "settings" => array (
            "enabled" => 1,
            "text/plain" => "If you would like to unsubscribe and stop receiving these emails click here: <% %>.",
            "text/html" => "<p>If you would like to unsubscribe and stop receiving these emails <% click here %>.</p>"
        )
    )
);
foreach($filters as $filter => $contents) {
    $settings = $contents['settings'];
    foreach($settings as $key => $value) {
        $mail->addFilterSetting($filter, $key, $value);
    }
}

/\* SEND MAIL
/  Replace the the address(es) in the setTo/setTos
/  function with the address(es) you're sending to.
====================================================*/
try {
    $mail->
    setFrom( "acb@calltet.com" )->
    setSubject( "Test attachment through PHP" )->
    setText( "Hello,\n\nThis is a test attachment email through PHP from SendGrid.    We have sent this to you because you requested a test message be sent from your account.\n\nThis is a link to google.com: http://www.google.com\nThis is a link to apple.com: http://www.apple.com\nThis is a link to sendgrid.com: http://www.sendgrid.com\n\nThank you for reading this test message.\n\nLove,\nYour friends at SendGrid" )->
    setHtml( "<table style=\"border: solid 1px #000; background-color: #666; font-family: verdana, tahoma, sans-serif; color: #fff;\"> <tr> <td> <h2>Hello,</h2> <p>This is a test attachment email through PHP from SendGrid.    We have sent this to you because you requested a test message be sent from your account.</p> <a href=\"http://www.google.com\" target=\"_blank\">This is a link to google.com</a> <p> <a href=\"http://www.apple.com\" target=\"_blank\">This is a link to apple.com</a> <p> <a href=\"http://www.sendgrid.com\" target=\"_blank\">This is a link to sendgrid.com</a> </p> <p>Thank you for reading this test message.</p> Love,<br/> Your friends at SendGrid</p> <p> <img src=\"http://cdn1.sendgrid.com/images/sendgrid-logo.png\" alt=\"SendGrid!\" /> </td> </tr> </table>" );
    $sendgrid->send( $mail );

```
echo "Sent mail successfully.";
```

} catch ( Exception $e ) {
    echo "Unable to send mail: ", $e->getMessage();
}

?>

**2 . Second code**

```
        $url = 'https://api.sendgrid.com/';
        $user = '####';
        $pass = '######';




        $fileName = $filename;
        $filePath = 'path';


                $params = array(
            'api_user'  => $user,
            'api_key'   => $pass,
            'to'        => $to_mail,
            'subject'   => $subject,
            'html'      => $body.'<br/><p>If You Want to Unsubscripe Please <a style="color:#3A70D5;" title="Click Here">Click Here</a></p>',
            'from'      => 'callnotification@calltext.com',
            'files['.$fileName.']' => '@'.$filePath.'/'.$fileName
          );





        print_r($params);

        $request =  $url.'api/mail.send.json';

        // Generate curl request
        $session = curl_init($request);

        // Tell curl to use HTTP POST
        curl_setopt ($session, CURLOPT_POST, true);

        // Tell curl that this is the body of the POST
        curl_setopt ($session, CURLOPT_POSTFIELDS, $params);

        // Tell curl not to return headers, but do return the response
        curl_setopt($session, CURLOPT_HEADER, false);
        // Tell PHP not to use SSLv3 (instead opting for TLS)
        curl_setopt($session, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_2);
        curl_setopt($session, CURLOPT_RETURNTRANSFER, true);

        // obtain response
        $response = curl_exec($session);
        curl_close($session);

        // print everything out
        print_r($response);
```

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?
#### Technical details:
- sendgrid-php Version: master (latest commit: [commit number])
- PHP Version: 5.x

**Comment by thinkingserious** [comment]
Hello @mohiolmis,

That library version is now unsupported, could you please try with the new version, found in this repo?

Here is an attachment example: https://github.com/sendgrid/sendgrid-php/blob/master/examples/helpers/mail/example.php#L82

Thanks!

With Best Regards,

Elmer

**Comment by switchme-developer** [comment]
Hi @mohiolmis ,

I am facing the same problem.Any attachment send with sendgrid is getting corrupted in the received email.We are using v2 of sendgrid in our code.Will migrating to v3 of sendgrid help solve this issue??
We will have to make changes to our codebase for this. 

Thanks

**Comment by thinkingserious** [comment]
Please see [this example](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#attachments) for sending attachments with the latest version of this library.
