### ISSUE TITLE
Exact same file name cannot be placed as attachment

### ISSUE THREAD

**Issue by biggienor** [sendgrid/sendgrid-php#311]
We send emails through SendGrid with the help of the sendgrid-php library. This works like a charm.
Since recently we noticed that if a filename has already been placed as a attachment, only one of both gets send to the receiver.
#### Steps to Reproduce

Have two files with the exact same name but in different folders.
Try to send them as attachment to a random emailaddress
#### Technical details:
- sendgrid-php Version: master (latest commit: [commit number])
- PHP Version: 5.6

**Comment by thinkingserious** [comment]
Thanks for reporting this @biggienor,

We have added this to our backlog for a fix.

**Comment by joe-niland** [comment]
Hi,

I tried this using the code in this Gist:

https://gist.github.com/joe-niland/e69c223b85a481b30ca2548c85c7b4e2

Seemed to work fine - I received two attachments, both with the same file name. @biggienor is this how you were using the SDK?

**Comment by biggienor** [comment]
Hi @joe-niland,
Thanks for providing the feedback. We don't add attachment as followed:

$att1 = new \SendGrid\Attachment();
$att1->setContent( file_get_contents("test_files/1/1.txt") );
$att1->setType("text/plain");
$att1->setFilename("1.txt");
$att1->setDisposition("attachment");
$mail->addAttachment( $att1 );

We add the file directly into the addAttachment() function. Is it necessary to use the other functions as well?

**Comment by joe-niland** [comment]
Hey @biggienor 

I'm not familiar enough with the internals to comment, sorry.
If you have a code snippet, I could try to repro your issue.

**Comment by thinkingserious** [comment]
@biggienor,

If you are uncomfortable sharing the code publicly, please send to dx@sendgrid.com. Thanks!

**Comment by biggienor** [comment]
@thinkingserious thinkingserious

Sorry for the late response. I wasn't aware that I did not get notified for replies.
I think i've found the bug in my case. 

In the toWebFormat() function of the Email library, the following code is writen.

`if ($this->getAttachments()) {
            foreach ($this->getAttachments() as $f) {
                $file = $f['file'];
                $extension = null;
                if (array_key_exists('extension', $f)) {
                    $extension = $f['extension'];
                };
                $filename = $f['filename'];
                $full_filename = $filename;

                if (isset($extension)) {
                    $full_filename = $filename . '.' . $extension;
                }
                if (array_key_exists('custom_filename', $f)) {
                    $full_filename = $f['custom_filename'];
                }

                if (array_key_exists('cid', $f)) {
                    $web['content[' . $full_filename . ']'] = $f['cid'];
                }

                $contents = '@' . $file;

                // Guzzle handles this for us.
                // http://guzzle3.readthedocs.org/en/latest/http-client/request.html#post-requests
                // if (class_exists('CurlFile', false)) { // php >= 5.5
                // $contents = new \CurlFile($file, $extension, $filename);
                // }

                $web['files[' . $full_filename . ']'] = $contents;
            };
        }`

Our clients demand that the exact filename should be represented in the attachments. We use the custom_filename option for this matter, which would result that the key in $web will be overwritten.

**Comment by thinkingserious** [comment]
Thanks for following up @biggienor and to @joe-niland for lending a hand.

If you both of you would kindly fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLSelP4uF-wGJebxVYq1DYw5WzHomEUauab3YiqrshyCkRs0fqw/viewform#start=invite), I would love to send you some swag.

**Comment by joe-niland** [comment]
Thanks @thinkingserious - very kind!

**Comment by biggienor** [comment]
Thanks @thinkingserious 👍

**Comment by biggienor** [comment]
Hi @thinkingserious 
Is this bug already resolved in a version of sengrid-php? I would love to hear from you!

**Comment by thinkingserious** [comment]
Hello @biggienor,

I believe that we determined there was no bug. Are you still having issues?

**Comment by biggienor** [comment]
HI @thinkingserious,

The code I showed above is coming from your API. Can you help me by telling me if I have to update the API? Our current version is 4.0.4 and the code here is 5.1.2?

**Comment by thinkingserious** [comment]
Hi @biggienor,

If you want to use @joe-niland's [solution](https://github.com/sendgrid/sendgrid-php/issues/311#issuecomment-253383654), then yes, please update to the latest version of this library.
