### ISSUE TITLE
Show sendgrib email reply in my Webapps

### ISSUE THREAD

**Issue by mohiolmis** [sendgrid/sendgrid-php#312]
#### Issue Summary

I am developing an Apps with sendgrid. I can send email to my user and get there reply email in my inbox. Now I want to show the reply emails in my website. Have no idea how can I do that 

#### Technical details:

* sendgrid-php Version: master (latest commit: [commit number])
* PHP Version: 5.x

**Comment by thinkingserious** [comment]
Hello @mohiolmis,

Please reach out to our support team at https://support.sendgrid.com. We will do our best to help.

With Best Regards,

Elmer
