### ISSUE TITLE
PHP API - empty response body

### ISSUE THREAD

**Issue by michal84** [sendgrid/sendgrid-php#315]
Hello,

about 2-3 weeks ago I was implementing SendGrid php api to my client. Back then when I was using:

`$response = $client->client->contactdb()->recipients()->post([$request_body]);`

I've received:

`object(SendGrid\Response)[5]
  public '_status_code' => int 201
  public '_body' => string '{"error_count":0,"error_indices":[],"new_count":0,"persisted_recipients":["bS5waWV0cmFzekBuZXVyb3N5cy5wbA=="],"unmodified_indices":[0],"updated_count":0}' (length=153)
  public '_headers' => string 'HTTP/1.1 201 CREATED
Server: nginx
...
...
`
this was on version 5.0.9.

Right now in 5.1.1 I receive this:

`/home/michal/sendgrid/lib/SendGridHelper.php:76:
object(SendGrid\Response)[5]
  protected 'statusCode' => int 201
  protected 'body' => boolean false
  protected 'headers' => 
    array (size=1)
      0 => string '1' (length=1)`

as you can see the response body is empty. But weird is that I can catch proper body with this code:
`ob_start();
$response = $client->client->contactdb()->recipients()->post([$request_body]);
        $curl_response = ob_get_contents();`
so in my `$curl_response` variable I would have this:
`{"error_count":0,"error_indices":[],"new_count":0,"persisted_recipients":["bS5waWV0cmFzekBuZXVyb3N5cy5wbA=="],"unmodified_indices":[0],"updated_count":0}`

Please fix this bug because right now I need to use old version :)

**Comment by thinkingserious** [comment]
Hi @madara84,

Thanks for letting us know and for providing a detailed issue!

I've added this to our backlog for a fix.

**Comment by mpietraszneurosys** [comment]
could you give me an estimation time when it will be fixed on master branch ?

**Comment by thinkingserious** [comment]
Hi @mpietraszneurosys,

It does not look like this would get fixed this quarter unless we get more people voting on this issue or if someone submits a pull request.

**Comment by vsmori** [comment]
@mietraszneuo

Quick Fix: 

Edit sendgrid's Client.php and add the following lines :

        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($curl, CURLOPT_HEADER, true);
        curl_setopt($curl, CURLOPT_CUSTOMREQUEST, strtoupper($method));
        curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);

After the following line:

        curl_setopt($curl, CURLOPT_HTTPHEADER, $this->headers);

in makeRequest function.

**Comment by haibo3318** [comment]
I encountered the same problem.  @vsmori 's solution works.

**Comment by cballenar** [comment]
Same issue here, @vsmori 's solution worked as well. Please address.

**Comment by thinkingserious** [comment]
Thanks for sharing your solution @vsmori. Please fill out [this form](https://sendgrid.com/docs/User_Guide/email_activity.html) so we can send you some swag :)

@haibo3318, @cballenar,

Thanks for your votes, I've added them to our backlog.

**Comment by vsmori** [comment]
@thinkingserious , please send again the form.

**Comment by thinkingserious** [comment]
@vsmori, sorry about that, [here it is](https://docs.google.com/forms/d/e/1FAIpQLSelP4uF-wGJebxVYq1DYw5WzHomEUauab3YiqrshyCkRs0fqw/viewform#start=invite).

**Comment by birdy247** [comment]
I am also seeing this issue.  The above worked for me.

**Comment by ylupien** [comment]
**Stop turning off CURLOPT_SSL_VERIFYPEER and fix your PHP config**

Disabling verification of the certificate allows bad guys to man-in-the-middle the communication without you knowing it. Disabling verification makes the communication insecure. Just having encryption on a transfer is not enough as you cannot be sure that you are communicating with the correct end-point. 

References : 
https://snippets.webaware.com.au/howto/stop-turning-off-curlopt_ssl_verifypeer-and-fix-your-php-config/
https://curl.haxx.se/libcurl/c/CURLOPT_SSL_VERIFYPEER.html

Remove this setting by default and let unsecure users to turn it off with a configuration.
```PHP
if ($this->disableSSLVerifyPeer) {
  curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
}
```

**Comment by thinkingserious** [comment]
Thanks for the feedback @ylupien,

I have added your vote.

**Comment by birdy247** [comment]
For clarity, is this a new BUG introduced in 5.1.1 (I never had an issue prior to this)?

If @vsmori solution has a security flaw, what is the recommended approach, revert to a previous version?

Many thanks

**Comment by thinkingserious** [comment]
@birdy247,

I suggest you use the previous version until we have time to investigate deeper.

**Comment by Dreyer** [comment]
Isn't this all related to [#328](https://github.com/sendgrid/sendgrid-php/issues/328), #333 and the fact that the cURL PHP module missing CA certificates so by default it will reject all SSL certificates as unverifiable?

**Comment by birdy247** [comment]
Is there any update on this?

**Comment by thinkingserious** [comment]
Hi @birdy247,

It's still fairly low on our backlog. The only thing that would give this issue a significant bump in priority would be a PR.

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello Everyone,

Please follow progress at this thread: https://github.com/sendgrid/sendgrid-php/issues/321

**Comment by siwach22** [comment]
Hi ,

I'm geting this response on the clinet server when run the code. But on local its working fine and laos show log in activity on send grid. But when put code on client server and test it give this response and email goes. But not showing in activity log

Thanks To  All
SendGrid\Response Object
(
    [statusCode:protected] => 0
    [body:protected] => 
    [headers:protected] => Array
        (
            [0] => 
        )

)

**Comment by thinkingserious** [comment]
@siwach22,

Please review this this thread: https://github.com/sendgrid/sendgrid-php/issues/348

Thanks!

**Comment by shahrpt** [comment]
I was facing the same problem and spent a couple of figuring out and set the CURLOPT in Client.php of sendGrid API. 
_I have set CURLOPT_SSL_VERIFYPEER => to false instead of true_

![image](https://user-images.githubusercontent.com/2241234/52641442-a6674c00-2efa-11e9-8e7d-11eaba5f384a.png)

I hope this may help others to a void getting the 0 status code.
