### ISSUE TITLE
Upgrade the Coding Standards to PSR-2

### ISSUE THREAD

**Issue by okneloper** [sendgrid/sendgrid-php#317]
PEAR sounds like something obsolete and the coding standards are very outdated and some even don't make any sense, for instance things like ASCII,  ISO-8859-1, 'one line feed after the closing PHP tag' etc.. 

Since the code in the repo is not follwing PEAR standards very well anyway (I mean it either does or does not - nothing in between), I propose switching to a more modern, sensible and widely used PSR.

**Comment by thinkingserious** [comment]
Hello @okneloper,

We are happy to consider a change, do you have a suggestion? [PSR-2](http://www.php-fig.org/psr/psr-2/)?

**Comment by okneloper** [comment]
Yeah, what meant by PSR is PSR 2 which also includes PSR 1. I would expect more people to be happy to code to that standard than to PEAR.
