### ISSUE TITLE
Delete subaccounts returns 200

### ISSUE THREAD

**Issue by cdiacon** [sendgrid/sendgrid-php#320]
Hi

Looks that any api calls with ->delete() makes a get() request  and return a 200 Ok when needs to return 204 and delete the data. Here is for example for subusers request ; 

```
 ob_start();
        $response = $this->client->subusers()->_($username)->delete();

        $curl_response = ob_get_contents();

        dd($curl_response);

result 
"{"disabled":false,"email":"nkoepp@gmail.com","id":3877032,"username":"greenfelder.annamae"}"
```
#### Steps to Reproduce

Same for other resources 
$response = $this->client->api_keys()->_($api_key)->delete();
#### Technical details:
- sendgrid-php Version: master 5.1.1
- PHP Version: 5.6

**Comment by thinkingserious** [comment]
Hello @cdiacon,

Thanks for the heads up! I've added this to our backlog for a fix.

**Comment by adduc** [comment]
Pull Request [sendgrid/php-http-client#12](https://github.com/sendgrid/php-http-client/issues/12) should resolve this issue.
