### ISSUE TITLE
Call to a member function addSubstitution() on null from use cases example

### ISSUE THREAD

**Issue by tobsn** [sendgrid/sendgrid-php#335]
[https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md)

explains:
```
$mail = new SendGrid\Mail($from, $subject, $to, $content);
$mail->personalization[0]->addSubstitution("-name-", "Example User");
$mail->personalization[0]->addSubstitution("-city-", "Denver");
$mail->setTemplateId("13b8f94f-bcae-4ec6-b752-70d6cb59f932");
$sg = new \SendGrid('xxx');
$response = $sg->client->mail()->send()->post( $mail );
```

If I do the same I'm getting this:
`Call to a member function addSubstitution() on null `

Is there something missing?

Thank you!

**Edit:**
I changed it to a json request:

```
	$request_body = json_decode('{
		"personalizations": [
			{
				"to": [
					{"email": "myemail@email.com"}
				],
				"substitutions": {
					"-firstname-": "John"
				},
				"subject": "My Subject"
			}
		],
		"from": {"email": "sender@email.com"},
		"template_id": "13b8f94f-bcae-4ec6-b752-70d6cb59f932"
	}');
	$sg = new \SendGrid('xxx');
	$response = $sg->client->mail()->send()->post( $request_body );
```

Above throws the error:
`{"errors":[{"message":"Content-Type should be application/json.","field":null,"help":null}]}`

**Composer:**
`"sendgrid/sendgrid": "^5.1"`

**EDIT:**
I realized in my first example the $content is empty, once set correctly the on null error goes away but it now complains about this:
`"{"errors":[{"message":"The to array is required for all personalization objects, and must have at least one email object with a valid email address.","field":"personalizations.0.to","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.personalizations.to"}]}`

Which makes not much sense since addTo() is executed by the contractor of Mail {} which sets the personalization array as well.

**Comment by thinkingserious** [comment]
Hi @tobsn,

Can you please post the json request for the last call that is giving the error regarding the to array?

Thanks!

**Comment by tobsn** [comment]
Sorry, code doesn't exist anymore here only above.

The example code didn't work at all, there are tons of issues and straight up wrong code, and after a day of crawling around in the codebase, a week of waiting for a fix from Sendgrid via support, and when I was told I can fix the documentation myself on twitter (it's a paid service - go fix your documentation yourself - that was super odd) we decided it's better to move business to Mailchimp.

**Comment by thinkingserious** [comment]
@tobsn,

Thanks for the follow up. I'm sorry that you had such a poor experience with us. If you end up coming back, please feel free to reach out to me directly for assistance. To hopefully help others, here was the results of my own troubleshooting:

As it is now, I can not duplicate the error, using the example code referenced above.

Here is the specific result of my latest test without the helper and without using composer:

```bash
wget https://sendgrid-open-source.s3.amazonaws.com/sendgrid-php/sendgrid-php.zip
unzip sendgrid-php.zip
cd sendgrid-php
code test.php
```

```php
<?php

// If you are not using Composer (recommended)
require("./sendgrid-php.php");

$request_body = json_decode('{
  "personalizations": [
    {
      "to": [
        {
          "email": "dx@sendgrid.com"
        }
      ],
      "substitutions": {
        "-name-": "Example User",
        "-city-": "Denver"
      },
      "subject": "I\'m replacing the subject tag"
    }
  ],
  "from": {
    "email": "elmer@sendgrid.com"
  },
  "content": [
    {
      "type": "text/html",
      "value": "I\'m replacing the <strong>body tag</strong>"
    }
  ],
  "template_id": "13b8f94f-bcae-4ec6-b752-70d6cb59f932"
}');

$apiKey = getenv('SENDGRID_API_KEY');
$sg = new \SendGrid($apiKey);

try {
    $response = $sg->client->mail()->send()->post($request_body);
} catch (Exception $e) {
    echo 'Caught exception: ',  $e->getMessage(), "\n";
}

echo $response->statusCode();
```

```bash
php ./test.php
```

The result was a 202 response and the email was sent correctly.
