### ISSUE TITLE
Setup Environment variable on windows

### ISSUE THREAD

**Issue by omer-sds** [sendgrid/sendgrid-php#338]
can anyone explain how am i going to setup the environment variable on windows, i tried pasting the source in cmd as guided 

```
echo "export SENDGRID_API_KEY='YOUR_API_KEY'" > sendgrid.env
echo "sendgrid.env" >> .gitignore
source ./sendgrid.env
```

but it says 'source' is not recognized as an internal or external command , and it create a .gitignore file in `c:\users\myusername\.gitignore` which has `"sendgrid.env" ` witten inside. can someone guide what should i be doing

**Comment by thinkingserious** [comment]
Hello @omer-sds,

My apologies, those examples are for Unix based systems, for Windows, please see: https://github.com/sendgrid/sendgrid-csharp#setup-environment-variables

I will leave this issue open so we can update our documentation.

Thanks!

**Comment by smkazim** [comment]
Hello @thinkingserious 

please help in Update the development Environment with your SENDGRID_API_KEY.

**Comment by thinkingserious** [comment]
Hi @smkazim,

Please check this out: https://github.com/sendgrid/sendgrid-csharp#setup-environment-variables

Thanks!

**Comment by akoladesam** [comment]
Please can you explain how am i going to setup the environment variable for php.

What does this lines mean;

Update your development environment with your SENDGRID_API_KEY. Run the following in your shell:

echo "export SENDGRID_API_KEY='YOUR_API_KEY'" > sendgrid.env
echo "sendgrid.env" >> .gitignore
source ./sendgrid.env

**Comment by IshayMaya** [comment]
Hello , can you please provide a solution for node.js too ? the docs still refer only linux system

**Comment by CBL-deborah-morrison** [comment]
i was able to run these commands from a BASH Command Window run as Administrator -- bash includes does not have issue with source command

echo "export SENDGRID_API_KEY='YOUR_API_KEY'" > sendgrid.env
echo "sendgrid.env" >> .gitignore
source ./sendgrid.env
