### ISSUE TITLE
SendGrid PHP API not working

### ISSUE THREAD

**Issue by JeanCarlosRacoski** [sendgrid/sendgrid-php#340]
Hi there, I am a payed user and I am having trouble with the SendGrid PHP API.
I have downloaded from the official site ([Integration Page](https://github.com/sendgrid/sendgrid-php)) and it gives me this error:
**Fatal error: Class 'SendGrid\Email' not found in /home/ubuntu/workspace/forgot-pass.php on line 65 Call Stack: 0.0002 245096 1. {main}() /home/ubuntu/workspace/forgot-pass.php:0 0.0009 254952 2. sendMail() /home/ubuntu/workspace/forgot-pass.php:15**

I cannot install it using composer and I need to refer to the path.

Please tell me that there is another API folder/zip to download.

Thanks for the attention.

P.S.: I have tryied the support and they could not help me at all, they have sent me some example in which the lib folder is completely diferent from the downloadable and the PHP example is installed using composer (which, again, I cannot do).

**Comment by paoga87** [comment]
@JeanCarlosRacoski did you download the package here: https://sendgrid-open-source.s3.amazonaws.com/sendgrid-php/sendgrid-php.zip ?

There is an issue with this as well: [https://github.com/sendgrid/sendgrid-php/issues/341](url)

**Comment by JeanCarlosRacoski** [comment]
Yes that issue was posted by us as well.
I have downloaded the exact same files as you've posted just to be sure and the error remains:
Fatal error: Class 'SendGrid\Email' not found in /home/...

**Comment by mbernier** [comment]
Can you please check that your vendor/autoload.php file exists?

**Comment by mbernier** [comment]
If you are not using Composer, simply download and install the latest packaged release of the library as a zip.

Then require the library from package:

`require("path/to/sendgrid-php/sendgrid-php.php");`

**Comment by JeanCarlosRacoski** [comment]
Read the first post in the thread please.
- Composer is not being used;
- That ship has sailed a long time ago my friend, we have read the tutorial thanks, but we need a little more info from the experts

Either there is another lib to download besides the two found and reported here, which may content all the required files... or something is very wrong with that integration tutorial. That is my guess after all these days trying and even editing their files and folders.

**Comment by mbernier** [comment]
Duplicate issue - in order to have a single conversation I am going to redirect people here https://github.com/sendgrid/sendgrid-php/issues/341#issuecomment-270430098
