### ISSUE TITLE
Getting "Fatal error: Class 'SendGrid\Email' not found"

### ISSUE THREAD

**Issue by ramonbez** [sendgrid/sendgrid-php#341]
I've tried this fix below, but it didn't work: http://stackoverflow.com/questions/29000442/sendgrid-gives-fatal-error

**Comment by paoga87** [comment]
I have the same issue... and adding the `require 'lib/SendGrid/Email.php';` does not work and throws the error for re-declaring a class.

**Comment by JeanCarlosRacoski** [comment]
Yep, same thing here.

**Comment by mbernier** [comment]
Can you please check that your vendor/autoload.php file exists?

**Comment by mbernier** [comment]
If you are not using Composer, simply download and install the latest packaged release of the library as a zip.

Then require the library from package:

`require("path/to/sendgrid-php/sendgrid-php.php");`

**Comment by JeanCarlosRacoski** [comment]
Sorry Matt, no dice, as I told you in the other thread in which you've posted the very same thing... which is the tutorial basically.

**Comment by mbernier** [comment]
I have opened the zip file linked from the tutorial and the sendgrid-php.php is in fact there. Again, if you can check permissions on the files in the directory as that may be the issue, since the files (sendgrid-php.php and vendor/autoload.php) are both included in the downloadable zip directory.

**Comment by JeanCarlosRacoski** [comment]
I did changed the path, or else the error would be different, agreed? Cause I had this issue with the file not found and the error is not the same.

The class is missing, not the file.

**Comment by JeanCarlosRacoski** [comment]
these are the file permissions
-rw-rw-r--  1 ubuntu ubuntu     39 Nov 17 23:08 sendgrid-php.php

**Comment by mbernier** [comment]
I cannot speak to everyone's server settings, but I believe that you need executable permissions. This post on Stackoverflow is saying that depending on your settings you might be able to have 644, but I always ran 755 when I was building software. :) 

http://stackoverflow.com/a/2096288/1296778

**Comment by JeanCarlosRacoski** [comment]
ok, changed the permissions:
-rwxr-xr-x  1 ubuntu ubuntu     39 Nov 17 23:08 sendgrid-php.php

Sadly, still the same error.

**Comment by Laver2k** [comment]
Im also having this issue.

I included the library (and the path is definitely correct) but as soon as I create a 'new SendGrid\Email', I get the 'fatal error, class not found' message.

Im not using Composer and the require sendgrid-php.php suggestion doesnt help as this file doesnt exist in the current version of the library.

**Comment by paoga87** [comment]
@mbernier I changed permissions to 0755, just like @JeanCarlosRacoski did and I'm still getting the error as well. I'm not sure it has to do with permissions, since I am running SendGrind on v2 using the v2 library (without Composer) as well, and the file perm there is 0644.

**Comment by thinkingserious** [comment]
@paoga87,

What version of this library are you using?
How did you install it?
What version of PHP are you running on your server?
Could you provide the sample code that is not working?

Thanks!

**Comment by thinkingserious** [comment]
@Laver2k,

Have you tried downloading from here? https://github.com/sendgrid/sendgrid-php#alternative-install-package-from-zip

**Comment by thinkingserious** [comment]
@JeanCarlosRacoski,

What version of this library are you using?
How did you install it?
What version of PHP are you running on your server?
Could you provide the sample code that is not working?

Thanks!

**Comment by thinkingserious** [comment]
@ramonbez,

What version of this library are you using?
How did you install it?
What version of PHP are you running on your server?
Could you provide the sample code that is not working?

Thanks!

**Comment by JeanCarlosRacoski** [comment]
To be sure, I've downloaded the files again from the link you have suggested, but the error remains.
I have not installed it, I've created the key variable and required the files after uploading them (and yes the path is correct btw)

PHP Version 5.5.9-1ubuntu4.20

I am currently using the tutorial code, however I have changed the path to the lib (which again, is correct) and email addresses of course.

(https://app.sendgrid.com/guide/integrate/langs/php)

// If you are not using Composer
require("path/to/sendgrid-php/sendgrid-php.php");
$from = new SendGrid\Email("Example User", "test@example.com");
$subject = "Sending with SendGrid is Fun";
$to = new SendGrid\Email("Example User", "test@example.com");
$content = new SendGrid\Content("text/plain", "and easy to do anywhere, even with PHP");
$mail = new SendGrid\Mail($from, $subject, $to, $content);
$apiKey = getenv('SENDGRID_API_KEY');
$sg = new \SendGrid($apiKey);
$response = $sg->client->mail()->send()->post($mail);
echo $response->statusCode();
echo $response->headers();
echo $response->body();

**Comment by thinkingserious** [comment]
Hello @JeanCarlosRacoski,

Thanks for the additional details

I was not able to reproduce. Here is what I did:

```bash
wget https://sendgrid-open-source.s3.amazonaws.com/sendgrid-php/sendgrid-php.zip
unzip sendgrid-php.zip
cd sendgrid-php
code test.php
```

```php
<?php
require("./sendgrid-php.php");
$from = new SendGrid\Email("DX PHP Test", "dx@sendgrid.com");
$subject = "Sending with SendGrid is Fun";
$to = new SendGrid\Email("Elmer", "elmer+phptest@sendgrid.com");
$content = new SendGrid\Content("text/plain", "and easy to do anywhere, even with PHP");
$mail = new SendGrid\Mail($from, $subject, $to, $content);
$apiKey = getenv('SENDGRID_API_KEY');
$sg = new \SendGrid($apiKey);
$response = $sg->client->mail()->send()->post($mail);
echo $response->statusCode();
```

```bash
php ./test.php
```

The result was a sent email with a return code of 202

**Comment by paoga87** [comment]
@thinkingserious: 
What version of this library are you using?
**The latest version, found at the URL you provided (https://sendgrid-open-source.s3.amazonaws.com/sendgrid-php/sendgrid-php.zip)**
How did you install it?
**Unzipped folder, put the unzipped files within my code repo.**
What version of PHP are you running on your server?
**5.4.28**
Could you provide the sample code that is not working?

```
<?php
	require (".sendgrid-php.php");
	
	$from = new SendGrid\Email("DX PHP Test", "anything@sendgrid.com");
	$subject = "Sending with SendGrid is Fun";
	$to = new SendGrid\Email("Elmer", "pgarcia+phptest@email.com");
	$content = new SendGrid\Content("text/plain", "and easy to do anywhere, even with PHP");
	$mail = new SendGrid\Mail($from, $subject, $to, $content);
	$apiKey = getenv('SG.my_key_here');
	$sg = new \SendGrid($apiKey);
	$response = $sg->client->mail()->send()->post($mail);
	echo $response->statusCode();
?>
```
--Require path working correctly. 

Note: I am now getting a 401 response code. I have tested my API key via cURL  (JSON) and I am able get emails; but this code keeps returning 401 status code.

**Comment by thinkingserious** [comment]
Hello @paoga87,

That error is related to your API key.

Note that `$apiKey = getenv('SG.my_key_here');` will not work. 

Instead, try `$apiKey = 'SG.my_key_here';`

For details: 
https://github.com/sendgrid/sendgrid-php/blob/master/TROUBLESHOOTING.md#environment-variables-and-your-sendgrid-api-key

**Comment by paoga87** [comment]
@thinkingserious awesome! Got it working now; 202 response and did receive the email.
Thanks a lot for your help!

**Comment by paoga87** [comment]
@thinkingserious 
Quick question: Using the Mail Helper Library, how can we add custom arguments and/or attachments? I tried following the example here (https://github.com/sendgrid/sendgrid-php/blob/master/examples/helpers/mail/example.php#L31) but it's not working.

Here's a snapshot of what I have:
```php
<?php
	require ("./sendgrid-php.php");
	
	$from = new SendGrid\Email("DX PHP Test", "anything@sendgrid.com");
	$subject = "Sending with SendGrid is Fun";
	$to = new SendGrid\Email("Paola", "pgarcia+phptest@email.com");
	$content = new SendGrid\Content("text/plain", "and easy to do anywhere, even with PHP");
      
        $personalization = new Sendgrid\Personalization();
        $personalization->addCustomArg("meeting_name","myMeetingNameHere");
        $attachment = new SendGrid\Attachment();
	$attachment->setType("application/pdf");
	$attachment->setFilename("myFile.pdf");
     
	$mail = new SendGrid\Mail($from, $subject, $to, $content);
        $mail->addPersonalization($personalization);
        $mail->addAttachment($attachment);

	$apiKey = 'SG.my_key_here';
	$sg = new \SendGrid($apiKey);
	$response = $sg->client->mail()->send()->post($mail);
	echo $response->statusCode();
?>
```

**Comment by thinkingserious** [comment]
Hello @paoga87,

It looks like you are missing the [base64 encoded content](https://github.com/sendgrid/sendgrid-php/blob/master/examples/helpers/mail/example.php#L91).

Please take a look at the link above.

Thanks!

**Comment by paoga87** [comment]
@thinkingserious 
I added the following:
```php

    $myPDF = 'path/to/myFile.pdf';
    $myPDF_encoded = chunk_split(base64_encode(file_get_contents($myPDF)));
					
     $attachment = new SendGrid\Attachment();
     $attachment->setContent($myPDF_encoded);
```
Still returning response 400.

**Comment by thinkingserious** [comment]
Hi @paoga87,

I think you need to remove the `chunk_split`. Please see: https://github.com/sendgrid/sendgrid-php/issues/272

**Comment by paoga87** [comment]
@thinkingserious yes, that did it.
Thank you for your help!

**Comment by hectorsabina** [comment]
I might be a bit late to the party, but for those still having issues using this lib without composer, try naming classes this way:

`$from = new \SendGrid\Email("Example User", "test@example.com");``

Notice the extra `\` at the beginning. This is to import this class from the global namespace, instead from the one you've defined already for the class you're using this library from (check [php namespaces](http://php.net/manual/en/language.namespaces.global.php) for more info).

**Comment by thinkingserious** [comment]
Thanks for the feedback @hectorsabina! 

I think your example would be great to put [here](https://github.com/sendgrid/sendgrid-php/blob/master/TROUBLESHOOTING.md). Would you mind submitting a PR?

Thanks again!

With Best Regards,

Elmer

**Comment by alyak46141414** [comment]
I found that this happen because sendgrid use extra library that loaded by composer 

vendor\sendgrid\php-http-client\

and of course you cannot get these without composer . 

basically need two files from it 

Client.php
Response.php

**Comment by thinkingserious** [comment]
@alyak46141414,

If you are not using Composer, you can download the relevant files [here](https://github.com/sendgrid/sendgrid-php#alternative-install-package-from-zip).

Thanks!

**Comment by loretoparisi** [comment]
@thinkingserious @hectorsabina I can confirm that even within WordPress 4.5.x this issue could happen due to a missing `\` at beginning, cause the runtime thinks that the namespace is the current one (your plugin's namespace) hence the following code will work if 

1) You put in the root folder of your WP plugin the provided `sendgrid-php` unzipped contents within a `sendgrid-php` folder;
2) Add a `require_once dirname(__FILE__) . "/sendgrid-php/sendgrid-php.php";`

```php
private function sendEmail() {

		$from = new \SendGrid\Email(null, "info@mydomain.com");
		$subject = "Weekly Customers Update";
		$to = new \SendGrid\Email(null "recipient1@somedomain.com");
		
		$content = new \SendGrid\Content("text/plain", "Report attached.");
		// $content = new \SendGrid\Content("text/html", "<h1>Sending with SendGrid is Fun and easy to do anywhere, even with PHP</h1>");

		$mail = new \SendGrid\Mail($from, $subject, $to, $content);
		$to = new  \SendGrid\Email(null, "recipient2@somedomain.com");
		$mail->personalization[0]->addTo($to);

		$apiKey = 'xxxxx';
		$sg = new \SendGrid($apiKey);
		$response = $sg->client->mail()->send()->post($mail);
		//echo $response->statusCode();
		//echo $response->body();
		//print_r($response->headers());
	}
```

Hope this helps, saved my time!!!

**Comment by preshboy** [comment]
I am testing my locally. Is that the problem that I have? Do I need to take it to a live server?

**Comment by thinkingserious** [comment]
Hello @preshboy,

What error are you seeing?

With Best Regards,

Elmer

**Comment by nccharles** [comment]
I am getting this error, is there anyone can help me?
`401 Array ( [0] => HTTP/1.1 401 Unauthorized [1] => Server: nginx [2] => Date: Tue, 19 Feb 2019 12:34:25 GMT [3] => Content-Type: application/json [4] => Content-Length: 88 [5] => Connection: keep-alive [6] => Access-Control-Allow-Origin: https://sendgrid.api-docs.io [7] => Access-Control-Allow-Methods: POST [8] => Access-Control-Allow-Headers: Authorization, Content-Type, On-behalf-of, x-sg-elas-acl [9] => Access-Control-Max-Age: 600 [10] => X-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html [11] => [12] => ) {"errors":[{"message":"Permission denied, wrong credentials","field":null,"help":null}]}`

**Comment by Coners** [comment]
just so you know .. everyone here is wrong .... "**they**" (SendGrid) simply took out **\SendGridEmail()** and replaced it with **\SendGrid\Mail\Mail()** and so the callers are slightly different .. i.e.

            $sendgrid = new SendGrid("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
		$email = new \SendGrid\Mail\Mail();
		$email->setFrom("test@example.com", "Example User");
		$email->setSubject("Sending with SendGrid is Fun");
		$email->addTo("bigman@getme.com", "Example User");
		$email->addContent(
			"text/plain", "and easy to do anywhere, even with PHP"
		);
		$email->addContent(
			"text/html", "<strong>and easy to do anywhere, even with PHP</strong>"
		);
		try {
			$response = $sendgrid->send($email);
			print $response->statusCode() . "\n";
			print_r($response->headers());
			print $response->body() . "\n";
		} 
		catch (Exception $e) {
			echo 'Caught exception: ',  $e->getMessage(), "\n";
		}`

**Comment by thinkingserious** [comment]
Hello @lucacrippa88,

Please see my response on the other thread. Thanks!

**Comment by IndigoSnake** [comment]
Hi @thinkingserious
I have a 400 error.
please help me.

	$personalization = new SendGrid\Personalization();
	$personalization->addCustomArg("meeting_name","myMeetingNameHere");

	$myPDF = './myfile.pdf';
        $myPDF_encoded = base64_encode(file_get_contents($myPDF));
					
        $attachment = new SendGrid\Attachment();
	$attachment->setType("application/pdf");
        $attachment->setContent($myPDF_encoded);
	 
	$mail = new SendGrid\Mail($from, $subject, $to, $content);
	$mail->addPersonalization($personalization);
	$mail->addAttachment($attachment);

Thanks.
