### ISSUE TITLE
removereceived

### ISSUE THREAD

**Issue by mlhkr** [sendgrid/sendgrid-php#342]
We can remove the received ip address with this code (X-SMTPAPI header)

`$filters = [
 'removereceived' => [
 'settings' => [
 'enable' => 1
 ],
 ],
 ];
 $mailData->setFilters($filters);
 $mail_json = $mailData->jsonString();
 $message_headers = $message->getHeaders();
 $message_headers->addTextHeader($header, $mail_json);
`

any way to achieve it with helper classes?

**Comment by mlhkr** [comment]
OK I found a topic about it but still can't add header with using helper classes:
https://community.sendgrid.com/sendgrid/topics/strip-originating-ip-in-smtp-header

Example code:
`$mail = new SendGrid\Mail($from, $subject, $to, $content);
$mail->personalization[0]->addHeader('X-SMTPAPI','{"filters":{"removereceived":{"settings":{"enable":1}}}}');`

Getting:
`{"errors":[{"field":null,"message":"resource not found"}`

**Comment by thinkingserious** [comment]
Hi @mlhkr,

Could you provide the rest of the code so that I can try to reproduce.

Also, this example might be helpful: https://github.com/sendgrid/sendgrid-php/blob/master/examples/helpers/mail/example.php#L22

Thanks!
