### ISSUE TITLE
Any plan to support proxies as in ^4.0 ?

### ISSUE THREAD

**Issue by Taluu** [sendgrid/sendgrid-php#345]
We are currently stuck at using sendgrid php on `^4.0`, because it seems that `^5.0` does not support the option `proxy`, unless we read that wrong.

Any idea on how to upgrade, if it is possible ? Or should we stay on `^4.0` ?

Note ; I didn't follow the template, as it is not a "bug" per se, but a "feature request".

Thanks !

**Comment by thinkingserious** [comment]
Hi @Taluu,

Thanks for the pull request! We have it on our backlog for review and merge.
