### ISSUE TITLE
setContent only accepts base64 encoded strings

### ISSUE THREAD

**Issue by sebmih** [sendgrid/sendgrid-php#347]
#### Issue Summary

There is nowhere in the entire library where it is mentioned that the setContent function from the Attachment class only accepts a base64 encoded string. Not giving a correct parameter to the function will result in a {"errors":[{"message":"Bad Request","field":null,"help":null}]}, status 400. 

#### Steps to Reproduce

1. install and use the SG library
2. give a non base64 encoded string to the setContent function from the Attachment class
3. log response status and body

It's a documentation bug. We shouldn't have to guess the proper encoding for a string parameter - it should be clearly specified either in the function definition or in the examples.

#### Technical details:

* sendgrid-php Version: master (latest commit: [commit number])
* PHP Version: 5.x

**Comment by thinkingserious** [comment]
Hello @sebmih,

You are correct, we will get this fixed. Thanks for the heads up!

With Best Regards,

Elmer

**Comment by paoga87** [comment]
@thinkingserious 
I can help updating the docs on this, if you need to. Let me know how to proceed.
Thank you!

**Comment by thinkingserious** [comment]
@paoga87,

Awesome! Just go ahead and make a pull request :)

Thanks!

**Comment by paoga87** [comment]
Hello @sebmih @thinkingserious,

Documentation on BASE64 encoded content exists here: https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/how_to_migrate_from_v2_to_v3_mail_send.html#-Attachments

@sebmih is that what you were looking for?

**Comment by sebmih** [comment]
@paoga87 Yes, but that's not the point. I shouldn't have to go a different website, in a different docs to find what I need.

**Comment by paoga87** [comment]
@thinkingserious do you have any idea of exactly where I can add the attachment note on the documentation?

**Comment by thinkingserious** [comment]
How about here: https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md

Like we have here: https://github.com/sendgrid/sendgrid-nodejs/blob/master/USE_CASES.md

**Comment by thinkingserious** [comment]
This documentation is completed here: https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#attachments
