### ISSUE TITLE
sendgrid-php.php removed from latest release?

### ISSUE THREAD

**Issue by travstoll** [sendgrid/sendgrid-php#349]
sendgrid-php/sendgrid-php.php as noted in docs when not using composer isn't in the latest release.  Am I missing something?

**Comment by thinkingserious** [comment]
Hi @travstoll,

Did you download from here? https://github.com/sendgrid/sendgrid-php#alternative-install-package-from-zip

I just checked and the file was there.

I hope that helps.

With Best Regards,

Elmer

**Comment by travstoll** [comment]
@thinkingserious I did download from there eventually and agree its there when using the link there (https://sendgrid-open-source.s3.amazonaws.com/sendgrid-php/sendgrid-php.zip)

However, in the latest release directory, for v5.1.2, where I typically download releases from, it is not: https://github.com/sendgrid/sendgrid-php/archive/v5.1.2.zip

**Comment by travstoll** [comment]
I believe these should be the same version, but am not sure.  Line 19 on both for lib/SendGrid.php both indicate const VERSION = '5.1.2';

**Comment by thinkingserious** [comment]
Hello @travstoll,

Thanks for the clarification! I'm not sure why the file is not in that zip, looking at the [upload script](https://github.com/sendgrid/sendgrid-php/blob/master/scripts/s3upload.sh), I'm not sure why it's not getting included. I'll add this to our backlog for investigation.

With Best Regards,

Elmer

**Comment by damonpace** [comment]
This is a big issue for noobs like me. I don't use composer. You're referencing the files in your docs, but it's nowhere to be found in the 'sendgrid-php-master.zip' from github. It is however in the 'sendgrid-php.zip' on AWS. It would be helpful if you said something about downloading it from AWS else if you don't see it in the Zip files. I thought I was going crazy.

**Comment by thinkingserious** [comment]
Hello @damonpace,

Thanks for the feedback! I'm definitely interested in how to make the install process as smooth as possible, so thank you for your help in that regard.

I'm assuming that first time users will head here first: https://github.com/sendgrid/sendgrid-php#installation. In that case, the download links are provided to those who don't use composer. 

I'm unsure of how you arrived at downloading directly from GitHub. What could we have done to avoid that situation? 

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Please follow progress on making this process smoother here: https://github.com/sendgrid/sendgrid-php/issues/388
