### ISSUE TITLE
Comma not allowed in for recipient names?

### ISSUE THREAD

**Issue by biggienor** [sendgrid/sendgrid-php#351]
#### Issue Summary
Hi,

Recently I noticed something strange with delivering emails to clients.
As we wan't to deliver an email like below, the message will get dropped. The cause is that somehow the email address changed to "firstname".

name => "Firstname Lastname, Company"
email => "emailaddress@domain.ext"

After some research, I found out that the issue lies with the comma in the name field. Does this mean that the comma isn't allowed in the name field?

Kind regards,
Norman

#### Technical details:

* sendgrid-php Version: 5.1.2
* PHP Version: 5.6

**Comment by thinkingserious** [comment]
@biggienor,

Correct, ,'s and ;'s are not allowed: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html#-Limitations

With Best Regards,

Elmer
