### ISSUE TITLE
Problems with relative path

### ISSUE THREAD

**Issue by tarcisiozf** [sendgrid/sendgrid-php#352]
#### Issue Summary

if you require the sendgrid-php.php (Non-composer version) in a background process you may have relative path problems. Can be simply solved by replacing with:

```
<?php
	require __DIR__ . '/vendor/autoload.php';
?>
```

**Comment by tarcisiozf** [comment]
This file is in the .gitignore file, so I had to open an issue instead of a pull request

**Comment by thinkingserious** [comment]
Hello @tarcisiozf,

If you still would like to make the pull request, here is where we generate that file upon upload to s3: https://github.com/sendgrid/sendgrid-php/blob/master/scripts/s3upload.sh#L10

In any case, please fill out this [form](https://docs.google.com/forms/d/e/1FAIpQLSelP4uF-wGJebxVYq1DYw5WzHomEUauab3YiqrshyCkRs0fqw/viewform#start=invite) so we can send you some swag for being awesome :)

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Closing this one, since you already created the pull request here: https://github.com/sendgrid/sendgrid-php/pull/353

We just need your signed CLA to continue. Thanks!
