### ISSUE TITLE
GET /suppression/spam_report/{email} call not working / returning 404

### ISSUE THREAD

**Issue by jim-at-miramontes** [sendgrid/sendgrid-php#354]
This endpoint doesn't seem to be working: After making a SendGrid object with my api key (which is working fine), I'm calling it from PHP as:

$email = "some_address@some_domain.com"; 
$response = $sg->client->suppression()->spam_report()->_($email)->get();

just as the documentation (https://github.com/sendgrid/sendgrid-php/blob/master/USAGE.md) shows. I get, on return:

SendGrid\Response::__set_state(array( 
'statusCode' => 404, 
'body' => '{"errors":[{"field":null,"message":"resource not found"}]}', 
'headers' => 
array ( 
', 0 => 'HTTP/1.1 404 NOT FOUND 
', 1 => 'Server: nginx 
', 2 => 'Date: Wed, 01 Feb 2017 17:10:55 GMT 
', 3 => 'Content-Type: application/json 
', 4 => 'Content-Length: 58 
', 5 => 'Connection: keep-alive 
', 6 => ' 
7 => '', 
), 
))

I would think that the spam_report call would work in the same way as the bounce list or invalid_emails calls -- if there's nothing there, the API call succeeds with a status code of 200, but returns a body of [] (empty array). 404, to me, would suggest that the endpoint just doesn't exist. For instance, if I make an intentionally flawed api call like:

$response = $sg->client->suppressionsdfgjkfdslgj()->blocks()->_($email)->get()

I get the same kind of 404 result as I'm currently getting from the spam report call.

#### Technical details:

* sendgrid-php Version: master; public release version
* PHP Version: 5.6.27

**Comment by thinkingserious** [comment]
Hi @jim-at-miramontes,

`spam_report` should be `spam_reports`

I hope that helps!

Thanks!

**Comment by jim-at-miramontes** [comment]
Indeed!  Works fine; it just needs a doc update, I guess.  Thanks!
