### ISSUE TITLE
Allow setting curlOptions

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-php#356]
Update the [client instantiation](https://github.com/sendgrid/sendgrid-php/blob/master/lib/SendGrid.php#L51) based on [this client dependency ](https://github.com/sendgrid/php-http-client/pull/13)update.

**Comment by ajbonner** [comment]
Timely, needed some mechanism for passing timeouts to the underlying curl library.

**Comment by thinkingserious** [comment]
@ajbonner,

Thanks for the vote, it has been added to our backlog.

Currently, this item is fairly low on our backlog. For it to gain priority, we need either more votes or a PR.

Thanks for your support!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
This was fixed with https://github.com/sendgrid/sendgrid-php/releases/tag/v5.2.0

Thanks!
