### ISSUE TITLE
PHP 7 Compatibility

### ISSUE THREAD

**Issue by Nosferius** [sendgrid/sendgrid-php#357]
WP version: 4.7.2
PHP Version: 5.5.9-1ubuntu4.20
Sendgrid version: 1.10.7

 Today I was checking our websites that run your plugin for PHP 7 compatibility and found that I got a few errors/warnings. I am sending you these findings in hopes you can solve these issues as we would like to upgrade our websites to PHP 7.
I hope by sending you this e-mail that we can help each other.
FILE: /nas/content/live/ehbs/wp-content/plugins/sendgrid-email-delivery-simplified/lib/class-sendgrid-tools.php
----------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 6 WARNINGS AFFECTING 3 LINES
----------------------------------------------------------------------------------------------------------------------------------
1279 | WARNING | Function mcrypt_get_iv_size() is deprecated since PHP 7.1; use OpenSSL instead
1279 | WARNING | Extension 'mcrypt' is deprecated since PHP 7.1 - use openssl (preferred) or pecl/mcrypt once available instead.
1284 | WARNING | Function mcrypt_create_iv() is deprecated since PHP 7.1; use OpenSSL instead
1284 | WARNING | Extension 'mcrypt' is deprecated since PHP 7.1 - use openssl (preferred) or pecl/mcrypt once available instead.
1295 | WARNING | Function mcrypt_decrypt() is deprecated since PHP 7.1; use OpenSSL instead
1295 | WARNING | Extension 'mcrypt' is deprecated since PHP 7.1 - use openssl (preferred) or pecl/mcrypt once available instead.
----------------------------------------------------------------------------------------------------------------------------------

**Comment by thinkingserious** [comment]
Hello @Nosferius,

It looks like you are no using the most recent SendGrid SDK version, which is currently v5.1.2.

Also, those errors don't appear to be related to our library, it looks like your PHP extensions need updating.

I hope that helps!

With Best Regards,

Elmer

**Comment by benklocek** [comment]
@thinkingserious I also am looking to upgrade to php7, and those warnings are coming from /wp-content/plugins/sendgrid-email-delivery-simplified/lib/class-sendgrid-tools.php, not an external library. PHP 7 has deprecated the mcrypt default extension, so the plugin will need to be updated to use the appropriate functions (see http://php.net/manual/en/function.mcrypt-decrypt.php).

**Comment by thinkingserious** [comment]
@benklocek,

Ah, I see, you are referring to the Word Press plugin. I will alert the team that manages that. Thanks!

**Comment by thinkingserious** [comment]
@Nosferius @benklocek,

Please follow this issue here: https://github.com/sendgrid/wordpress/issues/44

Thanks!
