### ISSUE TITLE
Getting a 301 Moved Permanently from Web API

### ISSUE THREAD

**Issue by edu2004eu** [sendgrid/sendgrid-php#359]
#### Issue Summary

I'm using a really old version of this library (unfortunately I can't find any version info; but I assume it's [v1.1.5](https://github.com/sendgrid/sendgrid-php/tree/v1.1.5)). For some time now, emails are not being sent. I've debugged the issue, and I'm getting a `301 Moved Permanently` from the Web API.

From what I can see, the `$domain` property in `SendGrid/Web.php` is `http://sendgrid.com/`, while I'm getting a redirect to the same endpoint, but HTTPS: https://sendgrid.com/[...]

Did the API change recently? Do we need to update the URL to point to https? I've temporarily changed it to https://sendgrid.com/ and it started working. I'm just looking for a confirmation that this is the right change.

I know it's a really old version, but you know... old project. Updating would mean breakage in 100 places :)

#### Steps to Reproduce

This is my code:

        $sendgrid = new SendGrid("username", "password");
        $mail = new SendGrid\Mail();
        
        $mail->setSubject($subject);
        $mail->setHtml($htmlContent);
        $mail->setFrom($from);
        if ($to) {
            $mail->addTo($to);
        }
        if($addCC){
            $mail->addCc($addCC);
        }
        if ($data['tos']) {
            $mail->setTos($data['tos']);
        }
        if($data['addCategory']) {
            $mail->addCategory($data['addCategory']);
        }

        return $sendgrid->web->send($mail);

#### Technical details:

* sendgrid-php Version: not sure, no versioning info found; copyright says 2011; might be 1.1.5
* PHP Version: 5.6

**Comment by thinkingserious** [comment]
Hello @edu2004eu,

Yes, we have updated the API to require https.

Also, I highly recommend you update to the latest version of the library, if for no other reason than to use API keys instead of your SendGrid username and password.

Please let me know if have any additional questions or concerns.

Thanks!

With Best Regards,

Elmer
