### ISSUE TITLE
Return headers() as associative array

### ISSUE THREAD

**Issue by danielsippel** [sendgrid/sendgrid-php#361]
I followed your steps here:
https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md

`var_dump($response->headers());`

```
array:15 [
  0 => "HTTP/1.1 202 Accepted\r"
  1 => "Server: nginx\r"
  2 => "Date: Wed, 22 Feb 2017 14:14:30 GMT\r"
  3 => "Content-Type: text/plain; charset=utf-8\r"
  4 => "Content-Length: 0\r"
  5 => "Connection: keep-alive\r"
  6 => "X-Message-Id: rL5XOoCUSkm-0sH4CLipBx\r"
  7 => "X-Frame-Options: DENY\r"
  8 => "Access-Control-Allow-Origin: https://sendgrid.api-docs.io\r"
  9 => "Access-Control-Allow-Methods: POST\r"
  10 => "Access-Control-Allow-Headers: Authorization, Content-Type, On-behalf-of, x-sg-elas-acl\r"
  11 => "Access-Control-Max-Age: 600\r"
  12 => "X-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html\r"
  13 => "\r"
  14 => ""
]
```

I think it could happen, that the needed "X-Message-Id" will not always be in [6], so please provide headers in a nicer way, e.g. associative array - carriage return character removed. Thanks!

"X-Message-Id" is the Sendgrid Message Id which I need for further processing of Webhooks.

**Comment by danielsippel** [comment]
e.g.

```
private function getHeadersNice($headers) {
        $return = [];
        foreach ($headers as $key => $header) {
            if ($key == 0) {
                $return['Status'] = $header;

            } else {
                $exploded = explode(":",$header);

                if (isset($exploded[1])) {
                    $return[trim($exploded[0])] = trim($exploded[1]);
                }
            }
        }

        return $return;
    }
```

or use composer and set guzzle as requirement and use this instead of curl ;-)

**Comment by thinkingserious** [comment]
Hello @danielsippel,

I think this is a great idea and I've added it to our backlog for implementation.

With regards to Guzzle, we removed that dependency because we were getting too many compatibility issues reported from our customers.

With Best Regards,

Elmer

**Comment by WadeShuler** [comment]
👍 I agree, headers should be an associative array.

**Comment by thinkingserious** [comment]
Thanks @WadeShuler, I've added your vote to this issue in our backlog.

**Comment by thinkingserious** [comment]
Solved by https://github.com/sendgrid/php-http-client/pull/19
