### ISSUE TITLE
BCC - working but not replacing placeholders/substitutions

### ISSUE THREAD

**Issue by danielsippel** [sendgrid/sendgrid-php#366]
Example code:

```
[...]
$mail = new SendGrid\Mail($from, $subject, $to, $content);
$mail->personalization[0]->addSubstitution("{{customerName}}", "customer name here");

$bcc = new SendGrid\BccSettings();
$bcc->setEnable(true);
$bcc->setEmail('bccEmailAddress@domain.com');
$mailSettings = new SendGrid\MailSettings();
$mailSettings->setBccSettings($bcc);

$mail->setMailSettings($mailSettings);
[...]
```

In the original email, {{customerName}} is replaced with "customer name here" <- Ok, as expected.
In the BCCed email, this placeholder is replaced with empty value "" <- Bug.

**Comment by thinkingserious** [comment]
Hello @danielsippel,

I believe substitutions should work for bccs if you add the bcc as follows: https://github.com/sendgrid/sendgrid-php/blob/master/examples/helpers/mail/example.php#L40

Except you would use `personalization[0]` if you are using the `SendGrid\Mail` constructor.

With Best Regards,

Elmer

**Comment by danielsippel** [comment]
Thanks, implemented it that way, working.
Much nicer code now as well :-)
