### ISSUE TITLE
I have use the inline CSS, but V3 still destory the CSS style, WHY?

### ISSUE THREAD

**Issue by DavidFnck** [sendgrid/sendgrid-php#369]
#### Issue Summary

when I send the HTML content by the V3, the CSS style was destroied totally, How to solve the problem?

when I use the swfit-mailer, everything is OK. but why I change to V3, it's the second question, 

when I run it on the VPS, swift-mailer occured the warning below: PHP Fatal error: Uncaught Swift_TransportException: Expected response code 250 but got code "500", with message "500 Command not implemented

#### Technical details:

* sendgrid-php Version: master (latest commit: [commit number])
* PHP Version: 7.x

**Comment by cbschuld** [comment]
@DavidFnck - do you have an example of what gets squashed?  I have found a few different issues with the v3 endpoint and I'd love to see if your issue is impacting our usage too

**Comment by thinkingserious** [comment]
Hello @DavidFnck,

Could you please provide some example code so we can further assist, including the desired output vs the bad output?

Thanks!

With Best Regards,

Elmer
