### ISSUE TITLE
Attachment getting corrupted

### ISSUE THREAD

**Issue by goyal2989** [sendgrid/sendgrid-php#372]
When we send a mail to our users having attachment, the file is getting corrupted.

Below is the code and version of lib

require SNEDGIRD_LIB_PATH . 'vendor/autoload.php';
$sendgrid = new SendGrid(SENDGRID_USERNAME, SENDGRID_PASSWORD);
$mail = new SendGrid\Email();

$mail->setFromName($mailArr['sender'])->
                    setFrom("no-reply@test.com")->
                    addTo($to)->
                    setSubject($mailArr['subject'])->
                    setHtml($html)->
                    setAttachments($files);

            $response = $sendgrid->send($mail);

Php version : 5.6
Sendgrid version: 2.0.3

**Comment by SendGridDX** [comment]
Hello @goyal2989,

That version of our SDK is no longer supported. Are you able to upgrade to the latest version?

With Best Regards,

Elmer
