### ISSUE TITLE
computer is window,   it is  is not work!  

### ISSUE THREAD

**Issue by qwe356558603** [sendgrid/sendgrid-php#379]
![image](https://cloud.githubusercontent.com/assets/18321666/25061979/36d7c43c-21f5-11e7-9ffd-f74633e4450a.png)

**Comment by qwe356558603** [comment]
![image](https://cloud.githubusercontent.com/assets/18321666/25062128/8cbbb112-21f8-11e7-9fc7-3b4e151bd1c2.png)

**Comment by thinkingserious** [comment]
Hello @qwe356558603,

[Here is an explanation](http://www.dowdandassociates.com/blog/content/howto-set-an-environment-variable-in-windows-command-line-and-registry/) of how to set it via the command line.

Please let me know if you continue to have any issues.

Thanks!

Elmer
