### ISSUE TITLE
Fatal Error : Namespace declaration statement

### ISSUE THREAD

**Issue by readyglam** [sendgrid/sendgrid-php#380]
#### Issue Summary
i took the example php code and ran it as a seperate page to send emails, it worked fine. when intergated the code with my main page. it throws namaspace error
````
<?php
namespace SendGrid;
// If you are not using Composer
require ("sendgrid-php/sendgrid-php.php");
function helloEmail()
{
    $from = new Email(null, "pugaz.s@gmail.com");
    $subject = "Hello World from the SendGrid PHP Library";
    $to = new Email(null, "readyglam4u@gmail.com");
    
    $content = new Content("text/plain", "some text here");
    $mail = new Mail($from, $subject, $to, $content);
    $to = new Email(null, "pugaz_s@yahoo.com");
    $mail->personalization[0]->addTo($to);
    echo json_encode($mail, JSON_PRETTY_PRINT), "\n";
    return $mail;
}

function sendHelloEmail()
{
    $apiKey = 'xx';
    $sg = new \SendGrid($apiKey);
    $request_body = helloEmail();
    $response = $sg->client->mail()->send()->post($request_body);
    echo "<br> Status Code". $response->statusCode();
    echo $response->body();
    //echo $response->headers();
}

sendHelloEmail();  // this will actually send an email
//sendKitchenSink(); // this will only send an email if you set SandBox Mode to false
?>
```
`

#### Technical details:

* sendgrid-php Version: master (latest commit: [commit number])
* PHP Version: 5.6.25

**Comment by thinkingserious** [comment]
Hello @readyglam,

1. How did you install the library both for the separate page example and for the integrated version?
2. Could you please provide the error message?

With Best Regards,

Elmer

**Comment by readyglam** [comment]
Error :
Fatal error: Namespace declaration statement has to be the very first statement in the script in C:\wamp64\www\test\confirmation.php on line 1

i did not install the library. i have them copied in the resp folders. and used the below lines as reference.
```
namespace SendGrid;
// If you are not using Composer
require ("sendgrid-php/sendgrid-php.php");
```

the above code in the summary is my sample page code. and it has namespace as the 2nd line below the php tag, but when i do the same in my main page, it says the namespace should be as line 1. 

how do i place it in line 1 when there is not more lines above it.

**Comment by thinkingserious** [comment]
Where did you download the code from?

**Comment by readyglam** [comment]
https://github.com/sendgrid/sendgrid-php/blob/master/examples/helpers/mail/example.php

the link above is the example i used to write my mail code

**Comment by thinkingserious** [comment]
It looks like you might have a space after `<?php`

**Comment by readyglam** [comment]
<?phpnamespace SendGrid; 

am i suppose to write it like this ?? if i just press  and enter key after my php tag the namespace goes to the second line.

**Comment by readyglam** [comment]
`<?phpnamespace SendGrid;`

if i remove that space after my php tag, the line becomes like above mentioned. if i just press and enter key after php tag , the namespace goes to the second line leaving a space again.. 

how do i fix this.

**Comment by thinkingserious** [comment]
Hi @readyglam,

Where did you download the source code from? Was it here: https://github.com/sendgrid/sendgrid-php#alternative-install-package-from-zip

**Comment by readyglam** [comment]
yes , that is the GIT page from where i saved the library.  below link is the one which lead me to git page.
https://sendgrid.com/docs/Integrate/libraries.html

**Comment by thinkingserious** [comment]
Hello @readyglam,

Here are the steps I took (I did not get any error):

```bash
mkdir sendgrid-php-test
cd sendgrid-php-test
wget https://sendgrid-open-source.s3.amazonaws.com/sendgrid-php/sendgrid-php.zip
unzip sendgrid-php.zip
vi temp.php
```

```php
<?php
namespace SendGrid;
require("./sendgrid-php/sendgrid-php.php");

$from = new Email("SendGrid DX Team", "dx@sendgrid.com");
$subject = "Hello World from the SendGrid PHP Library!";
$to = new Email("Elmer Thomas", "elmer.thomas@sendgrid.com");
$content = new Content("text/plain", "Hello, Email!");
$mail = new Mail($from, $subject, $to, $content);

$apiKey = getenv('SENDGRID_API_KEY');
$sg = new \SendGrid($apiKey);

$response = $sg->client->mail()->send()->post($mail);
echo $response->statusCode();
```

```bash
php temp.php
```

I received status code 202 and the email was delivered.

Please take a look and compare my steps and code with yours. Thanks!
