### ISSUE TITLE
400 error Invalid type. mail_settings.sandbox_mode

### ISSUE THREAD

**Issue by azar1** [sendgrid/sendgrid-php#381]
$mail_settings->setBccSettings($bcc_settings);
    $sandbox_mode = new SandBoxMode();
    $sandbox_mode->setEnable(false);
    $mail_settings->setSandboxMode($sandbox_mode);
    $bypass_list_management = new BypassListManagement();
    $bypass_list_management->setEnable(true);
    $mail_settings->setBypassListManagement($bypass_list_management);
    $footer = new Footer();
    $footer->setEnable(true);
    $footer->setText("Footer Text");

this code is not working

**Comment by thinkingserious** [comment]
Hello @azar1,

The following code is working for me:

```php
<?php
namespace SendGrid;
// If you are using Composer (recommended)
require 'vendor/autoload.php';

// If you are not using Composer
// require("path/to/sendgrid-php/sendgrid-php.php");

$from = new Email(null, "dx@sendgrid.com");
$subject = "Hello World from the SendGrid PHP Library!";
$to = new Email(null, "elmer.thomas@sendgrid.com");
$content = new Content("text/plain", "Hello, Email!");
$mail = new Mail($from, $subject, $to, $content);

$apiKey = getenv('SENDGRID_API_KEY');
$sg = new \SendGrid($apiKey);

$mail_settings = new MailSettings();
$sandbox_mode = new SandBoxMode();
$sandbox_mode->setEnable(false);
$mail_settings->setSandboxMode($sandbox_mode);
$mail->setMailSettings($mail_settings);

$response = $sg->client->mail()->send()->post($mail);
echo $response->statusCode();
```

It looks like you are missing `$mail_settings = new MailSettings();`

With Best Regards,

Elmer

**Comment by azar1** [comment]
Thank you for your reply,

but,

showing this error when i make $sandbox_mode->setEnable(false);

400{"errors":[{"message":"Invalid type. Expected: object, given: array.","field":"mail_settings.sandbox_mode","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.mail_settings.sandbox_mode"}]}

**Comment by thinkingserious** [comment]
Can you please provide me with the output to:

```php
echo json_encode($mail, JSON_PRETTY_PRINT), "\n";
```

Please place that right before:

```php
$response = $sg->client->mail()->send()->post($mail);
```

Thanks!
