### ISSUE TITLE
Sendgrid with template

### ISSUE THREAD

**Issue by moontrv** [sendgrid/sendgrid-php#382]
My code works (email is sent) without the line with setTemplateId() method, whenever I try to use a template, email is not sent. 
I follow example from https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#transactional_templates with both cases: "With Mail Helper Class", "Without Mail Helper Class".
        $from = new SendGrid\Email(null, "test@example.com");
        $subject = "I'm replacing the subject tag";
        $to = new SendGrid\Email(null, "test@example.com");
        $content = new SendGrid\Content("text/html", "I'm replacing the <strong>body tag</strong>");
        $mail = new SendGrid\Mail($from, $subject, $to, $content);
        $mail->personalization[0]->addSubstitution("-name-", "Example User");
        $mail->personalization[0]->addSubstitution("-city-", "Denver");
        $mail->setTemplateId("myTemplateId...");
        
        $apiKey = 'myApiKey';
        $sg = new \SendGrid($apiKey);
        
        try {
            $response = $sg->client->mail()->send()->post($mail);
        } catch (Exception $e) {
            echo 'Caught exception: ',  $e->getMessage(), "\n";
        }

**Comment by thinkingserious** [comment]
Hello @moontrv,

Are you getting any exception message? If so, what is it?

With Best Regards,

Elmer

**Comment by moontrv** [comment]
Hi, thanks.
It turns out that we setup an account which expire the trial period, so that email with template will not be sent. I tried with another newly-created sendgrid account and email with template can be sent.

**Comment by thinkingserious** [comment]
Thanks for following up @moontrv!
