### ISSUE TITLE
Email not received with state delivered

### ISSUE THREAD

**Issue by anthonyav** [sendgrid/sendgrid-php#383]
#### Issue Summary

In certain case, my email in not received.

#### Steps to Reproduce

Here is the php code 

              `              
                $from = new SenGridEmail(null, $this->no_answer_email);
                $content = new Content("text/plain", '-message-');
                $mail = new Mail();
                $mail->setFrom($from);
                $mail->addContent($content);
                $mail->addCategory($name);
                $mail->addCustomArg('toto','super');

                $tos = [
                    "anthony1@outlook.com",
                    "exemple1@gmail.com",
                    "exemple2@gmail.com",
                    "exemple3@gmail.com",
                    "anthony1@hotmail.fr",
                ];

                foreach ($tos as $key => $to) {
                    $personalization = new Personalization();
                    $personalization->addTo(new SenGridEmail("anthony".$key, $to));
                    $personalization->setSubject('subject for anthony'.$key);
                    $personalization->addSubstitution('-message-', 'super email for '.$to);
                    $mail->addPersonalization($personalization);
                }

                $apiKey = $this->sendgridKey;
                $sg = new SendGrid($apiKey);

                $response = $sg->client->mail()->send()->post($mail);
                print_r($response->statusCode());
                print_r($response->headers());
                print_r($response->body());`

anthony1@hotmail.fr is link to anthony1@outlook.com account (outlook)
exemple2@gmail.com is an alias of exemple1@gmail.com

In this configuration anthony1@outlook.com doesn't receive the email.
if i change the order of the array like this:
    `
                $tos = [
                    "anthony1@hotmail.fr",
                    "exemple1@gmail.com",
                    "exemple2@gmail.com",
                    "exemple3@gmail.com",
                    "anthony1@outlook.com",
                ];`

Then anthony1@hotmail.fr doesn't receive the email
- All email have the state delivered
- All other emails are received
- The code return from the API is 202

#### Technical details:

* sendgrid-php Version: 5.4
* PHP Version: 5.6

**Comment by thinkingserious** [comment]
Hello @anthonyav,

Could you please share the result of:

```php
echo json_encode($mail, JSON_PRETTY_PRINT), "\n";
```

right before you call

```php
$response = $sg->client->mail()->send()->post($mail);
```

Thanks!

**Comment by thinkingserious** [comment]
Hi @anthonyav,

Just checking back in. After 30 days we will close this issue, but feel free to re-open if you continue to experience this issue.

Thanks!
