### ISSUE TITLE
Need better examples of real use cases - ie: mail to users in db

### ISSUE THREAD

**Issue by WadeShuler** [sendgrid/sendgrid-php#385]
There isn't really a real life use-case for how we would send an email to all the users in our database with custom personalizations in the subject and email content and utilizing batches for max efficiency. If we have 10k users in our system, we shouldn't call the API 10k times. I think the API has a limit of 1k emails (to + bcc + cc) per call.

psuedo example:

    $batchSize = 500;              //  the max number per batch (api call)
    
    $users = [
        ['id' => 1, 'username' => 'testuser1', 'email' => 'testuser1@example.com', 'firstname' => 'Test 1', 'lastname' => 'User'],
        ['id' => 2, 'username' => 'testuser2', 'email' => 'testuser2@example.com', 'firstname' => 'Test 2', 'lastname' => 'User'],
        ['id' => 3, 'username' => 'testuser3', 'email' => 'testuser3@example.com', 'firstname' => 'Test 3', 'lastname' => 'User'],
        ['id' => 4, 'username' => 'testuser4', 'email' => 'testuser4@example.com', 'firstname' => 'Test 4', 'lastname' => 'User'],
        ['id' => 5, 'username' => 'testuser5', 'email' => 'testuser5@example.com', 'firstname' => 'Test 5', 'lastname' => 'User']
    ];
    
    $batchContainer = [];          //  master array holding arrays of batches
    $tempBatch = [];               //  temp array, resets on each loop
    $count = 0;                    //  holds the count to stay under max per batch
    
    foreach ( $users as $user )
    {
      if ( $count >= $batchSize )
      {
        $batchContainer[] = $tempBatch;     // add temp batch array to batch container
        $tempBatch = [];                    // reset temp batch holder
        $count = 0;                         // reset count
      }
      
      $tempBatch[] = $user;                 // add user array to temp batch
      $count++;
    }

    $batchContainer[] = $tempBatch;         // add leftovers - maybe not necessary or needs checking

    // unset some memory hogging variables for performance
    unset($users);
    unset($tempBatch);
    unset($count);
    
    // -- now the mailing part
    
    $mailer = new \SendGrid($apiKey);
    
    $errors = [];
    $responses = [];
    
    foreach ($batchContainer as $batch)
    {        
        try {
            $responses[] = $mailer->send($batch);
        } catch (Exception $e) {
            $errors[] = $e->getMessage();
        }
    }

**NOTE:** This is not working code. I ripped it out of a working script I made, then chopped it up to try and have it make sense for this issue on GH. Basically we take 10k users, break them up into batches of 500 per batch, and make 1 API call to send the batch (of 500). So if we had 2k users, it would make 4 API calls only. This isn't efficient, I don't show creating the personalization, etc. The personalizations helper should be utilized when looping to build the batchContainer.

Requirements of mailing to your entire db of users:

  - Batch send: Should be 1 API call to send batch of emails (ie: to 500 people per batch)
  - Utilize substitutions in Subject and message body

Is it possible to set in the global substitutions an array of values, ie: `addSubstitution('-name-', $names)`? Or do we have to do this on each loop for each user (which seems like way more resources)?

Subject should be able to be like: "Hey -username- open this email"
Obviously message body should be able to have subs as well: "Dear, -firstname-"

---

To be honest, I find this sendgrid-php helper library to be confusing and a PITA. I may just write my own helper to build the JSON.

**Comment by thinkingserious** [comment]
Hello @WadeShuler,

Thanks for taking the time to provide such detailed feedback!

Unfortunately, currently our fully loaded working example, [is completely generic](https://github.com/sendgrid/sendgrid-php/blob/master/examples/helpers/mail/example.php), but perhaps it will help.

Substitutions are applied within the personalizations and do not support an array of values, here is [an example](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#transactional_templates) of that. You may want to utilize [sections](https://github.com/sendgrid/sendgrid-nodejs/issues/301#issuecomment-249701332) for global replacements.

With regards to the user experience, we would appreciate your feedback as we complete our mail helper roadmap. For that, please see "Mail Helper Enhancement (v3 mail/send)" under [projects](https://github.com/sendgrid/sendgrid-php/projects). We will be starting the conversation [here](https://github.com/sendgrid/sendgrid-php/issues/300).

To dig even further, we would love to learn more about your experience with SendGrid and with our libraries. If you are available for a 30 minute conversation, please grab a time on our Developer Experience PM's calendar! https://calendly.com/matt-bernier/30min

Thanks!

With Best Regards,

Elmer

**Comment by WadeShuler** [comment]
Thanks I will review the links later when I am available.

From examples I have seen for the SendGrid SMTP API, it supports passing an array of substitutions directly. I was hoping this would handle that as well.

I think I may use the SendGrid http client API and build my own helper module and use the client directly to build the json.

I am creating an extension for Yii2 to support SendGrid and I want it to handle bulk mailing efficiently. Currently there isn't a Yii2 extension for SendGrid bulk mailing using the web API. So I'm just filling a hole as I stumbled across it.

**Comment by thinkingserious** [comment]
Thanks for the follow up @WadeShuler,

If you publish your work on GitHub, please drop a link here. 

We do have a [very thin HTTP client here](https://github.com/sendgrid/php-http-client) that might be useful for you. This SDK depends on that library.

Either way, feel free to reach out if we can further assist. Thanks!

Elmer
