### ISSUE TITLE
Keeping track of email conversation.

### ISSUE THREAD

**Issue by hifall** [sendgrid/sendgrid-php#386]
#### Issue Summary

Our app has a scenario like this: an end user sends an email to our email address abcd@domain.com, and our app uses Sendgrid's PHP API to send an email to that end user as reply. In order to keep the email messages in a conversation, we use the References field in email headers. That is all the email messages that have a common email ID in the References field belong to the same conversation.

The problem is: we are not able to set the References field in email header when we send the email.

#### Steps to Reproduce

Step 1.
`$mail = new SendGrid\Mail($from, $subject, $to, $content);`
`$mail->addHeader("References", "<tencent_55C652396BB5139C55E4FF22@qq.com>");`
Step 2.
Expect to see `<tencent_55C652396BB5139C55E4FF22@qq.com>` in the sent email. But a Sendgrid-generated email ID is used.

What can I do to group email messages in a conversation in such a scenario?

**Comment by thinkingserious** [comment]
Hello @hifall,

I believe what you need is custom_args, [like so](https://github.com/sendgrid/sendgrid-php/blob/master/examples/helpers/mail/example.php#L72).

With Best Regards,

Elmer

**Comment by hifall** [comment]
Thanks for your reply. Do you mean this?

```
$to = new SendGrid\Email($toName, $to);
$personalization = new SendGrid\Personalization();
$personalization->addTo($to);
$personalization->addCustomArg("user_id", "<tencent_55C652396BB5139C55E4FF22@qq.com>");
$sg = new \SendGrid($apiKey);
$response = $sg->client->mail()->send()->post($mail);
```

What is the expected change? I have tried this, and I am not seeing any References or user_id field in the email header.

Thanks in advance.

**Comment by thinkingserious** [comment]
How about adding the header to the personalization object, [like so](https://github.com/sendgrid/sendgrid-php/blob/master/examples/helpers/mail/example.php#L45)?

How are you inspecting the headers?

**Comment by hifall** [comment]
Adding the header like so seems to work:

`$personalization->addHeader("X-Test", "test");`

That is: the variable appears in the email's header like:
Message-ID: <XuKOVhZwT1aqi-Z99EUI6A@ismtpd0017p1sin1.sendgrid.net>
Subject: the title
X-Test: test

The way I am inspecting the headers is to export the email from the web client to an eml file, then open it in a text editor.

**Comment by hifall** [comment]
Also tested with a Gmail account, and used web Gmail's "Show original" feature to display the email header, and couldn't find References or user_id.

**Comment by hifall** [comment]
If I do this:

`$personalization->addHeader("References", "<tencent_55C652396BB5139C55E4FF22@qq.com>");`

The References field appears in the header. Although I still need to check if it will be picked up by email clients.

Is this how I should do it?

**Comment by hifall** [comment]
Update on this matter: it seems although the References field added to email header using addHeader seems present, email messages from different conversations are grouped into one conversation. That is, email messages having References field pointing to different conversations are considered from the same conversation by the email client.

I did this test on the web client I am using, which is Tencent's Exmail, BTW.

**Comment by thinkingserious** [comment]
@hifall,

That looks correct to me. Please let me know if you need further assistance.

Thanks!

Elmer
