### ISSUE TITLE
Fix ClickTracking settings serialization

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-php#387]
#### Issue Summary

See https://github.com/sendgrid/sendgrid-php/pull/316

**Comment by thomasbachem** [comment]
The same fix is needed for `OpenTracking`, `SubscriptionTracking` and `Ganalytics`.

**Comment by thinkingserious** [comment]
This has been moved [here](https://github.com/sendgrid/sendgrid-php/issues/434).
