### ISSUE TITLE
Move downloads location for the source code

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-php#388]
#### Issue Summary

Currently the source code is hosted on Amazon AWS, we will be moving the downloads in house.

See https://github.com/sendgrid/sendgrid-php/issues/349

**Comment by WadeShuler** [comment]
Why not just use the Github release zips? Just link to the version release...

**Comment by thinkingserious** [comment]
@WadeShuler,

For non-composer users we need to add this file: https://github.com/sendgrid/sendgrid-php/blob/master/scripts/s3upload.sh#L10

Moving forward, I think we can just include that file in this repo. 

Maybe we just have a note that for old versions you will need to copy that file into the root of the project.

- Elmer
