### ISSUE TITLE
Email sent with SendGrid has wrong References header.

### ISSUE THREAD

**Issue by hifall** [sendgrid/sendgrid-php#389]
Here is the scenario:
First I sent an email from my Gmail account to my corporate account, and that email has a message id: `<CA+=LkNG81HAKehPHFtZ18-5c4E5JwTCQfv57i1w9YRJ8OMEkkA@mail.gmail.com>`. Then I used SendGrid to send another email referencing the first like this:
```
    $mail = new SendGrid\Mail();
    $personalization = new SendGrid\Personalization();
    $mail->setFrom($from);
    $personalization->setSubject($subject);
    $personalization->addTo($to);
    $mail->addContent($content);
    if ($references != false) {
        $personalization->addHeader("References", trim($references));
    }
    $mail->addPersonalization($personalization);
    $sg = new \SendGrid($apiKey);
    $response = $sg->client->mail()->send()->post($mail);
```
The second email delivered. However, it came with an incorrect References header:
`<CA =LkNG81HAKehPHFtZ18-5c4E5JwTCQfv57i1w9YRJ8OMEkkA@mail.gmail.com>`.
It seems that the `+` in the first email's message id was replaced by a space.

Any idea why?

The following is the head info copied from web Gmail.

Delivered-To: xxxx@gmail.com
Received: by 10.129.181.65 with SMTP id c1csp1607171ywk;
        Sun, 30 Apr 2017 07:38:04 -0700 (PDT)
X-Received: by 10.98.202.80 with SMTP id n77mr22688010pfg.158.1493563084862;
        Sun, 30 Apr 2017 07:38:04 -0700 (PDT)
Return-Path: <bounces+5025980-ae95-xxxx=gmail.com@sendgrid.net>
Received: from o1678916x17.outbound-mail.sendgrid.net (o1678916x17.outbound-mail.sendgrid.net. [167.89.16.17])
        by mx.google.com with ESMTPS id 19si7833996pgd.10.2017.04.30.07.38.04
        for <xxxx@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Sun, 30 Apr 2017 07:38:04 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+5025980-ae95-xxxx=gmail.com@sendgrid.net designates 167.89.16.17 as permitted sender) client-ip=167.89.16.17;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@sendgrid.net;
       spf=pass (google.com: domain of bounces+5025980-ae95-xxxx=gmail.com@sendgrid.net designates 167.89.16.17 as permitted sender) smtp.mailfrom=bounces+5025980-ae95-xxxx=gmail.com@sendgrid.net
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=sendgrid.net; h=content-transfer-encoding:content-type:from:mime-version:to:subject:references:x-feedback-id; s=smtpapi; bh=8MvEg3KlM4QsBo9Hc9R/ldsXgpk=; b=sOR0/jRvvRE+T3GJBV n/GxTPxgayp+6kS4GzXC1tHP3xRw8cmyBpFWuNgA7rQz/o4N2F3VRnVqA6MFWzcu rtpMvb/WorpClpsgbV444V+uYZklpYuTnuw/lJatncyumc/gV1bxzGsJ7hYRcguQ 8sy3lrqBkC0GqL+aN7/2Gzp50=
Received: by filter0210p1las1.sendgrid.net with SMTP id filter0210p1las1-22378-5905F6CB-8
        2017-04-30 14:38:03.489520775 +0000 UTC
Received: from NTAyNTk4MA (mail.okdesk.cn [182.254.152.63]) by ismtpd0017p1sin1.sendgrid.net (SG) with HTTP id MB3cpXkeTdKMViBip6OXNw Sun, 30 Apr 2017 14:38:03.262 +0000 (UTC)
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset=UTF-8
Date: Sun, 30 Apr 2017 14:38:03 +0000
From: Mirachat Team <xxxx@mirachat.com>
Mime-Version: 1.0
To: "xxxx@gmail.com" <xxxx@gmail.com>
Message-ID: <MB3cpXkeTdKMViBip6OXNw@ismtpd0017p1sin1.sendgrid.net>
Subject: Update
References: <CA =LkNG81HAKehPHFtZ18-5c4E5JwTCQfv57i1w9YRJ8OMEkkA@mail.gmail.com>
X-SG-EID: jB0MaDyhcltIeK0rCzu+HvTbzkJlioShdKuul3ZZZ/r91FSHGR/EHMohiXHfAGGJwyGCDIqh/5xgxt QavdjBaPJKoGwwrz4tDwm9u++XK6X+AgRiKZ3bz5gezGHcHP03V+MpQNg7ddszFzrT6mAp5AV/YCAB KhwQOpGIa0F4M+oImp+VpkQhdS2fDIJT4OMb/aGEFksAMR24gFBwGuwbMF606wP0a8vU3t37duVi9j U=
X-Feedback-ID: 5025980:dRM4xrUa6rvm3BcOcE1eDVU4Nd2hqaTHtyq65tBAQ/s=:dRM4xrUa6rvm3BcOcE1eDVU4Nd2hqaTHtyq65tBAQ/s=:SG

**Comment by thinkingserious** [comment]
Hello @hifall,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
