### ISSUE TITLE
Reply To doesn't support "name" but v3 docs show it should

### ISSUE THREAD

**Issue by WadeShuler** [sendgrid/sendgrid-php#390]
If you look at the [docs](https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html), `reply_to` supports `name`. However, this library doesn't.

**Comment by thinkingserious** [comment]
Thanks for the heads up @WadeShuler! I have added this to our backlog for a fix.

**Comment by WadeShuler** [comment]
Thanks

Maybe in a few days or weeks I will create a PR to fix it. I have to get a few projects off my plate before I can spend the time on it.

**Comment by thinkingserious** [comment]
Thats awesome @WadeShuler, thanks!

**Comment by MACscr** [comment]
Any luck? We really need this.

**Comment by thinkingserious** [comment]
Thanks for reaching out @MACscr,

I've added your vote to this issue in our backlog to help it gain priority.

**Comment by dejami-jbauer** [comment]
I'm sad this basic functionality is missing, please add my vote

**Comment by thinkingserious** [comment]
Hi @dejami-jbauer, @WadeShuler, @MACscr,

The awesome @caseyw has implemented this functionality with PR #390. Please follow along there for updates, we should be merging that soon.

With Best Regards,

Elmer
