### ISSUE TITLE
send_at time using wrong time

### ISSUE THREAD

**Issue by WadeShuler** [sendgrid/sendgrid-php#395]
For testing my Yii2 mailer extension, I set the sendAt time to 5 minutes in the future. I have tested this with setting the send_at time to the global SendGrid object and adding the send_at time to individual personalizations (in my batch mode). Both ways do the same thing, report the incorrect sent time.

In my mailer:

    ->setSendAt(time() + (5 * 60))

Which breaks down where I build the message:

    if ( isset($this->sendAt) && is_int($this->sendAt) ) {
        $this->getSendGridMail()->setSendAt($this->sendAt);
    }

Headers from when it was initially sent via API:

    "Date: Thu, 11 May 2017 19:44:28 GMT\r"

Gmail after it actually sent (I am EST)
3:44 PM (6 minutes ago)

Funny thing it, it was 3:50 when I got this email in Gmail (I was 1 minute late checking the email). That worked as it should. I queued it at 44 minutes after and SendGrid should have sent it at 49 minutes after, which it did. Problem is, the minute it came into my inbox, it reported it was 6 minutes old. That it was mailed 6 minutes ago, back when I sent it off to the SendGrid API.

It should report that it was sent at 3:49 (time it was really sent, 5 mins later) not 3:44 (the time I queued it via `send_at`). What if I was to queue an email for 8 hours later, when it sends it would jump backwards in time like it was a stuck email.

The full code can be seen here: https://github.com/WadeShuler/yii2-sendgrid

**Comment by thinkingserious** [comment]
Hello @WadeShuler,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
