### ISSUE TITLE
Uncaught TypeError with Sendgrid Plugin

### ISSUE THREAD

**Issue by ooples** [sendgrid/sendgrid-php#398]
I'm getting the following exception after installing the sendgrid plugin on magento 2.1.7

PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Zend_Mail_Protocol_Smtp::__construct() must be of the type array, null given, called in /var/www/html/vendor/magento/zendframework1/library/Zend/Mail/Transport/Smtp.php on line 198 and defined in /var/www/html/vendor/magento/zendframework1/library/Zend/Mail/Protocol/Smtp.php:123
Stack trace:
#0 /var/www/html/vendor/magento/zendframework1/library/Zend/Mail/Transport/Smtp.php(198): Zend_Mail_Protocol_Smtp->__construct(NULL, NULL, NULL)
#1 /var/www/html/var/generation/SendGrid/EmailDeliverySimplified/Model/Transport/Interceptor.php(76): Zend_Mail_Transport_Smtp->_sendMail()
#2 /var/www/html/vendor/magento/zendframework1/library/Zend/Mail/Transport/Abstract.php(348): SendGrid\EmailDeliverySimplified\Model\Transport\Interceptor->_sendMail()
#3 /var/www/html/var/generation/SendGrid/EmailDeliverySimplified/Model/Transport/Interceptor.php(89): Zend_Mail_Transport_Abstract->send(Object(Magento\Framework\Mail\Message))
#4 /var/www/html/vendor/magento/zendframework1/library/Zend/ in /var/www/html/vendor/magento/zendframework1/library/Zend/Mail/Protocol/Smtp.php on line 123

**Comment by thinkingserious** [comment]
Hi @ooples,

Did you solve your issue?

Thanks!

Elmer
