### ISSUE TITLE
Doc error: GET /contactdb/lists/{list_id}/recipients does not take a list_id query param

### ISSUE THREAD

**Issue by jim-at-miramontes** [sendgrid/sendgrid-php#399]
https://github.com/sendgrid/sendgrid-php/blob/master/USAGE.md#get-contactdblistslist_idrecipients states that list_id is a possible (or required?) query param:

`$query_params = json_decode('{"page": 1, "page_size": 1, "list_id": 1}');`

However, this fails: a request using these params returns a status body of:

`'body' => '{"errors":[{"message":"The following parameters are not custom fields or reserved fields: [list_id]"}]}`

When I removed list_id from the list of parameters, the call worked; I expect it's only a doc error.  Or, am I missing something?

**Comment by thinkingserious** [comment]
Hi @jim-at-miramontes,

Indeed, that is a documentation error, it should be:

```csharp
$query_params = json_decode('{"page": 1, "page_size": 1}');
$list_id = "test_url_param";
$response = $sg->client->contactdb()->lists()->_($list_id)->recipients()->get(null, $query_params);
echo $response->statusCode();
echo $response->body();
print_r($response->headers());
```

Thanks for letting us know!

With Best Regards,

Elmer

**Comment by caseyw** [comment]
I believe this can be closed.

**Comment by thinkingserious** [comment]
Thanks @caseyw!
