### ISSUE TITLE
Receiving blank email notification from my own email associated with sendgrid

### ISSUE THREAD

**Issue by sumeena** [sendgrid/sendgrid-php#400]
#### Issue Summary

I am using your official sendgrid library to send bulk emails every 10 minutes, the script is running through a cron job on Linux environment, everything is working just perfect, all the users connected to my website are receiving emails whenever they are supposed to, the only exception i am facing is that i am receiving a blank email notification all the time when script runs, and the even more complicated thing is the email i received is from my own email address, that means i am sending email to myself, every 10 minutes, here is the email "emmahall@example.com", this is the email account i have registered with on sendgrid, and from this account i am sending emails to the users.
Please help me to sort out this issue as i have contacted with your support team many times but all went in vain.

I have posted a sample from my code below:

try {
			$name=$firstname;
			$sendgrid = new SendGrid($user_sendgrid, $pass_sendgrid);
			$email = new SendGrid\Email();
			$email
				->setSmtpapiTos($emails)
				->setFrom('emmahall@example.com')
				->setSubject(' ')
				->setText(' ')
				->addFilterSetting("templates", "template_id", $get_row2['sendgridtransactionaltemplateid'])
				->addSubstitution("[email]", $emails)
				->addSubstitution("[firstname]", $firstname)
				->addSubstitution("[lastname]", $lastname)
				->addSubstitution("[address]", $address)
				->addSubstitution("[city]", $city)
				->addSubstitution("[state]", $state)
				->addSubstitution("[zipcode]", $zipcode)
				->addSubstitution("[phonenumber]", $phonenumber)
				->addSubstitution("[signupdate]", $signupdate)
				->addSubstitution("[pagelocation]", $pagelocation)
				->addSubstitution("[ip]", $ip)
				->addSubstitution("[url]", $url)
				->addSubstitution("[kenshoo]", $kenshoo)
				->addSubstitution("[custom1]", $custom1)
				->addSubstitution("[custom2]", $custom2)
				->addSubstitution("[custom3]", $custom3)
				->addSubstitution("[weblink]", $url)
				->addSubstitution("[unsubscribe]", $unsubscribe)
				->setHtml(' ');
			$sendgrid->send($email);
			echo BR;
		}
		catch (Exception $e) {
			$this->notify($user_sendgrid,$pass_sendgrid,'upgradeGoogleSheet_google broke out at: ');				// Notification Email When Script1 For Desktop Users Broke Out
		}

Also I have attached the header content of the blank email i just received recently.
[header.txt](https://github.com/sendgrid/sendgrid-php/files/1080253/header.txt)

Please check it.

Thanks in advance.

#### Technical details:
* PHP Version: 5.x

**Comment by thinkingserious** [comment]
Hi @sumeena,

Based on that header, your email is being flagged as spam by your email client. 

Did you modify that header.txt so that your domain was changed to example.com?

**Comment by sumeena** [comment]
Thanks for your response, the domain example.com is just dummy as i cannot reveal the real domain name due to privacy issues.

**Comment by sumeena** [comment]
and the header attached belongs to the email which i receive every 10 minutes, which i should not receive.

**Comment by sumeena** [comment]
one thing i would like to let you know, that the script runs in the following way:
it loops for 15 times, every time it gets users from db and post their emails as an array to sendgrid with substitute parameters, and for every loop the array contains 8-10 emails, the process lasts for less than 1 minute,
and this scripts runs every 10 minutes, so is it possible that it posts emails to sendgrid 15 times without any delay, that's why it is causing that issue?

**Comment by sumeena** [comment]
okay i got something related to it, on your official website, it is clearly stated that sendgrid sends email notification if it encounters some parsing error, here is the source:
https://sendgrid.com/docs/API_Reference/SMTP_API/using_the_smtp_api.html#-Requirements-and-Limitations
the same thing happened to me, but why the email is blank all the time??

**Comment by sumeena** [comment]
okay i got something related to it, on your official website, it is clearly stated that sendgrid sends email notification if it encounters some parsing error, here is the source:
https://sendgrid.com/docs/API_Reference/SMTP_API/using_the_smtp_api.html#-Requirements-and-Limitations
the same thing happened to me, but why the email is blank all the time??

**Comment by thinkingserious** [comment]
Hi @sumeena,

Thanks for sharing those details!

That is not an issue related to this SDK. Could you please reach out to our [support team](https://support.sendgrid.com), as they will be able to better assist.

Thanks!

With Best Regards,

Elmer
