### ISSUE TITLE
require vendor autoload failed to open stream

### ISSUE THREAD

**Issue by nzhome** [sendgrid/sendgrid-php#407]
I am using hostgator, and I get this error.  I have used sendgrid-php.php just fine since Oct 2015, and it stopped working in the last few months.  now when I use the latest sendgrid-php I get this silly error.

<br />
<b>Warning</b>:  require(vendor/autoload.php): failed to open stream: No such file or directory in <b>/home2/website1/public_html/sendgrid-php/sendgrid-php.php</b> on line <b>2</b><br />
<br />
<b>Warning</b>:  require(vendor/autoload.php): failed to open stream: No such file or directory in <b>/home2/website1/public_html/sendgrid-php/sendgrid-php.php</b> on line <b>2</b><br />
<br />
<b>Fatal error</b>:  require(): Failed opening required 'vendor/autoload.php' (include_path='.:/opt/php54/lib/php') in <b>/home2/website1/public_html/sendgrid-php/sendgrid-php.php</b> on line <b>2</b><br />

**Comment by nzhome** [comment]
oh god damn,  /vendor/  is also in the gitignore  file..  where are these files? why do you insist on exluding them from this repository!?

**Comment by thinkingserious** [comment]
I assume that based on your response to the [other issue](https://github.com/sendgrid/sendgrid-php/issues/406), this issue is resolved. If that is not the case, please let me know. Thanks!
