### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by cisqo** [sendgrid/sendgrid-php#417]
#### Issue Summary

Hi,
it seems like i have a problem with sending mail using sengrid.
Everything was working fine yesterday, but I just can't send a mail today.
What happend in beetween (the change occured at 4pm yesterday french hour).

Here is the error I get:

Exception::__set_state(array( 'message' => 'SSL certificate problem, verify that the CA cert is OK. Details: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed', 'string' => '', 'code' => 0, 'file' => '/home/gouvimpo/diagnostic-experts/includes/classes/SendGridtest/vendor/mashape/unirest-php/lib/Unirest/Unirest.php', 'line' => 209, 'trace' => array ( 0 => array ( 'file' => '/home/gouvimpo/diagnostic-experts/includes/classes/SendGridtest/vendor/mashape/unirest-php/lib/Unirest/Unirest.php', 'line' => 71, 'function' => 'request', 'class' => 'Unirest', 'type' => '::', 'args' => array ( 0 => 'POST', 1 => 'https://api.sendgrid.com/api/mail.send.json', 2 => array ( 'to' => 'xxx@xxxxx.fr', 'from' => 'xxx@xxxxxxx.fr', 'x-smtpapi' => '{"to":["xxxx@xxxxxxxx"],"category":["xxxxxxxx"]}', 'subject' => 'xxxxxx', 'text' => NULL, 'html' =>

Any advice or Idea would be nice, should I update my sendgrid lib version?
Thank for you valuable help!
Regards.

#### Steps to Reproduce

I'll just simplify my code here:

include('../../includes/classes/SendGridtest/vendor/autoload.php');
 $from = "contact@diagnostic-experts.fr";
    
    $html_mail="blablabla";
    $sujet = "XXXXX";
// $objMail= new mailer();
    $sendgrid = new SendGrid('XXX', 'XXXX');
    $mail = new SendGrid\Email();

    try {
        $mail->addCategory("XXXXX");
        $mail->addTo(XXXX)->
        setFrom($from)->
        setSubject($sujet)->

        setHtml(($html_mail));
        $response = $sendgrid->send($mail);

        if (!$response) {
            throw new Exception("Did not receive response.");
        } else if ($response->message && $response->message == "error") {
            throw new Exception("Received error: " . join(", ", $response->errors));
        } else {
            //print_r($response);
        }
    } catch (Exception $e) {
        var_export($e);
    }

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* sendgrid-php Version:  const VERSION = "2.0.3";
PHP Version 5.5.38

**Comment by thinkingserious** [comment]
Hello @cisqo,

I can verify that nothing changed with this library during that time frame.

I suggest you reach out to our support team to see if something changed regarding our certificate. If it did not, you might want to check the [configuration on server](https://stackoverflow.com/a/32366242). 

With Best Regards,

Elmer

**Comment by imbhavin95** [comment]
Same issue happen with me as well.

**Comment by thinkingserious** [comment]
Hello @imbhavin95,

Please reach out to our support team at https://support.sendgrid.com. Thank you!

With best regards,

Elmer
