### ISSUE TITLE
Tracking Settings cause Mail not to be sent

### ISSUE THREAD

**Issue by zaiddabaeen** [sendgrid/sendgrid-php#418]
I am attempting to disable tracking settings for some e-mails. When I set TrackingSettings, the e-mails are not sent anymore, no error occurs, and it cannot be seen in Sendgrid Activity dashboard.

```
        $sendgridEmail = new Mail(
             $fromEmail,
              'The subject',
              $toEmail,
              $content
        );

        $sendgridEmail = self::disableTracking($sendgridEmail);

        $trackingSettings = new TrackingSettings();
        $clickTracking = new ClickTracking();
        $clickTracking->setEnable(false);
        $clickTracking->setEnableText(false);

        $openTracking = new OpenTracking();
        $openTracking->setEnable(false);
        $openTracking->setSubstitutionTag(false);

        $trackingSettings->setClickTracking($clickTracking);
        $trackingSettings->setOpenTracking($openTracking);

        $sendgridEmail->setTrackingSettings($trackingSettings);

        $emailService->client->mail()->send()->post($sendgridEmail);
```

Where `$emailService` is `\SendGrid` from the DI.

I am using PHP7.1. Sendgrid latest version 6.0.0 (also tested with 5.5.*)

**If simply I remove the `$sendgridEmail->setTrackingSettings($trackingSettings);` line, the e-mail is sent.**

**Comment by zaiddabaeen** [comment]
Okay I commented out 

```
        $clickTracking->setEnableText(false);
        $openTracking->setSubstitutionTag(false);
```

And now the e-mails are sent again.

**Comment by thinkingserious** [comment]
Hi @zaiddabaeen,

Thanks for taking the time to share the results with us. I've added this to our backlog for further review. I'm glad you found a workaround, but I don't think this should be so difficult.

Currently, we are trying to make this SDK easier to use, to that end, we would appreciate your feedback on [our proposal](https://github.com/sendgrid/sendgrid-php/issues/413).

Thanks!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
This has been moved [here](https://github.com/sendgrid/sendgrid-php/issues/434).
