### ISSUE TITLE
Setting ASM Group ID causes email not to be sent

### ISSUE THREAD

**Issue by atgeo** [sendgrid/sendgrid-php#419]
Adding these lines stops emails from being sent without generating any errors in response.

$asm = new SendGrid\ASM();
$asm->setGroupId(1343);
$mail->setASM($asm);

I am using PHP 5.6. SendGrid PHP Client Library version 6.0.0.

**Comment by thinkingserious** [comment]
Hello @atgeo,

Please review the following:

1. No [exception](https://github.com/sendgrid/sendgrid-php/blob/master/TROUBLESHOOTING.md#error-messages) is thrown?
2. Please verify the group ID is valid
3. Could you provide the sanitized output of `echo json_encode($mail, JSON_PRETTY_PRINT), "\n";` just before you attempt the send the email?

Thanks!

With Best Regards,

Elmer

**Comment by atgeo** [comment]
No exception is thrown and group ID is valid.
Please check the output here: [output.json](https://drive.google.com/file/d/0B2lwHtooJi_pX2tob3U0T3pLVUU)

**Comment by thinkingserious** [comment]
Hi @atgeo,

I'm having trouble reproducing, here is my code:

```php
<?php
require("./sendgrid-php/sendgrid-php.php");

$from = new SendGrid\Email("Example User", "dx@sendgrid.com");
$subject = "Sending with SendGrid is Fun";
$to = new SendGrid\Email("Example User", "elmer.thomas@sendgrid.com");
$content = new SendGrid\Content("text/plain", "and easy to do anywhere, even with PHP");
$mail = new SendGrid\Mail($from, $subject, $to, $content);
$asm = new SendGrid\ASM();
$asm->setGroupId(1041);
$mail->setASM($asm);

$apiKey = getenv('SENDGRID_API_KEY');
$sg = new \SendGrid($apiKey);

$response = $sg->client->mail()->send()->post($mail);
echo $response->statusCode();
print_r($response->headers());
echo $response->body();
```

And this is what I see in my inbox: https://screencast.com/t/dB93gkeH7EE

Please take a look and let me know how we differ.

Thanks!

With Best Regards,

Elmer

**Comment by atgeo** [comment]
Hello @thinkingserious,

After checking your code, I saw that it is exactly what I'm doing. Perhaps it has to do with my obsolete Lite account?

Thank you,
George

**Comment by thinkingserious** [comment]
Hi @atgeo,

I'm not sure about that. I would suggest reaching out to our [support team](https://support.sendgrid.com) on that one, so that they can look deeper into the capabilities of your account.

With Best Regards,

Elmer
