### ISSUE TITLE
Disabled filters on V2 objects get ignored

### ISSUE THREAD

**Issue by thomasbachem** [sendgrid/sendgrid-php#420]
As of now, disabled filters on a V2 object get ignored when translating them to the V3 object – but I explicitly want to disable a default filter.

We need to change the conditional for `ClickTracking`, `OpenTracking`, `SubscriptionTracking` and `Ganalytics` from this:

    if ( $settings[ 'enable' ] ) {
        $open_tracking_settings->setEnable( true );
    }

to this:

    $open_tracking_settings->setEnable( $settings[ 'enable' ] );

To make this work, the serialization of `false` values for filters does also need to be fixed, see #387.

**Comment by thomasbachem** [comment]
Just to clarify what I want to achieve:

    $email = new SendGrid\Email();
    $email->addFilter('ganalytics', 'enable', false);

Should disable the Google Analytics link tagging filter that is enabled by default for our SendGrid account.

**Comment by thinkingserious** [comment]
Hi @thomasbachem,

I've added your vote to issue #387. It's currently not to high on our backlog, but a PR would bump it to near the top.

With Best Regards,

Elmer
