### ISSUE TITLE
Sendgrid_Translator::get_smtp_filter_settings() shouldn't ignore disabled filter settings

### ISSUE THREAD

**Issue by thomasbachem** [sendgrid/sendgrid-php#421]
As of now, disabled filters on a V2 object get ignored when translating them to the V3 object – but I explicitly want to disable a default filter.

This needs to be removed from `Sendgrid_Translator::get_smtp_filter_settings()`:

    // If it's not enabled, return empty array, no need to make the payload bigger
    if ( ! $email_v2->smtpapi->filters[ $filter_key ][ $filter_sub_label ][ $filter_enabled ]  ) {
      return $output_array;
    }

See also #420.

**Comment by thinkingserious** [comment]
I think #387 will also solve this. Please let me know if this is not the case.
