### ISSUE TITLE
Unable to cancel my account and unable to contact support

### ISSUE THREAD

**Issue by a2nt** [sendgrid/sendgrid-php#422]
Support website never shows me logged in, but I'm. So I'm unable to make support request. Cancel account button doesn't work either and shows this shit. U need to fix it ASAP cuz otherwise I will call lawyer.
![screen shot 2017-08-29 at 2 09 46 am](https://user-images.githubusercontent.com/672794/29789537-8c690bb0-8c60-11e7-8772-79ccbd357267.png)

**Comment by thinkingserious** [comment]
Hello @a2nt,

Your account has been successfully downgraded according to our records. If you have any further questions please contact support at support@sendgrid.com. Thanks!

With Best Regards,

Elmer
