### ISSUE TITLE
Method 'mail' not found in SendGrid\Client

### ISSUE THREAD

**Issue by TeodorVecerdi** [sendgrid/sendgrid-php#424]
#### Issue Summary

While attempting to run the mail example (The one with the Mail Helper class) I encountered a error.
I have tried both the Composer and the direct library and the same problem occurs.
On this line `$response = $sg->client->mail()->send()->post($mail);` on `mail()` I get `Method 'mail' not found in SendGrid\Client`. 
After that everything falls apart

#### Steps to Reproduce
Not needed.

#### Technical details:

* sendgrid-php Version: 6.0 (latest)
* PHP Version: 7.1.9

**Comment by thinkingserious** [comment]
Hi @TeodorVecerdi,

My apologies, I can not reproduce. Here are the steps I took:

```sh
mkdir test
cd ./test
code composer.json
```

`composer.json`

```js
{
    "require": {
      "sendgrid/sendgrid": "~6.0"
    }
 }
```

```sh
code test.php
```

`code.php`

```php
<?php
// If you are using Composer (recommended)
require 'vendor/autoload.php';

// If you are not using Composer
// require("path/to/sendgrid-php/sendgrid-php.php");

$from = new SendGrid\Email("DX Team", "dx@sendgrid.com");
$subject = "Sending with SendGrid is Fun";
$to = new SendGrid\Email("Elmer Thomas", "elmer.thomas@sendgrid.com");
$content = new SendGrid\Content("text/plain", "and easy to do anywhere, even with PHP");
$mail = new SendGrid\Mail($from, $subject, $to, $content);

$apiKey = getenv('SENDGRID_API_KEY');
$sg = new \SendGrid($apiKey);

$response = $sg->client->mail()->send()->post($mail);
echo $response->statusCode();
print_r($response->headers());
echo $response->body();
```

```sh
php test.php
```

The email was sent successfully.

Could you please walk me through your install steps?

Thanks!

With Best Regards,

Elmer

**Comment by TeodorVecerdi** [comment]
Thanks for the quick reply, @thinkingserious !
Here are the steps I followed:
sendemail.php and composer.json are the same as your files.
then I did

> composer install

and then php sendemail.php
and this is what I got:
> J:\Development\GitHub\PHP\test>php sendemail.php
PHP Fatal error:  Uncaught Error: Call to undefined function SendGrid\curl_init() in J:\Development\GitHub\PHP\test\vendor\sendgrid\php-http-client\lib\Client.php:142
Stack trace:
#0 J:\Development\GitHub\PHP\test\vendor\sendgrid\php-http-client\lib\Client.php(214): SendGrid\Client->makeRequest('post', 'https://api.sen...', Object(SendGrid\Mail), NULL)
#1 J:\Development\GitHub\PHP\test\sendemail.php(17): SendGrid\Client->__call('post', Array)
#2 {main}
  thrown in J:\Development\GitHub\PHP\test\vendor\sendgrid\php-http-client\lib\Client.php on line 142

**Comment by thinkingserious** [comment]
Hi @TeodorVecerdi.

It looks like you may have run into this issue: https://stackoverflow.com/questions/34842596/call-to-undefined-function-curl-init-even-it-is-enabled-in-php7

**Comment by TeodorVecerdi** [comment]
@thinkingserious I have installed curl and added it to the path. I don't understand what I should do.

**Comment by thinkingserious** [comment]
@TeodorVecerdi,

Now that you have done that, what happens when you do `composer install`?

**Comment by TeodorVecerdi** [comment]
> Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
   Installing sendgrid/php-http-client (3.7.0): Loading from cache
   Installing sendgrid/sendgrid (6.0.0): Loading from cache
Writing lock file
Generating autoload files

**Comment by thinkingserious** [comment]
Ok, that looks good. How about when you run `php sendemail.php`?

**Comment by TeodorVecerdi** [comment]
The same error

**Comment by TeodorVecerdi** [comment]
> PHP Fatal error:  Uncaught Error: Call to undefined function SendGrid\curl_init() in J:\Development\GitHub\PHP\test\vendor\sendgrid\php-http-client\lib\Client.php:142
Stack trace:
#0 J:\Development\GitHub\PHP\test\vendor\sendgrid\php-http-client\lib\Client.php(214): SendGrid\Client->makeRequest('post', 'https://api.sen...', Object(SendGrid\Mail), NULL)
#1 J:\Development\GitHub\PHP\test\sendemail.php(17): SendGrid\Client->__call('post', Array)
#2 {main}
  thrown in J:\Development\GitHub\PHP\test\vendor\sendgrid\php-http-client\lib\Client.php on line 142

**Comment by thinkingserious** [comment]
For some reason your install of php7 is not finding curl_init(). 

Can you try stepping through [these steps](https://stackoverflow.com/questions/34842596/call-to-undefined-function-curl-init-even-it-is-enabled-in-php7/35273081#35273081)?

**Comment by TeodorVecerdi** [comment]
I'm on windows, this is my first time doing this. Curl was disabled in php.ini indeed. Thank you for the help @thinkingserious

**Comment by thinkingserious** [comment]
Awesome, thanks for following up :)
