### ISSUE TITLE
Call to undefined function SendGrid\mb_convert_encoding()

### ISSUE THREAD

**Issue by TeodorVecerdi** [sendgrid/sendgrid-php#425]
#### Issue Summary
While debugging my script(again) I saw that it was working locally and not when hosted on heroku.
Then I looked at the log files and saw this: 

> 2017-08-31T22:27:03.789749+00:00 app[web.1]: [31-Aug-2017 22:27:03 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function SendGrid\mb_convert_encoding() in /app/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php:745
2017-08-31T22:27:03.789811+00:00 app[web.1]: Stack trace:
2017-08-31T22:27:03.789947+00:00 app[web.1]: #0 /app/index.php(36): SendGrid\Content->__construct('text/html', '<table style='b...')
2017-08-31T22:27:03.789971+00:00 app[web.1]: #1 {main}
2017-08-31T22:27:03.790084+00:00 app[web.1]:   thrown in /app/vendor/sendgrid/sendgrid/lib/helpers/mail/Mail.php on line 745

#### `index.php`

> require 'vendor/autoload.php';
header("Access-Control-Allow-Origin: *");
if(!(isset($_POST['email']) && isset($_POST['messageType']) && isset($_POST['projectName']) && isset($_POST['firstName']) && isset($_POST['lastName']) && isset($_POST['message']))){
	echo "Unable to process request";
	return;
}
$email = $_POST['email'];
$type = $_POST['messageType'];
$project = $_POST['projectName'];
$firstName = $_POST['firstName'];
$lastName = $_POST['lastName'];
$message = $_POST['message'];
echo "Got your data: ".$email.";".$firstName.";".$lastName.";".$project.";".$type.";".$message;
$from = new SendGrid\Email($firstName . " " . $lastName, $email);
$subject = $type == "Message" ? "www.teodorvecerdi.me | " . $type : "www.teodorvecerdi.me | " . $type . " | " . $project;
$to = new SendGrid\Email("Teodor Vecerdi", "teodor.vecerdi@gmail.com");
$content = new SendGrid\Content("text/html", "message");
$mail = new SendGrid\Mail($from, $subject, $to, $content);
$apiKey = 'API KEY';
$sg = new \SendGrid($apiKey);
$response = $sg->client->mail()->send()->post($mail);
echo $response->statusCode();
print_r($response->headers());
echo $response->body();

**What is wrong?**

#### Technical details:

* sendgrid-php Version: 6.0
* PHP Version: 7.1.9

**Comment by thinkingserious** [comment]
Looks like you need to [enable mbstring](https://devcenter.heroku.com/articles/php-support#extensions). See [here](https://stackoverflow.com/a/25632531) for more detail.

**Comment by TeodorVecerdi** [comment]
Thank you @thinkingserious ! It works now. I already enabled mbstring and did a composer update but nothing was downloaded and I thought that I did something wrong.

**Comment by gusbemacbe** [comment]
The package `simple_html_dom` is dead.

**Comment by thinkingserious** [comment]
Hi @gusbemacbe,

I'm not sure what the relevance of `simple_html_dom` is in this context. The fix here was to enable mbstring.

With Best Regards,

Elmer

**Comment by BerkhanBerkdemir** [comment]
If you are working with Heroku you need to add to your `composer.json` file

```yaml
{
  "require": {
    "ext-mbstring": "*"
  }
}

```

This comment added according from this [comment](https://github.com/sendgrid/sendgrid-php/issues/425#issuecomment-326439579)

**Comment by thinkingserious** [comment]
Thanks for the concrete example @BerkhanBerkdemir!

**Comment by mstahlmann** [comment]
I tried all of this an nothing is working.

**Comment by mstahlmann** [comment]
PHP Fatal error:  Uncaught Error: Call to undefined function SendGrid\\Mail\\mb_convert_encoding()

**Comment by thinkingserious** [comment]
Hello @mstahlmann,

Have you tried [this](https://stackoverflow.com/a/37441536)? Thanks!

**Comment by mstahlmann** [comment]
I did. Not sure why it is not working
 I’ll double check.

**Comment by thinkingserious** [comment]
Hi @mstahlmann,

[Here](http://php.net/manual/en/function.extension-loaded.php) is how you can check if an extension is loaded.

**Comment by mstahlmann** [comment]
It passes this test for the module in question. I’ll try ythe composer install again

**Comment by thinkingserious** [comment]
Thanks @mstahlmann.

**Comment by hgsadhrakiya** [comment]
What if we haven't used the composer in the project?
Can we use this API without composer?
