### ISSUE TITLE
Reply to should be a collection of email addresses.

### ISSUE THREAD

**Issue by shonjord** [sendgrid/sendgrid-php#428]
#### Issue Summary

We currently have this flow:

`Person 1` which belongs to the company sends an e-mail with `reply to` (`Person 1`, `Person 2`, `Person 3`... `Person N`) which also belongs to the company to `Person X` (which is not part of the company).

`Person X` replies this e-mail to the listed ones (`Person 1`, `Person 2`, `Person 3`... `Person N`) so in case any of the ones listed in the reply to field (`1, 2, 3`... `N`) is not present in the company or doesn't read the e-mail etc, the other ones are aware of the response, this is very crucial for us.

This way `Person X` doesn't have to know or write manually to who he/she should reply to, that should be automatic.

#### Steps to Reproduce

So currently the library accepts only one reply to instead of multiple, I think the implementation should be very easy and shouldn't affect the current flow of the API, since instead of:
```
{
    "reply_to": "test@example.com"
}
```

We suggest something like:

```
"reply_to":[
  {
     "email":"test@example.com"
  },
  {
     "email":"other@example.com"
  },
  {
     "email":"last@example.com"
  }
]
```

#### Technical details:

* sendgrid-php Version: master
* PHP Version: all

**Comment by shonjord** [comment]
@thinkingserious

**Comment by thinkingserious** [comment]
Thank you for taking the time to write this out for us!

**Comment by thinkingserious** [comment]
@shonjord,

In the mean time, as it may take some time for this to rise in the product backlog, how about using a catchall email address that forwards to the relevant parties?

With Best Regards,

Elmer

**Comment by mbernier** [comment]
I am curious if there is another way to make this work... Sorry if this is a repeat of a question asked previously - 

What if you make the "CC" param of the personalization to be `Person 1`, `Person 2`, `Person 3`... `Person N` ? This would have the same net-effect on a reply email, in that the customer's email application should make sure the reply always goes to everyone who is on the email in Reply-to and CC.

**Comment by shonjord** [comment]
@ogilliland can you take a look at the suggestion of @thinkingserious ? :) thanks.

**Comment by ogilliland** [comment]
The catch-all address suggested by @thinkingserious will work as a stopgap measure, but the disadvantage is that it will also fill up the inboxes of people on that mailing list who care about different email chains.

The CC solution on the other hand relies on the recipient clicking "reply-all" instead of just "reply", and takes away our ability to ensure delivery of the reply to all necessary parties.

**Comment by shonjord** [comment]
@thinkingserious any thoughts on what @ogilliland said?

**Comment by thinkingserious** [comment]
@shonjord,

I think you can customize the catch-all addresses in the same way you would customize what emails were included in the multi-reply-all. (e.g. Billing goes to X, Y, Z and Marketing goes to A, B, C, etc.)

**Comment by thinkingserious** [comment]
Thanks to @ogilliland, for the clarification!

**Comment by mbernier** [comment]
There is another, more involved, work around. If you wanted to, you use inbound parse to solve this by identifying the recipients of a specific email through a conversation identifier based email address at send time. By setting the reply-to email to something like "[conversation id here]@subdomain.mydomain.com", when someone replies the email is parsed by SendGrid and passed to you as data. Then, when you receive the reply via parse, look that conversation ID up and forward the response to those people, keeping the reply-to as the conversation ID email address.

This may not be ideal, but it does give you the opportunity to see and track all replies that come to the original email, while also making sure all of the appropriate people on the thread get the replies.

**Comment by joelstein** [comment]
See https://github.com/sendgrid/sendgrid-csharp/issues/339.
