### ISSUE TITLE
How Can I set unsubscribe link while sending email via API

### ISSUE THREAD

**Issue by kevalsbt** [sendgrid/sendgrid-php#429]
#### Issue Summary

Basically I would like to set a unsubscribe link under custom text while sending email via API.
Text would be "follow this link to be removed" (on this I want to set unsubscribe link).

I have enabled **Subscription Tracking** function from panel which displays unsubscribe link but I want to have my own link which I can place where I want.

#### I tried following combinations to set link

1. <% follow this link to be removed %>
2. < a href="[Unsubscribe]">follow this link to be removed < / a > (ignore white space around tag)
3. < a href="[unsubscribe]">follow this link to be removed< / a > (ignore white space around tag)
4. <%asm_preferences_url%> 

#### Code
$sendgrid = new SendGrid('API-KEY');

$email = new SendGrid\Email();
$email->setSmtpapiTos($strArray)
->setFrom($eml['from_email'])
->setFromName($eml['from_name'])
->setSubject($sub)
->setHtml($nl_html)
->setSubstitutions(array('[%email%]' => $strArray));

$result = $sendgrid->send($email);

I have chat with support team but they do not have necessary resources to provide this level of analysis.
What am I missing here, or do I have to set any additional setting from my panel?

#### Technical 

* sendgrid-php Version: master
* PHP Version: 5.x

**Comment by thinkingserious** [comment]
Hello @kevalsbt,

I believe your issue pertains to [this SDK](https://github.com/sendgrid/smtpapi-php). Could you please post your issue there?

Thanks!

With Best Regards,

Elmer
