### ISSUE TITLE
for loop multiple emails

### ISSUE THREAD

**Issue by lesh3000** [sendgrid/sendgrid-php#432]
#### Issue Summary
I try to send multiple emails using sendgrid library, it sends HTML emails
The first email is sent. However the following get error 400 if echo $response->status();
Using try-catch block no error is shown

eventually, I am using for loop but for a sake of simplicity I put here simpler example:

require 'sendgrid-php/sendgrid-php.php';
$sendgrid_apiKey = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';
 $subject='XXXXXXXXXXXXXXXXXXXXXX';
 
 $from = new SendGrid\Email("XXX XXXX", "d.lXXX@XXX.com");
 $to = new SendGrid\Email("dm sh", "lesXXXXXXXXX@yahoo.com");
  
    ob_start();
    require_once 'phpMailer/interview.php';
    $content = ob_get_contents();
    ob_end_clean();
    
  
  $body = new SendGrid\Content("text/html", $content);
  $mail = new SendGrid\Mail($from, $subject, $to, $body);
 
  $sg = new \SendGrid($sendgrid_apiKey);
  $response = $sg->client->mail()->send()->post($mail);
  
  
  
  $from = new SendGrid\Email("xx  xx x x", "xxxxnskix@oxxx.xxx");
 $to = new SendGrid\Email("xxx", "xxxx@gx.xxx");
  
    ob_start();
    require_once 'phpMailer/interview.php';
    $content = ob_get_contents();
    ob_end_clean();
    
  try{
  $body = new SendGrid\Content("text/html", $content);
  $mail = new SendGrid\Mail($from, $subject, $to, $body);
 // $mail->addReplyTo('exx@xxxx.co', 'xxxx xxxx');
  $sg = new \SendGrid($sendgrid_apiKey);
  $response = $sg->client->mail()->send()->post($mail); 
  }
  catch (Exception $e) {
    echo 'Caught exception: ',  $e->getMessage(), "\n";
}

Overall I wondering what is a right way to include HTML content into sendgrid email

**Comment by thinkingserious** [comment]
Hello @lesh3000,

Can you try the following after `echo $response->status();`?

`echo $response->body();`

Also, if it's a 400 error, that means it's likely an error relating to your API Key. Do you have this code (`$sg = new \SendGrid($sendgrid_apiKey);`) inside or outside of your loop?

Might be useful to check the value of $sendgrid_apiKey on the second call.

With Best Regards,

Elmer

**Comment by lesh3000** [comment]
Hello @thinkingserious;

Thank you so much for helping out.
Eventually ->body(); helped me to resolve the problem.
The issue was in ob_.

Many thanks!
