### ISSUE TITLE
v6 new Mail constructor

### ISSUE THREAD

**Issue by raulp** [sendgrid/sendgrid-php#433]
I want to express a possible issue/frustration with the new version.
The Mail class now requires 4 mandatory params. To me, that should never be the case. Why was that even implemented? What was the issue that was tried to be solved?
Consider my case, where I have to send a batch to 10,000 people, and all my classes are initializing the Mail object WAY before I even loop the email addresses.
I used to easily create a few Mail objects and set custom headers and such. Now, I have to find the first lead just to init the Mail class ... makes no sense.

I'm not sure if it's just me, but I'll stick to the old version for now, rather than use this counter-intuitive way of sending with the library. 

I can understand this for single emails maybe ... so you don't have to manually init all the classes and so on ... but that should have been a choice, not a forced option. My 2 cents.

I propose that those params be set back as optional.

**Comment by thinkingserious** [comment]
Hi @raulp!

Thank you so much for taking the time to provide some feedback and just in time as development on v7 of this library is underway.

Do you mind moving this conversation [here](https://github.com/sendgrid/sendgrid-php/issues/413)? Thanks!

With Best Regards,

Elmer

**Comment by raulp** [comment]
Oh, wonderful ... hope i can get some bandwidth, might even help with some PR's if possible.
Thanks !
