### ISSUE TITLE
PHP Mail Helper Refactor

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-php#434]
#### Issue Summary

An interface to easily interact with the `mail/send` endpoint of the [SendGrid v3 Web API](https://sendgrid.com/docs/API_Reference/api_v3.html).

The specification for this project is [here](https://github.com/sendgrid/sendgrid-php/blob/master/mail-helper-refactor.md) and the discussion around this specification can be found [here](https://github.com/sendgrid/sendgrid-php/issues/413).

#### Acceptance Criteria

All of the use cases [defined here](https://github.com/sendgrid/sendgrid-php/blob/master/mail-helper-refactor.md) are implemented and all corresponding tests are passing.

**Comment by COil** [comment]
Hi the rewrite is very welcome. When looking at this php class  `sendgrid/php-http-client/lib/SendGrid/Client.php` for example it looks like PH4 code, no access modifier declared, properties declared dynamically, etc...

**Comment by thinkingserious** [comment]
Please see [this comment](https://github.com/sendgrid/sendgrid-php/issues/568#issuecomment-356223737) regarding making parameters optional.

**Comment by thinkingserious** [comment]
Hello Everyone!

@COil @zanderwar @caseyw @izhukovich @Tzafra @senorgeno @vitya1 @Braunson @cbschuld @paoga87 @Taluu @mazanax @ninsuo @ianh2 @WadeShuler @jaimehing @KnightAR

Development on the SendGrid PHP Mail Helper Refactor is underway on [this branch](https://github.com/sendgrid/sendgrid-php/tree/v7). The example in `sendmail.php` is currently working on that branch.

The next step over the next few days is to implement the [Kitchen Sink example](https://github.com/sendgrid/sendgrid-php/blob/master/mail-helper-refactor.md#kitchen-sink---an-example-with-all-settings-used) and then implement the corresponding tests. I should be able to release v7.0.0 shortly afterwards to Packagist.

Your feedback during this home stretch is greatly appreciated! I want to make sure we have a solid v7.0.0 base from which to iterate on.

Thanks!

With Best Regards,

Elmer
