### ISSUE TITLE
Create a tutorial to deploy a simple Hello Email app on Heroku with PHP using this SDK

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-php#441]
Create a tutorial that explains how to create a simple Hello Email app and [deploy to Heroku](https://devcenter.heroku.com/articles/heroku-button).

The example should utilize best practices for storing credentials. By the end of the tutorial, the user should be able to send an email using their deployed app.

Please add the tutorial to USE_CASES.md.

**Comment by gabidavila** [comment]
I want to tackle this, but first I have a simple question, because it is bugging me. The issue asks for best practices for storing credentials while in [USE_CASES.md](USE_CASES.MD) you advocate for `require` on the library and not using composer. Why?

```php
<?php
// If you are using Composer
require 'vendor/autoload.php';

// If you are not using Composer (recommended)
// require("path/to/sendgrid-php/sendgrid-php.php");
```

**Comment by thinkingserious** [comment]
Hello @gabidavila,

Good catch, the `(recommended)` text should be next to the `// If you are using Composer` comment. Do you mind making a PR to fix that?

Thanks!

With Best Regards,

Elmer

**Comment by gabidavila** [comment]
Of course, will be there soon enough.

**Comment by mbernier** [comment]
@gabidavila how's it going? Anything we can do to help?

**Comment by childish-sambino** [comment]
Closing as this feels like more of a blog post than library documentation and use cases.
