### ISSUE TITLE
Create a tutorial to deploy a simple Hello Email app on Digital Ocean with PHP using this SDK

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-php#442]
Create a tutorial that explains how to create a simple Hello Email app and [deploy to Digital Ocean](https://www.digitalocean.com/community/tutorials/how-to-set-up-automatic-deployment-with-git-with-a-vps).

The example should utilize best practices for storing credentials. By the end of the tutorial, the user should be able to send an email using their deployed app.

Please add the tutorial to USE_CASES.md.

**Comment by gr8shivam** [comment]
Would love to take on this but need test accounts on SendGrid as well as DigitalOcean for this.

**Comment by thinkingserious** [comment]
Hi @gr8shivam,

You can obtain a free SendGrid account [here](https://sendgrid.com/free?source=sendgrid-php). For Digital Ocean, you can utilize their [free trial](https://cloud.digitalocean.com/registrations/new).

I hope that helps.

With Best Regards,

Elmer

**Comment by gr8shivam** [comment]
Already used the free trial + student promotion. 😆

**Comment by mbernier** [comment]
@gr8shivam how's it going? Anything we can do to help?

**Comment by childish-sambino** [comment]
Closing as this feels like more of a blog post than library documentation and use cases.
