### ISSUE TITLE
No content in the attachment

### ISSUE THREAD

**Issue by kumarshail** [sendgrid/sendgrid-php#446]
#### Issue Summary
When sending email from localhost apache server, the filename which is getting sent is correct, but there is no content in the file. The file size is 1KB.

#### Steps to Reproduce
```php
$from = new SendGrid\Email("pk", "some@example.com");
$subject = "Sending with SendGrid is Fun";
$to = new SendGrid\Email("sk", "some2@example.com");
$content = new SendGrid\Content("text/plain", "and easy to do anywhere, even with PHP");
$mail = new SendGrid\Mail($from, $subject, $to, $content);

$fileName = 'test.pdf';
$filePath = dirname(__FILE__);
$base64Data = base64_encode(file_get_contents($filePath.'/'.$fileName));

print_r($base64Data);

$attachment = new SendGrid\Attachment();
$attachment->setContent($base64Data);
$attachment->setType("application/pdf");
$attachment->setFilename('@'.$filePath .'/'.$fileName);
$attachment->setDisposition("attachment");
$attachment->setContentId("Balance Sheet");
$mail->addAttachment($attachment);


$apiKey = '*****************************************************************';
$sg = new \SendGrid($apiKey);

$response = $sg->client->mail()->send()->post($mail);
echo $response->statusCode();
print_r($response->headers());
echo $response->body();
```

#### Technical details:

* sendgrid-php Version: master (latest commit: [commit number])
* PHP Version: PHP 7.1.10-1+ubuntu17.04.1+deb.sury.org+1

**Comment by mbernier** [comment]
Could you please provide output from your print statements using a local file? 
I like to test with a logo from here: https://sendgrid.com/resource/brand/

**Comment by lalitvj** [comment]
Used same code. Seems to be working fine with the normal standard installation. Can you provide some output response?

![screen shot 2017-10-21 at 5 06 45 pm](https://user-images.githubusercontent.com/19746749/31851386-4d371648-b682-11e7-8d41-cc8635a29d3a.png)
