### ISSUE TITLE
Create a tutorial to create a Slack event integration with PHP using this SDK

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-php#447]
Create a tutorial that explains how to create a simple [integration with Slack](https://api.slack.com/events-api) that allows an email to be triggered based on some [defined event](https://api.slack.com/events).

The example should utilize best practices for storing credentials.

Please add the tutorial to USE_CASES.md.

**Comment by semijoelon** [comment]
I'll have a pull request submitted for this shortly.

**Comment by childish-sambino** [comment]
Closing as this feels like more of a blog post than library documentation and use cases.
