### ISSUE TITLE
Send PDF file attachment in Email using Sendgrid Web_API_v3

### ISSUE THREAD

**Issue by BhagyashreeCC** [sendgrid/sendgrid-php#472]
Hi,
I am new to sendgrid v3 API. I have latest library downloaded. I am able to send simple email using v3 API, but I am not getting end point to send pdf file attachment email using v3 API. Please help me out to resolve my issue.

Thanking you in advance.

**Comment by thinkingserious** [comment]
Hello @BhagyashreeCC,

Welcome to SendGrid!

Have you tried the example [here](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#attachments)?

With Best Regards,

Elmer

**Comment by BhagyashreeCC** [comment]
@thinkingserious  Thanks for quick and perfect solution.
Your help is really appreciable. :)

**Comment by FlaviuRadulescu** [comment]
Hello @thinkingserious 

do you have an example of how you can add multiple files (PDF) to the same email?

Also, what is the best solution to add to an email plain/text and HTML? I don't see an example in which I can add two mime types.

Thank you,
Flaviu

**Comment by thinkingserious** [comment]
Hello @FlaviuRadulescu,

For adding multiple attachments, please see [here](https://github.com/sendgrid/sendgrid-php/blob/master/examples/helpers/mail/example.php#L78).

You can use [`addContent`](https://github.com/sendgrid/sendgrid-php/blob/master/examples/helpers/mail/example.php#L75) to add additional contents.

I hope that helps!

With Best Regards,

Elmer

**Comment by Farangi** [comment]
Hey @thinkingserious can you please help me out:
I am currently sending Invoices through SendGrid using dyncamic templates, but i also i want to give receivers the option to download invoice as PDF. What is the best solution for that, and please keep in mind that i am using Node/Express backend, so kindly refer to js based docs.

**Comment by childish-sambino** [comment]
@Farangi Please open a new issue.
