### ISSUE TITLE
Set custom argument in an email using sendgrid v3 API

### ISSUE THREAD

**Issue by BhagyashreeCC** [sendgrid/sendgrid-php#473]
Hi, 
I want to set Custom Arguments for each email id while sending email using sendgrid v3 API. which can letter retrieve email status using that custom argument. Also It would be great if I can get reference for how can I get email status using sendgrid v3 API.

Thanks in Advance.

**Comment by thinkingserious** [comment]
Hi @BhagyashreeCC,

[Here is an example](https://github.com/sendgrid/sendgrid-php/blob/master/examples/helpers/mail/example.php#L47) for setting Custom Arguments.

You can obtain the email status in real time using our [Event Webhook](https://sendgrid.com/docs/API_Reference/Webhooks/event.html).

With Best Regards,

Elmer

**Comment by BhagyashreeCC** [comment]
Hi @thinkingserious ,

Thank you for the solution.. :)

**Comment by PyroxFyre** [comment]
I did the same thing as what you linked, but still not working. there is 2 methods to add custom args on $mail Object, but none of them work or at least, no custom args is shown in the response

**Comment by shwetha-manvinkurke** [comment]
@PyroxFyre we don't usually track closed issues. Could you open a new issue with details on what you are trying to do and your code snippet?
