### ISSUE TITLE
How to get each email id status using sendgrid v3 API

### ISSUE THREAD

**Issue by BhagyashreeCC** [sendgrid/sendgrid-php#478]
Hi,
I wanted to fetch each email id status using sendgrid v3 API -PHP (e.g. Delivered, Processed, Open, etc.).
Do I need to make any setting in my sendgrid account for the same?
Please help me to found solution.

Thanking in Advance.

**Comment by BhagyashreeCC** [comment]
HI,
I have enabled Event notification in my sendgrid account. also created .php file on my server to get required response from sendgrid. But when I hit "Test your Integration" button, I am getting "No Content" in response. I don't understand why? Please help me to resolve my issue.
Let me know If I need to change any settings in my account.

Thanks in Advance.

**Comment by mbernier** [comment]
Just to make sure I am following you here: 
- You have a script that will receive data from SendGrid's event webhook
- You are recording the data it receives?
- You gave SendGrid the URL
- You hit the Test Integration, and you receive an empty request? 

If all of this is true, please make sure that your script is accepting multipart-form data. The post is not a truly RESTful POST. If that still doesn't work, please try pointing your webhook setting for SendGrid to https://requestb.in (You will need to go there and set up a URL)

Once you are getting data from SendGrid's testing, post that here and we will see what else we can do to help!

**Comment by BhagyashreeCC** [comment]
Hi,

-  Yes, I am having below code
`<?php
$data = file_get_contents("php://input",
			                 false,
					stream_context_create(array(
						'http' => array(
							'method'  => 'POST',
					    	        'headers' => 'Content-Type: multipart/form-data'
							),
						)
					)
			     );
$events = json_decode($data, true);
`
- Yes, already written script to record the data in text file 
- Yes, https://mywebsite.com/parse_email_log.php is the url set in sendgrid's Mail settings > eveny notification
- Yes, I received empty request.

I hope that I am using multipart-form data in correct way which is mentioned in point 1
Following URL giving me "Ok" in response: 
http://mywebsite.com/index.php/report/requestbin

Please let me know if there is another solution.
Thanks in Advance.

**Comment by BhagyashreeCC** [comment]
http://mywebsite.com/index.php/report/requestbin 
having below code 
`function requestbin(){
		$result = file_get_contents('https://requestb.in/1c1uuql1');
		echo $result;
	}`

**Comment by thinkingserious** [comment]
Hello @BhagyashreeCC,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
