### ISSUE TITLE
Attach files to email from S3

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-php#480]
This should be added to the Mail helper method  (unless a new dependency is required, in that case describe the usage in the USE_CASES.md file), where the file that is attached can be sitting on an S3 bucket.

In most circumstances, for Spam detection reasons, it would be better to link to the file- however, there are legitimate use cases for attaching a file. Example: Receipt PDFs

**Comment by semijoelon** [comment]
I'll add an example of this to USE_CASES.md since it will use the [AWS SDK for PHP](https://aws.amazon.com/sdk-for-php/).
