### ISSUE TITLE
Attach files to email from Box.com

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-php#481]
This should be added to the Mail helper method  (unless a new dependency is required, in that case describe the usage in the USE_CASES.md file), where the file that is attached can be sitting in Box.com storage.

In most circumstances, for Spam detection reasons, it would be better to link to the file- however, there are legitimate use cases for attaching a file. Example: Receipt PDFs

**Comment by semijoelon** [comment]
I'll work on this issue.

**Comment by thinkingserious** [comment]
Thank you @semijoelon, it’s all yours!
