### ISSUE TITLE
Add CodeCov support to .travis.yml

### ISSUE THREAD

**Issue by mbernier** [sendgrid/sendgrid-php#541]
Issue Summary

Add these entries to the .travis.yml file so codecov reports show up!
https://github.com/codecov/example-php/blob/master/.travis.yml

**Comment by pxgamer** [comment]
I'm happy to do this.

**Comment by Rishabh04-02** [comment]
@pxgamer @mbernier I'm a new contributor, can I take up this issue?

**Comment by pxgamer** [comment]
@Rishabh04-02 I guess it's up to them, but fine by me. :+1:
