### ISSUE TITLE
Hacktoberfest: SendGrid Current Status

### ISSUE THREAD

**Issue by mbernier** [sendgrid/sendgrid-php#546]
## SendGrid DX team current status:
- Wow
- OMG
- THANK YOU

Hacktoberfest 2017 has completely blown us away. We have had over 900 pull requests from over 300 contributors all in the last 30 days. That is more PRs than we normally get in 2 years! 
We are actively working to review, comment, and/or merge as many PRs as we possibly can as quickly as we can.

We are currently working on “intaking” all the PRs that have come in, oldest first (we have about 400 remaining to go through). We are making sure that each PR we review is one we have a chance of merging - there have been a couple spammy items that came through. Due to the massive influx of requests so far, @thinkingserious and @mbernier have been working nights and weekends all month just to keep up! We’re not even mad, this is amazing!  
## Hey, that’s great for you - but what about my shirt!
If you have signed the CLA before 11/1, but haven’t had a PR merged yet, do not despair! We know we are behind on even just commenting on every PR to show you that we received it (something we typically do). If you submitted a mergeable (non-spam, actually adds value to the project) PR during October 2017, we will grant access to [this page](https://dx.sendgrid.com/swag) to redeem your shirt, sticker, and hacker pin. Next year, we will be sure to communicate this information sooner. We are sorry for any confusion we have caused. We appreciate those of you who have reached out to find out what’s going on! 

## What can I do to help move things along?
**Have you signed the CLA yet?** 
We can only merge items from contributors who signed the CLA

**Can you help another contributor?** 
If you can identify potential problems, add suggestions, or even leave a comment with your review of another PR (Looks good to me! Or I approve this change), that would help us review those PRs much faster, making it easier to get to your PR.

**Do you even write tests, friend?** 
If you see a place where we could have a test to validate a piece of functionality, add it in. We know We know! It’s just another PR we have to review and merge. You’re right, it is! However, the more tests we have, the earlier our CI tool can catch issues, saving us a review as well as back and forth time. 

@ankitjain28may, @bertuss, @dereckson, @gr8shivam, @jopanel, @kraigh, @lrtr, @luqmansungkar, @nalinbhardwaj, @pangaunn, @pxgamer, @qligier, @rparpa, @runz0rd, @samundra, @ssiddhantsharma, @thepriefy, @uppe-r

**Comment by ankitjain28may** [comment]
@mbernier Thanks for reviewing so much PRs and yes, i really like to connect to this organization and help you by making my contributions.

**Comment by pxgamer** [comment]
Thank you for the opportunity to contribute. :+1:

**Comment by mbernier** [comment]
@ankitjain28may We would love to have you as a part of the community - everything we do in our API libraries makes it easier for another developer to knock an item off their backlog. Things like tests, linter compliance, and even documentation/examples all make a HUGE difference for someone who has a job to get done! 

@pxgamer Thank you for trusting us with your time and your code. We have a mission to make sure that we are welcoming and that we give everyone a fair shake because while we are focused on making customer's lives better, we totally understand that open source contributions work like a resume. Contributing to a repo might get you a job in the future, or at least help with that process, and we would love to hear stories that being involved in our open source projects made a difference!

**Comment by nitish24p** [comment]
Thanks @mbernier @thinkingserious  .. Any idea when the tees will be shipped? I'd love to contribute to the node js SDK, if its ok.

**Comment by mbernier** [comment]
@nitish24p 
The hacktoberfest shirts are being counted and hopefully shipped in the next two weeks.

Outside of hacktoberfest, we always give a shirt to a ontributor's first non-hacktoberfest PR that is merged.

**Comment by ssiddhantsharma** [comment]
It's been a good time contributing to OS with your firm and the support we
(fellow developers) got from SendGrid was just phenomenal.

You guys gave us an incentive of Tees and Swag, and we worked to resolve
issues. I think it's been a great HacktoberFest for all of us, who have
actually given their time and contributed to your repos.

What I was thinking of, is promoting your firm on online media, because I
was flattered by your timely response on my PR's and the way you handled
the queries. In short, SendGrid people (The two guys who constantly used to
ping us on our mails about our PR's) did a great job.

So, I would like to dedicate a space for you and your team on my blog, my
all social media handles describing how my experience went working with you
this october.

I worked with other firms, with there PR's and issues but no one was as
good like SendGrid in terms of handling out Swag and giving sweet little
personal reviews on PR's.

So, the moment I will get the swag and the tees, I will go berserk on my
social media describing how this all went for me. Maybe, A Vlog too on my
youtube channel!

Thanks guys for making it great,
Looking forward to next year and meanwhile, reviewing the left over issues
on the repos.

**Comment by thinkingserious** [comment]
Thank you for the kind words @ssiddhantsharma!

We would love to learn more about your experience and possible future collaborations. Could you please schedule a meeting with my manager @mbernier [here](https://calendly.com/matt-bernier/hacktoberfest-follow-up/11-09-2017?back=1)? Thanks!

With Best Regards,

Elmer

**Comment by ssiddhantsharma** [comment]
Surely will do that. Eager to share my experience with him!

**Comment by ssiddhantsharma** [comment]
Hey team, any updates when we will be getting our swags!

<https://about.me/siddhantsharma?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>
Siddhant Sharma
about.me/siddhantsharma
<https://about.me/siddhantsharma?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>

**Comment by thinkingserious** [comment]
Hi @ssiddhantsharma,

I don't have an exact date, but our swag provider now has all of the new shirts, stickers and pins ready for distribution. You should be receiving an email from KotisDesigns with information on your swag shortly.

With Best Regards,

Elmer

**Comment by samundra** [comment]
Hi,

does it means we can still change the address for delivery ?

**Comment by thinkingserious** [comment]
Hi @samundra,

I'm not sure, I would have to check your particular order with our vendor.

Could you please email us at dx@sendgrid.com with your updated information and I can check with our vendor.

With Best Regards,

Elmer

**Comment by ankitjain28may** [comment]
@thinkingserious I didnt receive any mail, can you please let me know the status of my swag ?
