### ISSUE TITLE
Add the ability to impersonate a subuser

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-php#551]
Please see the [Python implementation](https://github.com/sendgrid/sendgrid-python/pull/314) for an example.

**Comment by stianpr** [comment]
Would be nice to get this in. We currently have to extend the SendGrid class to add the `on-behalf-of` header. And the documentation is clearly wrong because it states that one has to [prefix the username with `subuser_`](https://sendgrid.api-docs.io/v3.0/how-to-use-the-sendgrid-v3-api/on-behalf-of) which doesnt work. Should update the documentation also.

**Comment by thinkingserious** [comment]
Hi @stianpr!

Agreed! I can't wait until this reaches the top of the backlog.

**Comment by Jericho** [comment]
@stianpr I [asked about the "subuser_" prefix](https://github.com/sendgrid/sendgrid-csharp/issues/634#issuecomment-342010438) and [I was told](https://github.com/sendgrid/sendgrid-csharp/issues/634#issuecomment-342959047) that it's necessary. Your experience seem to indicate that it's not the case so I'm a little confused.

@thinkingserious It would be great if you could settle this question once and for all: is the `subuser_` prefix necessary or not?

**Comment by stianpr** [comment]
@Jericho @thinkingserious Well, during my testing and implementation of this it only worked without the `subuser_` prefix. It would be nice to clarify this and fix the documentation (or the API) so that we know what to use.

**Comment by thinkingserious** [comment]
@stianpr @Jericho,

You would replace subuser_ with the actual subuser name.

In our documentation (https://sendgrid.api-docs.io/v3.0/how-to-use-the-sendgrid-v3-api/on-behalf-of) we will be updating `on-behalf-of: subuser_<username>` to read as `on-behalf-of: <username>`.

Thanks!
