### ISSUE TITLE
Use Dotenv in examples

### ISSUE THREAD

**Issue by cmckni3** [sendgrid/sendgrid-php#556]
#### Issue Summary

Demonstrate and encourage the use of `.env` files being loaded through PHP and using `$_SERVER` or `$_ENV` to avoid race conditions. Will remove the need to have the .env files export.

See https://github.com/vlucas/phpdotenv

#### Steps to Reproduce

N/A

**Comment by samundra** [comment]
@cmckni3 I think it's not worth loading the complete library only for loading the env which can be done merely exporting a variable in the environment. Currently you can see the repository contains `.env.sample` that can be copied to `.env`. 

So from my side it's :-1:

**Comment by thinkingserious** [comment]
@cmckni3,

It would be useful to provide this demonstration in our USE_CASES.md file. Would you be up for that?

With Best Regards,

Elmer

**Comment by cmckni3** [comment]
That makes sense to me. I probably should have suggested something along those lines. I want to proliferate best practices on the development side.
