### ISSUE TITLE
Duplicate emails: 2 emails send for each 1 send

### ISSUE THREAD

**Issue by CostaC** [sendgrid/sendgrid-php#557]
#### Issue Summary

Emails are being sent twice.  I don't run this in a loop, I just send and exit.

I'm using the code specified at: 

https://github.com/sendgrid/sendgrid-php#without-mail-helper-class

The only changes I made to the code was adding my API key, and using the require() instead of the composer autoload method.

I also put an "exit;" after the "$response = ...." line to make sure the code isn't running twice.

I also tried sending to various email addresses  and 2 identical emails always arrive. 

#### Technical details:

* sendgrid-php Version: 5.4.2 (downloaded today from link in readme: http://dx.sendgrid.com/downloads/sendgrid-php/sendgrid-php-latest.zip )
* PHP Version: 5.6.25

**Comment by CostaC** [comment]
My code:

`$path = APP.'vendors'.DS.'sendgrid-php'.DS.'sendgrid-php.php';
include_once($path);


$request_body = json_decode('{
  "personalizations": [
    {
      "to": [
        {
          "email": "XXXXXXXXX@gmail.com"
        }
      ],
      "subject": "Sending with SendGrid is Fun"
    }
  ],
  "from": {
    "email": "info@XXXXXXXXXXX.com"
  },
  "content": [
    {
      "type": "text/plain",
      "value": "body"
    }
  ]
}',true);


$apiKey = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';
$sg = new \SendGrid($apiKey);

$response = $sg->client->mail()->send()->post($request_body);
exit;
`

**Comment by ankitjain28may** [comment]
@CostaC hi, What is `APP`, `DS` in `$path = APP.'vendors'.DS.'sendgrid-php'.DS.'sendgrid-php.php';`

**Comment by CostaC** [comment]
APP is the path to my app.  That's not the problem because the emails are being sent, therefore the include path is correct.

**Comment by thinkingserious** [comment]
Hi @CostaC,

I don’t see anything obvious. What does the code that runs the above snippet look like?

With Best Regards,

Elmer

**Comment by CostaC** [comment]
This code is the only code in a test function (was testing Sendgrid API since I usually use SMTP which sends 1 email without issues).  

Since this is the only place I call the Sendgrid API code and I have an exit directly after the send(), there is no way this function is being called twice.  I'm on my dev machine so this is not production code.  Again, sending via SMTP works fine.

I intentionally tested it this way to isolate the problem as much as possible.

**Comment by thinkingserious** [comment]
How are you running the code?

**Comment by CostaC** [comment]
After some digging, it's not the Sendgrid code.   I tried a raw curl POST to requestb.in  and it's receiving 2 POSTs even though I have an `exit;` after the curl_exec().  Very weird.

**Comment by thinkingserious** [comment]
Thanks for the follow up @CostaC!

**Comment by ruqeebak** [comment]
SendGrid issue: Why am I receiving duplicate copies of email messages, and how do I stop it? I am not using curl request....
Help asap
Thanks

**Comment by thinkingserious** [comment]
Hello @ruqeebak,

What method are you using to send your emails?

**Comment by ruqeebak** [comment]
Hello @thinkingserious 
Here is my code for sending mail...

  $message = '<html><body>';
    $message .= '<table rules="all" style="border:1px solid #666;" cellpadding="10">';
    $message .= "<tr><td style='border:1px solid #666;border-collapse:collapse;'><strong>Name </strong> </td><td style='border:1px solid #666;border-collapse:collapse;'>" . trim($name) . "</td></tr>";
    $message .= "<tr><td style='border:1px solid #666;border-collapse:collapse;'><strong>Contact </strong> </td><td style='border:1px solid #666;border-collapse:collapse;'>" . trim($mobile) . "</td></tr>";
    $message .= "<tr><td style='border:1px solid #666;border-collapse:collapse;'><strong>Email Id </strong> </td><td style='border:1px solid #666;border-collapse:collapse;'>" . trim($email) . "</td></tr>";
    $message .= "<tr><td style='border:1px solid #666;border-collapse:collapse;'><strong>City  </strong> </td><td style='border:1px solid #666;border-collapse:collapse;'>" . trim($city) . "</td></tr>";

    $message .= $datee;
    $message .= "</table>";
    $message .= "</body></html>";

    $body = $message;  

    $from = new Email("Avant Enquiry", "d*****@****.co.in");
    
    $to = new Email(null, "p****@***.co.in");
    $content = new Content("text/html", "$body");
    $mail = new Mail($from, $sub, $to, $content);
    
    $apiKey = 'SG.NO*****';
    $sg = new \SendGrid($apiKey);

    $request_body = $mail;
    $response = $sg->client->mail()->send()->post($request_body); 

Please check and let me know.
Thanks ....

**Comment by thinkingserious** [comment]
Hello @ruqeebak,

As is, this code should only send one email. I think the issue may be that this code is getting called twice. Can you share the logic of the calling code?

With Best Regards,

Elmer

**Comment by ruqeebak** [comment]
Hello,

Thanks for your response,
This code is in Mail_send.php file, and I am calling this code through AJAX call.

Here is AJAX method ..

$.ajax({
            type: "POST",
            url: "Mail_send.php",
            data: { formname: formname, name: name, mobile: mobile, email: email, city: city, date: date },
            datatype: "html",
            success: function(result){
            	
                
            },
            error: function(result) {
            	
            }
        });

I am calling this ajax method only once, on click event of button.

Please check and let know
Thanks.

**Comment by thinkingserious** [comment]
Hello @ruqeebak,

I suspect the click event is being triggered twice. [Here is some guidance](https://stackoverflow.com/questions/6731894/click-event-is-calling-twice-in-jquery) on how to debug.

With Best Regards,

Elmer

**Comment by NealBozeman** [comment]
This issue happened to me after upgrading to PHP7. I'm still trying to figure out the cause.

**Comment by thinkingserious** [comment]
Hi @NealBozeman,

Do you mind sharing the relevant source code? 

Also,

What version of this SDK are you using?
Has nothing changed other using PHP 7?

Thanks!

With Best Regards,

Elmer

**Comment by campgurus** [comment]
I have this issue with a dynamic template from SendGrid that am calling in Express.

In calling the api, I loop through a list of users and send emails out to each of them. Usually 1-3 of these users will get the email twice or three times and it is not always the same user.

Here is the code that sends the mail:

```
// POST new act route 
router.post('/', auth.required, async (req, res, next) => {
  const now = new Date();
  // return last created Act
  result = await Act
    .query()
    .where('users_id', req.user.id)
    .orderBy('created_at', 'desc')
    .limit(1);
  
  console.log('in post new act route, this is the last act of user ', req.user.id, ': ', result);
  console.log('in post new act route, this is the start of today ', req.user.id, ': ', now.setHours(0,0,0,0));

  // conditional to disable if last Act.created_at == Today

  if(result.length === 0 || result[0].created_at.getTime() <= now.setHours(0,0,0,0)) {
    await Act.query()
    .insert({
      deed: req.body.act.deed,
      users_id: req.body.act.userId 
    }) 


    // return other members of a user's groups
    let groups_members = await knex.raw(`SELECT DISTINCT users.id, users.email, users.username FROM users JOIN memberships ON users.id = memberships.users_id WHERE memberships.groups_id IN (SELECT memberships.groups_id FROM memberships WHERE memberships.users_id = ${req.user.id})`);
  
    console.log('groups members are: ', groups_members.rows)

    console.log('sending email re new act')
    let recipients = groups_members.rows.filter(function(member) {
      return member.id !== req.user.id;
    });
    let actor = await User.query().findById(req.user.id)
    console.log('actor is :', actor.username)
    console.log("recipients is: ", recipients)
    console.log("recips length is: ", recipients.length)

    for (let i = 0; i < recipients.length; i++) {
      console.log('current recipient is: ', recipients[i].email)
      const msg = {
        from: "darius@writerboards.com",
        template_id: 'd-817cf045347d47689410854740fba13a',
        personalizations: [{
            to: { email: recipients[i].email },
            dynamic_template_data: {
              subject: "Someone just met their daily goal!",
              recipient_name: recipients[i].username, 
              actor_name: actor.username,
              action_name: req.body.act.deed,
              button_url: 'https://writerboards.com',
            },
        }],
        
      };
      if (process.env.NODE_ENV === 'production') {
        let sendResult = await sgMail.send(msg);
        console.log(sendResult);
      } else {
        console.log('not sending message in this environment: ', process.env.NODE_ENV)
      }
    }

  } else {
    res.json ({
      "message": "This user already acted today."
    });
  }
  
  // client.track({
  //   event: 'Act created',
  //   userId: req.user.id,
  //   properties: {
  //     body: req.body.post.body
  //   }
  // });

  res.json({
    success: true, message: 'ok' 
  });   // respond back to request
});
```
