### ISSUE TITLE
Template email with personalization causing 400 status

### ISSUE THREAD

**Issue by koficypher** [sendgrid/sendgrid-php#559]
#### Issue Summary

Using a personalization to send to add a substitution tag in my function gives the following error
{"errors":[{"message":"Additional property type is not allowed.","field":"personalizations.0.to.0.type","help":null},{"message":"Additional property value is not allowed.","field":"personalizations.0.to.0.value","help":null},{"message":"Invalid type. Expected: string, given: object.","field":"subject","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.subject"},{"message":"Invalid type. Expected: object, given: string.","field":"content.0","help":null}]}

#### Steps to Reproduce

  public function sendPasswordReset($email,$special_link)
  {
    $from = new SendGrid\Email("Ushipex", "system@unitedshippingexpress.com");
    $to = new SendGrid\Email(null,$email);
    $subject = "Password Reset";
    $content = new SendGrid\Content("text/html", "Thank you for using Ushipex");
    $mail = new SendGrid\Mail($from,$to,$content,$subject);
    $mail->personalization[0]->addSubstitution("-speciallink-", $special_link);
    $mail->setTemplateId("xxxxxxxxxxxxxxxxxx");

    $apiKey = $this->apiKey;
    $sg = new \SendGrid($apiKey);

        try {
           $response = $sg->client->mail()->send()->post($mail);
              } catch (Exception $e) {
                 echo 'Caught exception: ',  $e->getMessage(), "\n";
              }

                echo $response->statusCode();
                print_r($response->headers());
                echo $response->body();
  }

#### Technical details:
*used the sdk to create my own wrapper in codeigniter

**Comment by thinkingserious** [comment]
Hello @koficypher,

Can you please provide the JSON request body, per the instructions [here](https://github.com/sendgrid/sendgrid-php/blob/master/TROUBLESHOOTING.md#request-body) under the heading "Viewing the Request Body"? My guess is that one of your input variables is missing.

With Best Regards,

Elmer

**Comment by ZMelo-Sendgrid** [comment]
Hello @koficypher 

We are just reaching out to see if you still need assistance with your issue.

Thanks,
Zach

**Comment by thinkingserious** [comment]
Please feel free to re-open if you still need assistance @koficypher. Thanks!
