### ISSUE TITLE
No mail sent when using 2 personalizations

### ISSUE THREAD

**Issue by josephernest** [sendgrid/sendgrid-php#561]
When I do this, everything works, i.e. mail sent to `test2@example.com` and bcc to `test3@example.com`:

```
$from = new SendGrid\Email(null, "test1@example.com");
$to = new SendGrid\Email(null, "test2@example.com");
$bcc = new SendGrid\Email(null, "test3@example.com");
$content = new SendGrid\Content("text/plain", "Hello %you%. Bye");
$mail = new SendGrid\Mail($from, $subject, $to, $content);
$contenthtml = new SendGrid\Content("text/html", "<strong>Hello %you%</strong>.<br>Bye");
$mail->addContent($contenthtml);
$mail->personalization[0]->addSubstitution("%you%", "Bob");
$mail->personalization[0]->addBcc($bcc);

$response = (new \SendGrid($sendgridapikey))->client->mail()->send()->post($mail);
```

**However, when I do the following, no mail is sent to anybody. Why?**

```
$from = new SendGrid\Email(null, "test1@example.com");
$to = new SendGrid\Email(null, "test2@example.com");
$bcc = new SendGrid\Email(null, "test3@example.com");
$content = new SendGrid\Content("text/plain", "Hello %you%. Bye");
$mail = new SendGrid\Mail($from, $subject, $to, $content);
$contenthtml = new SendGrid\Content("text/html", "<strong>Hello %you%</strong>.<br>Bye");
$mail->addContent($contenthtml);
$mail->personalization[0]->addSubstitution("%you%", "Bob");

$pers1 = new SendGrid\Personalization();   // NEW PERSONALIZATION
$pers1->addBcc($bcc);
$pers1->addSubstitution("%you%", "Alice");
$mail->addPersonalization($pers1);      // IS THE ORDER WRONG?

$response = (new \SendGrid($sendgridapikey))->client->mail()->send()->post($mail);
```

**Comment by thinkingserious** [comment]
Hello @josephernest,

It looks like you need to define a to address for the second personalization. I could tell you for sure if you tell me what the JSON looks like before you make the API call, like [so](https://github.com/sendgrid/sendgrid-php/blob/master/examples/helpers/mail/example.php#L171).

[Here](https://github.com/sendgrid/sendgrid-php/blob/master/examples/helpers/mail/example.php#L22) is a full example of sending to multiple personalizations that I hope will help.

With Best Regards,

Elmer

**Comment by josephernest** [comment]
Here is what I wanted to do: I wanted to send an email, from PHP:

    From: myself@gmail.com
    To: recipient@yahoo.com

But as I send it from PHP, I won't see it in my usual mailbox (Gmail), so I finally did:

    From: myself@gmail.com
    To: recipient@yahoo.com
    Bcc: myself@gmail.com

**But** I wanted that 

1. Recipient receives this:

    From: myself@gmail.com
    To: recipient@yahoo.com
    ContentHTML:  ...........  <img src="myserver.com/trackpixel.jpg?id=recipient">

2. I receive this in my Gmail inbox:

    From: myself@gmail.com
    To: recipient@yahoo.com
    Bcc: myself@gmail.com
    ContentHTML:  ...........  <img src="myserver.com/trackpixel.jpg?id=ANOTHERCODEHERE!">

Any idea how to do this @thinkingserious?

**Comment by thinkingserious** [comment]
Hi @josephernest,

I think the problem here is that we do not allow duplicate emails in the payload. Perhaps you can do:

`myself@example.com`
`myself+somelabel@example.com`

With Best Regards,

Elmer

**Comment by josephernest** [comment]
Thanks for your answer @thinkingserious. I've tested with another email but still I can't have this working:

1. Recipient receives this:

        From: myself@gmail.com
        To: recipient@yahoo.com
        ContentHTML:  ...........  <img src="myserver.com/trackpixel.jpg?id=recipient">

2. I see this in my Gmail inbox:

        From: myself@gmail.com
        To: recipient@yahoo.com
        Bcc: myself@gmail.com
        ContentHTML:  ...........  <img src="myserver.com/trackpixel.jpg?id=ANOTHERCODEHERE!">

**Comment by thinkingserious** [comment]
Hi @josephernest,

I'm not quite sure about this one so I've added this to my backlog for further review.

In the mean time, you might want to reach out to our [support team](https://support.sendgrid.com) for a likely faster response as I don't believe this is a SDK issue.

With Best Regards,

Elmer

**Comment by jonleslalom** [comment]
i think this might be an issue with the API, as I'm running into the email not sending if i have a bcc recipient along with a to recipient (using the C# SDK) as well

**Comment by thinkingserious** [comment]
Thanks for the confirmation @jonleslalom! Could you please also reach out to our [support team](https://support.sendgrid.com/) for help on this?

**Comment by jonleslalom** [comment]
@thinkingserious shoot! forgot to update my comment. I was actually able to get it to work - I was using it incorrectly: I was adding a new personalization similar to the OP, but when you add a personalization with only a BCC entry, the email won't send. The SDK itself could be cleaned up in my opinion, but if you instead add the bcc to mail.personalization[0], it works.

**Comment by thinkingserious** [comment]
Thanks @jonleslalom!

We are working on cleaning up the SDK right now and we love your opinion. If you have a moment, please check out [the proposal](https://github.com/sendgrid/sendgrid-php/issues/413).

With Best Regards,

Elmer

**Comment by TakesTheBiscuit** [comment]
@josephernest 
Did you check out https://github.com/sendgrid/sendgrid-php/blob/7d2540d168b8fbe4d4642243fa7f85decfd471ea/examples/helpers/mail/example.php#L120-L124 ?

To me it looks like you do the above then attach to the mail with:
```
    $mail->setMailSettings($mail_settings);
```
?

**Comment by TakesTheBiscuit** [comment]
Or
```
$request_body = json_decode('{
  "email": "email@example.com", 
  "enabled": false
}');
$response = $sg->client->mail_settings()->bcc()->patch($request_body);
echo $response->statusCode();
echo $response->body();
print_r($response->headers());
```

**Comment by thinkingserious** [comment]
@josephernest,

Were you able to get things going?

**Comment by adamreisnz** [comment]
I seem to be running into a similar problem, where even if using `foo+test@bar.com` I only ever get one of the emails.

**Comment by childish-sambino** [comment]
@adamreisnz Recommend opening a new issue to further debug this since it's a couple years old. That said, I wouldn't trust plus-addressing for testing purposes. SendGrid does not support duplicate address in a single personalization.

**Comment by adamreisnz** [comment]
I think it's working fine, but we're probably running into the following: https://groups.google.com/forum/m/#!topic/gmail-users/06i04ievzSg

I'll leave that here for anyone else finding this thread and running into the same issue.

Can you tell me if when using a single email request with multiple personalizations, does Sendgrid send out the messages with unique message ID's or with the same message ID?

From testing, I observed that if we use a dynamic subject line, the emails all arrive as expected. When we use the same subject line, then even if we use different email addresses (which get redirected to the same inbox), only one of them will show up.

It's probably gmail doing some filtering.
