### ISSUE TITLE
Get notifications via email when an email is opened

### ISSUE THREAD

**Issue by josephernest** [sendgrid/sendgrid-php#562]
SendGrid can track when the emails are opened:

[![enter image description here][1]][1]

How to get a notification (via email) **when emails are opened**, for which the recipient is different to `myself@gmail.com`? (I don't want to receive a notification when *I open* my own emails sent to myself as BCC).

Do I need to use the SendgridAPI? How? Can I ask Sendgrid to send a notification? (To my server, who will send the notification? To something else?)

  [1]: https://i.stack.imgur.com/8d2Zb.jpg

**Comment by josephernest** [comment]
Solved with *Dashboard > Settings > Mail settings > Event notification > HTTP POST URL*.

**Comment by thinkingserious** [comment]
Thanks for posting the solution @josephernest!
