### ISSUE TITLE
Enable tracking for a specific email, even if Settings > Tracking > Open Tracking is disabled

### ISSUE THREAD

**Issue by josephernest** [sendgrid/sendgrid-php#563]
I disabled `Settings > Tracking > Open Tracking` because I don't need it for most emails. (It would modify my email content by adding a tracking pixel, which I don't want enabled for all emails):

![](https://i.stack.imgur.com/KmQ0p.jpg)

**How to enable tracking for a specific email sent via sendgrid-php?**

    $tracking_settings = new SendGrid\TrackingSettings();
    $open_tracking = new SendGrid\OpenTracking();
    $open_tracking->setEnable(true);
    $tracking_settings->setOpenTracking($open_tracking);
    $mail->setTrackingSettings($tracking_settings);

Is this the right way to do it?

**Comment by thinkingserious** [comment]
That looks good to me @josephernest. Please let us know if you run into any trouble.

**Comment by josephernest** [comment]
@thinkingserious Confirmed working.

**Comment by thinkingserious** [comment]
Thanks for the follow up @josephernest!
