### ISSUE TITLE
Sendgrid issue with personalization in V2

### ISSUE THREAD

**Issue by morazain** [sendgrid/sendgrid-php#567]
#### Issue Summary
I have a simple example of trying to send personalized  emails using substitution in V2.
I created the php program below and get the following output. No emails are sent and the response appears to be empty.

****Output****
Header
{"to":["guy@morazain.com","guy.morazain@gmail.com"],"sub":{"|name|":["Guy","Gaston"],"|password|":["1234","4321"]}}
Content:
Dear |name|,

The information you requested is below
passord: |password|
Params:
Array ( [from] => info@morazain.com [subject] => PHP Test [html] =>
Dear |name|,

The information you requested is below
passord: |password|
[x-smtpapi] => {"to":["guy@morazain.com","guy.morazain@gmail.com"],"sub":{"|name|":["Guy","Gaston"],"|password|":["1234","4321"]}} )
request:https://api.sendgrid.com/api/mail.send.json
print response:

So what am i doing wrong?

****code****
attached
[test2.zip](https://github.com/sendgrid/sendgrid-php/files/1565608/test2.zip)

**Comment by thinkingserious** [comment]
Hello @morazain,

v2 support using this SDK is no longer supported. I recommend upgrading to the latest version of this SDK, which supports v3 of our API. While v2 is not deprecated, it will not receive any new features or SDK support.

I will leave this issue open in case someone in the community who is still using v2 may have some insight.

With Best Regards,

Elmer

**Comment by morazain** [comment]
Unfortunately I cant get V3 to send out even the simplest email. 

I took to the example in your docs, and it does not send out an email.

the output i get is:  0Array ( [0] => )

see attached code
[testV3.zip](https://github.com/sendgrid/sendgrid-php/files/1572833/testV3.zip)

ps: i reported this in 566

**Comment by thinkingserious** [comment]
Thanks @morazain,

I will respond on issue 566

**Comment by morazain** [comment]
I have succeeded in creating a test program in PHP using the V3.
Attached. 
[test3m.zip](https://github.com/sendgrid/sendgrid-php/files/1576792/test3m.zip)
