### ISSUE TITLE
Other API (Contacts, Campaigns...)

### ISSUE THREAD

**Issue by Chev12** [sendgrid/sendgrid-php#572]
Hi, it's unclear to me if this project includes support for other API than the Send Mail. Does it ? Couldn't find any Roadmap either.

**Comment by thinkingserious** [comment]
Hello @Chev12,

You can find basic support for all of our endpoints [here](https://github.com/sendgrid/sendgrid-php/blob/master/USAGE.md). Full documentation is located [here](https://sendgrid.com/docs/API_Reference/api_v3.html).

I hope that helps!

With Best Regards,

Elmer
