### ISSUE TITLE
Support: Email actions Markup for Gmail and Google Inbox

### ISSUE THREAD

**Issue by simonflore** [sendgrid/sendgrid-php#579]
#### Issue Summary

I'm trying to enable Email actions for Gmail and Google Inbox  - [documentation here](https://developers.google.com/gmail/markup/actions/actions-overview) - which should be pretty basic. It appears due to the fact that Sendgrid enforces [Quoted-Printable](https://en.wikipedia.org/wiki/Quoted-printable) 

#### Steps to Reproduce

1. Send an email with the REST Api v3 and add email action to your source
2. Open source in Gmail and paste in Email Markup Tester to detect Email actions
3. No actions found

Gmail has 26% of the email clients market share and this feels like something Sendgrid should address. Are there any ways to work around this?

#### Technical details:

* sendgrid-php Version: master 
* PHP Version: 7.1

**Comment by simonflore** [comment]
Btw, I'm aware this isn't really related to the PHP Library, but your support service directed me to Github if I wanted feedback from Sendgrid Engineering.

**Comment by thinkingserious** [comment]
Hi @simonflore,

I don't know what the answer to this is, but I agree with you that it would be awesome to support this. I'm not sure if it's something we can do via the SDK, but I've added it to our backlog for further investigation. 

Do you mind sharing the source code you were using for your tests?

Thanks!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Thanks for taking the time on clarifying this, I'm passing this along to our product team.

**Comment by simonflore** [comment]
@thinkingserious Any idea if this is something to be considered?

**Comment by thinkingserious** [comment]
@simonflore,

It's on the product teams radar, but to gain priority we need more voices expressing a need/want for this feature. If you happen to know anyone else who may benefit, please encourage them to submit feedback.

With Best Regards,

Elmer

**Comment by nagi603** [comment]
Hi @thinkingserious ,

We also ran into this, and are considering replacing sendgrid with frankly anything else that can provide this feature, as other alternatives would be of magnitudes more work, plus of course would require extra work from the users which is never a good thing.

Regards,
 Balázs András Nagy

**Comment by thinkingserious** [comment]
Thanks for adding in your vote @nagi603!

**Comment by simonflore** [comment]
@thinkingserious Pretty sure this isn't the place to get those votes and it's something your product team should be able to get their head around.

**Comment by thinkingserious** [comment]
Hello @simonflore,

Every vote added here is passed along to our product team. 

For a more direct vote, a submission to our feedback form at SendGrid.com is an option.

With Best Regards,

Elmer

**Comment by J-Gonzalez** [comment]
Also adding a "vote" here as we are trying to implement this but are unable to using Sendgrid. The QuotedPrintable issue is what's causing any Email Markup code to be ignored by Gmail.

**Comment by thinkingserious** [comment]
Thanks @J-Gonzalez!

**Comment by kylearoberts** [comment]
Hello @simonflore @J-Gonzalez @nagi603 

I'm part of the support team and tested this issue out myself. I used the following in my content:

```
    <html>
    <head>
      <title></title>
      <script type="application/ld+json">
      {
        "@context": "http://schema.org",
        "@type": "EmailMessage",
        "potentialAction": {
          "@type": "ViewAction",
          "target": "https://watch-movies.com/watch?movieId=abc123",
          "name": "Watch movie"
        },
        "description": "Watch the 'Avengers' movie online"
      }
      </script>
    </head>
    <body>
    <div itemscope itemtype="http://schema.org/EmailMessage">
      <div itemprop="potentialAction" itemscope itemtype="http://schema.org/ViewAction">
        <link itemprop="target" href="https://watch-movies.com/watch?movieId=abc123"/>
        <meta itemprop="name" content="Watch movie"/>
      </div>
      <meta itemprop="description" content="Watch the 'Avengers' movie online"/>
    </div>
    </body>
    </html>
```

This is one of the examples from [Googles docs](https://developers.google.com/gmail/markup/reference/go-to-action) and it worked. You can see it [here](https://content.screencast.com/users/k.r.sg/folders/Jing/media/00f31239-89c3-45d8-9dd4-541fde28128d/00000450.png).

Could I get some examples of how you are trying to use this so I can run further testing and get to the bottom of this issue? If I could get some full examples like mine it would really help.

Thank you in advance.

Kyle

**Comment by doctorby** [comment]
@kylearoberts, I tried to send the same content using sendgrid web-app transactional template and didn't get any luck.

**Comment by kylearoberts** [comment]
Hey @doctorby 

I ran some tests and think I figured out what is going on in the example you gave. I tested in both our Legacy Templates and Transactional Templates and found that in Google's new Gmail UI the code does not work, but in the Old UI it does work.

[Here](https://content.screencast.com/users/k.r.sg/folders/Jing/media/3dd477cb-f5d6-4733-bea9-549a477a1007/00000453.png) is an example of the new UI.
[Here](https://content.screencast.com/users/k.r.sg/folders/Jing/media/5ff3430b-df2e-48c4-a210-c596d7d305d6/00000454.png) is an example of the old UI.

So with this in mind the issue may need to be brought up to Google to get them to support it in the new UI. I can also say this does not work in [Inbox](https://content.screencast.com/users/k.r.sg/folders/Jing/media/82e6256f-a232-46cb-9b28-9f577e6abd80/00000455.png).

**Comment by kylearoberts** [comment]
@doctorby 

Still trying to figure out why it would be different in your test. I am guessing you used the same template data/content I did? Did you do a v2 call or v3, or SMTP? There should not be an issue/difference with a trial account. Let me know what happened with your further tests. I'll retest and see if I can come up with some variations.

**Comment by doctorby** [comment]
@kylearoberts 
Yes, i used the same. [screenshot](https://www.screencast.com/t/S7kEtfxzupa)
and sent template from sendgrid.com Preview & Test page.

**Comment by kylearoberts** [comment]
@doctorby 

I just want to make sure I have things correct. Were you ever able to get things to work in the new Gmail? I know I was not and it looks like we are running the same test.

**Comment by doctorby** [comment]
@kylearoberts I found that it works in the new gmail, but only on focus. I have an invitation with a working RSVP action. [screenshot](https://www.screencast.com/t/PmkjUAsHc)

**Comment by doctorby** [comment]
@kylearoberts, I don't have more info, this is a letter from google calendar. Just to prove that the markup works in a new design.

**Comment by kevinnwang98** [comment]
@kylearoberts 
Just wanted to check if you guys are supporting this feature now, Im running into the same issue with adding EmailAction mark-ups.

**Comment by epopov** [comment]
Have same issue.

**Comment by kylearoberts** [comment]
@kevinnwang98 @epopov 
I just want to confirm that you have registered with Google for this feature. In testing we found we had to register to get things to work. https://developers.google.com/gmail/markup/registering-with-google

**Comment by epopov** [comment]
To register you need to send them emails from actual production server. How
I can do that if it doesn't work until I registered?

**Comment by thinkingserious** [comment]
Hi @epopov,

Have you tried filling out [their form](https://docs.google.com/forms/d/e/1FAIpQLSfT5F1VJXtBjGw2mLxY2aX557ctPTsCrJpURiKJjYeVrugHBQ/viewform?pli=1)?

With Best Regards,

Elmer

**Comment by eshanholtz** [comment]
Closing as this was marked as a non-library issue.

**Comment by noway** [comment]
Yeah, there's a catch 22 with Registering with Google. We need the integration to work in order to develop and test, but they require a production-ready email in order to enable integration?

What a joke, not sure what Google is thinking. How would I send a production email from an x@gmail.com account? We are using GSuite, to begin with, we don't have those, and it's not like you can connect x@gmail.com account with Sendgrid with proper DKIM/SPF.

BTW here's the registration form. I don't have any issue with giving them all that info but how would I send them a correct email markup email without being able to test it first. https://docs.google.com/forms/d/e/1FAIpQLSfT5F1VJXtBjGw2mLxY2aX557ctPTsCrJpURiKJjYeVrugHBQ/viewform?pli=1

**Comment by noway** [comment]
Nvm, you can just send an email to yourself, so if you have access to `user@acme.com` and `acme.com` is connected to both GSuite and Sendgrid you should be able to test.
