### ISSUE TITLE
You're not a wizard harry!

### ISSUE THREAD

**Issue by zanderwar** [sendgrid/sendgrid-php#581]
This package feels a little unloved and rushed, given the fact that everything runs through `__call` on `\SendGrid\Client` and return's a `\SendGrid\Response`.. it provides very little in the way of making it developer friendly.

I would much rather, at the very least, see the following all over `Client` 

```
/**
 * Client
 * @method \SendGrid\Response contactdb()
 * @method \SendGrid\Response mail()
 * @method \SendGrid\Response etc()
 */
```

and a greater improvement would be to define individual response objects and lose the magic

**Comment by thinkingserious** [comment]
We agree @zanderwar and an update is underway. [I would love to get your feedback](https://github.com/sendgrid/sendgrid-php/issues/434). Thanks!

**Comment by thinkingserious** [comment]
Refer to #434
