### ISSUE TITLE
Not getting emails 

### ISSUE THREAD

**Issue by Paulens007** [sendgrid/sendgrid-php#582]
Hello! im new at programing and everything soo, im having this problem on sendgrind and wordpress and woocommerce, i'm not getiing mails (then i make order, in my online shop), and i  i tried everything .... maybe you know how to fix ? check photos i screenshoted my errors

https://imgur.com/a/x8e6i

`
### WordPress Environment ###

Home URL: http://technika.onlinewebshop.net
Site URL: http://technika.onlinewebshop.net
WC Version: 3.3.3
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.33
PHP Post Max Size: 20 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.7.20
Max Upload Size: 15 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ❌ wp_remote_post() failed. Contact your hosting provider. cURL error 7: Failed to connect to www.paypal.com port 443: Connection refused
Remote Get: ❌ wp_remote_get() failed. Contact your hosting provider. cURL error 7: Failed to connect to woocommerce.com port 443: Connection refused

### Database ###

WC Database Version: 3.3.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 1.26MB
Database Data Size: 1.09MB
Database Index Size: 0.17MB
wp_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_aeidn_account: Data: 0.02MB + Index: 0.00MB
wp_aeidn_blacklist: Data: 0.02MB + Index: 0.00MB
wp_aeidn_goods: Data: 0.02MB + Index: 0.00MB
wp_aeidn_goods_archive: Data: 0.02MB + Index: 0.00MB
wp_aeidn_log: Data: 0.02MB + Index: 0.00MB
wp_aeidn_price_formula: Data: 0.02MB + Index: 0.00MB
wp_aeidn_stats: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB
wp_comments: Data: 0.00MB + Index: 0.01MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 0.68MB + Index: 0.04MB
wp_postmeta: Data: 0.14MB + Index: 0.04MB
wp_posts: Data: 0.12MB + Index: 0.02MB
wp_termmeta: Data: 0.00MB + Index: 0.01MB
wp_terms: Data: 0.00MB + Index: 0.01MB
wp_term_relationships: Data: 0.00MB + Index: 0.00MB
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wp_usermeta: Data: 0.00MB + Index: 0.01MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_webhooks: Data: 0.01MB + Index: 0.00MB

### Post Type Counts ###

attachment: 24
customize_changeset: 22
page: 12
post: 2
postman_sent_mail: 27
product: 4
revision: 6
shop_order: 6
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (14) ###

AffiliateImporterAI: by CR1000Team – 2.0.5 – Not tested with the active version of WooCommerce
Contact Form 7: by Takayuki Miyoshi – 5.0
Easy WP SMTP: by wpecommerce – 1.3.5
Jetpack by WordPress.com: by Automattic – 5.8
Post SMTP: by Jason Hendriks
Yehuda Hassine – 1.8

WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.5.2
WooCommerce PayPal Powered by Braintree Gateway: by WooCommerce – 2.1.1
WooCommerce Stripe Gateway: by WooCommerce – 4.0.7
WooCommerce Services: by Automattic – 1.11.0
WooCommerce: by Automattic – 3.3.3
WordPress Database Backup: by Austin Matzko – 2.3.3
Wp-Insert: by Namith Jawahar – 2.3
WP Mail SMTP: by WPForms – 1.2.5
SEOPress: by Benjamin DENIS – 2.6.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Shop Isle
Version: 1.1.40
Author URL: https://themeisle.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Braintree (Credit Card) ###

Environment: Production
Tokenization Enabled: 
Debug Mode: Off

### Braintree (PayPal) ###

Environment: Production
Tokenization Enabled: 
Debug Mode: Off

**Comment by thinkingserious** [comment]
Hello @Paulens007,

Are you using the Wordpress plugin? If so, [here](https://wordpress.org/plugins/sendgrid-email-delivery-simplified/
) is the correct place to post this issue.

With Best Regards,

Elmer
