### ISSUE TITLE
PHP7.2 warning with uninitialised $header variable

### ISSUE THREAD

**Issue by lucasnetau** [sendgrid/sendgrid-php#583]
#### Issue Summary

In function SendGrid\Email::getHeadersJson a check of the headers array is done with count() to check if any headers have been set. The $headers variable is not initialised in the class definition or in the constructor to an empty array. Since PHP7.2 a warning is generated when count() is performed on a non-countable array. This leads to the log file being spammed on every email sent.

#### Steps to Reproduce

1. Send email via SendGrid php client without setting any headers
2. Check php error logs.

Warning: count(): Parameter must be an array or an object that implements Countable in /src/vendor/sendgrid/sendgrid/lib/SendGrid/Email.php on line 522

An easy fix is to initialise the $headers variable in the constructor with an empty array. 

#### Technical details:

* sendgrid-php Version: master (latest commit: [commit number])
* PHP Version: 7.2

**Comment by lucasnetau** [comment]
PHP RFC reference to the change.

https://wiki.php.net/rfc/counting_non_countables

**Comment by thinkingserious** [comment]
Hi @lucasnetau,

Thanks for reporting this and offering an easy solution!

I've added this to our backlog for implementation.

With Best Regards,

Elmer

**Comment by valerianpereira** [comment]
Is this resolved? Unable to reproduce / find the file.

**Comment by lucasnetau** [comment]
Hi, yes this can be closed, I was porting a system over to PHP7.2 and failed to see that the version of the sendgrid client was installing an older version 3.2 locked by composer, surprisingly this one change was all that needed to be done to get it working in PHP7.2
