### ISSUE TITLE
Can't define CURL Option (timeout)

### ISSUE THREAD

**Issue by jonaswebdev** [sendgrid/sendgrid-php#586]
#### Issue Summary

I'm using the lasted SendGrid-php lib "6.0.0" and saw an issue related to `curl` options.

The method sign of SendGrid/Client constructor Class (file: sendgrid/php-http-client/lib/Client.php) have just 4 input attributes:
`    public function __construct($host, $headers = [], $version = '/v3', $path = [])
`

but the SendGrid constructor Class (file: sendgrid/sendgrid/lib/SendGrid.php) call a SendGrid/Client object sending five attributes, ie, the last attribute is lost:
`        $curlOptions = isset($options['curl']) ? $options['curl'] : null;
        $this->client = new \SendGrid\Client($host, $headers, '/v3', null, $curlOptions);`

In this way, we can't define the CURL options property.

I hope had been clear on my report...

**Comment by thinkingserious** [comment]
Thanks @jonaswebdev!

Your report is clear and now available for community contribution. I've also added it to our internal backlog for a fix.

With Best Regards,

Elmer

**Comment by jonaswebdev** [comment]
Elmer,

Great, how can I fix it and send a PR?
https://github.com/sendgrid/sendgrid-php/blob/master/CONTRIBUTING.md right?

**Comment by thinkingserious** [comment]
Yes, @jonaswebdev, thanks! Feel free to add comments here if you have further questions.
