### ISSUE TITLE
Updates for the new Email Activity API (beta)

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-php#587]
SendGrid has added an API to download information from the Email Activity feed. There are four new endpoints:
* [GET /messages](https://sendgrid.api-docs.io/v3.0/email-activity/filter-all-messages)
* [GET /messages/{msg_id}](https://sendgrid.api-docs.io/v3.0/email-activity/filter-messages-by-message-id)
* [POST /messages/download/](https://sendgrid.api-docs.io/v3.0/email-activity/request-csv)
* [GET /messages/download/{download_uuid}](https://sendgrid.api-docs.io/v3.0/email-activity/download-csv)

A getting started doc for the API is [here](https://sendgrid.com/docs/API_Reference/Web_API_v3/Tutorials/getting_started_email_activity_api.html).

The following items need to be updated in this repo:
* [USAGE.md](https://github.com/sendgrid/sendgrid-python/blob/master/USAGE.md)
* [/examples](https://github.com/sendgrid/sendgrid-python/tree/master/examples) (create a `messages` folder with a file `messages.py`)
* [Tests](https://github.com/sendgrid/sendgrid-python/blob/master/test/test_sendgrid.py)
* [USE_CASES.md](https://github.com/sendgrid/sendgrid-python/blob/master/USE_CASES.md)

**Comment by benrolfe** [comment]
Have these _new_ endpoints been implemented in the PHP SDK?

**Comment by mudit1987100** [comment]
I am using the sendgrid api in my project and working fine but it's not returning the msg_id and also I don't found any documentation that how to get that msg_id in response when we send a email. Can you please, help me on this. Thanks in advance.

**Comment by childish-sambino** [comment]
@mudit1987100 It's a response header when sending mail: `X-Message-Id`

**Comment by mudit1987100** [comment]
Thanks for your response but this message id is not that id using which I can track the activity of the email. How I can get he sendgrid assigned ID so I can pass it into the activity API. I have checked the webhooks but for that we have to upgrade our servers which will be costly so is there any way we can get the ID in response and directly pass that ID into activity API. Please, help on this.

**Comment by childish-sambino** [comment]
@mudit1987100 This was discussed here with some examples: https://github.com/sendgrid/sendgrid-php/issues/948

**Comment by mudit1987100** [comment]
@childish-sambino Thanks for your quick reply. I tried this way:

https://api.sendgrid.com/v3/messages?limit=10&query=msg_id%3D%22iioCSRBVTmWWymThlO0kbA%25%22

e.g. msg_id = 'message_id%'

but I am getting blank array:

stdClass Object ( [messages] => Array ( ) )

**Comment by childish-sambino** [comment]
@mudit1987100 Recommend trying this with cURL or Postman first to make sure the syntax is proper.

**Comment by mudit1987100** [comment]
@childish-sambino Many Thanks. I am using cURL to call this API here's the code below:

$url = 'https://api.sendgrid.com/v3/messages?limit=10&query=msg_id%3D%22iioCSRBVTmWWymThlO0kbA%25%22';
$header = array();
$header[] = 'Authorization: Bearer <<My API Key Here>>';

$ch = curl_init($url);

curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
curl_setopt($ch, CURLOPT_HTTPHEADER, $header);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$response = curl_exec($ch);
$result = json_decode($response);
curl_close($ch); // Close the connection
print_r($result);

**Comment by childish-sambino** [comment]
@mudit1987100  You'll need to use `LIKE` to do the prefix matching I mentioned in the other thread. E.g.,
`$url = 'https://api.sendgrid.com/v3/messages?limit=10&query=msg_id LIKE "iioCSRBVTmWWymThlO0kbA%"';
`

**Comment by mudit1987100** [comment]
@childish-sambino Many Many Thanks. It worked. Here's the final url I encoded may be it can help someone else:

$url = 'https://api.sendgrid.com/v3/messages?limit=10&query=msg_id+LIKE+%22iioCHDBVTmWWymThlO5kbA%25%22'

Below is the response:

( [messages] => Array ( [0] => stdClass Object ( [from_email] => donotreply@example.com [msg_id] => iioCSRBVTmWWymThlO8kbA.filterdrecv-p3mdw1-75c584b9c6-jp7b2-18-5F15E2A1-X.0 [subject] => Sending with Twilio SendGrid is Fun [to_email] => to_email@gmail.com [status] => delivered [opens_count] => 3 [clicks_count] => 0 [last_event_time] => 2020-07-08T15:19:00Z ) ) )

Again Thanks @childish-sambino

**Comment by mudit1987100** [comment]
@childish-sambino is it possible to get the messade id using the SMTP email as I'm using SMTP protocol to send email but not getting the X-Message-ID in header. Please, help me on this. Many Thanks

**Comment by childish-sambino** [comment]
@mudit1987100 I'm not familiar with what data is available in the SMTP response. Best to reach out to [support](https://support.sendgrid.com/hc/en-us).

**Comment by mudit1987100** [comment]
@childish-sambino many thanks for the help
