### ISSUE TITLE
Sometimes recipient receiving multiple identical emails

### ISSUE THREAD

**Issue by shrutijathar** [sendgrid/sendgrid-php#589]
#### Issue Summary

A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, code examples.

#### Steps to Reproduce

1. This is the first step
2. This is the second step
3. Further steps, etc.

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* sendgrid-php Version: master (latest commit: [commit number])
* PHP Version: 5.4 to 7.2 (as of February 1, 2018)

**Comment by thinkingserious** [comment]
Hello @shrutijathar,

Could you please provide us with some further details? Is it possible to share the code that is causing this problem?

With Best Regards,

Elmer

**Comment by ssiddhantsharma** [comment]
@thinkingserious I ran some tests and they were working fine. This issue is not replicable and I don't seem to have any problems with multiple identical emails being sent.

**Comment by ssiddhantsharma** [comment]
Close this issue as this is not a replicable bug.
I ran unit tests - https://github.com/sendgrid/sendgrid-php/tree/master/test/unit
