### ISSUE TITLE
Integration with Lumen\Laravel

### ISSUE THREAD

**Issue by bharatvaggu** [sendgrid/sendgrid-php#590]
Hi

How to integrate with "Lumen framework". Can you please provide steps?.

Thanks

**Comment by thinkingserious** [comment]
Hello @bharatvaggu,

Perhaps [this is the information you need](https://sendgrid.com/docs/Integrate/Frameworks/laravel.html)?

With Best Regards,

Elmer

**Comment by pranjalkumar** [comment]
Anyone managed to solve the issue

**Comment by thinkingserious** [comment]
Hello @pranjalkumar,

When you tried [these docs](https://sendgrid.com/docs/Integrate/Frameworks/laravel.html) what was the error you received?

Thanks!

With Best Regards,

Elmer

**Comment by pranjalkumar** [comment]
@thinkingserious Solved it. Actually, the problem with Lumen is that it doesn't come with any pre-installed driver for mail. And then you have to handle the version issue. But nevertheless, I managed to resolve the issue.

**Comment by bnymn** [comment]
Would you share your solution with us also, please? @pranjalkumar
