### ISSUE TITLE
Fatal error: Cannot declare class SendGrid\Email, because the name is already in use 

### ISSUE THREAD

**Issue by loretoparisi** [sendgrid/sendgrid-php#593]
Hello,
I'm using the SendGrid API in Wordpress. As soon as I install the Sendgrid widget plugin I get this error 

```
Fatal error: Cannot declare class SendGrid\Email, because the name is already in use in /wp-content/plugins/sendgrid-email-delivery-simplified/vendor/sendgrid-php/SendGrid/Email.php on line 5
```

I have tried to check the class existance in this way:

```php
if( class_exists('\\SendGrid\\Email') === false ) {
	require_once dirname(__FILE__) . "/sendgrid-php/sendgrid-php.php";
}
```

I have found this way to check the plugin in the "Caldera" wordpress plugin here https://github.com/CalderaWP/Caldera-Forms/commit/004a069bf6edb61d8e7bda2774128ff312394256#diff-c21b436023d2e0e85ea940ce6c7bbbfc

So, now I have solved disabling the "Sendgrid Widget" plugin and only using my plugin. If I enable it, the plugin will check for an existing sendgrid sdk installed in the correct way?

Thank you.

**Comment by thinkingserious** [comment]
Hello @loretoparisi,

The plugin will not check for an existing SendGrid SDK installation. I don't believe the plugin was designed with this use case in mind. 

Perhaps you can install the plugin and then access the SendGrid SDK through the plugin, since the plugin includes the SendGrid SDK.

With Best Regards,

Elmer

**Comment by loretoparisi** [comment]
@thinkingserious thank you, maybe I can try to use it from the plugin SDK, in that case, will I have to access through global objects?

**Comment by thinkingserious** [comment]
HI @loretoparisi,

I'm not sure, I don't have any experience with the SendGrid Wordpress Plugin.
