### ISSUE TITLE
Percent Symbol in html message causing Json Encoding Error when using postRequest to create a new Sendgrid campaign

### ISSUE THREAD

**Issue by rbalassa** [sendgrid/sendgrid-php#596]
When I try to create a new Sendgrid campaign by sending a postRequest, I get a system error "Unable to parse response body into JSON" in "sendgrid-php/lib/SendGrid.php(140):"

After several hours of debugging, I noticed that this only happened when I had % signs into the html code of the email. When I remove the html code, the JSON is parsed without any issue.

Here is a sample code I'm using to reproduce the error:

`<html><head><title></title></head><body><div style="width:100%">Check out our spring line!</div></body></html>`

Any idea how to resolve this, other than removing the % symbols from the html code?

Thanks!

* sendgrid-php Version: 3
* PHP Version: 7.2

**Comment by thinkingserious** [comment]
Hello @rbalassa,

I believe it's a matter of encoding the HTML, [like so](https://stackoverflow.com/a/4783070).

With Best Regards,

Elmer

**Comment by rbalassa** [comment]
Thanks Elmer for the reply.

I tested the htmlspecialchars function, and the result is not what is expected. The html is converted completely, but the % stay the same.

`&lt;html&gt;&lt;head&gt;&lt;title&gt;&lt;/title&gt;&lt;/head&gt;&lt;body&gt;&lt;div style=&quot;width:100**%**&quot;&gt;Check out our spring line!&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;`

So still the same problem.

Any other idea?

Thanks.

**Comment by rbalassa** [comment]
Yes, I need to json_encode the string before adding to the array, but the percent symbols is still an issue. When I remove the %, it parses correctly.

**Comment by thinkingserious** [comment]
Hi @rbalassa,

I have added this to our backlog for further investigation.

**Comment by thinkingserious** [comment]
Hello @rbalassa,

I was not able to reproduce this issue.

Here is the code I used:

```php
<?php
require 'vendor/autoload.php'; // If you're using Composer (recommended)
// comment out the above line if not using Composer
// require("./sendgrid-php.php"); 
// If not using Composer, uncomment the above line


$apiKey = getenv('SENDGRID_API_KEY');
$sg = new \SendGrid($apiKey);

$response = $sg->client->senders()->get();
print $response->statusCode() . "\n";
print $response->body() . "\n";
print_r($response->headers());

$request_body = json_decode('{
    "categories": [
      "spring line"
    ],
    "custom_unsubscribe_url": "",
    "html_content": "<html><head><title></title></head><body><div style=\"width:100%\">Check out our spring line!</div></body></html>",
    "plain_content": "Check out our spring line!",
    "sender_id": 148501,
    "subject": "New Products for Spring!",
    "suppression_group_id": 42,
    "title": "March Newsletter"
  }');
  $response = $sg->client->campaigns()->post($request_body);
  print $response->statusCode() . "\n";
  print $response->body() . "\n";
  print_r($response->headers());
```

And this is what I see in the interface:

![screen shot 2018-08-14 at 9 45 15 am](https://user-images.githubusercontent.com/146695/44105509-d253d556-9fa6-11e8-8b5a-0ff1a5ac2565.png)
