### ISSUE TITLE
Function mail doesn't exist

### ISSUE THREAD

**Issue by martijnmelchers** [sendgrid/sendgrid-php#597]
Hi,

alot of functions in the SendGrid class result to undefined this makes code completion not work and it makes the library ugly. Is there any way to fix those errors?

![0c1488910fb5e0a829a7f05d3 1](https://user-images.githubusercontent.com/6060006/38466425-1373faf8-3b29-11e8-81e3-fb06a9ef28dc.png)
![45cd35df5deb5e0a4adb3a9b5 1](https://user-images.githubusercontent.com/6060006/38466432-318e4624-3b29-11e8-9776-37ca8c18dbfe.png)

#### Technical details:

* sendgrid-php Version: 6.2
* PHP Version: 7.2

**Comment by thinkingserious** [comment]
Hello @martijnmelchers,

Can you tell me how you installed the SDK please?

Also, updates to this SDK are [on the way](https://github.com/sendgrid/sendgrid-php/issues/434) to improve the DX, hopefully I can get version 7 out by next week. That should help.

With Best Regards,

Elmer

**Comment by martijnmelchers** [comment]
Hi @thinkingserious,

it works but it doesn't look good in the editor. this could be solved by adding the function to the sendgrid client

I was also wondering is it possible to send a template without a "content" tab? It's kinda useless for templates...

**Comment by martijnmelchers** [comment]
@thinkingserious 

Ok! I have figured out how to fix the issue!

It's actually a problem with [php-http-client](https://github.com/sendgrid/php-http-client). Adding the following (using PHPDoc) will fix the issue. It seems like there is almost no documentation.

`Mail.php`
![3d8ddbdbc60c1105ab8a4f0a8 1](https://user-images.githubusercontent.com/6060006/38520521-5510d2c2-3c43-11e8-8805-6669c5d3cb71.png)

`Client.php`
![0a8a84812684588ad8f2a26b8 1](https://user-images.githubusercontent.com/6060006/38520578-73246e22-3c43-11e8-941c-44bd6369571f.png)


This fixes both issues:

![262014ce4d050318bfa80420f 1](https://user-images.githubusercontent.com/6060006/38520643-9e1f883c-3c43-11e8-85b6-66cbd35d3c71.png)


I might be able to document the php-doc library when I have some time. Let me know if you want this?

**Comment by thinkingserious** [comment]
That would be amazing @martijnmelchers!

**Comment by martijnmelchers** [comment]
Added alot of methods, might not be the best way but let me know! [#98](https://github.com/sendgrid/php-http-client/pull/98) Will document this library more tomorrow. It's too bad everything uses `__call()` makes everything messy!
