### ISSUE TITLE
 Message won't send when attachment is present

### ISSUE THREAD

**Issue by robapavas** [sendgrid/sendgrid-php#603]
Issue Summary

im using sendgrid for sending mails. when i attach a file (pdf or doc) i can't send it. when i comment on the $attachment it sends succesfully. when i use localhost it does attach the file and send correctly. i don't get any errors or warnings. the $response i use for debug doesn't appear either. here is the code im using

require 'vendor/autoload.php';

$name = $_POST['Name'];
$email = $_POST['Email'];
$phone = $_POST['Telephone'];
$state = $_POST['State'];
$manufacturing = $_POST['ManufacturingP'];
$about = $_POST['about'];
$manufacturing2 = implode(', ', $manufacturing);
$file1 = $_FILES['upfile']['name'];
                  

$from = new SendGrid\Email("domain name", "test@mydomain.com");
$subject = 'Candidates for Manufacturing';
$to = new SendGrid\Email("domain name", "test@mydomain.com");;
$content = new SendGrid\Content("text/html","
<html>
<head>
	<title>domain</title>
</head>
<body>
Name : {$name}<br>
Email : {$email}<br>
Telephone : {$phone}<br>
State : {$state}<br>
Manufacturing : {$manufacturing2}<br>
About : {$about} 
</body>
</html>");

$attachment = new SendGrid\Attachment();
$attachment->setContentPath($file1);
$attachment->setType('application/vnd.openxmlformats-officedocument.wordprocessingml.document');
$attachment->setType('application/pdf');
$attachment->setType('application/msword');
$attachment->setDisposition("attachment");

$mail = new SendGrid\Mail($from, $subject, $to, $content);
$mail->addAttachment($attachment);

$apiKey = '###########';
$sg = new \SendGrid($apiKey);

$response = $sg->client->mail()->send()->post($mail);

echo $response->statusCode();
print_r($response->headers());
echo $response->body();
Technical details:

sendgrid v3 api
php
godaddy hosting service

**Comment by robapavas** [comment]
i used that example and it works in localhost. can you explain a little more?

**Comment by thinkingserious** [comment]
```php
// This is the Base64 encoded content, I don't see where you set this in your example
$attachment->setContent($file_encoded);
// There can only be one type per attachment and in your example, I see three
$attachment->setType("application/text");
// This seems correct
$attachment->setDisposition("attachment");
// I don't see where you set this in your example
$attachment->setFilename("my_file.txt");
```

**Comment by robapavas** [comment]
i have changed it to 
	$file = 'file1.pdf';
	$file_encoded = base64_encode(file_get_contents($file));
	$attachment = new SendGrid\Attachment();
	$attachment->setContentPath($file_encoded);
	$attachment->setType('application/pdf');
	$attachment->setDisposition("attachment");
	$attachment->setFilename("file1.pdf");

now is worse. i can't even send it through localhost.

**Comment by robapavas** [comment]
well i manage to work it out 

ill leave the code: 

	try {
    
    // Undefined | Multiple Files | $_FILES Corruption Attack
    // If this request falls under any of them, treat it invalid.
    if (
        !isset($_FILES['upfile']['error']) ||
        is_array($_FILES['upfile']['error'])
    ) {
        throw new RuntimeException('Invalid parameters.');
    }

    // Check $_FILES['upfile']['error'] value.
    switch ($_FILES['upfile']['error']) {
        case UPLOAD_ERR_OK:
            break;
        case UPLOAD_ERR_NO_FILE:
            throw new RuntimeException('No file sent.');
        case UPLOAD_ERR_INI_SIZE:
        case UPLOAD_ERR_FORM_SIZE:
            throw new RuntimeException('Exceeded filesize limit.');
        default:
            throw new RuntimeException('Unknown errors.');
    }

    // You should also check filesize here. 
    if ($_FILES['upfile']['size'] > 1000000) {
        throw new RuntimeException('Exceeded filesize limit.');
    }

    // DO NOT TRUST $_FILES['upfile']['mime'] VALUE !!
    // Check MIME Type by yourself.
    $finfo = new finfo(FILEINFO_MIME_TYPE);
    if (false === $ext = array_search(
        $finfo->file($_FILES['upfile']['tmp_name']),
        array(
            'doc' => 'application/msword',
            'docx' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            'pdf' => 'application/pdf',
        ),
        true
    )) {
        throw new RuntimeException('Invalid file format.');
    }

    // You should name it uniquely.
    // DO NOT USE $_FILES['upfile']['name'] WITHOUT ANY VALIDATION !!
    // On this example, obtain safe unique name from its binary data.
    if (!move_uploaded_file(
        $_FILES['upfile']['tmp_name'],
        sprintf('./uploads/%s.%s',
            sha1_file($_FILES['upfile']['tmp_name']),
            $ext
        )
    )) {
        throw new RuntimeException('Failed to move uploaded file.');
    }

 //   echo 'File is uploaded successfully.';

} catch (RuntimeException $e) {

    echo $e->getMessage();

}	

	require 'vendor/autoload.php';

	$first_name = $_POST['Name'];
	$email = $_POST['Email'];
	$phone = $_POST['Telephone'];
	$state = $_POST['State'];
	$manufacturing = $_POST['ManufacturingP'];
	$about = $_POST['about'];
	$manufacturing2 = implode(', ', $manufacturing); // this is an array of checkboxes
	$path = "./uploads/"; 

	$latest_ctime = 0;
	$latest_filename = '';    

	$d = dir($path);
	while (false !== ($entry = $d->read())) {
	  $filepath = "{$path}/{$entry}";
	  // could do also other checks than just checking whether the entry is a file
	  if (is_file($filepath) && filectime($filepath) > $latest_ctime) {
	    $latest_ctime = filectime($filepath);
	    $latest_filename = $entry;
	  }
	}

	$final_path = "{$path}/{$latest_filename}";           

	$from = new SendGrid\Email("name", "my@domain.com");
	$subject = 'subject';
	$to = new SendGrid\Email("name", "my@domain.com");;
	$content = new SendGrid\Content("text/html","
	<html>
	<head>
		<title>domain name</title>
	</head>
	<body>
	Name : {$first_name}<br>
	Email : {$email}<br>
	Telephone : {$phone}<br>
	State : {$state}<br>
	Manufacturing : {$manufacturing2}<br>
	About : {$about} 
	</body>
	</html>");

	$attachment = new SendGrid\Attachment();
	$attachment->setContentPath($final_path);
	$attachment->setType('application/vnd.openxmlformats-officedocument.wordprocessingml.document');
	$attachment->setType('application/pdf');
	$attachment->setType('application/msword');
	$attachment->setDisposition("attachment");

	$mail = new SendGrid\Mail($from, $subject, $to, $content);
	$mail->addAttachment($attachment);

	$apiKey = #######';
	$sg = new \SendGrid($apiKey);
	
	$response = $sg->client->mail()->send()->post($mail);

**Comment by thinkingserious** [comment]
Thanks for sharing your solution @robapavas!
