### ISSUE TITLE
Ensure text/plain is always the first object among multiple Content objects

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-php#608]
#### Issue Summary

The SendGrid API requires that a MimeType of "text/plain" should always be first in an array of Content objects, when specified. Our examples currently demonstrate this, but we should ensure that this is the case in the SDK in the event that someone sets "text/html" (for example) as the first Content object. The update should be made in the Mail object, [getContents](https://github.com/sendgrid/sendgrid-php/blob/master/lib/mail/Mail.php#L1099) method.

**Comment by hjamesw93** [comment]
@thinkingserious Happy to give this a go!

**Comment by thinkingserious** [comment]
Awesome, thank you @hjamesw93!
