### ISSUE TITLE
Detect if an attachment is Base64 encoded, if not, automatically encode it

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-php#611]
#### Issue Summary

This should be done in the `[setContent](https://github.com/sendgrid/sendgrid-php/blob/master/lib/mail/Attachment.php#L78)` method of the Attachment object.

[See here for an example](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#attachments).

**Comment by martijnmelchers** [comment]
@thinkingserious 

I could make this, but how would we detect if an attachment is base64 encoded?

**Comment by thinkingserious** [comment]
@martijnmelchers,

Thanks for offering to take this on!

I don’t know the best way to do this yet and I’m open to suggestions.

A quick search on the web reveals a bunch of solutions, but not foolproof.

In the end we should be sure to return an exception if the SendGrid API rejects the encoding.

With Best Regards,

Elmer
