### ISSUE TITLE
Add type validations to each setter and implement SendGrid custom exceptions

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-php#612]
#### Issue Summary

The correct types should be documented in phpdoc format already in the source code, but [this documentation](https://sendgrid.com/docs/API_Reference/api_v3.html) can be used to double check the types. If the type is incorrect we should throw a custom exception.

This feature should be added to the objects [here](https://github.com/sendgrid/sendgrid-php/tree/master/lib/mail).

**Comment by hjmsw** [comment]
I can have a look at this :)

**Comment by doctorpepper608** [comment]
@thinkingserious @hjmsw  maybe `filter_var($email, FILTER_VALIDATE_EMAIL) ` in in `Mail->setFrom($email, $name=null) `method should be parameterized , because validation disallow valid email addresses [localdomain]@domain.com which is more than 64 characters
