### ISSUE TITLE
Create MimeType constants for the Attachments object

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-php#613]
#### Issue Summary

Here is an [example](https://github.com/sendgrid/sendgrid-php/blob/master/lib/mail/MimeType.php). The MimeTypes should be defined .in a new file /mail/AttachmentMimeType.php. Please use [this list](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types).

**Comment by michaeljdennis** [comment]
Hi @thinkingserious,

Should every MIME type on that page be included in the new class?

Thanks!

**Comment by thinkingserious** [comment]
Hi @michaeljdennis,

Just not the deprecated types. Thanks!

With Best Regards,

Elmer

**Comment by childish-sambino** [comment]
Closing as I don't see the value added.
