### ISSUE TITLE
Improve the examples in the /examples directory to include try/catch and better printing.

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-php#617]
#### Issue Summary

We currently have [this](https://github.com/sendgrid/sendgrid-php/blob/master/examples/accesssettings/accesssettings.php#L17), let's update to [this](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#single-email-single-recipient).

**Comment by hjmsw** [comment]
Pull request submitted. Macros came in handy here! :)
