### ISSUE TITLE
Invalid inline documentation

### ISSUE THREAD

**Issue by martijnmelchers** [sendgrid/sendgrid-php#619]
Hi, nice work on the inline commenting although some mistakes have been made! Easily fixable and will probably send a pull-request to fix it soon.

The variables you comments with `//` but those also have to be done with `/**/` or PHPDoc won't accept them.

Shown below:

![1c320eb43040ce81a01c0e2d7 1](https://user-images.githubusercontent.com/6060006/40284282-156f46fc-5c8d-11e8-848f-d29f93dc9476.png)

**Comment by thinkingserious** [comment]
Thanks @martijnmelchers!

What tool are you using to catch those errors? phpcs did not catch those :(

With Best Regards,

Elmer

**Comment by martijnmelchers** [comment]
My editor is IntellIJ but the docs also state that they need to start with `/**` 

You can read that [here](https://docs.phpdoc.org/getting-started/your-first-set-of-documentation.html)

**Comment by thinkingserious** [comment]
Thanks @martijnmelchers!

Not sure why the linter is not catching it, but it definitely is wrong. I'll leave this issue open until we can resolve it.

**Comment by martijnmelchers** [comment]
I will resolve it!
