### ISSUE TITLE
Variables not populating in template

### ISSUE THREAD

**Issue by ebranch** [sendgrid/sendgrid-php#622]
#### 

The problem I running into is when the first email is sent out it's not populating the variables for the template but the second email that is sent out has the variables.

![screenshot_20180524_145304](https://user-images.githubusercontent.com/1250718/40667751-ddebf4fa-6330-11e8-90ca-07cf7e9b38f2.png)
![screenshot_20180524_145304](https://user-images.githubusercontent.com/1250718/40667778-f172848a-6330-11e8-841d-aab63401a13e.png)

```php
#### Code
<?php
/**
 * Load Sendgrid Library into memory and prepare it
 */
require_once __DIR__ . "/../../library/sendgrid-php/vendor/autoload.php";

/**
 *  Parse System INI File, grab Sendgrid KEY and save it into $SENDGRID_KEY variable
 */
require(dirname($_SERVER['DOCUMENT_ROOT']) . '/webconfig/getConfigFile.php');
// $SENDGRID_KEY = $APCODE['sendgrid-access-info']['SendGridKey'];
$apiKey =  $APCODEI['sendgrid-access-info']['SendGridKey'];

function saleComplete() {





  $email_data['from'] = 'email';
  $email_data['to'] = 'email';
  $email_data['subject'] = 'Item merch';
  $email_data['TID'] = "Template id";
  $email_data['from'] = 'email';

  $ctt['{{order_id}}'] = '3526984';
  $ctt['{{pharmacy_name}}'] = 'john doe';
  $ctt['{{credit_ammount}}'] = '88.65';
  $ctt['{{order_date}}'] = 'May 06, 2018';
  $ctt['{{banking_info}}'] = 'Comerica Bank xxxx-xxx';
  $ctt['{{order_information}}'] = '1 Full Pack BOTTLE (80 ML) of ACUICYN DAILY EYELID & EY ';
  $ctt['{{matchmoney_info}}'] = '$55.38';
  $ctt['{{order_date}}'] = 'May 06, 2018';


  // Create mail object
  $from    = new SendGrid\Email("Big John",  $email_data['from']);
  $subject =  $email_data['subject'];
  $to      = new SendGrid\Email("Mr.B",  $email_data['to']);
  $content = new SendGrid\Content("text/html", "MatchRX.com");
  $mail    = new SendGrid\Mail($from, $subject, $to, $content);

  // Set template ID
  $mail->setTemplateId($email_data['TID']);


  // Set personalization
  $personalization = new \SendGrid\Personalization();
  $email7 =new SendGrid\Email("elton", "eltonsdesign@gmail.com");
   $personalization->addTo($to);
  // $personalization->addTo( $ctt['{{pharmacy_name}}']);

   //echo json_encode($mail, JSON_PRETTY_PRINT), "\n";

   // // Add Variable Content
   foreach ($ctt as $key => $value) {
    $personalization->addSubstitution($key, $value);
   }

   // Inject Personalization in the selected template
    $mail->addPersonalization($personalization);


// $mail->addCustomArg("order id",  $ctt['{{order_id}}']);
   // sleep(5);

}



function sendsaleComplete()
{
    
    $apiKey =  $APCODE['sendgrid-access-info']['SendGridKey'];
    $sg = new \SendGrid($apiKey);
    $request_body = saleComplete();
    $response = $sg->client->mail()->send()->post($request_body);
    echo "<pre>\n\$apiKey = $apiKey\n ";
    print_r($request_body);
    echo $response->statusCode();
    echo $response->body();
    // print_r($response->headers());

}


sendsaleComplete();  // this will actually send an email

?>
```

* sendgrid-php Version: master (latest commit: [commit number])
* PHP Version: 5.6, 7.0, 7.1, 7.2 (as of May 17, 2018)

**Comment by thinkingserious** [comment]
Hello @ebranch,

When you use the `SendGrid\Mail` constructor, an initial `Personalization` object is created. You can operate on it [like so](https://github.com/sendgrid/sendgrid-php/blob/4d500a972739ef2c596299f3ad822dd231aab4df/examples/helpers/mail/example.php#L32).

I hope that helps!

With Best Regards,

Elmer

**Comment by ebranch** [comment]
Sorry that's not problem, my variables populate on the second email that is sent out. The varables are blank on the first email.

**Comment by thinkingserious** [comment]
@ebranch,

Do you mind posting your request body, [like this](https://github.com/sendgrid/sendgrid-php/blob/master/TROUBLESHOOTING.md#request-body)? Thanks!

**Comment by ebranch** [comment]
@thinkingserious 

"from":{  
   "name":"MatchRX",
   "email":"it@matchrx.com"
},
"personalizations":[  
   {  
      "to":[  
         {  
            "name":"Mr.B",
            "email":"eltonsdesign@gmail.com"
         }
      ]
   },
   {  
      "to":[  
         {  
            "name":"Elton",
            "email":"ebranch@matchrx.com"
         }
      ],
      "substitutions":{  
         "{{order_id}}":"3526984",
         "{{pharmacy_name}}":"Rogers Pharmacy",
         "{{credit_ammount}}":"88.65",
         "{{order_date}}":"May 06, 2018",
         "{{banking_info}}":"Comerica Bank xxxx-045",
         "{{order_information}}":"1\u00a0Full\u00a0Pack\u00a0BOTTLE\u00a0(80\u00a0ML)\u00a0of\u00a0ACUICYN\u00a0DAILY\u00a0EYELID\u00a0& EY\u00a0",
         "{{matchmoney_info}}":"$55.38"
      }
   }
],
"subject":"SendGrid Email Test",
"content":[  
   {  
      "type":"text/html",
      "value":"MatchRX.com"
   }
],
"template_id":"XXXXXXXX"

**Comment by ebranch** [comment]
@thinkingserious  

I have resolved the issue, once I implement my code because i'm behind the ball I will explain the solution. Thank you for your help.

**Comment by thinkingserious** [comment]
Thank you @ebranch!
