### ISSUE TITLE
macOS Word Attachments Invalid

### ISSUE THREAD

**Issue by smockensturm** [sendgrid/sendgrid-php#623]
#### Issue Summary

Attachments work swell as outlined in the example docs. However, something is getting munged with the mime-type or encoding or something, idk. We cannot open the attachment in macOS Pages, with the message:

> docname can't be opened right now. The file format is invalid.

#### Steps to Reproduce

1. Attach a docx per the examples.
  
```
   $file_encoded = base64_encode($_FILES["document"]["tmp_name"]);
   $email->addAttachment(
            $file_encoded,
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            $filename,
            "attachment"
    );
```
mime types found here:
https://stackoverflow.com/questions/4212861/what-is-a-correct-mime-type-for-docx-pptx-etc

2. Try to open the attachment.

As stated, the email comes through with the attachment seemingly in tact. Double click the attachment in macOS prompts Pages to attempt an open and we get the message above.

#### Technical details:

* sendgrid-php Version: [7.0.0] - XXXX-XX-XX
* PHP Version: 5.6

**Comment by martijnmelchers** [comment]
Try `application/vnd.ms-word`

**Comment by smockensturm** [comment]
Thanks. No change.

**Comment by martijnmelchers** [comment]
Hmmm, weird it should really work! https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types

**Comment by martijnmelchers** [comment]
Perhaps the attachment isn't read correctly by your code could you give more code on what comes before and after the snippet you have provided?

**Comment by smockensturm** [comment]
Sure. Here's the whole bit. Nothing tricky. (I've also tried `application/octet-stream`)

```
<?php

  require("sendgrid-php/sendgrid-php.php");

  $company = $_POST["company"];

  $html = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html>\n<head>\r\n";
  $html .= "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n";
  $html .= "</head>\r\n";
  $html .= "<body>\r\n";
  $html .= "<div style='width: 560px; background-color: #fff; padding:20px'>";
  $html .= "<p>You've received a document via the form on your website.</p>";
  $html .= "<table cellpadding='3'>";
  $html .= "<tr><td align='right'><strong>Company Name: </strong></td><td>".$company."</td></tr>";
  $html .= "</table>";
  $html .= "</div></body></html>";

  $email = new \SendGrid\Mail\Mail();
  $email->setFrom("contactus@maumeeventures.com", "Maumee Ventures");
  $email->setSubject("A New Document from Maumee Ventures - Staged");
  $email->addTo("my@email.com", "My Name");
  $email->addContent(
	  "text/html", $html
  );

  $filename = $_FILES["plan-doc"]["name"];
  $file_encoded = base64_encode($_FILES["plan-doc"]["tmp_name"]);

  $email->addAttachment(
	$file_encoded,
	"application/vnd.ms-word",
	$filename,
	"attachment"
  );

  $sg = new \SendGrid('mySGkey');

  try {
	  $response = $sg->client->mail()->send()->post($email);
	  print $response->statusCode() . "\n";
	  print_r($response->headers());
	  print $response->body() . "\n";
  } catch (Exception $e) {
	  echo 'Caught exception: ',  $e->getMessage(), "\n";
  }


?>
```

**Comment by martijnmelchers** [comment]
Maybe you could verify that `$file_encode` is actually something by decoding on an online website.

**Comment by smockensturm** [comment]
Changed this line:

`$file_encoded = base64_encode($_FILES["plan-doc"]["tmp_name"]);`

To this:

`$file_encoded = base64_encode(file_get_contents($_FILES["plan-doc"]["tmp_name"]));`

And all is well.

**Comment by martijnmelchers** [comment]
Glad it could be resolved! 👍 

Happy coding!
