### ISSUE TITLE
Fix GroupsToDisplay::setGroupsToDisplay's handling of array arguments

### ISSUE THREAD

**Issue by moismailzai** [sendgrid/sendgrid-php#624]
#### Issue Summary

According to the [API docs](https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html), `asm.groups_to_display` should be an array of integers.

Several of the examples in this repository show that sendgrid-php is meant to support passing an array to `asm.groups_to_display`:
* https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md references `$email->setAsm(1, [1, 2, 3, 4])`. The expectation is that the `setAsm` method would pass its second argument to the groups_to_display setter.
* https://github.com/sendgrid/sendgrid-php/blob/master/examples/helpers/mail/example.php#L117 references `$asm->setGroupsToDisplay([4,5,6,7,8])`. The expectation is that this array would be set as the `asm.groups_to_display`.

However, both of these examples return `400` with: 
`{"errors":[{"message":"Invalid type. Expected: integer, given: array.","field":"asm.groups_to_display.0","help":null}]}
`

This because the `setGroupsToDisplay` method of the `GroupsToDisplay` class is wrapping its argument (`$groups_to_display`) in an array: `$this->groups_to_display[] = $groups_to_display;`. This is necessary when `$groups_to_display` is a single integer, but it breaks when `$groups_to_display` is already an array. The fix is a conditional that checks if `$groups_to_display` is an array.

#### Steps to Reproduce

1. Create a new mail object `$email = new \SendGrid\Mail\Mail()` and setAsm with two arguments, an integer and an array of integers: `$email->setAsm(1, array( 2, 3, 4))`.
2. Send the mail and you will get a `400` response citing `asm.groups_to_display`.

Alternatively,

1. Create a new mail object and configure your ASM like below:
```
$asm = new \SendGrid\Mail\Asm();
$asm->setGroupId(1);
$asm->setGroupsToDisplay(array(2, 3, 4));
...
$email->setAsm($asm);
```
2. Send the mail and you will get a `400` response citing `asm.groups_to_display`.

#### Technical details:

* sendgrid-php Version: master (latest commit: [a3da5cdb59e60bd692325ff286d68095a03bd928](https://github.com/sendgrid/sendgrid-php/commit/a3da5cdb59e60bd692325ff286d68095a03bd928))
* PHP Version: 7.1, 7.2

**Comment by thinkingserious** [comment]
Thank you @moismailzai!
