### ISSUE TITLE
add mail from in personnalisations array

### ISSUE THREAD

**Issue by luffyfr** [sendgrid/sendgrid-php#635]
Hi,
I would like personnalise the mail from in the personnalisation array.

Made something like this :

```javascript
{
  "personalizations": [
    {
      "to": [
        {
          "email": "john@example.com"
        }
      ],
      "subject": "Hello, with the personnalise mail from"
      "from": {
             "email": "from_address_personalise@example.com"
      }
    },
    {
      "to": [
        {
          "email": "robert@example.com"
        }
      ],
      "subject": "Hello, with the global mail from"
    }
  ],
  "from": {
    "email": "from_address@example.com"
  },
  "content": [
    {
      "type": "text/plain",
      "value": "Hello, World!"
    }
  ]
}
```

instead of 

```javascript
{
  "personalizations": [
    {
      "to": [
        {
          "email": "john@example.com"
        }
      ],
      "subject": "Hello, World!"
    }
  ],
  "from": {
    "email": "from_address@example.com"
  },
  "content": [
    {
      "type": "text/plain",
      "value": "Hello, World!"
    }
  ]
}
```

is there anyway to make this or i must made a loop from each different sender ?

Thanks

#### Issue Summary

A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, code examples.

#### Steps to Reproduce

1. This is the first step
2. This is the second step
3. Further steps, etc.

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* sendgrid-php Version: master (latest commit: [commit number])
* PHP Version: 5.6, 7.0, 7.1, 7.2 (as of May 17, 2018)

**Comment by thinkingserious** [comment]
Hello @luffyfr,

It looks like you might be trying to execute [this use case](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#multiple-emails-multiple-recipients). Please take a look and let me know what you think.

With Best Regards,

Elmer
