### ISSUE TITLE
Sections tag not working

### ISSUE THREAD

**Issue by alemadlei-tech** [sendgrid/sendgrid-php#636]
#### Issue Summary

I have a transactional template with placeholders added in order to use the replacement functionality provided by sections tag.

However, they are not being replaced once the email is sent.

If I instead add them to every recipient by means of having personalization, they work.

#### Steps to Reproduce

```
use \SendGrid\Mail\From as SendGridEmailFrom;
use \SendGrid\Mail\EmailAddress as SendGridEmailAddress;
use \SendGrid\Mail\Mail as SendGridMail;

        // Builds the email message.
        $mail = new SendGridMail($from);

        // Sets the email contents.
        $mail->setTemplateId($template_id);
        foreach ($sections as $key => $value) {
          $mail->addSection("%{$key}%", $value);
        }

        // Builds each personalization object with the information from each recipient.
        foreach ($message_recipients as $recipient) {
          $personalization = new SendGridPersonalization();
          $personalization->addTo(new SendGridEmailAddress($recipient->getContact()->getEmail(), $recipient->getContact()->getName()));

          // Adds it to the mail object
          $mail->addPersonalization($personalization);

        }

       // Sets data.
      $mail->setSubject($subject);

      $client->mail()->send()->post($mail);

```

Message is sent, but sections are never replaced in the final email message..

#### Technical details:

* sendgrid-php Version: 7.0
* PHP Version: 5.6

**Comment by thinkingserious** [comment]
Hi @alemadlei-tech,

I believe [this is the use case](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#transactional-templates) you need.

Please let me know if this solves your issue.

Thanks!

With Best Regards,

Elmer

**Comment by alemadlei-tech** [comment]
Hello,

It doesn't seem to work though.

I have a very basic template. Two replacements.

I'm sending this email with multiple personalization objects.

The template contains things that are specific for each recipient (name, address) but some other things are also variable but common among them (date that is being sent, promotional code).

So, when I send it, section tags are not replaced, only substitions that are part of each personalization object.

**Comment by thinkingserious** [comment]
Hi @alemadlei-tech,

Are you saying that you have tried the example I posted and it failed? If so, could you please post that code so I can take a look? Thanks!
