### ISSUE TITLE
Returning Error 500

### ISSUE THREAD

**Issue by ronaldo2018** [sendgrid/sendgrid-php#637]
I'm trying to use sendgrid, but when I send it and it goes to the page where the code from sendgrid returns me error 500, how could I solve this problem?

`<?php
require 'vendor/autoload.php'; // If you're using Composer (recommended)
// Comment out the above line if not using Composer
// require("./sendgrid-php.php"); 
// If not using Composer, uncomment the above line

$email = new \SendGrid\Mail\Mail(); 
$email->setFrom("email", "Example User");
$email->setSubject("Sending with SendGrid is Fun");
$email->addTo("email", "Example User");
$email->addContent("text/plain", "and easy to do anywhere, even with PHP");
$email->addContent(
    "text/html", "<strong>and easy to do anywhere, even with PHP</strong>"
);
$sendgrid = new \SendGrid(getenv('passowordId'));
try {
    $response = $sendgrid->send($email);
    print $response->statusCode() . "\n";
    print_r($response->headers());
    print $response->body() . "\n";
} catch (Exception $e) {
    echo 'Caught exception: ',  $e->getMessage(), "\n";
}`

I was able to log in normally via ssh

`[root@ubuntu-s-1vcpu-1gb-nyc1-01 ~]# telnet smtp.sendgrid.net 2525
Trying 108.168.183.160...
Connected to smtp.sendgrid.net.
Escape character is '^]'.
220 SG ESMTP service ready at ismtpd0010p1iad1.sendgrid.net
auth login
334 VXNlcm5hbWU6
login
334 UGFzc3dvcmQ6
senha
235 Authentication successful
`

**Comment by bootsie123** [comment]
The same thing is happening to me. Yesterday everything was completely fine. Now for some reason today I keep getting an HTTP ERROR 500 when trying to use sendGrid. Find any solutions yet?

**Comment by ronaldo2018** [comment]
Não há outra solução para isso, estou esperando por uma resposta deles

2018-07-04 20:12 GMT-03:00 bootsie123 <notifications@github.com>:

**Comment by thinkingserious** [comment]
Hello @ronaldo2018,

Have you tried reading the message, [like this](https://github.com/sendgrid/sendgrid-php/blob/master/TROUBLESHOOTING.md#error)?

Thanks!

With Best Regards,

Elmer

**Comment by ronaldo2018** [comment]
I tried now to execute the function to correct the error, I went like this:

```
require 'vendor / autoload.php';

$ email = new \ SendGrid \ Mail \ Mail (); 
$ email-> setFrom ("email", "Exemplo Usuário"); 
$ email-> setSubject ("Enviando com o SendGrid é divertido"); 
$ email-> addTo ("email", "Usuário do exemplo"); 
$ email-> addContent ("text / plain", "e fácil de fazer em qualquer lugar, mesmo com PHP"); 
$ email-> addContent ( 
"text / html", " e fácil de fazer em qualquer lugar, mesmo com PHP " 
); 

try {
    $response = $sendgrid->send($email);
    print $response->statusCode() . "\n"; 
    print_r($response->headers());
    print $response->body() . "\n"; // SendGrid specific errors are found here
} catch (Exception $e) {
    echo 'Caught exception: ',  $e->getMessage(), "\n";
}
```

Still in continuation, is returning 500 error on the screen, could it be on the default port being used? I need to use 2525 because I'm on DigitalOcean

**Comment by ronaldo2018** [comment]
I looked at the log and it is returning this:

2018-07-07 02:22:55.199078 [NOTICE] [198.41.230.20:14741] [STDERR] PHP Fatal error:  Uncaught Error: Class 'SendGrid\Mail\Mail' not found in /home/dominio.com.br/public_html/wp-content/themes/Divi/sistEmail.php:7
Stack trace:
#0 {main}
  thrown in /home/dominio.com.br/public_html/wp-content/themes/Divi/sistEmail.php on line 7

**Comment by thinkingserious** [comment]
Hi @ronaldo2018,

Could you please tell me how you installed the SDK? Thanks!

With Best Regards,

Elmer

**Comment by nomoreboredom** [comment]
I do experience same issue, i am not using composer. Just adding using a relative path ```require("./libs/sendgrid-php/sendgrid-php.php");```

**Comment by nomoreboredom** [comment]
Found the issue for me, the package should be downloaded from here: 
https://github.com/sendgrid/sendgrid-php. 
Not sure from where I downloaded it first, but the correct one has additionally a docker folder, and some files.

**Comment by thinkingserious** [comment]
Hi @nomoreboredom,

Yes, that is the correct link, thanks for clarifying the issue.

@ronaldo2018,

Have you downloaded the code from this link? https://github.com/sendgrid/sendgrid-php

**Comment by RAMTO** [comment]
Hey guys, I am receiving the same error 500, on this line:
`$email->addContent("text/plain", "Some text");`

I am not using composer and I downloaded the latest version from GitHub.

Please help...

**Comment by thinkingserious** [comment]
Hello @RAMTO,

Could you please try retrieving the error message, [like this](https://github.com/sendgrid/sendgrid-php/blob/master/TROUBLESHOOTING.md#error)? Thanks!

With Best Regards,

Elmer
