### ISSUE TITLE
Vendor autoload.php doesn't exist?

### ISSUE THREAD

**Issue by alvarotrigo** [sendgrid/sendgrid-php#638]
I'm getting the following error:

> Warning: require(/xxxxxxxx/sendgrid/vendor/autoload.php): failed to open stream: No such file or directory in /xxxxxxxx/sendgrid/sendgrid-php.php on line 14

I found these related issues but there's no proper solution offered there: https://github.com/sendgrid/sendgrid-php/issues/407

Why is this vendor not file not included in github??
The [PHP example you guys provide](https://sendgrid.com/docs/Integrate/Code_Examples/v3_Mail/php.html) doesn't even work this way.

**Comment by martijnmelchers** [comment]
Have you installed it with `composer require`?

>

**Comment by alvarotrigo** [comment]
No. The docs say using composer is optional. I'm not familiar with composer and I would rather not use it if I can. 
What it doesn't specify is where to get the file when not using composer.

**Comment by martijnmelchers** [comment]
Although using composer is not required I do really recommend it. It makes updating so much easier and its super easy to use.

But here goes:

If you dont want use composer you need to download the folder as `.zip` and extract it and add:

`require directory/sendgrid-php/loader.php`

**Comment by alvarotrigo** [comment]
> and add:
require directory/sendgrid-php/loader.php

Add that where?

**Comment by alvarotrigo** [comment]
Also, there's no such file "loader.php" in the root folder of sendgrid-php.
Are you talking about the one within the `lib` folder? `lib/loader.php` ?

**Comment by alvarotrigo** [comment]
Even when replacing:

```php
require("./vendors/sendgrid/sendgrid-php.php");
```

For
```php
require directory/sendgrid-php/loader.php
```
 
I get the following error:

> Warning: require_once(/xxx/sendgrid/lib/mail/BatchId): failed to open stream: No such file or directory in /xxx/sendgrid/lib/loader.php on line 19

**Comment by alvarotrigo** [comment]
I had to end up using composer...

**Comment by thinkingserious** [comment]
Hi @alvarotrigo,

My apologies, you received that last error because of [this bug](https://github.com/sendgrid/sendgrid-php/pull/634).

I'm glad you were able to get things going with Composer, it's an excellent tool.

With Best Regards,

Elmer

Thanks for helping out @martijnmelchers!

**Comment by alvarotrigo** [comment]
Thanks for the info!

**Comment by pleckie** [comment]
This bug is still here in Jan 2020.

Update the documentation on https://sendgrid.com/docs/for-developers/sending-email/v3-php-code-example/ 

It isn't helpful to the product to have stale documentation, and then just say 'Use composer' when it it Literally in the documentation.

**Comment by EvaLok** [comment]
@alvarotrigo @pleckie i made a PR that allows for standalone usage (still requires the `php-http-client` dependency, of course), not sure if they'll use it but may be useful for you :)
