### ISSUE TITLE
400 Bad Request for almost the same API call that worked previously

### ISSUE THREAD

**Issue by AlexandruI** [sendgrid/sendgrid-php#640]
#### Issue Summary

Recently upgraded the API to V3. All the API calls are working as expected, except one that is almost the same as a working one using PHP. 

**The working one:** 

2018-06-15 09:20:31 Info: Data: SendGrid\Mail Object
(
    [namespace:protected] => SendGrid
    [from] => SendGrid\Email Object
        (
            [name:SendGrid\Email:private] => HYCM
            [email:SendGrid\Email:private] => HYCM.EDD@hycm.com
        )

    [personalization] => Array
        (
            [0] => SendGrid\Personalization Object
                (
                    [tos:SendGrid\Personalization:private] => Array
                        (
                            [0] => SendGrid\Email Object
                                (
                                    [name:SendGrid\Email:private] => -
                                    [email:SendGrid\Email:private] => harry.charitou@hycm.com
                                )

                        )

                    [ccs:SendGrid\Personalization:private] =>
                    [bccs:SendGrid\Personalization:private] =>
                    [subject:SendGrid\Personalization:private] =>
                    [headers:SendGrid\Personalization:private] =>
                    [substitutions:SendGrid\Personalization:private] => Array
                        (
                            [%username%] => Test Test
                        )

                    [custom_args:SendGrid\Personalization:private] =>
                    [send_at:SendGrid\Personalization:private] =>
                )

        )

    [subject] =>
    [contents] =>
    [attachments] =>
    [template_id] => 15dbbbc6-4e84-460e-9a0c-717c77a42e7e
    [sections] =>
    [headers] =>
    [categories] =>
    [custom_args] =>
    [send_at] =>
    [batch_id] =>
    [asm] =>
    [ip_pool_name] =>
    [mail_settings] =>
    [tracking_settings] =>
    [reply_to] =>
)

**The one that failed:**

    [namespace:protected] => SendGrid
    [from] => SendGrid\Email Object
        (
            [name:SendGrid\Email:private] => HYCM_Api
            [email:SendGrid\Email:private] => customerservice@hycm.com
        )

    [personalization] => Array
        (
            [0] => SendGrid\Personalization Object
                (
                    [tos:SendGrid\Personalization:private] => Array
                        (
                            [0] => SendGrid\Email Object
                                (
                                    [name:SendGrid\Email:private] => -
                                    [email:SendGrid\Email:private] => ralph.melhem@eu.hycm.com
                                )

                        )

                    [ccs:SendGrid\Personalization:private] =>
                    [bccs:SendGrid\Personalization:private] =>
                    [subject:SendGrid\Personalization:private] =>
                    [headers:SendGrid\Personalization:private] =>
                    [substitutions:SendGrid\Personalization:private] => Array
                        (
                            [%message%] => Invalid Registration Request
                            [%username%] => -
                            [%file%] => registrations
                            [%level%] => 6
                        )

                    [custom_args:SendGrid\Personalization:private] =>
                    [send_at:SendGrid\Personalization:private] =>
                )

        )

    [subject] =>
    [contents] =>
    [attachments] =>
    [template_id] => 68248583-9855-41c5-9353-6a92f7a81b23
    [sections] =>
    [headers] =>
    [categories] =>
    [custom_args] =>
    [send_at] =>
    [batch_id] =>
    [asm] =>
    [ip_pool_name] =>
    [mail_settings] =>
    [tracking_settings] =>
    [reply_to] =>
)

**Comment by hyralph** [comment]
This was resolved by explicitly setting each substitution's value to String.
My suggestion would be to do that on the php library's model level to prevent it from happening to others

**Comment by paul-automox** [comment]
We just updated to v7 of the library and discovered a few of our calls simply returning a Bad Response from the API with no additional details.  Thanks to this thread, we forced our code to always send a string when adding template variables to the SendGrid PHP's `SendGrid\Mail\To` class.  Seems like this code may need to be updated:

https://github.com/sendgrid/sendgrid-php/blob/master/lib/mail/Substitution.php#L87
