### ISSUE TITLE
emails are not going to cc email address

### ISSUE THREAD

**Issue by harshit-jalhotra** [sendgrid/sendgrid-php#645]
Hello,

We are using sendgrid library to sending emails. We are able to send emails to email addresses in "To" however sendgrid is not sending emails to email addresses in "cc". It is showing email address in cc but not sending emails.

I tried sending emails using codeigniter library with sendgrid credentials and it works perfectly.

Kindly help.

**Comment by thinkingserious** [comment]
Hello @harshit-jalhotra,

To further assist, could you please provide the following information:

1. What version of this SDK are you using and how did you install it?
2. Please provide the relevant source code

Thanks!

With Best Regards,

Elmer
