### ISSUE TITLE
Personalization not adding properly

### ISSUE THREAD

**Issue by Premasanthakumar** [sendgrid/sendgrid-php#647]
When i add personalization and sent the mail to many different users the personalization never gets added.

**Comment by thinkingserious** [comment]
Hello @Premasanthakumar,

Do you mind sharing the relevant source code so that I may try to reproduce?

With Best Regards,

Elmer

**Comment by Premasanthakumar** [comment]
import java.io.IOException;

import com.sendgrid.Content;
import com.sendgrid.Email;
import com.sendgrid.Mail;
import com.sendgrid.Method;
import com.sendgrid.Personalization;
import com.sendgrid.Request;
import com.sendgrid.Response;
import com.sendgrid.SendGrid;

public class Welcome {
	public static void emailSendForRegister(String toUsername,String name,String custId) {
    	Email from = new Email("techadmin@thesyndicate.tech");
    	String subject = "Welcome to Spark";
    	Email to = new Email(toUsername);
    	Content content = new Content("text/html","hjb");
    	Mail mail = new Mail(from, subject, to, content);
    	
    	
     	mail.setTemplateId("Template ID");
    	

    	SendGrid sg = new SendGrid("Send-Grid API KEY");
        
    	Request request = new Request();
    	try {
    		 Personalization obj = new Personalization();
    		    obj.addSubstitution("%first_name%", name);
    	 	   obj.addSubstitution("%mid%", custId);
    	 	    obj.addTo(to);
    	    	 mail.addPersonalization(obj);
    	  request.setMethod(Method.POST);
    	  request.setEndpoint("mail/send");
    	  request.setBody(mail.build());
    	 
    	  Response response = sg.api(request);
    	  System.out.println(response.getStatusCode());
          System.out.println(response.getBody());
          System.out.println(response.getHeaders());
    	} catch (IOException ex) {
    		System.out.println(ex);
    	}
  }
	public static void main(String args[]) {
	String toUsername = "premas@thesyndicate.tech";
	String name = "Prema"; 
	String custId = "1271";
	emailSendForRegister(toUsername,name,custId);
}
}

**Comment by martijnmelchers** [comment]
This is not a PHP related issue. You should file your issue over at the [sendgrid-java](https://github.com/sendgrid/sendgrid-java/issues)  repository
