### ISSUE TITLE
Add Dynamic Template Support

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-php#648]
#### Issue Summary

On 7/24/2018, our team publicly launched dynamic content for transactional templates. It is now available for all customers sending over v3 of our Mail Send API. Iterate over lists, handle conditionals and more, thanks to native support for a subset of Handlebars syntax!

More information can be found in our [blog post announcement](https://sendgrid.com/blog/how-to-use-sendgrids-dynamic-templates-for-your-transactional-emails/).

You can currently use this feature by manually creating the request body as [shown here](https://github.com/sendgrid/sendgrid-php/blob/master/USAGE.md#v3-mail-send). 

Now, we need to create helper code and examples for this SDK.

#### Acceptance Criteria

* [Implement a helper similar to what we have for the legacy templates](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#transactional-templates)
* Update the [USE_CASES.md](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#transactional-templates) example to demonstrate the new *Dynamic Templates* using the helper and re-name the current example to *Legacy*

#### Documentation
- [Reference Implementation](https://github.com/sendgrid/sendgrid-nodejs/pull/691#issuecomment-407490342)
- [How to Send an Email With Dynamic Transactional Templates](https://sendgrid.com/docs/User_Guide/Transactional_Templates/how_to_send_an_email_with_transactional_templates.html)
- [Using Handlebars](https://sendgrid.com/docs/User_Guide/Transactional_Templates/Using_handlebars.html)
- [Interactive API Docs](https://dynamic-templates.api-docs.io/3.0/mail-send-with-dynamic-transactional-templates/v3-mail-send)

**Comment by martijnmelchers** [comment]
I will try to do this, can you assign me to this issue?

**Comment by thinkingserious** [comment]
That's fantastic @martijnmelchers!

I can't assign people to issues who are outside of the SendGrid org, so I've simply marked it as "status: work in progress".

**Comment by martijnmelchers** [comment]
@thinkingserious Could you merge PR #620 so I won't get conflicts and I can use the continue to use the improved PHPDocs?

**Comment by thinkingserious** [comment]
Yes, I'll get that one merged ASAP @martijnmelchers. Thanks for your patience!

**Comment by martijnmelchers** [comment]
I'll start once it's merged so no conflicts will occur.

**Comment by thinkingserious** [comment]
Thanks @martijnmelchers!

I apologize for the delay. I just want to make sure we are all synced up with respect to the style guidelines. Preferably in an automated way.

**Comment by alsuka** [comment]
Hi,
I found dynamic_template_data in personalizations can be used for sending transactional email via cURL call. ref:
https://sendgrid.com/docs/User_Guide/Transactional_Templates/how_to_send_an_email_with_transactional_templates.html
But I want to check is this lib(sendgrid-php) support for setting dynamic_template_data object?
https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#transactional-templates

much thanks!

**Comment by kylearoberts** [comment]
Hello @alsuka,

As of right now I think the helper for using dynamic_template_data is still being worked on, but you can still pass it in a JSON payload like is shown [here](https://github.com/sendgrid/sendgrid-php/blob/master/examples/mail/mail.php). The difference is you would want a payload that has the dynamic_template_data in each personalization like [this](https://sendgrid.com/docs/User_Guide/Transactional_Templates/how_to_send_an_email_with_transactional_templates.html#-Send-a-transactional-email). If you have further questions, please let us know.

- Kyle

**Comment by jaarkko** [comment]
Did we have documentation with examples on how to send dynamic data in a call?

**Comment by thinkingserious** [comment]
Hello @jaarkko,

[Here you go](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#transactional-templates). Thanks!

With Best Regards,

Elmer
