### ISSUE TITLE
Build smtp request to send to Mailhog 

### ISSUE THREAD

**Issue by Ridder90** [sendgrid/sendgrid-php#649]
I know this is a SDK for the web API. But can it be possible to build an  `\SendGrid\Mail\Mail` object and send it to a mailcatcher like Mailhog? I have some complex group mailings and it would be really handy to properly test e-mail on staging and development environments without burning the domain reputation. 

This would be something I am looking for. Or is there a more appropriated approach?
```
$email = new \SendGrid\Mail\Mail(); 
$email->setFrom("test@example.com", "Example User");
$email->setSubject("Sending with SendGrid is Fun");
$email->addTo("test@example.com", "Example User");
$email->addContent("text/plain", "and easy to do anywhere, even with PHP");
$email->addContent(
  "text/html", "<strong>and easy to do anywhere, even with PHP</strong>"
);
$sendgrid = new \SendGrid(getenv('SENDGRID_API_KEY'));

if(getenv('ENV') == 'PRODUCTION'){
  try {
    $response = $sendgrid->send($email);
  } catch (Exception $e) {
    echo 'Caught exception: ',  $e->getMessage(), "\n";
  }
}else{
  $smtp = $sendgrid->getSMTP( $email);
  $smtp->Host = 'mailhog';
  $smtp->Port = 1025;
  $smtp->send();
}
```

**Comment by thinkingserious** [comment]
Perhaps [this SDK](https://github.com/sendgrid/smtpapi-php) is what you need. Check it out and let me know. Thanks!

**Comment by Ridder90** [comment]
Thanks! I think that this could probably work. However I just updated to v7.0.0 and updated my code accordingly. I really like the personalization API: 
```
new \SendGrid\Mail\To( $i->user_email, $i->display_name, array(
  '%NAME%' => $i->display_name, 
  '%ID%' => $i->ID 
));
```
Change it back to the below example really feels like a step backwards. 
```
$header->addTo($i->user_email);
$header->addSubstitution('%NAME%', array($i->display_name));
$header->addSubstitution('%ID%', array($i->ID));
```
I think I will stick with this SDK then. If you have any other suggestions on testing with this SDK I will be glad to here them. Else you could close this issue. 

Thanks for the help anyway!

**Comment by thinkingserious** [comment]
Have you tried using the [Sandbox Mode](https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/sandbox_mode.html)?

Alternatively, [Prism](https://sendgrid.com/blog/stoplight-io-to-test-api-endpoints/) may be useful for your use case.

**Comment by Ridder90** [comment]
Thanks for the follow up! Sandbox mode would be perfect if it would return something i can push to Mailhog.

Last month i made a huge mistake. When updated to v7 i used a snippet like this to send some transactions e-mail to about 50 persons. 
```
$email = new \SendGrid\Mail\Mail(); 
$email->setFrom($from, $fromName);
$email->setSubject($subject);
$email->addContent("text/html",$body);
$email->addCategory($template);
$email->addContent("text/plain", $text);
// < v7 I used
// $email->setSmtpapiTos($tos);

foreach ($tos as $email => $name) {
 	 // Mistakes where made...
	 $email->addTo($email, $name);
}

 $email->addSubstitutions($SUBS);
  
```
I tested it with Sandbox Mode and it succeeded. I send a test mail to myself and i (and only i) received the mail in perfect order. In my production environment i send the mail to 50 persons and disaster happened. Instead of 50 different mails, one mail was send to 50 persons with all e-mail adresses visible to one and another. Not so nice in times of GDPR. 

This mistake could have been avoided if I could test the mail object with Mailhog.

I am not really seeing how Prism can help. Sorry.

**Comment by thinkingserious** [comment]
Hello @Ridder90,

I believe [this](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#send-multiple-emails-to-multiple-recipients) is the use case you need.

When testing multiple emails, I suggest using emails such as dx+test1@sendgrid.com, dx+test2@sendgrid.com, etc...

I hope that helps.

With Best Regards,

Elmer

**Comment by Ridder90** [comment]
Thanks Elmer, it is already working fine. Still looking for a feature to catch email en a test inbox or something like mailhog though. 

What does the dx+test**n**@sendgrid.com adresses do? Do you have any documentation?

**Comment by thinkingserious** [comment]
I just use dx+<something>@sendgrid.com to do tests where I need to send to multiple email addresses. That way, all the test emails appear in the same inbox, saving a bit of time.

https://www.quora.com/Is-there-any-free-alternative-to-mailtrap-ios-services) that I hope may be useful to you.

**Comment by Ridder90** [comment]
This workaround works for me:
```
if(getenv('ENV') == 'DEV'){
	$email->enableSandBoxMode();
	foreach ($email->getPersonalizations() as $i) {
		foreach ($i->getTos() as $t) {
                         //send each email in each personalization to mailhog
			wp_mail($t->getEmail(), $this->subject, $this->body);
		}
	}
}

try {
	$result = $sg->send( $email );
} catch(\SendGrid\Exception $e) {
	error_log($e);
}
```
