### ISSUE TITLE
PDF corrupted in sendgrid email template

### ISSUE THREAD

**Issue by NavinGelot** [sendgrid/sendgrid-php#654]
#### Issue Summary

Hello, 
In sendgrid template email integration i  am sending json as body to work around with template

i am getting everything right as i want but PDF is not opening in email.
it works with TXT file but not with PDF is anything that i am missing

####code

```
val originalInput = "test input"
      val geek_output = new ByteArrayOutputStream()
      geek_output.write(originalInput.getBytes(), 0, originalInput.getBytes().length)
      val encodedPdf = new String(Base64.getEncoder.encode(geek_output.toByteArray))

      val pdf = new Attachments
      pdf.setFilename("test.pdf")
      pdf.setContent(encodedPdf)

      val request = new Request
      request.setMethod(Method.POST)
      request.setEndpoint("mail/send")
      request.setBody(s"""{"reply_to": ${mapper.writeValueAsString(replyTo)}, "from": ${mapper.writeValueAsString(from)},"personalizations": [{"dynamic_template_data": $dynamicTemplate, "to": [${mapper.writeValueAsString(to)}]}], "template_id": "template_id", "attachments": [${mapper.writeValueAsString(pdf)}], "content": [{"type": "text/html", "value": " "}]}""".stripMargin)

      val sg = new SendGrid("mykey")
      val response = sg.api(request)
```

#### Technical details:

sendgrid version: 
compile group: 'com.sendgrid', name: 'sendgrid-java', version: '4.2.1'

**Comment by martijnmelchers** [comment]
Hi, this is another issue related to [sengrid-java](https://github.com/sendgrid/sendgrid-java/) please file an issue at that directory

**Comment by NavinGelot** [comment]
Hi @martijnmelchers ,
Thanks for your reply 

i have tried that example with TXT file but not with PDF

https://github.com/sendgrid/sendgrid-java/blob/master/src/test/java/com/sendgrid/helpers/AttachmentBuilderTest.java

**Comment by martijnmelchers** [comment]
Hi, I understand that it is not working but this library for PHP you should file an issue at the Java library with the link provided above.
