### ISSUE TITLE
Search contact having a custom_fields specific value

### ISSUE THREAD

**Issue by mikoelsuperbeasto** [sendgrid/sendgrid-php#655]
Hello,

#### Issue Summary
I'm trying to search all contacts having a custom_fields with specific values and then get a total count but what ever i do, it return this: The following parameters are not custom fields or reserved fields..

Here is the custom field data:

```
{
    "id": 2472636,
    "name": "referral",
    "type": "text"
}
```

#### Steps to Reproduce
```
$query_params = json_decode('{"{referral}": "email@domain.com"}');
$response = $sg->client->contactdb()->recipients()->search()->get(null, $query_params);
echo $response->statusCode();
echo $response->body();
print_r($response->headers());
```
Look like we can't search for custom fields... ?

**Comment by thinkingserious** [comment]
Hello @mikoelsuperbeasto,

Were you able to get your issue resolved?

With Best Regards,

Elmer
