### ISSUE TITLE
Got 403 error code when get mail activity

### ISSUE THREAD

**Issue by lamkhtn** [sendgrid/sendgrid-php#664]
I got 403 error when try to get all mail activity

{"errors":[{"field":null,"message":"access forbidden"}]}

This is my code in laravel 5.5

$sg = new \SendGrid(config('app.sendgrid_api_key'));
		$request_body = json_decode('{
		  "enabled": true
		}');
		$response = $sg->client->tracking_settings()->open()->patch($request_body);
		dump($response->body());
		die();

**Comment by thinkingserious** [comment]
Hello @lamkhtn,

This is an API Key issue, here are a couple of things to try:

1. Double check the value of `app.sendgrid_api_key` in your application.
2. Try making a [simple cURL call](https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/curl_examples.html) with your API key to rule out if the API key itself is not functional.

If it's number 1, please try creating a new API key in the UI.

With Best Regards,

Elmer

**Comment by fbarcelo-cirsa** [comment]
I start to use API, to check message activity to verify if mail was delivered. This feature is very, very basic. I'm very disappointed with sendgrid.

**Comment by thinkingserious** [comment]
Hello @fbarcelo-cirsa,

I'm not quick sure I understand what went wrong. Are you saying that after making your API call, you do not see the request on your [Dashboard](https://app.sendgrid.com/email_activity)? 

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @fbarcelo-cirsa,

This means there is an issue with your API Key. I suggest you reach out to our [support team](https://support.sendgrid.com) to help resolve your issue.

**Comment by mayurkumarbajaj** [comment]
@fbarcelo-cirsa maybe you did not give the required permission while setting API key.
Create a new key with Full Access, and try again with a newly created key.

I also faced the similar issue, I solved it by using the full access api key.

Hope this will help.

**Comment by ducpp7406** [comment]
I encountered exacly the same issue. I tried to use the newly created full access API key, but it didnt help. I think SendGrid should investigate this issue seriously.

**Comment by jackbaron** [comment]
Yeah maybe i found the problem. To request the API email activity you need to pay an extra fee.
https://sendgrid.api-docs.io/v3.0/email-activity/filter-all-messages
