### ISSUE TITLE
Invalid smtpapi with new templates, it works with Legacy

### ISSUE THREAD

**Issue by mwleinad** [sendgrid/sendgrid-php#666]
#### Issue Summary

The header looks like this

`{"sub":{":cta_button":["https:\/\/cloud.ilosvideos.com\/user\/verifyEmail?email=daniel.lopez54%40vidgrid.com&verify=v156383t5b71c414c9640"]},"filters":{"templates":{"settings":{"enabled":1,"template_id":"d-836f5a25d6734f989625c81a9916f00d"}}}}`

#### Steps to Reproduce

The only difference between a working delivered email and not being delivered is the template_id
If I change the template id

And the difference I see is that the old template id is a UUID
3493a166-f1fa-4a4b-acbb-58bab464da5c

and the new one has a new format
d-836f5a25d6734f989625c81a9916f00d

Did the header change? Do I need to send different parameters?

#### Technical details:

*API V2
* PHP Version: 7.1

**Comment by thinkingserious** [comment]
Hello @mwleinad,

You will need to use the legacy templates with the SMTPAPI. Dynamic Templates are only supported in v3 of our API.

This SDK has rudimentary support with helper code on the way, please follow [this issue](https://github.com/sendgrid/sendgrid-php/issues/648) for details and progress.

With Best Regards,

Elmer
