### ISSUE TITLE
isBase64 function problem which added in version 7.0.1

### ISSUE THREAD

**Issue by developer-devPHP** [sendgrid/sendgrid-php#667]
#### Issue Summary

A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, code examples.

#### Steps to Reproduce

1. Try to send as an attachment text file which contains  for example \n
2. Before setContent call convert your attachment as base64

After all this process the isBase64 function will return false, because it not passed ctype_print
#### Technical details:

This issue in version 7.0.1 and came from  merge with number #618

my suggestion to change isBase64 function something like this

```php
private function isBase64($string) {
   $decoded_data = base64_decode($string, true);
   $encoded_data = base64_encode($decoded_data);
   if ($encoded_data != $string) return false;
   else{ 
        $decoded_data=str_ireplace("\t","",$decoded_data);
        $decoded_data=str_ireplace("\n","",$decoded_data);
        $decoded_data=str_ireplace("\r","",$decoded_data);
        if (!ctype_print($decoded_data)) 
            return false;
        }
   
   return true;
}
```

so new part is this 
```php
$decoded_data=str_ireplace("\t","",$decoded_data);
$decoded_data=str_ireplace("\n","",$decoded_data);
$decoded_data=str_ireplace("\r","",$decoded_data);
```

**Comment by developer-devPHP** [comment]
@thinkingserious  Could you please check this.

**Comment by developer-devPHP** [comment]
@martijnmelchers not only \n. For example if it is contained some formatting text with \n
like this:
```text
some text
some additional text
```
in this situation `ctype_print` will return `false`

**Comment by developer-devPHP** [comment]
Just run this simple check
```php
var_dump(ctype_print('some text
some additional text'));
```

**Comment by thinkingserious** [comment]
Nice find @developer-devPHP!

Please allow us to send you some swag by filling out [this form](ttps://dx.sendgrid.com/swag).

Thanks!
