### ISSUE TITLE
The from object must be provided for every email send. It is an object that requires the email parameter, but may also contain a name parameter

### ISSUE THREAD

**Issue by ntt13793** [sendgrid/sendgrid-php#672]
when i use that function to send email. It has some errors: {"errors":[{"message":"The from object must be provided for every email send. It is an object that requires the email parameter, but may also contain a name parameter. e.g. {\"email\" : \"example@example.com\"} or {\"email\" : \"example@example.com\", \"name\" : \"Example Recipient\"}

```php
function helloEmail()
{
    try {
        $from = new From(null, "test@example.com");
        $subject = "Hello World from the SendGrid PHP Library";
        $to = new To(null, "test@example.com");
        $content = new Content("text/plain", "some text here");
        $mail = new Mail($from, $to, $subject, $content);
        $to = new To(null, "test2@example.com");
        $mail->addPersonalization($to);
        //echo json_encode($mail, JSON_PRETTY_PRINT), "\n";
        return $mail;
    } catch (\Exception $e) {
        echo $e->getMessage();
    }
    return null;
}
``php

Can you help me?

**Comment by thinkingserious** [comment]
Hello @ntt13793,

What is happening is that when you do this `$mail->addPersonalization($to);` you are creating a second personalization, which does not have a from address. The first personalization is created under the hood in this statement `$mail = new Mail($from, $to, $subject, $content);`

I believe what you are trying to do is send 1 email to multiple recipients. In that case, please see [this example](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#send-an-email-to-multiple-recipients).

With Best Regards,

Elmer

**Comment by ntt13793** [comment]
thank you so much
