### ISSUE TITLE
Email activity API rate limit issue

### ISSUE THREAD

**Issue by ashuomble5** [sendgrid/sendgrid-php#673]
I am using email activity API in my web application to get each user's data.
While doing so I am running cronjob script for gathering all the users at one go.
But sometimes it fails when I make a call to API. I know that sendgrid uses rate limitation for every API at some threshold which bans the originating IP for some time.
But I want to know how much requests are possible at one go so we can change the logic accordingly.
This is the error response I am getting:
![2018-08-16-15-35-localhost](https://user-images.githubusercontent.com/26411777/44252495-01550a80-a21a-11e8-85fa-ae067df04bea.png)

Also is there any better way to tackle this issue?

**Comment by martijnmelchers** [comment]
You can see the requests remaining in the headers. More info can be found [here](https://sendgrid.com/docs/API_Reference/Web_API_v3/How_To_Use_The_Web_API_v3/rate_limits.html)

**Comment by thinkingserious** [comment]
Thanks for helping out @martijnmelchers!

@ashuomble5,

[See this documentation](https://sendgrid.com/docs/API_Reference/Web_API_v3/How_To_Use_The_Web_API_v3/rate_limits.html) regarding our rate limits. tl;dr; you can not increase the rate limit.

To see the headers:

```php
$response = $sendgrid->send($email);
print_r($response->headers());
```

With Best Regards,

Elmer

**Comment by ashuomble5** [comment]
Hi @thinkingserious, 
Thanks for mentioning the reference, as we are dealing with the large amount of data we moved to webhooks from email activity. I am closing this issue.
Once again thanks for the help.
