### ISSUE TITLE
Autoloader not working when not using composer

### ISSUE THREAD

**Issue by morazain** [sendgrid/sendgrid-php#677]
#### Issue Summary

I moved some working code from one of my sites to another. The code sends personalized emails using the V3 API. When I ran the new installation of the code, I got the following  fatal error:
   **Class 'SendGrid\Content' not found**
Line 2 below that generated the error:
   $sg = new \SendGrid( $apiKey );
   $content = new SendGrid\Content( "text/html", $msg ); 
    $mail = new SendGrid\mail();
Thinking that perhaps  the SnedGrip libraries on the site were noty up to date,  I downloaded the latest api zip (7.2.0) uploaded it to the site and still got the same error.

So I flipped the two lines
   $sg = new \SendGrid( $apiKey );
    $mail = new SendGrid\mail();
   $content = new SendGrid\Content( "text/html", $msg ); 
and got the fatal error:
   C lass SendGrid\Mail not found

#### Steps to Reproduce

see above

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

This happened the first time I tried to use V3 a year or two ago. There were two files that I downloaded to fix the problem but cant find a reference to them anymore.

#### Technical details:

* sendgrid-php Version: V3 VERSION = '7.2.0'
* PHP Version: PHP Version 5.6.30

**Comment by thinkingserious** [comment]
Hello @morazain,

Can you verify that your code is using the correct path? `require("<PATH TO>/sendgrid-php.php");`

With Best Regards,

Elmer

**Comment by morazain** [comment]
I did. I don't get an error on the require_once below and it does not error
on $sg = new SendGrid($apikey);

require_once(ABSPATH
."/custom/SendGridV7.2.0/sendgrid-php/sendgrid-php.php");

Cheers,

Guy Morazain
Follow Me <http://twitter.com/GuyMorazain>

**Comment by thinkingserious** [comment]
Hi @morazain,

Can you try `\SendGrid\Content` and `\SendGrid\Mail`? Thanks!

**Comment by morazain** [comment]
Same problem *Fatal error*: Class 'SendGrid\Content' not found in
Cheers,

Guy Morazain
Follow Me <http://twitter.com/GuyMorazain>

**Comment by thinkingserious** [comment]
Hi @morazain,

Here are the steps I performed to try and reproduce:

1. mkdir sendgrid-php-test
2. cd sendgrid-php-test
3. wget https://github.com/sendgrid/sendgrid-php/releases/download/v7.2.0/sendgrid-php.zip
4. unzip sendgrid-php.zip
5. vi test.php

```php
<?php
require("./sendgrid-php/sendgrid-php.php");

$email = new \SendGrid\Mail\Mail(); 
$email->setFrom("dx@sendgrid.com", "Example User");
$email->setSubject("Sending with SendGrid is Fun");
$email->addTo("elmer.thomas@sendgrid.com", "Example User");
$email->addContent("text/plain", "and easy to do anywhere, even with PHP");
$email->addContent(
    "text/html", "<strong>and easy to do anywhere, even with PHP</strong>"
);
$sendgrid = new \SendGrid(getenv('SENDGRID_API_KEY'));
try {
    $response = $sendgrid->send($email);
    print $response->statusCode() . "\n";
    print_r($response->headers());
    print $response->body() . "\n";
} catch (Exception $e) {
    echo 'Caught exception: '. $e->getMessage() ."\n";
}
```
6. :wq
7. php test.php
8. Works as expected

I'm running PHP version 7.1.16

**Comment by morazain** [comment]
That works for me too. However you are not using Content

I notice that  you used $mail = new \SendGrid\Mail\Mail(); and I was
using $mail = new \SendGrid\Mail();
so I changed it and it no longer bombs on that line but still bombs on:
$content = new \SendGrid\Content("text/html", $b);

Anyway I went back to the previous version of V3 and it worked fine. It
produces this when I run it:

 /home/content/p3pnexwpnas05_data01/45/2889745/html/mail/97/body.txt
This is a test |first| |date|
Attachements


   1. Men\'s_League_Draw.pdf
      <http://vernoncurling.com/mail/97/Mens_League_Draw.pdf>


/home/content/p3pnexwpnas05_data01/45/2889745/html/mail/97/ids.txt
966;43
2 Emails Sent!


So you still have issues with 7.2.0  The same code placed in the
SendGridV7.2.0 directory does this:

 /home/content/p3pnexwpnas05_data01/45/2889745/html/mail/97/body.txt
This is a test |first| |date|
/home/content/p3pnexwpnas05_data01/45/2889745/html/mail/97/ids.txt
966;43

*Fatal error*: Class 'SendGrid\Content\Content' not found in
*/home/content/p3pnexwpnas05_data01/45/2889745/html/custom/SendGridV7.2.0/newSendEmail_new.php*
on line *29*


Regards,

Guy

**Comment by thinkingserious** [comment]
Hello @morazain,

For the content object, please use `\SendGrid\Mail\Content`. You can view a [full example here](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#kitchen-sink).

Thanks for following up!

With Best Regards,

Elmer
