### ISSUE TITLE
Substitustions get overritten when adding To after creating Mail object

### ISSUE THREAD

**Issue by RaoulWernert** [sendgrid/sendgrid-php#678]
Hi,

I'm trying to achieve the usecase Send Multiple Emails to Multiple Recipients but in a slightly different manner. I'm creating the Mail object first and after that, using the addTo function to add a new To with it's own substitutions like this:

```
$from = new From(INFO_EMAIL_ADDRESS, INFO_EMAIL_NAME);
$mail = new Mail($from);

$to1 = new To($email1, $name1, array('-company_name-' => $company1->name));
$mail->addTo($to1);

$to2 = new To($email2, $name2, array('-company_name-' => $company2->name));
$mail->addTo($to2);
```

But when i var_dump $mail the length of tos is 2 but the length of substitutions is only 1 and it holds only the substitution of the last added one, is this intentional?

Thank you in advance

* sendgrid-php Version: 7.0.0
* PHP Version: 7.2

vardump of getPersonalizations:
```
array (size=1)
  0 => 
    object(SendGrid\Mail\Personalization)[46]
      private 'tos' => 
        array (size=2)
          0 => 
            object(SendGrid\Mail\To)[45]
              ...
          1 => 
            object(SendGrid\Mail\To)[47]
              ...
      private 'ccs' => null
      private 'bccs' => null
      private 'subject' => null
      private 'headers' => null
      private 'substitutions' => 
        array (size=1)
          '-company_name-' => string 'CompanyName2' (length=13)
      private 'dynamic_template_data' => null
      private 'has_dynamic_template' => boolean false
      private 'custom_args' => null
      private 'send_at' => null
```

**Comment by thinkingserious** [comment]
Hello @RaoulWernert,

[This example](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#send-multiple-emails-to-multiple-recipients) achieves the Send Multiple Emails to Multiple Recipients use case.

I hope that helps!

With Best Regards,

Elmer
