### ISSUE TITLE
Delete multiple recipient from a list

### ISSUE THREAD

**Issue by iamanupammaity** [sendgrid/sendgrid-php#681]
How can I delete multiple recipients from a list In PHP?
#### Issue Summary

A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, code examples.

#### Steps to Reproduce

1. This is the first step
2. This is the second step
3. Further steps, etc.

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* sendgrid-php Version: master (latest commit: [commit number])
* PHP Version: 5.6, 7.0, 7.1, 7.2 (as of May 17, 2018)

**Comment by thinkingserious** [comment]
Hello @iamanupammaity,

I think this is the [relevant documentation](https://github.com/sendgrid/sendgrid-php/blob/master/USAGE.md#delete-recipient).

With Best Regards,

Elmer

**Comment by iamanupammaity** [comment]
Thanks for the reply. However, my requirement is different. This code deletes the email id from all list and main list (All Contacts). I just want to remove multiple users from a specific list not the other lists,  

For example, there are 4 lists. list 1, list 2, list 3 and list 4. 
Now, I want to delete abc@abc.com and xyz@abc.com. Consider these two email id is present in three lists - list 1, list 2 and list 3. 

I now want to remove these two email id only from list 2 (not from list 1 and list 3). 

Kindly suggest how to do?

Thanks for your help.

**Comment by Jericho** [comment]
@iamanupammaity Removing multiple recipients from a list in a single API call is available in SendGrid's API but it's not documented. [I brought this up](https://github.com/sendgrid/sendgrid-csharp/issues/690) to @thinkingserious's and @ksigler7's attention several months ago and I was told the documentation would be corrected. However I don't see that it was updated.

**Comment by iamanupammaity** [comment]
Yes, it seems it is unavailable. 

 However, I have another query. Can I empty a list by API?

**Comment by thinkingserious** [comment]
Hello @iamanupammaity,

No, you can not empty a list by API directly in one call. Maybe deleting and recreating the list might be what you need?
