### ISSUE TITLE
Update integration tests to utilize StopLight.io's Prism version v2.X

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-php#690]
#### Issue Summary

We use a mock server for integration/contract testing that is driven by our OpenAPI specification and StopLight.io's Prism service. The service is spun up utilizing the prism.sh script in this repo.

Before writing any code, we suggest you review our `CONTRIBUTING.md` file and propose your solution for discussion here in the comments. Thank you!

#### Aceptance Criteria

* we automatically use the latest v2.X version of Prism locally, in Travis CI and in Docker
* tests pass locally, in Travis CI and using Docker
* update `CONTRIBUTING.md` documentation, if necessary

#### Notes & References

* [Prism GitHub Repo](https://github.com/stoplightio/prism)

**Comment by geryjuhasz** [comment]
https://github.com/sendgrid/sendgrid-php/pull/698
