### ISSUE TITLE
Implement auto-deploy to package manager

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-php#700]
#### Issue Summary

When all tests on the master branch pass in Travis CI, we would like to auto-deploy the release to the package manager.

Before writing any code, we suggest you review our `CONTRIBUTING.md` file and propose your solution for discussion here in the comments. Thank you!

#### Aceptance Criteria

* when Travis CI passes all tests on the master branch we auto-deploy to the package manager
* the version is determined by the `CHANGELOG.md`

**Comment by geryjuhasz** [comment]
@thinkingserious which package manager ? :)

**Comment by DCzajkowski** [comment]
I could work on that, but in the case of PHP and Packagist it doesn't really make sense. On Packagist, package version is determined by a git tag on the master branch. So deploying to Packagist as easy as creating a new tag. It seems over-the-top to automate that process, don't you think?

Also, how could we determine a version based on the `CHANGELOG`? Parse the .md file in search of  a line that matches a regex?

**Comment by thinkingserious** [comment]
@geryjuhasz Packagist.

@DCzajkowski,

Currently, to make a release to Packagist, I add the release [here](https://github.com/sendgrid/sendgrid-php/releases), which also includes building the downloadable version of this SDK. Do you think that can be automated via Travis CI?

Thanks!

**Comment by DCzajkowski** [comment]
It may be possible, but I have some questions:
- Why do you build `.zip` manually and what is the process of bundling it? `composer install && zip -r sendgrid-php.zip .`?
- Can the version be determined from `composer.json` instead of `CHANGELOG.md`?

**Comment by childish-sambino** [comment]
Done.
