### ISSUE TITLE
Run our *.md documents in this repo through the Grammer.ly service and update

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-php#709]
#### Issue Summary

We would like to get our English polished up throughout the repo.

#### Aceptance Criteria

* Every .md file in this repo has been run through the Grammer.ly service and updated accordingly

**Comment by ssiddhantsharma** [comment]
@thinkingserious Taking this up!

**Comment by thinkingserious** [comment]
Thank you @ssiddhantsharma!
