### ISSUE TITLE
Update documenation for retrieving a list of all templates (dynamic & legacy)

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-php#711]
#### Issue Summary

Please update the `USAGE.md` and corresponding `\example` with the call to list all templates. 

This is the API call required: GET https://api.sendgrid.com/v3/templates?generations=legacy,dynamic

#### Acceptance Criteria

* The Usage.md file demonstrates how to use this API call to retrieve all templates: GET https://api.sendgrid.com/v3/templates?generations=legacy,dynamic
* The corresponding `/example` file demonstrates how to use this API call to retrieve all templates: GET https://api.sendgrid.com/v3/templates?generations=legacy,dynamic

**Comment by renshuki** [comment]
Let me take this one too.

**Comment by thinkingserious** [comment]
Thank you @renshuki! Awesome!
