### ISSUE TITLE
Fix broken link in TROUBLESHOOTING.md

### ISSUE THREAD

**Issue by arshadkazmi42** [sendgrid/sendgrid-php#713]
#### Issue Summary

Following links are broken in [TROUBLESHOOTING.md](https://github.com/sendgrid/sendgrid-php/blob/master/TROUBLESHOOTING.md#testing-v3-mailsend-calls-directly)
- v3 send email example link is broken

**Comment by arshadkazmi42** [comment]
working on it

**Comment by childish-sambino** [comment]
Closed by #770
