### ISSUE TITLE
Create campain Issue

### ISSUE THREAD

**Issue by VirendraArekar** [sendgrid/sendgrid-php#730]
`{
  "title": "March Newsletter",
  "subject": "New Products for Spring!",
  "sender_id": 124451,
  "list_ids": [
    110,
    124
  ],
  "segment_ids": [
    110
  ],
  "categories": [
    "spring line"
  ],
  "suppression_group_id": 42,
  "custom_unsubscribe_url": "",
  "ip_pool": "marketing",
  "html_content": "<html><head><title></title></head><body><p>Check out our spring line!</p></body></html>",
  "plain_content": "Check out our spring line!"
}
`
url = POST https://api.sendgrid.com/v3/campaigns HTTP/1.1

My question is how to create campaign
what is the meaning of list_ids and segment ids also how can i pass my database contacts to create campaign please sir help me.

**Comment by Braunson** [comment]
@VirendraArekar 

### Example code to create a campaign

You can see how to create a campaign with the API in the `examples/campaigns/campaign.php` file in the repo located at  https://github.com/sendgrid/sendgrid-php/blob/master/examples/campaigns/campaigns.php#L15-L43

### [Campaigns](https://sendgrid.com/docs/glossary/campaigns/)

> Campaigns are used to send custom email templates to targeted recipient segments. In utilizing the Marketing Campaigns UI or API, one can create a sender identity, upload contacts, set up unsubscribe groups, edit email templates, and create a campaign to send specifically tailored email to different email group segments and boost your email marketing.

### [Lists](https://sendgrid.com/docs/glossary/lists/)

> Lists are static collections of Marketing Campaigns contacts. By default, the ALL CONTACTS section stores any new contacts you add. You may create new lists when adding contacts either manually, or when uploading a CSV (comma separated values) file. When you send an email campaign, you can add contact lists to the specific recipient segments you wish to target.

### [Segments](https://sendgrid.com/docs/glossary/segments/)

> Segments are dynamic collections of Marketing Campaigns contacts grouped, or segmented, based on the criteria you define. Groups can include data you track about them, such as gender, location, birthday, or package type, or how they've engaged with your emails previously. You can create a segment that pulls from ALL CONTACTS or a specific existing list.

SendGrid has a helpful glossary which can help you understand the different terms, it's here at https://sendgrid.com/docs/glossary/segments/

**Comment by thinkingserious** [comment]
Thanks for helping out @Braunson!

@VirendraArekar,

Do you still need any help?

With Best Regards,

Elmer

**Comment by AttaurrehmaanBhatti687** [comment]
I am creating a marketing campaign but it is not working and returning this error (errors field null message authorization required).

This is my code:
$curl = curl_init();
// Set some options - we are passing in a useragent too here
curl_setopt_array($curl, [
CURLOPT_RETURNTRANSFER => 1,
CURLOPT_URL => 'https://api.sendgrid.com/v3/campaigns',
CURLOPT_USERAGENT => 'Codular Sample cURL Request',
CURLOPT_POST => 1,
CURLOPT_POSTFIELDS => [
'title' => 'March Newsletter',
'subject' => 'New Products for Spring!',
'sender_id' => '',
'list_ids' => array("", ""),
'segment_ids' => array(""),
'categories' => array("spring line"),
'suppression_group_id' => 122,
'custom_unsubscribe_url' => '',
'ip_pool' => 'marketing',
'html_content' => '<title></title>

Check out our spring line!

',
'plain_content' => 'Check out our spring line!',
]
]);
// Send the request & save response to $resp
$resp = curl_exec($curl);
// Close request to clear up some resources
curl_close($curl);


Please clear about list_ids, segment_ids, sender_id

**Comment by thinkingserious** [comment]
Hello @VirendraArekar,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
