### ISSUE TITLE
Wrong condition in /mail/EmailAddress.php

### ISSUE THREAD

**Issue by smrtab** [sendgrid/sendgrid-php#739]
Good day,

The next condition on line 73 is wrong (file /mail/EmailAddress.php).
`if (!is_string($emailAddress) && filter_var($emailAddress, FILTER_VALIDATE_EMAIL))`

It turns out that email address shouldn't be a string and should be a valid address simultaneously in order to throw exception.

Probably the right condition is:
`if (!(is_string($emailAddress) && filter_var($emailAddress, FILTER_VALIDATE_EMAIL)))`

**Comment by adamjpeterson** [comment]
FYI this logic seems to fail once over 10000 times or so, such that the error is thrown when it shouldn't be. We are forcing the email to a string and legitimate emails are still throwing this exception. We've had to comment out this validation because it craps out too often.
