### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages. 

### ISSUE THREAD

**Issue by claudiumstoica** [sendgrid/sendgrid-php#75]
https://github.com/sendgrid/sendgrid-php/blob/v1.1.4/composer.json
line 8-11
mashape/unirest-php needs to be an uppercase M
since composer is seeing everything strict now
as mentioned in this github issue of composer: https://github.com/composer/composer/issues/2690

This is the error our users are receiving when attempting to install SendGrid PHP with the new version of composer : Your requirements could not be resolved to an installable set of packages.

**Comment by NoahTwine** [comment]
@motdotla You are a gentlemen and a scholar. Thanks.
