### ISSUE TITLE
no error no email

### ISSUE THREAD

**Issue by prashant-saxena** [sendgrid/sendgrid-php#752]
Hi,

Using v3 api.
1. Created a template for conformation of newsletter subscription.
2. Subject is defined there.
3. Created a button, and link is set to %subscribe%

	
```
$link = 'http://www.mysite.com/subscribe?sub=' . $uuid;
$from = new From('no-reply@mysite.com', "Mysite");
$to = new To('test@test.com', 'Example');
$email = new Mail($from, $to);
$email->addSection("%subscribe%", $link);
$email->setTemplateId("d-xxxxxxxxxxxxxxxxxxxxxxxxxxx");
						
$sendgrid = new \SendGrid(Config::SENDGRID_API_KEY);
try {
	$response = $sendgrid->send($email);
	Log::Notice($response->statusCode()); //202
	Log::Notice($response->headers());
	Log::Notice($response->body());
	return true;
} catch (Exception $e) {
	Log::Error($e->getMessage());
	return false;
}
```
I am getting 202 as status code but not receiving any email.

I would also like to know that when sending newsletter(multiple recipient) using template where I just need to add an unubscribe link individually to every **To** . How do i do it? For example
```
$tos = [];
for ($result as $row)
{
$tos[] = new To($row['email], $row['name], ['%unsubscribe%' => $row['link']])
}
// send emails
$email = new Mail($from, $tos);
```

* sendgrid-php Version: master (latest commit: [commit number])
* PHP Version: 5.6.30

**Comment by DrMeloMoney** [comment]
Hi @prashant-saxena I believe this issue is a Support request. I'll will work with you on ticket #1665493.

**Comment by tudders** [comment]
Did this get resolved. I'm getting a 202, but no emails delivered and buried within the response is something about  [11] => X-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html.

It's only with templates that this fails to deliver and this response appears. That is, if I send a vanilla email it will return an 202 and I get the email. When I use any variation of the demo code for templates, I get the 202, no email, and a X-No-CORS-Reason.

I'm using PHP 7.0, SDK as of today, via composer (7.2.1) and IIS.
