### ISSUE TITLE
Type Exception Handling for the Mail Helper

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-php#754]
#### Issue Summary

The appropriate types necessary for a successful `mail/send` API call is documented [here](https://sendgrid.com/docs/API_Reference/api_v3.html). We want to throw a type exception when the wrong type is provided.

#### Acceptance Criteria

* All parameters for the `mail\send` endpoint are type checked and if they fail the type check and exception is thrown with instructions on how to fix

**Comment by max-arias** [comment]
Hi, is this up for grabs? I'd like to give it a shot.
