### ISSUE TITLE
How to track 3 days email sent history

### ISSUE THREAD

**Issue by iamanupammaity** [sendgrid/sendgrid-php#786]
I want to know how to get the email history of the last three days. I want details like - which email id received the emails(subject of emails), which email id opened the email, links clicked,

**Comment by thinkingserious** [comment]
Hello @iamanupammaity,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by iamanupammaity** [comment]
> Hello @iamanupammaity,
> 
> Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at https://support.sendgrid.com.
> 
> Thank you!
> 
> SendGrid DX Team



> Hello @iamanupammaity,
> 
> Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at https://support.sendgrid.com.
> 
> Thank you!
> 
> SendGrid DX Team

However, I send email using this Library. Like this, I want to fetch the History/event data using this library.
for example In your library https://github.com/sendgrid/sendgrid-php/blob/master/USAGE.md#stats if I run the code, output is given mail delivered, open, requests etc in a day.
Like this, I want to get the date email id, subject, status etc.

The support team https://support.sendgrid.com. gav this lnk where the structure of output is given https://sendgrid.com/docs/API_Reference/Event_Webhook/event.html But, how can I get the data using PHP.

**Comment by iamanupammaity** [comment]
> Hello @iamanupammaity,
> 
> Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at https://support.sendgrid.com.
> 
> Thank you!
> 
> SendGrid DX Team

However, I send email using this Library. Like this, I want to fetch the History/event data using this library.
for example In your library https://github.com/sendgrid/sendgrid-php/blob/master/USAGE.md#stats if I run the code, output is given mail delivered, open, requests etc in a day.
Like this, I want to get the date email id, subject, status etc.

The support team https://support.sendgrid.com. gav this lnk where the structure of output is given https://sendgrid.com/docs/API_Reference/Event_Webhook/event.html But, how can I get the data using PHP.
