### ISSUE TITLE
Unable to add BCC with $personalizationIndex

### ISSUE THREAD

**Issue by MarvinWue** [sendgrid/sendgrid-php#788]
#### Issue Summary

It's not possible to add CC/BCC when passing a $personalizationIndex.
The issue seems to be caused by the missing $substitutions parameter when calling `addRecipientEmail` in `addCc` and `addBcc` in the Mail class.

```
$this->addRecipientEmail(
	"Bcc",
	$bcc,
	$name,
	// substitutions are missing here
	$personalizationIndex,
	$personalization
);
```

#### Error

`Fatal error: Uncaught SendGrid\Mail\TypeException: $substitutions must be an array. in ...\vendor\sendgrid\sendgrid\lib\mail\EmailAddress.php on line 162`

#### Technical details:

* sendgrid-php Version: 7.2.1
* PHP Version: 7.1.16

**Comment by peter279k** [comment]
@MarvinWue, thank you for your reply.

It looks like it missed the variable after tracing the line of [code](https://github.com/sendgrid/sendgrid-php/blob/b72ee445bf9e80636d6125c26c5134e62777d16b/lib/mail/Mail.php#L467) :+1: .

**Comment by thinkingserious** [comment]
Hello @MarvinWue,

Thanks for taking the time to report this!

I've added this to our backlog for a fix and also opened it up to the community for a PR.

With Best Regards,

Elmer
