### ISSUE TITLE
File Attachments v3 API

### ISSUE THREAD

**Issue by harshithsrinivas** [sendgrid/sendgrid-php#789]
Hi,

I have html application form and a php code to get fetch data and put it in the database and send an email of the resume. Except for the sending file attachment everything is working fine.

<?php
$dbName, "UID"=>$uid, "PWD"=>$pwd); $local = $_POST['local']; $firstname = $_POST['firstname']; $lastname = $_POST['lastname']; $email = $_POST['email']; $phonenumber = $_POST['phonenumber']; $visa =$_POST['visa']; $available = $_POST['available']; $role = $_POST['role']; $experience = $_POST['experience']; $phonescreen = $_POST['phonescreen']; $uslocation = $_POST['uslocation']; //Get uploaded file data $file_tmp_name = $_FILES['fileupload']['tmp_name']; $file_name = $_FILES['fileupload']['name']; $file_size = $_FILES['fileupload']['size']; $file_type = $_FILES['fileupload']['type']; $file_error = $_FILES['fileupload']['error']; $handle = fopen($file_tmp_name, "r"); $content = fread($handle, $file_size); fclose($handle); $encoded_content = chunk_split(base64_encode($conten)); $conn = sqlsrv_connect($server, $options); if($conn === false) { die(print_r(sqlsrv_errors(), true)); } $tableName = 'FullTime'; $query = "INSERT INTO [$tableName] (LocalToBoston,FirstName,LastName,Email,PhoneNumber,Visa,Availability,Role,YearsExperience,PhoneScreen,CurrentLocation,Resume,Date) VALUES ('$local','$firstname','$lastname','$email','$phonenumber','$visa','$available', '$role', '$experience', '$phonescreen', '$uslocation','https://websitetestco.azurewebsites.net/Resumes/Full_Time/$file_name',CURRENT_TIMESTAMP)"; if($file_error > 0) { die('Upload error or No files uploaded'); } move_uploaded_file($_FILES['fileupload']['tmp_name'], "Resumes/Full_Time/" . $_FILES['fileupload']['name']); $stmt = sqlsrv_query($conn, $query); if($stmt === false) { die(print_r(sqlsrv_errors(), true)); } $curl = curl_init(); $curl1 = curl_init(); //mailing curl_setopt_array($curl, array( CURLOPT_URL => "https://api.sendgrid.com/v3/mail/send", CURLOPT_RETURNTRANSFER => true, CURLOPT_ENCODING => "", CURLOPT_MAXREDIRS => 10, CURLOPT_TIMEOUT => 30, CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1, CURLOPT_CUSTOMREQUEST => "POST", CURLOPT_POSTFIELDS => "{ \"personalizations\":[{\"to\":[{\"email\":\"harshith@googlr.net\",\"name\":\"Harshith Srinivas\"}],\"subject\":\"Hello, World!\"}], \"from\":{\"email\":\"$email\",\"name\":\"$firstname\"}, \"reply_to\":{\"email\":\"abc@gmail.com\",\"name\":\"Sam Smith\"}, \"attachments\":[{\"content\":\"$encoded_content\",\"type\":\"$file_type\", \"filename\":\"$file_tmp_name\", \"disposition\":\"attachment\"}], \"content\":[{\"type\":\"text/html\",\"value\":\"
Are you willing to relocate to Boston?: $local

First Name: $firstname

Last Name: $lastname

Email: $email

Phone Number: $phonenumber

Visa Type: $visa

Availability: $available

Which Role are you applying for?: $role

Number of years of experience: $experience

Availability for phone screening in EST: $phonescreen

Current US Location: $uslocation

\"}] }", CURLOPT_HTTPHEADER => array( "authorization: Bearer <API KEY>", "content-type: application/json" ), )); curl_setopt_array($curl1, array( CURLOPT_URL => "https://api.sendgrid.com/v3/mail/send", CURLOPT_RETURNTRANSFER => true, CURLOPT_ENCODING => "", CURLOPT_MAXREDIRS => 10, CURLOPT_TIMEOUT => 30, CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1, CURLOPT_CUSTOMREQUEST => "POST", CURLOPT_POSTFIELDS => "{ \"personalizations\":[{\"to\":[{\"email\":\"$email\",\"name\":\"$firstname\"}],\"subject\":\"Hello, World!\"}], \"from\":{\"email\":\"harshith@abc.net\",\"name\":\"Careers\"}, \"reply_to\":{\"email\":\"abc@gmail.com\",\"name\":\"Sam Smith\"}, \"content\":[{\"type\":\"text/html\",\"value\":\"
Thank you for Applying

\"}] }", CURLOPT_HTTPHEADER => array( "authorization: Bearer <API Key>", "content-type: application/json" ), )); $response = curl_exec($curl); $response = curl_exec($curl1); $err = curl_error($curl); $err = curl_error($curl1); curl_close($curl); curl_close($curl1); header('Location: thankyou.html'); if ($err) { echo "cURL Error #:" . $err; } else { echo $response; } 
?>
This is my php code. Please help me in the file attachment.

Thanks,

**Comment by thinkingserious** [comment]
Hello @harshithsrinivas,

Could you please try using [this example](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#attachments)? Thanks!

With Best Regards,

Elmer
