### ISSUE TITLE
Substitutions not working

### ISSUE THREAD

**Issue by solonifer** [sendgrid/sendgrid-php#790]
#### Issue Summary

I have transactional template in send grid. In that email i have placeholders like: [first_name] etc...
I've tryied different options and ways to replace this placeholders.
What should i add to my code in order to make this work?

```
$from = new From("no-reply@project.com", "Project");
  $tos = [
    new To(
      'me@example.com', 'Example Name', ['first_name' => 'Example name'], 'Hello, test subject!'
    )
  ];
  $email = new Mail($from, $tos);
  $email->setTemplateId('d-********************************');
  $sendgrid = new \SendGrid(_SENDGRID_API_KEY_);
  try {
    $response = $sendgrid->send($email);
  } catch (Exception $e) {
    echo 'Caught exception: ' . $e->getMessage(). "\n";
  }
```

**Comment by solonifer** [comment]
I have also tried:

```
$substitutions = [
    "first_name" => "Steve"
];
$email->addDynamicTemplateDatas($substitutions);
```

Doesn't work for me.

**Comment by thinkingserious** [comment]
Hello @solonifer,

Could you please try [this example](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#transactional-templates)? Thanks!

With Best Regards,

Elmer

**Comment by solonifer** [comment]
@thinkingserious thank you!!! Worked for me 👍 
{{placeholder}} - this was the right placeholder.
