### ISSUE TITLE
The provided authorization grant is invalid, expired or revoked

### ISSUE THREAD

**Issue by praveentcom** [sendgrid/sendgrid-php#793]
#### Issue Summary

The error is,

401 Array ( 
[0] => HTTP/1.1 401 Unauthorized
[1] => Server: nginx
[2] => Date: Thu, 27 Dec 2018 20:59:24 GMT
[3] => Content-Type: application/json
[4] => Content-Length: 116
[5] => Connection: keep-alive
[6] => Access-Control-Allow-Origin: https://sendgrid.api-docs.io
[7] => Access-Control-Allow-Methods: POST
[8] => Access-Control-Allow-Headers: Authorization, Content-Type, On-behalf-of, x-sg-elas-acl
[9] => Access-Control-Max-Age: 600
[10] => X-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html
[11] =>
[12] => ) 
{"errors":[{"message":"The provided authorization grant is invalid, expired, or revoked","field":null,"help":null}]}

I have used .env to access my API Key in the PHP file,

(export SENDGRID_API_KEY='SG.xxxxxxxxxxxxx')

The code is,

<?php
  require("sendgrid/sendgrid-php.php");
  $email = new \SendGrid\Mail\Mail();
  $email->setFrom(new \SendGrid\Mail\From("noreply@classworks.co", "Classworks Leads"));
  $email->setSubject(new \SendGrid\Mail\Subject($_POST['school'] . " - Classworks Appointment"));
  $tos = [
    new \SendGrid\Mail\To("support@classworks.co", "Classworks Support"),
    new \SendGrid\Mail\To($_POST['email'], $_POST['name'])
  ];
  $email->addTos($tos);
  $email->addContent(new \SendGrid\Mail\HtmlContent("text/html", "<p><strong>Name:</strong> {$_POST['name']}</p>"));
  $email->addContent(new \SendGrid\Mail\HtmlContent("text/html", "<p><strong>Email:</strong> {$_POST['email']}</p>"));
  $email->addContent(new \SendGrid\Mail\HtmlContent("text/html", "<p><strong>Mobile:</strong> {$_POST['mobile']}</p>"));
  $email->addContent(new \SendGrid\Mail\HtmlContent("text/html", "<p><strong>School:</strong> {$_POST['school']}</p>"));
  $email->addContent(new \SendGrid\Mail\HtmlContent("text/html", "<p><strong>Count:</strong> {$_POST['count']}</p>"));
  $email->addContent(new \SendGrid\Mail\HtmlContent("text/html", "<p><strong>Gender:</strong> {$_POST['gender']}</p>"));
  $sendgrid = new \SendGrid('SENDGRID_API_KEY');
  try {
    $response = $sendgrid->send($email);
    print $response->statusCode() . "\n";
    print_r($response->headers());
    print $response->body() . "\n";
  } catch (Exception $e) {
    echo 'Caught exception: '. $e->getMessage() ."\n";
  }
?>

#### Steps to Reproduce

I have opened a ticket with SendGrid support. Please refer for more info. #1802462

#### Technical details:

* sendgrid-php Version: master
* PHP Version: 7.1

**Comment by peter279k** [comment]
@ThiruPraveen18, thank you or your reply.

Can you use the "```php```" syntax to fromat your code?

This will let codes be readable.

Thanks.
