### ISSUE TITLE
Sending the Same Email to Multiple Recipients new version ?

### ISSUE THREAD

**Issue by hurkan-sert** [sendgrid/sendgrid-php#800]
documentation was not enough,
Can you help us with sample code to send an email to multiple people with php api
The example structure used in this link was not very helpful:
https://sendgrid.com/docs/for-developers/sending-email/personalizations/

**Comment by tobyberesford** [comment]
What are you trying to do?

There is same code here for sending an email to multiple people:
https://sendgrid.com/docs/for-developers/sending-email/personalizations/#sending-the-same-email-to-multiple-recipients

**Comment by thinkingserious** [comment]
Thanks for trying to help @tobyberesford!

Hello @hurkan-sert,

Please see [these docs](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md) for how to use this SDK specifically. Thanks!

With Best Regards,

Elmer

**Comment by hurkan-sert** [comment]
okay I'm understand thank you
