### ISSUE TITLE
Are Use Cases wrong?

### ISSUE THREAD

**Issue by mwsasser** [sendgrid/sendgrid-php#803]
#### Issue Summary

The Use Cases state:  **require 'vendor/autoload.php';**

However the current version 7.2.1 doesn't have a **vendor** directory.  Did I miss something obvious?

**Comment by thinkingserious** [comment]
Hello @mwsasser,

If you are not using composer, please comment out the `require 'vendor/autoload.php'` and use:

```php
require("<PATH TO>/sendgrid-php.php");
// If not using Composer, uncomment the above line and
// download sendgrid-php.zip from the latest release here,
// replacing <PATH TO> with the path to the sendgrid-php.php file,
// which is included in the download:
// https://github.com/sendgrid/sendgrid-php/releases
```

Thanks!

With Best Regards,

Elmer

**Comment by mwsasser** [comment]
Thanks, I did miss that.  Hopefully it'll help someone else who is half-asleep when reading documentation too.
