### ISSUE TITLE
How do I send marketing email templates just like transactional emal templates?

### ISSUE THREAD

**Issue by nyel-dev** [sendgrid/sendgrid-php#807]
Is there a way to do this? I can't find any Marketing Template ID unlike Transactional templates where you could see the ID right away.

**Comment by thinkingserious** [comment]
Hello @nyel-dev,

Our [Marketing Campaigns product](https://sendgrid.com/docs/ui/sending-email/how-to-send-email-with-marketing-campaigns/) operates differently than our transactional emails. [Here](https://github.com/sendgrid/sendgrid-php/blob/master/USAGE.md#campaigns) are the supported endpoints. Please take a look and let me know if those endpoints meet your needs.

Thanks!

With Best Regards,

Elmer

**Comment by nyel-dev** [comment]
@thinkingserious thank you for the fast reply. I saw on the link you sent is I will be able to send a campaign. However what I need is I need to track the "open" and "click" of the transactional templates that I am sending just like how Marketing Campaign dashboard looks where they show you the statistics of the campaign. Would that be possible anywhere?

So it's kinda like a transactional template but I would still be able to see the statistics for my email.

**Comment by thinkingserious** [comment]
Hello @nyel-dev,

It sounds like you want to use either our [stats endpoint](https://github.com/sendgrid/sendgrid-php/blob/master/USAGE.md#stats) or [event webhook](https://sendgrid.com/docs/API_Reference/Event_Webhook/event.html). You could also view this data in the SendGrid UI.

With Best Regards,

Elmer
