### ISSUE TITLE
unable to send dynamic html contents for multiple mails 

### ISSUE THREAD

**Issue by veerendraceipal** [sendgrid/sendgrid-php#808]
I am trying to send email to 100 users. Each user details are different.
I want to send email to each user at a time with an array that contains, to email ids, [substitutes], subjects.
as per the sample code in this URL(second method .i.e, not fluent method):
https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#send-multiple-emails-to-multiple-recipients

Here I want to include dynamic html content also, but unable to do that.

Here I am placing screenshot.
![1493617037387 remmina-2019-2-19-15_23_9 888517](https://user-images.githubusercontent.com/47412262/53026268-91556480-3488-11e9-82bc-65451f48d31c.png)

In the above image, I am able to write dynamic subject, but cannot add html content after subject parameter.
So that I am trying to add html content as substitute (-body_message-) that to limit of 10000 bytes.
Is there any other method to send content dynamically for each user.
I am tried a lot, bot unable to solve the scenario.
thanks in advance.

**Comment by thinkingserious** [comment]
Hello @veerendraceipal,

Have you tried using transactional templates, [like so](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#transactional-templates)?

Thanks!

With Best Regards,

Elmer

**Comment by veerendraceipal** [comment]
Yeah, Dynamic templates won't work to my requirement, I have to send customized content as mail body to each user and the message is unique. Maybe I think, with the combination of Substitutes and Section tags will work to my requirement. If you can please provide some piece of code with substitutions and section tags...

Thanks!
Veerendra

**Comment by thinkingserious** [comment]
Hello @veerendraceipal,

In that case, you will want to use [this example](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#send-multiple-emails-to-multiple-recipients). Please try implementing as close to the default example as possible to verify that it works for your use case before customizing.

Please let me know how that goes.

With Best Regards,

Elmer
