### ISSUE TITLE
Readme instructions for using without composer still requires composer

### ISSUE THREAD

**Issue by nricklin** [sendgrid/sendgrid-php#81]
I downloaded this:  https://sendgrid-open-source.s3.amazonaws.com/sendgrid-php/versions/sendgrid-php-39c3745.zip

sendgrid-php.php requires vendor/autoload.php which requires composer.

**Comment by paoga87** [comment]
@nquinlan  thanks for providing the correct link, I was able to download the the php helper library from there, however, when implementing, I get the error: `Fatal error: require_once(): Failed opening required '.../sendgrid-php/vendor/composer/autoload_real.php'`; which in fact, there is no composer directory under the vendor folder.

Is there zip that provides this vendor? The v2 library I currently have DOES come with composer, but I really would like to upgrade to v3.

Thank you,
Paola G.

**Comment by KingsleyOgu** [comment]
Please how do I use send grid without composer, the package I downloaded still requires autoload

**Comment by childish-sambino** [comment]
@KingsleyOgu @paoga87 Hope this helps.

Unzip the SDK download file in the same directory as your PHP code. And then in your code require the loader file bundled with the SDK:

```
// Require the bundled autoload file - the path may need to change
// based on where you downloaded and unzipped the SDK
require __DIR__ . '/sendgrid-php/lib/loader.php';
```

**Comment by acafourek** [comment]
The solutions above no longer seem to work as the latest version (7.9.1) doesn't contain a `/vendor` directory or `/lib/loader.php`. Following README with `require("./sendgrid-php.php");` also produces composer error.
