### ISSUE TITLE
CORS when making API calls in PHP script

### ISSUE THREAD

**Issue by froggomad** [sendgrid/sendgrid-php#812]
When calling the script in the setup guide from a URL, I get

```
401 Array ( 
  [0] => HTTP/1.1 401 Unauthorized 
  [1] => Server: nginx 
  [2] => Date: Thu, 07 Mar 2019 14:44:40 GMT 
  [3] => Content-Type: application/json 
  [4] => Content-Length: 88 
  [5] => Connection: keep-alive 
  [6] => Access-Control-Allow-Origin: https://sendgrid.api-docs.io 
  [7] => Access-Control-Allow-Methods: POST 
  [8] => Access-Control-Allow-Headers: Authorization, Content-Type, On-behalf-of, x-sg-elas-acl 
  [9] => Access-Control-Max-Age: 600 
  [10] => X-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html 
  [11] => 
  [12] =>

```
Yet when I ssh to the server and run the script using `php testSendgrid.php` the script executes and I get a test email.

Assuming there's something in the host's configuration preventing the script from reading the .env when accessed from the web or some such nonsense, I want to use the tried and true method of hard-coding the API key in the variable `$sendGridAPIKey` in a password protected file.

I include the password protected file, then call `$sendgrid = new \SendGrid($sendGridAPIKey);` but I'm getting the same CORS message

PHP version 7.2
=====

Any help is much appreciated!

**Comment by froggomad** [comment]
Actually, I'm not getting invalid credentials when hard-coded, but still getting the CORS message - though this is a locked down server environment...

**Comment by thinkingserious** [comment]
Hello @froggomad,

The CORS message is not an error, you can find out more about that header [here](https://sendgrid.com/docs/Classroom/Basics/API/cors.html).

With Best Regards,

Elmer

**Comment by froggomad** [comment]
Hello @thinkingserious,

I'm using the PHP script from the PHP setup guide and the API key is secured. Am I not already using the "workaround" mentioned at the link you provided?

**Comment by froggomad** [comment]
I see it works using POST... makes sense now

**Comment by froggomad** [comment]
I previously stated the script was working when initiated from the POST method, but I'm still getting CORS.

Again, the script is in PHP and the API key is obscured so it's only visible to the server

**Comment by froggomad** [comment]
After resolving the credentials issue, the status code is 400 "Bad Request". According to chat support, it's not a CORS error. They say " all our errors will return the docs and cors links, no matter the error"

I gave them the code I'm using (which I've modified slightly from the sample script in the setup guide) and they said nothing in the code should be causing a "Bad Request"

```
require '../vendor/autoload.php';
        $sendEmail = new \SendGrid\Mail\Mail();
//Create content            
            $content = "content";
//Create Message
                $sendEmail->setFrom("email@server.org", "Name");
                $sendEmail->setSubject("Form Submission Confirmation");
                $sendEmail->addTo($email, "$fname, $lname");
                $sendEmail->addContent("text/plain", "Content");
                $sendEmail->addContent("text/html", $content);
                $sendgrid = new \SendGrid($sendGridAPIKey);
                try {
                        $response = $sendgrid->send($sendEmail);
                    } catch (Exception $e) {
                        error_log('sendgrid exception: '. $e->getMessage() ."\n");
                    }

```

**Comment by thinkingserious** [comment]
Hello @froggomad,

It appears I'm not understanding your issue completely. My apologies. 

I may not still be understanding completely, but from what I gather, you are trying to run the script through your browser and it's giving you a CORS error. If that's the case, then you will [need to create a separate server-side application](https://github.com/sendgrid/docs/issues/1417#issuecomment-334171280).

With Best Regards,

Elmer

**Comment by froggomad** [comment]
No worries, I haven't explained my use case much at all as I've been testing and was initially trying to run the script from a URL.

Now understanding the CORS issue, I'm running the script server side using the POST method and still getting an error. Again, support says this is *not* a CORS error. They say the CORS message comes along with all errors. They assumed I had an error in my code before looking at it, but verified that I don't and don't think I shouldn't be getting a 400 error.

**Comment by thinkingserious** [comment]
Hi @froggomad,

What does the server logs say after you make your POST? If it's that 401 error, perhaps your API key is not getting set properly on the server side. I would log as much as reasonable and take a look at your sever logs after making your POST.

With Best Regards,

Elmer

**Comment by froggomad** [comment]
Oddly the error resolved itself immediately after I started trying to look at the response body to try and debug further. The bug didn't want to be discovered so it's hiding lol

```
var_dump($response->statusCode());
echo('body:\n');
var_dump($response->body());
 echo('headers:\n');
 var_dump($response->headers());
```
