### ISSUE TITLE
"message":"Following RFC 1341, section 7.2, if either text/html or text/plain are to be sent in your email: text/plain needs to be first, followed by text/html, followed by any other content.","field":"content","help":null

### ISSUE THREAD

**Issue by hurkan-sert** [sendgrid/sendgrid-php#814]
foreach($params as $key => $value ){
$data["personalizations"][]["to"][] = ["email" => $value['eposta'] ];
$data["subject"] = "HELLO";
$data["from"]=["email"=>"example@gmail.com"];
$data["content"][]=["type"=>"text/html","value"=>" $value['content']"];
}
--

**Comment by thinkingserious** [comment]
Hello @hurkan-sert,

It does not look like you are using this helper library. Can you please verify? Did you install via composer or did you download the files?

With Best Regards,

Elmer

**Comment by hurkan-sert** [comment]
/*I don't use the library,curl with request api */ 
 foreach($params as $key => $value ) 
  {
  $data["personalizations"][]["to"][0] = ["email" => $value['eposta']];
  $data["subject"]= "E-ARSİV FATURA PDF GÖRÜNTÜSÜ";
                          
   $data["from"]=["email"=>"example@gmail.com"];
                        
    $data["content"][]=["type" =>"text/html","value"=>"<h2>hjkjhk0</h2>"];
}
     $data=json_encode($data);
  $sendgrid_apikey ='*********';
                        
                        $curl = curl_init();

                        curl_setopt_array($curl, array(
                            CURLOPT_URL => "https://api.sendgrid.com/v3/mail/send",
                            CURLOPT_RETURNTRANSFER => true,
                            CURLOPT_ENCODING => "",
                            CURLOPT_MAXREDIRS => 10,
                            CURLOPT_TIMEOUT => 30,
                            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
                            CURLOPT_CUSTOMREQUEST => "POST",
                            CURLOPT_POSTFIELDS => $data,
                            CURLOPT_HTTPHEADER => array(
                                "Authorization: Bearer $sendgrid_apikey  ", 
                                "Content-Type:application/json"                                
                            ),
                        ));
                    
                        $response = curl_exec($curl);
                        $err = curl_error($curl);

**Comment by thinkingserious** [comment]
Hello @hurkan-sert,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
