### ISSUE TITLE
Transactional Template Substitutions

### ISSUE THREAD

**Issue by michaelfromtheoutfit** [sendgrid/sendgrid-php#815]
#### Issue Summary

Trying to utilize Substitutions in Transactional Templates, following the example [found here](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#transactional-templates) as closely as possible with only minor tweaks. However when the email is delivered the handlebars code in the template is removed but not replaced with the variables passed in.

#### Steps to Reproduce

1. Create a Template by going to Templates->Transactional on Sendgrid.
2. Template code is as follows:

```
<html>
<head>
	<title></title>
</head>
<body>
Hello {{ firstname }},
<br /><br/>
I'm glad you are trying out the template feature!
<br /><br/>
I hope you are having a great day in {{ location }} :)
<br /><br/>
</body>
</html>
```

3. Implementation is as follows:

```
use \SendGrid\Mail\From as From;
use \SendGrid\Mail\To as To;
use \SendGrid\Mail\Subject as Subject;
use \SendGrid\Mail\PlainTextContent as PlainTextContent;
use \SendGrid\Mail\HtmlContent as HtmlContent;
use \SendGrid\Mail\Mail as Mail;

$from = new From("test@example.com", "Example User");
        $tos = [
          new To(
            "buffy@vampireslayer.com",
            "Example User 1",
            [
              'firstname' => 'Buffy',
              'location' => 'Sunnydale',
            ]
          )
        ];
        $email = new Mail(
          $from,
          $tos
        );
        $email->setTemplateId("MYTEMPLATEID");
        $sendgrid = new \SendGrid(getenv('SENDGRID_API_KEY'));
        try {
            $response = $sendgrid->send($email);
            print $response->statusCode() . "\n";
            print_r($response->headers());
            print $response->body() . "\n";
        } catch (Exception $e) {
            echo 'Caught exception: '.  $e->getMessage(). "\n";
        }
```

4. The email is sent successfully, but with this as the body:

```
Hello , 

I'm glad you are trying out the template feature! 

I hope you are having a great day in :)
```

Thanks in advance for any help figuring out what I'm doing wrong!

#### Technical details:

* sendgrid-php Version: 7.2.1
* PHP Version: 7.2

**Comment by hurkan-sert** [comment]
$data["personalizations"][]["dynamic_template_data"]=["name"=>$name,"surname" => $surname,"order_no"=>$order_no];

you can trying

**Comment by thinkingserious** [comment]
Hello @michaelfromtheoutfit,

I just tried your code and it worked for me. 

How did you install the library?

With Best Regards,

Elmer

**Comment by michaelfromtheoutfit** [comment]
> Hello @michaelfromtheoutfit,
> 
> I just tried your code and it worked for me.
> 
> How did you install the library?
> 
> With Best Regards,
> 
> Elmer

Hey Elmer! I installed the library with Composer. Thanks so much for giving it a try. Not sure why it isn't working for me.

**Comment by thinkingserious** [comment]
Maybe the `MYTEMPLATEID` is not pointing to the right template?

**Comment by michaelfromtheoutfit** [comment]
@thinkingserious I would think the same thing, but it is generating the correct template, just without the substitutions.

**Comment by thinkingserious** [comment]
I suggest you create a new separate test project and try implementing the example as-is (just changing the emails) to see if that works.
