### ISSUE TITLE
502 Missing JSON body

### ISSUE THREAD

**Issue by justageek** [sendgrid/sendgrid-php#816]
#### Issue Summary

We are getting a 502 response with the message Missing JSON body using the SendGrid class to post html body to the mail/send api endpoint.

#### Steps to Reproduce

1. Build a Mail object with html content
2. use the makeRequest call the the SendGrid->client  to send the Mail object to mail/send
Is there any way to troubleshoot this, I confirmed that we are adding content that is the html to send.

#### Technical details:

* sendgrid-php Version: master (latest commit: [commit number])
* PHP Version: 5.6

**Comment by justageek** [comment]
My full error response is
[headers:protected] => Array
                (
                    [0] => HTTP/1.1 100 Continue
                    [1] => 
                    [2] => HTTP/1.1 502 Bad Gateway
                    [3] => Server: nginx
                    [4] => Date: Wed, 13 Mar 2019 21:11:32 GMT
                    [5] => Content-Type: text/html
                    [6] => Content-Length: 6023
                    [7] => Connection: keep-alive
                    [8] => ETag: "5c6599f9-1787"
                    [9] => 
                    [10] => 
                )

        )

    [status] => 502
    [data] => 
    [errors] => Array
        (
            [0] => Array
                (
                    [message] => Missing JSON body.
                    [field] => 
                )

        )

**Comment by thinkingserious** [comment]
Hello @justageek,

Do you mind sharing the relevant code so that I can try and reproduce?

We do have a [TROUBLESHOOTING.md](https://github.com/sendgrid/sendgrid-php/blob/master/TROUBLESHOOTING.md) file that may help.

With Best Regards,

Elmer

**Comment by justageek** [comment]
Hi, my json file is huge, and sendgrid support said something about a null in the body was part of the problem, I have not had time to look at that yet.

**Comment by thinkingserious** [comment]
Can you share the code that generated the JSON?

**Comment by justageek** [comment]
This is from our wrapper class, I believe I see the problem with the constructor in the Mail class
`    public function __construct($from, $subject, $to, $content)
    {
        $this->setFrom($from);
	    $this->setSubject($subject);
	    $personalization = new Personalization();
        $personalization->addTo($to);
        $this->addPersonalization($personalization);
        $this->addContent($content);
    }`
It adds content even with the $content variable is empty, which creates a null value in the resulting json.

`  protected function buildMessage() {
    $this->mail = new Mail();
    $this->mail->setFrom($this->fromEmail, $this->fromName);
    $this->mail->setSubject($this->subject);

    if (!empty($this->messageBody)) {
      foreach ($this->messageBody as $content) {
        $this->mail->addContent($content);
      }
    }

    if (!empty($this->recipients)) {
      $this->mail->addTos($this->recipients);
    }

    $categories = array_filter(array_unique($this->categories));
    if (!empty($categories)) {
      foreach ($categories as $category) {
        $this->mail->addCategory($category);
      }
    }

    return $this->mail;
  }`

**Comment by thinkingserious** [comment]
Hello @justageek,

Did you confirm that was the problem? Thanks!
