### ISSUE TITLE
How to send different files (attachments) to each recipient

### ISSUE THREAD

**Issue by hurkan-sert** [sendgrid/sendgrid-php#817]
$tos []= new \SendGrid\Mail\To( 
                                
            $value['email'],  
             "Example User1",
                [
                   '-name-' => $deger['name'],
                     '-surname-' => 'CARTER'
                ],
                   "Subject 1 -name-",
                    $attachment /* Is there a structure that will be this way */
              );

**Comment by hurkan-sert** [comment]
Hi Elmer ,
can you help me for my problem ?

**Comment by thinkingserious** [comment]
Hello @hurkan-sert,

No, there is not, attachments work [like this](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#attachments) currently.

One way around this is if you provide your attachment behind a link. In that case, you would also be able to track the clicks.

With Best Regards,

Elmer

**Comment by hurkan-sert** [comment]
oke.thank you
