### ISSUE TITLE
CustomArg indexing into Personalizations

### ISSUE THREAD

**Issue by haywiremk** [sendgrid/sendgrid-php#819]
#### Issue Summary

The following code in Mail.php in the function addCustomArg() accepts a personalizationIndex.  However by the logic below if this [0] personalization exist there is no way to index past and add a customArg. Seem like should remove the first if statement and set the function variable default to 0 instead of null or is there some reason for this?  Seems like a bug prevent me from updating personalizaitons.

starting Line 847 in Mail.php
```php
            if ($this->personalization[0] != null) {
                $this->personalization[0]->addCustomArg($custom_arg);
            } else if ($this->personalization[$personalizationIndex] != null) {
                $this->personalization[$personalizationIndex]->addCustomArg(
                    $custom_arg
                );
            } else {
                $personalization = new Personalization();
                $personalization->addCustomArg($custom_arg);
                if (($personalizationIndex != 0)
                    && ($this->getPersonalizationCount() <= $personalizationIndex)
                ) {
                    $this->personalization[$personalizationIndex] = $personalization;
                } else {
                    $this->addPersonalization($personalization);
                }
            }
```

#### Technical details:

*loaded from composer
*"name": "sendgrid/sendgrid",
*"version": "7.2.1",

**Comment by thinkingserious** [comment]
Hello @haywiremk,

Thanks for highlighting this error. We will investigate further. In the mean time, I will label the issue appropriately and add to our backlog.

Thanks!

With Best Regards,

Elmer
