### ISSUE TITLE
Is PHP 7.3 supported

### ISSUE THREAD

**Issue by danielflippance** [sendgrid/sendgrid-php#820]
#### Issue Summary

Is PHP 7.3 supported? I see that the README notes the supported versions of PHP are 5.6, 7.0, 7.1 or 7.2

#### Steps to Reproduce

N/A

#### Technical details:

* sendgrid-php Version: master (latest commit: 447ac8738f868076acd93fc36bcdc0cd38e37b18)

**Comment by thinkingserious** [comment]
Hello @danielflippance,

[Yes :)](https://travis-ci.org/sendgrid/sendgrid-php/jobs/515291656). Thanks for asking!

With Best Regards,

Elmer
