### ISSUE TITLE
Update Prism script to pull the latest version automatically

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-php#822]
#### Issue Summary

The format of the releases page has changed and has broken [this code](https://github.com/sendgrid/sendgrid-php/blob/master/test/prism.sh#L3). We need to update it such that it pulls only the version number. We can then uncomment [this code](https://github.com/sendgrid/sendgrid-php/blob/master/test/prism.sh#L40).

**Comment by hpez** [comment]
Is this still an issue?

**Comment by childish-sambino** [comment]
Closing as prism integration has been moved to https://github.com/sendgrid/sendgrid-oai
