### ISSUE TITLE
Change subject only for the BCC

### ISSUE THREAD

**Issue by josephernest** [sendgrid/sendgrid-php#823]
I'm using

```
require("sendgrid-php/sendgrid-php.php");

$from = new SendGrid\Email("Me", "me@example.com");
$to = new SendGrid\Email("Customer", "customer@test.com");
$bcc = new SendGrid\Email("Me", "me@example.com");

$subject = "Test subject";
$content = new SendGrid\Content("text/plain", "Test content");

$mail = new SendGrid\Mail($from, $subject, $to, $content);
$mail->personalization[0]->addBcc($bcc);

$response = (new \SendGrid($sendgridapikey))->client->mail()->send()->post($mail);
```

to send an email to someone, and as a BCC to myself. It works.

**Now I'd like to modify the subject, but only for the BCC-to-myself email.** How to do this?

NB: I don't want to change the API version since everything works like it is here ^ and it took a lot of time to configure it :)

**Comment by thinkingserious** [comment]
Hello @josephernest,

To add a different subject for the bcc email address, you would need a different personalization object that had its own subject. I'm not sure if this would be the desired outcome though, as that new personalization object would be a separate email. But perhaps you can achieve the desired effect by copying the contents of the primary email into the second personalization.

With Best Regards,

Elmer

**Comment by josephernest** [comment]
Thank you! Could you add a sample code to do this?

**Comment by thinkingserious** [comment]
Hello @josephernest,

You can try something [like this](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#send-multiple-emails-to-multiple-recipients). Please let me know how it goes.

With Best Regards,

Elmer
