### ISSUE TITLE
502 errors trying to send email

### ISSUE THREAD

**Issue by justageek** [sendgrid/sendgrid-php#827]
#### Issue Summary

We have recently started getting 502 errors in code that had been working to send emails, we have just upgrade to version 7.x of the libraries, but even that code tested fine.

#### Steps to Reproduce

1. We build a Mail object that has html content for the body
2. We execute a post to mail/send with that Mail object as the argument.
`
SendGrid\Response Object
(
    [statusCode:protected] => 502
    [body:protected] => <html>
  <head>
    <title>SendGrid - 502 Bad Gateway</title>
    <style>@import url("https://fonts.googleapis.com/css?family=Dosis:300,400,700,800");/** Styles for the 403 Page **/.particle-error,.permission_denied,#particles-js {  width: 100%;  height: 100%;  margin: 0px !important;}#particles-js {  position: fixed !important;  opacity: 0.23;}.permission_denied {  background: #294661 !important;}.permission_denied a {  text-decoration: none;}.denied__wrapper {  max-width: 390px;  width: 100%;  height: 390px;  display: block;  margin: 0 auto;  position: relative;  margin-top: 8vh;}.permission_denied h1 {  text-align: center;  color: #fff;  font-family: "Dosis", sans-serif;  font-size: 100px;  margin-bottom: 0px;  font-weight: 800;}.permission_denied h3 {  text-align: center;  color: #fff;  font-size: 19px;  line-height: 23px;  max-width: 330px;  margin: 0px auto 30px auto;  font-family: "Dosis", sans-serif;  font-weight: 400;}.permission_denied h3 span {  position: relative;  width: 65px;  display: inline-block;}.permission_denied h3 span:after {  content: "";  border-bottom: 3px solid #e12127;  position: absolute;  left: 0;  top: 43%;  width: 100%;}.denied__link {  background: none;  color: #fff;  padding: 12px 0px 10px 0px;  border: 1px solid #fff;  outline: none;  border-radius: 7px;  width: 150px;  width: 150px;  font-size: 15px;  text-align: center;  margin: 0 auto;  vertical-align: middle;  display: block;  margin-bottom: 40px;  margin-top: 25px;  font-family: "Dosis", sans-serif;  font-weight: 400;}.denied__link:hover {  color: #e12127;  border-color: #e12127;  cursor: pointer;  opacity: 1;}.permission_denied .stars {  animation: sparkle 1.6s infinite ease-in-out alternate;}@keyframes sparkle {  0% {    opacity: 1;  }  100% {    opacity: 0.3;  }}#astronaut {  width: 43px;  position: absolute;  right: 20px;  top: 210px;  animation: spin 4.5s infinite linear;}@keyframes spin {  0% {    transform: rotateZ(0deg);  }  100% {    transform: rotateZ(360deg);  }}@media (max-width: 600px) {  .permission_denied h1 {    font-size: 75px;  }  .permission_denied h3 {    font-size: 16px;    width: 200px;    margin: 0 auto;    line-height: 23px;  }  .permission_denied h3 span {    width: 60px;  }  #astronaut {    width: 35px;    right: 40px;    top: 170px;  }}.saturn,.saturn-2,.hover {  animation: hover 2s infinite ease-in-out alternate;}@keyframes hover {  0% {    transform: translateY(3px);  }  100% {    transform: translateY(-3px);  }
    } </style>
  </head>
  <body class="permission_denied">
    <div id="particles-js"></div>
    <div class="denied__wrapper">
      <h1>502</h1>
      <h3>Ngnix - Bad Gateway</h3>
      <svg id="astronaut" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50">
        <g id="tiara-logo" transform="translate(8.000000, 8.000000)">
          <rect id="99E1F4" fill="#99E1F4" x="8" y="16" width="8" height="8"></rect>
          <rect id="99E1F4" fill="#99E1F4" x="0" y="8" width="8" height="8"></rect>
          <rect id="009DD9" fill="#009DD9" x="8" y="8" width="8" height="8"></rect>
          <rect id="00B3E3" fill="#00B3E3" x="16" y="8" width="8" height="8"></rect>
          <rect id="00B3E3" fill="#00B3E3" x="8" y="0" width="8" height="8"></rect>
          <rect id="1a82e2" fill="#1A82E2" x="0" y="16" width="8" height="8"></rect>
          <rect id="1a82e2" fill="#1A82E2" x="16" y="0" width="8" height="8"></rect>
        </g>
      </svg>
      <svg id="planet" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
      <circle class="saturn" cx="256" cy="256" r="149.536" fill="#FFF"/>
      <circle class="saturn" cx="256" cy="256" r="138" fill="#e12127"/>
      <circle class="saturn" cx="256" cy="256" r="108" fill="#FFF"/>
      <circle class="hover" cx="216" cy="214.081" r="32" fill="#e12127"/>
      <circle class="hover" cx="298" cy="214.081" r="32" fill="#e12127"/>
      <circle class="hover" cx="216" cy="296.081" r="32" fill="#e12127"/>
      <circle class="hover" cx="298" cy="296.081" r="32" fill="#e12127"/>
      <path class="stars" fill="#FFF" d="M112.456 363.093c-.056 7.866-6.478 14.197-14.344 14.142 7.866.056 14.198 6.48 14.142 14.345.056-7.866 6.48-14.198 14.345-14.142-7.868-.057-14.2-6.48-14.144-14.345zM432.436 274.908c-.056 7.866-6.478 14.198-14.344 14.142 7.866.057 14.197 6.48 14.142 14.345.056-7.866 6.48-14.197 14.345-14.142-7.868-.056-14.2-6.48-14.144-14.345zM159.75 58.352c-.12 16.537-13.62 29.848-30.157 29.73 16.537.118 29.848 13.62 29.73 30.156.118-16.537 13.62-29.848 30.156-29.73-16.54-.117-29.85-13.62-29.73-30.156z"/>
    </svg>
      <a href="https://sendgrid.com"><button class="denied__link">Return to Homepage</button></a>
    </div>
  </body>
  <script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
  <script>var particles={"particles":{"number":{"value":160,"density":{"enable":true,"value_area":800}},"color":{"value":"#ffffff"},"shape":{"type":"circle","stroke":{"width":0,"color":"#000000"},"polygon":{"nb_sides":5},"image":{"src":"img/github.svg","width":100,"height":100}},"opacity":{"value":1,"random":true,"anim":{"enable":true,"speed":1,"opacity_min":0,"sync":false}},"size":{"value":3,"random":true,"anim":{"enable":false,"speed":4,"size_min":0.3,"sync":false}},"line_linked":{"enable":false,"distance":150,"color":"#ffffff","opacity":0.4,"width":1},"move":{"enable":true,"speed":0.17,"direction":"none","random":true,"straight":false,"out_mode":"out","bounce":false,"attract":{"enable":false,"rotateX":600,"rotateY":600}}},"interactivity":{"detect_on":"canvas","events":{"onhover":{"enable":false,"mode":"bubble"},"onclick":{"enable":false,"mode":"repulse"},"resize":false},"modes":{"grab":{"distance":400,"line_linked":{"opacity":1}},"bubble":{"distance":250,"size":0,"duration":2,"opacity":0,"speed":3},"repulse":{"distance":400,"duration":0.4},"push":{"particles_nb":4},"remove":{"particles_nb":2}}},"retina_detect":true};particlesJS('particles-js',particles,function(){console.log('callback-particles.jsconfigloaded');});</script>
</html>

    [headers:protected] => Array
        (
            [0] => HTTP/1.1 100 Continue
            [1] => 
            [2] => HTTP/1.1 502 Bad Gateway
            [3] => Server: nginx
            [4] => Date: Thu, 11 Apr 2019 22:42:32 GMT
            [5] => Content-Type: text/html
            [6] => Content-Length: 6023
            [7] => Connection: keep-alive
            [8] => ETag: "5c65cb07-1787"
            [9] => 
            [10] => 
        )
)
`
#### Technical details:

* sendgrid-php 7.2.1
* PHP Version: 5.6

**Comment by thinkingserious** [comment]
Hello @justageek,

That error means your server is having trouble connecting with our server. You might want to reach out to our support team or your server provider to help debug that issue.

With Best Regards,

Elmer

**Comment by justageek** [comment]
Thanks, we found so far that because we are using a queue system provided by the Drupal CMS to send multiple messages in batch, we are going to try some modifications to how we instantiate the SendGrid library client and cache it statically, we found that the very first message always works perfectly, and then the rest do not, so we might be grasping at straws, but sending one-off messages works perfectly, it has something to do with queueing up a batch and processing then in a single cron run that appears to be part of the issue.

**Comment by justageek** [comment]
We are also seeing the following error

Undefined variable: plain_content Mail.php:1133 

I don't know if that would be causing issues with sending when building the message content.

**Comment by justageek** [comment]
Is there an easy way to debug the curl request the library uses to contact SendGrid?

**Comment by thinkingserious** [comment]
I would suggest taking a look at the [request body](https://github.com/sendgrid/sendgrid-php/blob/master/TROUBLESHOOTING.md#viewing-the-request-body) and comment out the sending function until resolution.

**Comment by edtsz** [comment]
I'm having the same problem. Today I got 35 occurrences.. :disappointed: 

Response:
```
    [headers:protected] => Array
        (
            [0] => HTTP/1.1 502 Bad Gateway
            [1] => Server: nginx
            [2] => Date: Thu, 18 Jul 2019 18:20:36 GMT
            [3] => Content-Type: text/html
            [4] => Content-Length: 6023
            [5] => Connection: keep-alive
            [6] => ETag: "5c6599f9-1787"
            [7] => 
            [8] => 
        )
```

My environment:
```
Linux CentOS 3.10.0-693.17.1.el7.x86_64

PHP 7.1.26 (cli) (built: Jan 12 2019 09:59:05) ( NTS )
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies

sendgrid/php-http-client        3.9.6
sendgrid/sendgrid               7.3.0
```

**Comment by SamMousa** [comment]
This issue is actually fixed here: https://github.com/sendgrid/sendgrid-php/commit/b0a3721d9e42121140b3ac4ecb5263827740a3ec

But the Sendgrid package(s) have been improperly tagged thus missing commits.

**Comment by thinkingserious** [comment]
Hello everyone, 

It looks to me like this issue is now fixed in the latest version of this helper library. Thanks!

With best regards,

Elmer
