### ISSUE TITLE
CC and BCC not working

### ISSUE THREAD

**Issue by lexicalbits** [sendgrid/sendgrid-php#83]
CC and BCC fields aren't working.  BCC is required for integration with a 3rd party service, so multiple TO fields aren't an option for me.

Test case:
```Shell
mkdir sgtest && cd sgtest
composer init -s dev
composer require sendgrid/sendgrid 2.0.3
echo "<?php return ['username'=>'', 'password'=>'']; ?>" > cfg.php
# Add your username and password to cfg.php
curl https://gist.githubusercontent.com/lexicalbits/9669433/raw/61ee6a296734d4aaad708fdd7a482780e886e60a/gistfile1.php > run.php
php run.php
```
If you use the default emails in the test, you can verify the results here:
http://mailinator.com/inbox.jsp?to=sgtest_to
http://mailinator.com/inbox.jsp?to=sgtest_cc
http://mailinator.com/inbox.jsp?to=sgtest_bcc

The test gist: https://gist.github.com/lexicalbits/9669433

My setup:
Ubuntu Server 12.04 in KVM
PHP from https://launchpad.net/~ondrej/+archive/php5
```Shell
php -v
PHP 5.5.4-1+debphp.org~precise+1 (cli) (built: Sep 27 2013 12:39:52) 
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2013 Zend Technologies
    with Zend OPcache v7.0.3-dev, Copyright (c) 1999-2013, by Zend Technologies
    with Xdebug v2.2.3, Copyright (c) 2002-2013, by Derick Rethans
```

**Comment by nextexile** [comment]
Just wanted to add, it's strange that BCC isn't working especially since it exists as a method in your class. Please make the proper adjustments to let other users know, as soon as possible.

**Comment by jlank** [comment]
+1

**Comment by nextexile** [comment]
I have to say, I ran into this again. While I "kinda" understand why you would get rid of Bcc, removing CC is slightly outrageous. In my line of work we have to send messages to entire teams of people, how are we supposed to achieve that without CC? And no, advising me to use yet another library / implementation is not acceptable.

**Comment by eddiezane** [comment]
This will be fixed in the upcoming v3.0.0 branch. We will be defaulting to
a web parameter for 'to' as opposed to the current usage of the smtpapi
header for 'to'.

On Monday, January 26, 2015, Serg Chernata <notifications@github.com> wrote:

> I have to say, I ran into this again. While I "kinda" understand why you
> would get rid of Bcc, removing CC is slightly outrageous. In my line of
> work we have to send messages to entire teams of people, how are we
> supposed to achieve that without CC? And no, advising me to use yet another
> library / implementation is not acceptable.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sendgrid/sendgrid-php/issues/83#issuecomment-71574394>
> .
>


-- 
Eddie Zaneski
{"device": "mobile"}

**Comment by nextexile** [comment]
Thanks for the quick response. If you get a chance, please let us know when that happens.

**Comment by spandadk** [comment]
Just had everything setup and working nicely - my class setup, email formatted and bang... ->setBcc - not working. What a big disappointment.
I went to your Github page, scrolled down to see it listed there as part of the documentation and scratched my head many times until I found this topic.

You really need to make it clear that this doesn't work with your php lib. I basically made my choice on this lib because of that.

It's been a year since this issue was put up - any news on progress on this?

Thanks a lot.

**Comment by eddiezane** [comment]
I am actively working on this on the [3.0.0 branch](https://github.com/sendgrid/sendgrid-php/tree/v3.0.0). It will be done very very shortly. So sorry for the delay.

**Comment by srm80** [comment]
I hit this one hard as well. Much time spent tracking down this bug. Thumbs up lanching version 3 as soon as possible.

**Comment by jamesspittal** [comment]
Working on implementing BCC on SendGrid in another application of ours and having experienced this issue, I'd love to use the actual BCC function rather than a work-around if possible. Any ETA on the 3.0.0 branch?

**Comment by eddiezane** [comment]
I have a pre-release up of v3.0.0 that should fix all of these issues. Would love some testers to provide feedback. 

I need to write up the changes and a better README, but [here's a primer](https://github.com/sendgrid/sendgrid-php/tree/v3.0.0#please-read-this).

`"sendgrid/sendgrid": "3.0.0-RC1"` in composer.

https://github.com/sendgrid/sendgrid-php/releases/tag/v3.0.0-RC1

**Comment by jamesspittal** [comment]
One of our developers (@animir) is currently testing this. /cc @animir

**Comment by odrobnik** [comment]
Is the new version the one used by parse's cloud module? Because there it does not seem to work.

**Comment by thinkingserious** [comment]
@odrobnik I don't know which version Parse is using in their cloud module. I suggest you contact their support team. Thanks.
