### ISSUE TITLE
Newsletter Widget on Wordpress

### ISSUE THREAD

**Issue by jm111015** [sendgrid/sendgrid-php#832]
#### Issue Summary

When I used the Newsletter Widget Subscription on homepage it works, it send an email for newsletter subscription, but on the other pages then I subcribe the newletter on footer it doesn't work.

Please advice.

#### Steps to Reproduce

1. This is the first step
2. This is the second step
3. Further steps, etc.

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* sendgrid-php Version: master (latest commit: [commit number])
* PHP Version: 5.6, 7.0, 7.1, 7.2 (as of May 17, 2018)

**Comment by thinkingserious** [comment]
Hello @jm111015,

I believe [this is the repo](https://github.com/sendgrid/wordpress) you are looking for :)

With Best Regards,

Elmer
