### ISSUE TITLE
Receive attachments using SendGrid

### ISSUE THREAD

**Issue by alvianzf** [sendgrid/sendgrid-php#838]
#### Issue Summary

Hi, I'm new to SendGrid, how can I receive attachments in SendGrid inbound phase?

#### Steps to Reproduce

1. I tried using the Raw MIME and decode it using base64

is there a better way?

#### Technical details:

* PHP Version: 5.6, 7.0, 7.1, 7.2 (as of May 17, 2018)

**Comment by thinkingserious** [comment]
Hello @alvianzf,

We currently have examples in [Python](https://github.com/sendgrid/sendgrid-python/tree/master/sendgrid/helpers/inbound) and [Node.js](https://github.com/sendgrid/sendgrid-nodejs/tree/master/packages/inbound-mail-parser). I hope that helps!

With Best Regards,

Elmer

**Comment by alvianzf** [comment]
Thank you very much
