### ISSUE TITLE
Sending of emails to multiple users like in LINA in jobstreet without seeing each other in TO list

### ISSUE THREAD

**Issue by jhayg12** [sendgrid/sendgrid-php#840]
#### Sending of emails to multiple users

I'm trying to send an email to multiple recipients with the same subject and content but the problem is the other emails that has been sent to have the other emails on the `to` list which I don't want to.

I tried to loop the recipients but it takes too much resources.
![image](https://user-images.githubusercontent.com/33854581/57754189-6fcee680-7720-11e9-8e76-ed599c363a1d.png)

**Comment by thinkingserious** [comment]
Hello @jhayg12,

I believe [this](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#send-multiple-emails-to-multiple-recipients) is the example you need. Please give it a try and let me know how it goes.

With Best Regards,

Elmer

**Comment by jhayg12** [comment]
Hi @thinkingserious 

Will try this one.

Thanks

**Comment by thinkingserious** [comment]
Did it work out for you @jhayg12?

**Comment by jhayg12** [comment]
Hi @thinkingserious 

Yeah it work out but I remove some parameters which I don't need to like the substitutions for `-name-` and `-github-` link . My only problem now is some of the emails sent went to spam folder with broken image.

**Comment by thinkingserious** [comment]
Hi @jhayg12,

With regards to your emails going to the spam folder, I suggest you [check out this article](https://sendgrid.com/blog/10-tips-to-keep-email-out-of-the-spam-folder/) for some general help. 

With regards to the broken images, is that due to the email or a broken link?

With Best Regards,

Elmer

**Comment by jhayg12** [comment]
Hi @thinkingserious 

Will check the link you provided.

Regarding the broken images the source file where directly coming from our Amazon S3 Server like `<img src="https://s3-us-west-2.amazonaws.com/ic-file-service-production-2/863d2390-75cd-11e9-86a1-b5883eeb06da/emaillaptop_image.png">` as our email footer. I'm using laravel blade for the email template.

**Comment by thinkingserious** [comment]
Hello @jhayg12,

With regards to the template, I suggest the [Litmus](https://litmus.com/) service for testing.

**Comment by jhayg12** [comment]
Hi @thinkingserious 

I think the [Litmus](https://litmus.com/) service where perfectly fit for our needs hope it will fix the broken image issue. BTW thanks for the quick response.

**Comment by thinkingserious** [comment]
Awesome, I'm going to close this issue out, but feel free to re-open or create a new issue if you need further help.

**Comment by jhayg12** [comment]
Hi @thinkingserious,

No email has been sent when using this [link](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#send-multiple-emails-to-multiple-recipients) when I tried to make the third parameters to an empty array

![image](https://user-images.githubusercontent.com/33854581/59738360-92aa6880-9293-11e9-86ed-fb381c8d9a59.png)

and by not using the third parameters on the Subject, PlainTextContent, and HtmlContent

![image](https://user-images.githubusercontent.com/33854581/59738299-5545db00-9293-11e9-8f6a-6363d6e99c6d.png)

Also found out that if the third parameters on the `$tos` array list is always the same like the `"-name-" => "Jayson Suyat"` for 5 recipients only one person will received an email.
