### ISSUE TITLE
Sending on behalf of customers

### ISSUE THREAD

**Issue by oferu** [sendgrid/sendgrid-php#842]
#### Issue Summary
Our application sends mass emails on behalf of our customers.
Currently, our "From" address is our customers' email address and this caused sending failures for customers having Yahoo or AOL email addresses because of Yahoo/AOL DMARC regulations as the emails are not really sent from Yahoo/AOL but from our application on their behalf.

How should we set up the email headers so that:
1.  The emails will not be blocked as a result of DMARC
2. Replies to the emails will go to the customers' email address
3. Bounces will also go to the customers' email address

Do you have an example for accomplishing the above 3?

We did try several things:
a. Set the From to our authenticated domain and set a Reply-To to the customer address. However, bounced emails are not received by the customer.
b. Set addHeader('Sender', 'someEmailAtOurDomain') hoping DMARC would now check authentication for the Sender and not the From but this still failed with the DMARC issue. 
c. Set addHeader('Return-Path', 'customerEmail') but this did not send bounced emails to the customer.

Following is our code:
		require FCPATH."vendor/autoload.php";
		$sendgrid = new SendGrid(SENDGRID_USERNAME, SENDGRID_PASSWORD);
		$email = new SendGrid\Email();
		$email->setTos($to_array);
		$email->setFrom($from_email);
		$email->setFromName($from_name);
		$email->setSubject($subject);
		$email->setHtml($body);

Thanks

**Comment by thinkingserious** [comment]
Hello @oferu,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
