### ISSUE TITLE
Emails sent with BCC do not have substitutions

### ISSUE THREAD

**Issue by jaspax** [sendgrid/sendgrid-php#845]
#### Issue Summary

This is essentially the same issue as #366: sending an email with a substitution or which uses `dynamic_template_data` goes correctly to the original sender, but does NOT correctly go to the person being BCC'd, as all substitutions are empty. The difference here is that I'm enabling BCC through the web interface at https://app.sendgrid.com/settings/mail_settings.

I understand the workaround given in the original bug, and I'm able to apply it to my codebase, but I insist that this is still a bug. I should be able to enable BCC via the web interface without needing to modify the code that generates the email. This is particularly the case because the main reason to enable the BCC feature is to create an additional copy of the email as it was sent to the customer for archival purposes.

#### Steps to Reproduce

1. Create any email with `dynamic_template_data`
```
    function welcomeEmail() {
        sendgrid.send({
            to: 'user@email.com',
            from: 'support@product.com',
            replyTo: 'support@product.com',
            subject: 'Welcome to our Product',
            templateId: 'd-08564cfbacd04f0fa62d1c28be2a8082',
            dynamic_template_data: { name: user.name }
        });
    }
```

2. Enable BCC in the web interface at https://app.sendgrid.com/settings/mail_settings
3. When BCC'd emails are recieved, all substitutions are empty.

#### Technical details:

* NodeJS @sendgrid/client 6.3.0

**Comment by thinkingserious** [comment]
Hello @jaspax,

Thank you for reporting this, I will surface to the product team.

With Best Regards,

Wlmer

**Comment by papigers** [comment]
What is the status of this? I have the same problem and I use the node API.

**Comment by jamesw6811** [comment]
Same here.

**Comment by Yetiinc** [comment]
Hi there, 
Did this get resolved? We're finding the same issue here. It was pulling in data till yesterday - now, no longer does.

**Comment by childish-sambino** [comment]
Similar to https://github.com/sendgrid/sendgrid-nodejs/issues/729

**Comment by thinkingserious** [comment]
Hello @jaspax,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
