### ISSUE TITLE
[ Magento2 ] SendGrid Email Delivery Extension causes setup:upgrade command to stall indefinitely when set in production mode

### ISSUE THREAD

**Issue by m-kento** [sendgrid/sendgrid-php#848]
#### Issue Summary

I am currently working on a Magento 2 (v2.2.6) site and I'm running into an issue where the SendGrid Email Delivery extension is preventing us from deploying in production mode. There doesn't seem to be any issue when the site is in developer mode, but once it is set into production mode, the setup:upgrade command stalls indefinitely once it reaches the SendGrid extension. This has been tested by removing extensions one by one and re-running the setup:upgrade command until it would no longer stall. 

I need to be able to use the SendGrid extension in production mode which I cannot do because of this issue and I was hoping someone would be able to shed some light into this issue and hopefully provide a solution.

#### Steps to Reproduce

1. Set site into production mode
2. Run the php bin/magento setup:upgrade command with the SendGrid Email Delivery extension enabled
3. Execution of setup:upgrade will start running and then eventually stall indefinitely
4. Remove SendGrid Email Delivery extension
5. Run setup:upgrade again and it will complete without stalling

I am expecting to be able to run the setup:upgrade command with the site set in production mode with the SendGrid Email Delivery extension enabled without having it stall indefinitely

#### Technical details:

* <module name="SendGrid_EmailDeliverySimplified" setup_version="2.0.0"/>
* PHP Version: 7.0
* Magento Version: 2.2.6

**Comment by thinkingserious** [comment]
Hello @m-kento,

I believe this is the correct repo for your issue: https://github.com/sendgrid/magento_m2_plugin

Thanks!

With Best Regards,

Elmer
