### ISSUE TITLE
Subject Line Not Displaying On SendGrid Email via Python (Django) 

### ISSUE THREAD

**Issue by sgrobert** [sendgrid/sendgrid-php#852]
#### Issue Summary

Hi there, I'm new to SendGrid and only have been attempting at the API last 2 days. I have been trying to display the "Subject" in the Email sent via SendGrid but none of my efforts showed up on the actual email itself. 

I have also double-checked that the total characters do not exceed the recommended 78 characters of the subject line for usage.

#### Steps to Reproduce

I've tried the examples shown in the following links:
a. https://github.com/sendgrid/sendgrid-python/blob/master/use_cases/transactional_templates.md
b. https://github.com/sendgrid/sendgrid-python/blob/master/examples/mail/mail.py
c. https://sendgrid.com/docs/API_Reference/api_v3.html

---

But none of the above seem to work, even though I have shifted the Subject title in the various aspects of the suggested JSON file, including within "dynamic_template_data", but none seem to work.

1. JSON settings on Python 
 ```
 message = {
            'mail_settings': {
                'bcc': {
                    'email': json_data['bcc_email'],
                    'enable': True,
                },
            },
            'personalizations': [
                {
                    'to': [
                        {
                            'email': json_data['to_email'],
                            'name': json_data['to_name'],
                        }
                    ],
                    'dynamic_template_data': {
                        'subject': json_data['subject'],
                        'email': json_data['to_email'],
                    },
                    'subject': json_data['subject'],
                }
            ],
            'from': {
                'email': json_data['from_email'],
                'name': json_data['from_name'],
            },
            "reply_to": {
                'email': json_data['reply_to_email'],
                'name': json_data['reply_to_name'],
            },
            'template_id': json_data['template_id'],
            'attachments': [
                {
                    'content': encoded,
                    'content_id': json_data['attachment_name'],
                    'disposition': 'attachment',
                    'filename': json_data['attachment_filename'],
                    'name': json_data['attachment_name'],
                    'type': 'application/pdf'
                }
            ],
        }
```

So after trying multiple angles, I am unsure what may I further attempt to show the details up on the subject line.

The format of the auto-generated subject line is as follows:

> **[ text ]-You PDF Enclosed-#XXX-XXXX-XXXX** 

Not too sure if the format does affect in being added to the Subject line as well. 

#### Technical details:

* sendgrid-python: sendgrid==6.0.5
* python: 2.7

---

Hope someone may assist me on this as I faced a number of issues and will be posting different issue docs in hopes to address them as soon as possible. Thank you!

**Comment by thinkingserious** [comment]
Hello @sgrobert,

Have you tried to update the settings in the UI like the example file attached?
<img width="1073" alt="Screen Shot 2019-06-13 at 9 15 17 PM" src="https://user-images.githubusercontent.com/146695/59483074-88661580-8e20-11e9-8dfd-521c98c50633.png">

With Best Regards,

Elmer

**Comment by sgrobert** [comment]
Hi @thinkingserious,

Thank you so much! This simple trick worked perfectly! 

Appreciate the help on this!
