### ISSUE TITLE
Cannot sent to multiple recipients if no third parameters (substitutions) provided on the `$tos` array list or by not using them in Subject, PlainTextContent, and HtmlContent Object

### ISSUE THREAD

**Issue by jhayg12** [sendgrid/sendgrid-php#854]
Hi @thinkingserious,

No email has been sent when using this [link](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#send-multiple-emails-to-multiple-recipients) when I tried to make the third parameters (substitutions) to an empty array

![image](https://user-images.githubusercontent.com/33854581/59738360-92aa6880-9293-11e9-86ed-fb381c8d9a59.png)

and by not using the third parameters (substitutions) on the Subject, PlainTextContent, and HtmlContent

![image](https://user-images.githubusercontent.com/33854581/59738299-5545db00-9293-11e9-8f6a-6363d6e99c6d.png)

Also found out that if the third parameters on the `$tos` array list is always the same like the `"-name-" => "Jayson Suyat"` for 5 recipients only one person will received an email.

_Originally posted by @jhayg12 in https://github.com/sendgrid/sendgrid-php/issues/840#issuecomment-503409646_

**Comment by thinkingserious** [comment]
Hello @jhayg12,

What is the result you are trying to achieve? Perhaps our [transactional templates](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#transactional-templates) are better suited for your use case. I believe the second example there is what you need.

With best regards,

Elmer

**Comment by jhayg12** [comment]
Hi @thinkingserious ,

What I want to achieve is something like this.

```
subject: Test Subject Email
email_body: Test Email Body
```

I want to send the email template above to multiple users without seeing each other on the TO list.
I already tried this one [link](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#send-multiple-emails-to-multiple-recipients) but I don't want to use any substitutions since my email template should be the same to all.

But when I tried to put some substitution parameters on the email subject such `subject 1` and `subject 2` it works as expected but it does not what I want. Is it possible to use this [link](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#send-multiple-emails-to-multiple-recipients) without using substitutions parameters

Thanks

**Comment by childish-sambino** [comment]
Yes, that's possible. Just don't pass any args beyond address and name:

```php
$tos = [
    new \SendGrid\Mail\To(
        "test+test1@example.com",
        "Example User1"
    ),
    new \SendGrid\Mail\To(
        "test+test2@example.com",
        "Example User2"
    ),
    new \SendGrid\Mail\To(
        "test+test3@example.com",
        "Example User3"
    )
];
```
