### ISSUE TITLE
not working on window OS

### ISSUE THREAD

**Issue by stefen-hasselberg** [sendgrid/sendgrid-php#857]
#### Issue Summary

HI All,
Hoping someone might be able to help me,  I have inherited a couple of PHP websites to look after at work and we shutting down our exchange server soon, so I need to update the websites to use sendgrid to send out the emails.  I have download the sendgrid-php library and copy the folder into the root directory of the website,  as we not using Composer.  
I have then try to send an email using the [Quick Start - Hello Email example](https://github.com/sendgrid/sendgrid-php#quick-start) but each time i get the following response

0
Array
(
    [0] => 
)

i have successfully send an email using curl and powershell so i know i'm not getting block by firewall.  But i can't send an email through using PHP.  Any information on how to fix this would be greatly appericated

Many Thanks
Stefen

#### Technical details:
* Windows 2008 R2 SP1
* sendgrid-php Version: 7.3.0
* PHP Version: 5.6.16  (as of July 03, 2019)

**Comment by thinkingserious** [comment]
Hello @stefen-hasselberg ,

Have you tried [this solution](https://github.com/sendgrid/sendgrid-php/issues/744#issuecomment-431465302)?

Thanks!

With best regards,

Elmer
