### ISSUE TITLE
api send() return 502

### ISSUE THREAD

**Issue by liyaal** [sendgrid/sendgrid-php#858]
Hi Sendgrid Team,

Since yesterday, each call to $sendgrid->send() return me that : 

502 Array ( [0] => HTTP/1.1 100 Continue [1] => [2] => HTTP/1.1 502 Bad Gateway [3] => Server: nginx [4] => Date: Fri, 05 Jul 2019 12:23:37 GMT [5] => Content-Type: text/html [6] => Content-Length: 6023 [7] => Connection: keep-alive [8] => ETag: "5c65bc03-1787" [9] => [10] => )

```
$email = new \SendGrid\Mail\Mail(); 
    $email->setFrom($expediteur_mail, $expediteur_nom);
    $email->setSubject($sujet);
    $email->addTo($destinataire, "");
    $email->addContent("text/plain", $message_txt);
    $email->addContent(
        "text/html", $message_html
    );
    $sendgrid = new \SendGrid('xXxXxXxX');
    try {
        $response = $sendgrid->send($email);
      print $response->statusCode() . "\n";
       print_r($response->headers());
        print $response->body() . "\n";
    } catch (Exception $e) {
       echo 'Caught exception: '. $e->getMessage() ."\n";
    }
```

Where can I have logs to know more aboit that ?

Thanks !

**Comment by thinkingserious** [comment]
Hello @liyaal,

This looks like it could have been a temporary server outage. Are you still experiencing this issue?

With best regards,

Elmer
