### ISSUE TITLE
Not getting from email in sendgrid event hook

### ISSUE THREAD

**Issue by VirendraArekar** [sendgrid/sendgrid-php#860]
> I send the email through Laravel Mail::send() function and i get no response but i created sendgrid webhook get it all email events which i send it but in the response there is not from email.i getting the to email and all the neccessary data but not getting the from email.I get it smtp_id  but this is the encrypted form of my sender or from email address.So how to get that from email value.

**Comment by thinkingserious** [comment]
Hello @VirendraArekar,

Could you please share your Event Webhook processing code so that I may try to reproduce?

Thanks!

With best regards,

Elmer
