### ISSUE TITLE
Floats in macros

### ISSUE THREAD

**Issue by Lasse-Unsigned-Double** [sendgrid/sendgrid-php#861]
#### Issue Summary

When using transactional templates, you cannot inject floats or doubles.

#### Steps to Reproduce

- Create transactional template.
- Attempt to substitute macro value with a double or float.

#### Suggested Fix:

In this file: https://github.com/sendgrid/sendgrid-php/blob/master/lib/mail/Substitution.php replace the is_int check on line 87 with is_numeric.

Also, it would be nice if you returned the offending value key.

**Comment by thinkingserious** [comment]
Hello @Lasse-Unsigned-Double,

Thanks for bringing this to our attention and for providing a fix!

This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

With best regards,

Elmer
