### ISSUE TITLE
Unsubscribe using transactional email with dynamic template

### ISSUE THREAD

**Issue by alvarotrigo** [sendgrid/sendgrid-php#862]
#### Issue Summary

When sending transactional emails using a dynamic template I want to offer subscribers the option to unsubscribe.

At the moment the Unsubscribe link and the Unsubscribe preferences link are empty and do nothing:

![image](https://user-images.githubusercontent.com/1706326/61319801-486fc500-a808-11e9-964d-f2a72089a877.png)

![image](https://user-images.githubusercontent.com/1706326/61319809-532a5a00-a808-11e9-94c1-b94ef59b3c45.png)

#### Steps to Reproduce

1. Create a template.
2. Add the unsubscribe module.
3. Send a transactional email using such template.

I know, there's another option, which is including the unsubscribe text under every email by using the "Settings > tracking > Subscription Tracking" option, but I'm not interested in it.

I want to be able to include the text in my template. 
--

#### Technical details:

* sendgrid-php Version: master latest

**Comment by natelowry** [comment]
You may need to set the ASM Unsubscribe Group ID as shown here (in ruby, but the concept is the same):
https://github.com/sendgrid/sendgrid-ruby/issues/59#issuecomment-379083848

**Comment by zeari** [comment]
This seems to be an unsolved problem for several years now.
How about some settings on the unsubscribe module in the editor? maybe some info near the module?
Or maybe some example with unsubscribe? 
Why does global unsubscribe need a group id? 
cant it default to the group id marked default?

**Comment by Elyx0** [comment]
Anyone found a solution?

**Comment by zeari** [comment]
@Elyx0 something along the lines of
```
mail.setASM(new ASM());
mail.asm.setGroupId(request.unsubscribeGroup);
```

For whatever language youre using. The group ID is under unsubscribe groups
![SendGrid](https://user-images.githubusercontent.com/11256940/67935571-d19de280-fbd2-11e9-85e0-c44da216f5e9.png)

**Comment by pigmento** [comment]
hello, i went to menu Settings > Tracking  option. I activated Subscription Tracking

**Comment by thinkingserious** [comment]
Hello everyone,

It looks like there were a few solutions offered here (thanks for chipping in :)) so I will close this one out. If someone is still having difficulty with this feature, please let us know. Thanks!

With best regards,

Elmer

**Comment by admarko** [comment]
Definitely still having issues with this. I have Subscription Tracking activated and still not working.

**Comment by childish-sambino** [comment]
@admarko Please open a new issue with details about the problem you're experiencing.
