### ISSUE TITLE
Empty templates array

### ISSUE THREAD

**Issue by atsareva** [sendgrid/sendgrid-php#864]
Hi guys!

####  Summary

I'm trying to get all transactional templates to save their IDs but **templates** method returns empty array. However if I try to get template by Id, It works fine.

#### Steps to Reproduce

**Templates** method doesn't work even via console using curl, therefore I just provide curl requests.
1. curl -X "GET" "https://api.sendgrid.com/v3/templates" -H "Authorization: Bearer MY_API_KEY" -H "Content-Type: application/json"

**Returns** 
`{"templates":[]}`

2. curl -X "GET" "https://api.sendgrid.com/v3/templates/d-cd5b73442ffc4e37bdf247abbe8d3095" -H "Authorization: Bearer MY_API_KEY" -H "Content-Type: application/json"

**Returns** 
```
{"id":"d-cd5b73442ffc4e37bdf247abbe8d3095","name":"Test2","generation":"dynamic","updated_at":"2019-07-21 15:10:38","versions":[{"id":"d38d3b8a-faf6-4cef-841e-e8b7fe4e364e","user_id":11514558,"template_id":"d-cd5b73442ffc4e37bdf247abbe8d3095","active":1," .....
......
```
#### Technical details:

* Ubuntu 18.04.2 LTS
* curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1c zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3

**Comment by tijmenve** [comment]
I'm having the exact same issue.

I'm able to get a template by id: $sendgrid->client->templates()->_($template_id)->get();

However when I try to load all templates: $response = $sendgrid->client->templates()->get();
$response->body():
This is the response:
`"{"templates":[]}"`

**Comment by atsareva** [comment]
Hi @tijmenve ,

I've contacted to SendGrid support and they answered that some calls have been changed.

Please try this url - https://api.sendgrid.com/v3/templates?generations=dynamic, it works for me

```
   $queryParams = array('generations' => 'dynamic');
   $response = $this->getClient()->templates()->get(null, $queryParams);
```

**Comment by tijmenve** [comment]
Great, this works for me.

Thank you @atsareva!

**Comment by thinkingserious** [comment]
Hello @atsareva,

Thanks for providing the solution!

With best regards,

Elmer
