### ISSUE TITLE
Inbound Webhook is not working in Sendgrid

### ISSUE THREAD

**Issue by maneeshrao66** [sendgrid/sendgrid-php#865]
#### Issue Summary

Hi, I have added Host and URL in Sendgrid Inbound parse after authenticate the domain name.
I added a URL, which is POST API and tested it on Postman and getting 200 response. But When I trying to reply my email and want to capture the Inbound message by using API. it is not printing anything.

#### API

    public function receiveSGEmailsInfo(Request $request)
    {
        $filePath1 = realpath('SendGridInfo/') . '/' . "webhook_SG_bouncetttt.txt";
        $file1 = fopen($filePath1, "a+");
        fwrite($file1, print_r("heloooo", true));
        fclose($file1);

        $fullPath =  realpath('SendGridInfo/') . '/' . "webhook_SG_email_received.txt";
        $file = fopen($fullPath, "a+");
        fwrite($file, print_r($_POST, true));
        fclose($file);
     }

**Comment by thinkingserious** [comment]
Hello @maneeshrao66,

Thanks for reaching out to us and thank you for your patience.

In the above example, I don't see where you are reading the values from the `$request` parameter. Is there some code missing?

With best regards,

Elmer
