### ISSUE TITLE
Cant' reach  https://api.sendgrid.com/v3/mail/send endpoint?

### ISSUE THREAD

**Issue by KamilSobieraj** [sendgrid/sendgrid-php#867]
Hello everyone!

I've got an issue with sending e-mails with PHP - I get202 status, but no e-mails are delivered. 

I've already contacted with SendGrid support team and we agreed that my  API KEY is valid and has correct permissions. 
I use:
- PHP 7.3.0
- Composer 1.8.3

This is my composer.json:
```
{
  "require": {
    "sendgrid/sendgrid": "^7.3",
    "sendgrid/php-http-client": "~3.9.6"
  }
}
```
I produced the simplest test endpoint to send an e-mail. It's in here -> http://konfiguratorszkolen.pl/send-email/test.php
The code in this PHP looks this:
```
<?php
require 'vendor/autoload.php'; 

$email = new \SendGrid\Mail\Mail(); 
$email->setFrom("testemail1@gmail.com", "Example User");
$email->setSubject("Sending with Twilio SendGrid is Fun");
$email->addTo("testemail2@gmail.com", "Example User");
$email->addContent("text/plain", "and easy to do anywhere, even with PHP");
$email->addContent(
    "text/html", "<strong>and easy to do anywhere, even with PHP</strong>"
);
$sendgrid = new \SendGrid("MyValidAPIKey");
try {
    $response = $sendgrid->send($email);
    print $response->statusCode() . "\n";
    print_r($response->headers());
    print $response->body() . "\n";
} catch (Exception $e) {
    echo 'Caught exception: '. $e->getMessage() ."\n";
}
?>
```
I get a response 202 which looks like this:
`202 Array ( [0] => HTTP/1.1 202 Accepted [1] => Server: nginx [2] => Date: Wed, 31 Jul 2019 14:50:07 GMT [3] => Content-Length: 0 [4] => Connection: keep-alive [5] => X-Message-Id: 5uTcFfC0QfatoX_YN-3dDg [6] => Access-Control-Allow-Origin: https://sendgrid.api-docs.io [7] => Access-Control-Allow-Methods: POST [8] => Access-Control-Allow-Headers: Authorization, Content-Type, On-behalf-of, x-sg-elas-acl [9] => Access-Control-Max-Age: 600 [10] => X-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html [11] => [12] => )
`
So it seems to be ok at this point.

Support says that I don't send POST request to the https://api.sendgrid.com/v3/mail/send endpoint. But shouldn't $response = $sendgrid->send($email); do that job?

What might be the issue? How can I reach the endpoint?

I want to add, that this kind of code worked perfectly in about May. It stopped a few weeks ago. What am I doing wrong?

**Comment by thinkingserious** [comment]
Hello @KamilSobieraj,

I'm not sure what is going on here as I'm unable to reproduce. Perhaps the email is going to SPAM? Does this happen 100% of the time?

With best regards,

Elmer
