### ISSUE TITLE
Sending duplicated emails randomly to some of the recipients

### ISSUE THREAD

**Issue by DiegoDePalacio** [sendgrid/sendgrid-php#870]
#### Issue Summary

A php cronjob is running once per day, getting the email addresses from a database and triggering a message to all of the recipients inside of a loop.

Inside of the same loop, the recipients are being marked in order to avoid duplicates.

Nevertheless, the duplicated emails are being sent at the same moment to the same recipient, sometimes are 2, 4 or even 11 emails with the same content.

By the way, the email is the primary key of the table that is being queried, decreasing, even more, the probability of a mistake inside of the sending loop.

#### Steps to Reproduce

This is the code of the script that I'm using:

<?php

include('api/conn.php');

$home = "https://mamadiario.com";
$sql = $conn->query("SELECT email, name FROM tbl_user WHERE subscribed > 0");
while ($subscriber = mysqli_fetch_assoc($sql)) {
    $date = date('Y-m-d',strtotime('-2 days', time()));
    $video = $conn->query("SELECT earned, mama_diario_id FROM `tbl_user_score_detail` WHERE email = '" . $subscriber['email'] . "' AND date = '" . $date ."' AND mama_diario_id > 0");
    $videoOutput = mysqli_fetch_assoc($video);
    $earnedValue = $videoOutput['earned'];
    $mama_video = $conn->query("SELECT mama_description, mama_vframe_url, mama_url, mama_vframe_id, webpage FROM `tbl_mama_videos` WHERE mama_vframe_id = '" . $videoOutput['mama_diario_id'] ."'");
    $mamavideo_values = mysqli_fetch_assoc($mama_video);

    if ($earnedValue == '-2') {
        require("sendgrid-php/sendgrid-php.php");
        $to = new SendGrid\Email($subscriber['name'], $subscriber['email']);
        $from = new SendGrid\Email("Mamá Diario", "mamadiariotips@mamadiario.com");
        $subject = 'EXPIRA PRONTO: Mamá Diario: '.$mamavideo_values['mama_description'];
        $_SESSION['imgUrl'] = $mamavideo_values['mama_vframe_url'];
        $_SESSION['desc'] = $mamavideo_values['mama_description'];
        $_SESSION['videoPage'] = $home . '/' . $mamavideo_values['webpage'].'.php?email='.$subscriber['email'].'&watched=1';
        include('expirationVideo.php');
        $content = new SendGrid\Content("text/html", $expirationMessage);
        $mail = new SendGrid\Mail($from, $subject, $to, $content);
        $apiKey = 'SENDGRID-API-KEY';
        $sg = new \SendGrid($apiKey);
        $response = $sg->client->mail()->send()->post($mail);
        unset($_SESSION['imgUrl']);
        unset($_SESSION['desc']);
        unset($_SESSION['videoPage']);
        $update_query = $conn->query("UPDATE `tbl_user_score_detail` SET `earned` = '0' WHERE `email` = '".$subscriber['email']."' AND `mama_diario_id` = '".$mamavideo_values['mama_vframe_id']."' ");
    }
}

What's is wrong?

#### Technical details:

SendGrid vesion (substracted from the Changelog.md file): ## [5.1.2] - 2016-10-11 ##

**Comment by DaWe35** [comment]
Please format your code, it's unreadable.

**Comment by thinkingserious** [comment]
Duplicate: https://github.com/sendgrid/sendgrid-php/issues/904
