### ISSUE TITLE
Web API setup issue

### ISSUE THREAD

**Issue by domenicobosco** [sendgrid/sendgrid-php#871]
#### Issue Summary

Please i need your help!!!

I'm trying to setup the web api by following the tutorial to the thee but i get the following error:

401 Array ( [0] => HTTP/1.1 401 Unauthorized [1] => Server: nginx [2] => Date: Wed, 21 Aug 2019 02:01:15 GMT [3] => Content-Type: application/json [4] => Content-Length: 88 [5] => Connection: keep-alive [6] => Access-Control-Allow-Origin: https://sendgrid.api-docs.io [7] => Access-Control-Allow-Methods: POST [8] => Access-Control-Allow-Headers: Authorization, Content-Type, On-behalf-of, x-sg-elas-acl [9] => Access-Control-Max-Age: 600 [10] => X-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html [11] => [12] => ) {"errors":[{"message":"Permission denied, wrong credentials","field":null,"help":null}]}

#### Steps to Reproduce

i have used this basic PHP code:

```php
<?php
//require 'vendor/autoload.php'; // If you're using Composer (recommended)
// Comment out the above line if not using Composer
 require("sendgrid-php/sendgrid-php.php");
// If not using Composer, uncomment the above line and
// download sendgrid-php.zip from the latest release here,
// replacing <PATH TO> with the path to the sendgrid-php.php file,
// which is included in the download:
// https://github.com/sendgrid/sendgrid-php/releases
$email = new \SendGrid\Mail\Mail(); 
$email->setFrom("my@email.com", "Example User");
$email->setSubject("Sending with SendGrid is Fun");
$email->addTo("customer@email.com", "Example User");
$email->addContent("text/plain", "and easy to do anywhere, even with PHP");
$email->addContent(
    "text/html", "<strong>and easy to do anywhere, even with PHP</strong>"
);
$sendgrid = new \SendGrid(getenv('SENDGRID API'));
try {
    $response = $sendgrid->send($email);
    print $response->statusCode() . "\n";
    print_r($response->headers());
    print $response->body() . "\n";
} catch (Exception $e) {
    echo 'Caught exception: '. $e->getMessage() ."\n";
}

?>
```

#### Technical details:

* sendgrid-php Version: master (latest commit: [commit number])
* PHP Version: 5.6

**Comment by DaWe35** [comment]
Please format your code, it's unreadable.

**Comment by DaWe35** [comment]
As you can see in the error message, you sent wrong credentials. You need to generate an API key, and change this line:

`$sendgrid = new \SendGrid(getenv('SENDGRID API'));`

Please close this issue, if this was the problem

**Comment by Robin-the-Frog** [comment]
What do you mean by?
with the path to the sendgrid-php.php file, // which is included in the download: // https://github.com/sendgrid/sendgrid-php/releases

**Comment by bay-dice** [comment]
If you are not using Composer and don't know how to setenv then replace getenv('SENDGRID API') with 'SENDGRID API'. That is get rid of getenev().
If using Composer update .env file with your API key and replace getenv('SENDGRID API') with getenv('SENDGRID_API_KEY') i guess.

**Comment by thinkingserious** [comment]
Hello @domenicobosco,

It looks like you having an authentication problem. Please verify that `getenv('SENDGRID API')` returns your SendGrid API key. 

Thanks for helping out @bay-dice!

With best regards,

Elmer
