### ISSUE TITLE
personalizationIndex Not Passed to addSubstitutions Function

### ISSUE THREAD

**Issue by larrylampco** [sendgrid/sendgrid-php#873]
#### Issue Summary

In Mail::addDynamicTemplateDatas, the paramters `$personalizationIndex` and `$personalization` are not passed to Mail::addSubstitutions. 

![image](https://user-images.githubusercontent.com/1054358/63709372-5c8de580-c7fc-11e9-81d1-9bbb7a97c49c.png)

#### Steps to Reproduce

N/A

#### Technical details:

* sendgrid-php Version: master (latest commit: f64b6fd)

**Comment by thinkingserious** [comment]
Hi @larrylampco,

Thanks for taking the time to bring this to our attention!

This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

With best regards,

Elmer
