### ISSUE TITLE
Composer version and Dynamic Templates 

### ISSUE THREAD

**Issue by joaorsilva** [sendgrid/sendgrid-php#876]
#### Issue Summary

If I use composer, the support for Dynamic Templates isn't there.
I get a 400 error that we can't use substitution with dynamic templates.
I would advise to update the composer version of this code.
Though, if I download the repository version and include those classes it work fine.

**Comment by thinkingserious** [comment]
Hi @joaorsilva,

[That PR](https://github.com/sendgrid/sendgrid-php/compare/v7.3.0...master) has not been released yet.

We are working towards a consistent 2 week release cycle by 2020. In the mean time, we appreciate your patience and if you need that fix now, please utilize the code in the `master` branch. Not ideal, but that could be a quick bandaid until we release the next version.

With best regards,

Elmer
