### ISSUE TITLE
我在使用 php api时遇到一些问题 如下图 返回了202 但是我没有收到邮件

### ISSUE THREAD

**Issue by burt00** [sendgrid/sendgrid-php#877]
https://user-images.githubusercontent.com/30595984/63987957-961c6480-cb0c-11e9-9891-207e6021f8de.png

**Comment by peter279k** [comment]
Could you reproduce issue and use English writing?

And it will be fine for SendGrid suppport team to know where issue is.

**Comment by burt00** [comment]
Okay thank youI returned using php
But I didn't receive the mail.
202 Array ( [0] => HTTP/1.1 202 Accepted [1] => Server: nginx [2] => Date: Fri, 30 Aug 2019 01:57:02 GMT [3] => Content-Length: 0 [4] => Connection: keep-alive [5] => X-Message-Id: PbNwZ7sVT4ScPbABuuPA-w [6] => Access-Control-Allow-Origin: https://sendgrid.api-docs.io [7] => Access-Control-Allow-Methods: POST [8] => Access-Control-Allow-Headers: Authorization, Content-Type, On-behalf-of, x-sg-elas-acl [9] => Access-Control-Max-Age: 600 [10] => X-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html [11] => [12] => )




------------------ 原始邮件 ------------------
发件人: "Chun-Sheng, Li"<notifications@github.com>; 
发送时间: 2019年8月30日(星期五) 上午10:31
收件人: "sendgrid/sendgrid-php"<sendgrid-php@noreply.github.com>; 
抄送: "祎"<2339139097@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [sendgrid/sendgrid-php] 我在使用 php api时遇到一些问题 如下图 返回了202 但是我没有收到邮件 (#877)




Could you reproduce issue and use English writing?
 
And it will be fine for SendGrid suppport team to know where issue is.

**Comment by peter279k** [comment]
Hi, thanks for your reply. But I don't know how your codes execute.

If possible, could you provide your executed code?

**Comment by burt00** [comment]
Thank you for your reply, I have solved it, but I am happy to share my code.
202 has been successful, but my mailbox has no reminder
Need to be removed "getenv" 
![image](https://user-images.githubusercontent.com/30595984/63992487-9e7d9b00-cb1e-11e9-8710-274d331ba8e1.png)

**Comment by peter279k** [comment]
Hi @burt00, hopefully you've solved the issue.

This issue can be closed because you've solved :).
