### ISSUE TITLE
Permission denied by following the SendGrid docs (PHP)

### ISSUE THREAD

**Issue by LucaPennisi** [sendgrid/sendgrid-php#878]
#### Issue Summary

I have just registered to sendgrid and followed the instructions to send PHP emails through the API. After following exactly what the docs said, I keep getting this error:

`401 Array ( [0] => HTTP/1.1 401 Unauthorized [1] => Server: nginx [2] => Date: Wed, 11 Sep 2019 16:09:41 GMT [3] => Content-Type: application/json [4] => Content-Length: 88 [5] => Connection: keep-alive [6] => Access-Control-Allow-Origin: https://sendgrid.api-docs.io [7] => Access-Control-Allow-Methods: POST [8] => Access-Control-Allow-Headers: Authorization, Content-Type, On-behalf-of, x-sg-elas-acl [9] => Access-Control-Max-Age: 600 [10] => X-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html [11] => [12] => ) {"errors":[{"message":"Permission denied, wrong credentials","field":null,"help":null}]}`

#### Steps to Reproduce

1. Follow the official guide (PHP API): https://app.sendgrid.com/guide/integrate/langs/php
2. Copy-paste a new API key
3. Run

#### Technical details:

Here's the code:

```
<?php
//require 'vendor/autoload.php'; // If you're using Composer (recommended)
// Comment out the above line if not using Composer
 require("sendgrid-php/sendgrid-php.php");
// If not using Composer, uncomment the above line and
// download sendgrid-php.zip from the latest release here,
// replacing <PATH TO> with the path to the sendgrid-php.php file,
// which is included in the download:
// https://github.com/sendgrid/sendgrid-php/releases
$email = new \SendGrid\Mail\Mail(); 
$email->setFrom("info@mydomain.com", "My Name");
$email->setSubject("Test");
$email->addTo("receiver@gmail.com", "Example User");
$email->addContent("text/plain", "and easy to do anywhere, even with PHP");
$email->addContent(
    "text/html", "<strong>and easy to do anywhere, even with PHP</strong>"
);
$sendgrid = new \SendGrid(getenv('COPY-PASTED-API-KEY'));
try {
    $response = $sendgrid->send($email);
    print $response->statusCode() . "\n";
    print_r($response->headers());
    print $response->body() . "\n";
} catch (Exception $e) {
    echo 'Caught exception: '. $e->getMessage() ."\n";
}
```

**Comment by DaWe35** [comment]
Change
`$sendgrid = new \SendGrid(getenv('COPY-PASTED-API-KEY'));`
to
`$sendgrid = new \SendGrid('COPY-PASTED-API-KEY');`

**Comment by thinkingserious** [comment]
Hi @LucaPennisi,

@DaWe35's suggestion is correct; however, I advise you to store your API Key in an environment variable and use the `getenv('YOUR_ENVIRONMENT_VARIABLE_NAME')` function to retrieve it. 

Thanks for helping out @DaWe35!

With best regards,

Elmer
