### ISSUE TITLE
Missing commits in 7.3.0 release 

### ISSUE THREAD

**Issue by SamMousa** [sendgrid/sendgrid-php#881]
I'm getting an issue in production that was fixed here:

https://github.com/sendgrid/sendgrid-php/commit/b0a3721d9e42121140b3ac4ecb5263827740a3ec

However, that commit, even though it was done in Oct 2018 is not part of 7.3.0
If I look at the file history in master:
![image](https://user-images.githubusercontent.com/547021/65578935-089b2b80-df77-11e9-9280-cf76696d741d.png)

And then look at the file history for 7.3.0:
![image](https://user-images.githubusercontent.com/547021/65579005-29638100-df77-11e9-85c0-95e780039d24.png)

This concerns me a lot since it basically means that 7.3.0, released on April 13th 2019 is missing arbitrary commits.

@thinkingserious You tagged the release, can you explain / look into what happened?

**Comment by thinkingserious** [comment]
Hello @SamMousa,

I'm not sure what happened there, but it does appear that those fixes are included in the current release. Are you able to upgrade?

With best regards,

Elmer
