### ISSUE TITLE
Issue with personalization

### ISSUE THREAD

**Issue by drimlike** [sendgrid/sendgrid-php#882]
#### Issue Summary

We had an issue with personalizations, where the first key was set to null, which was producing this error: The personalization block may not be null.

#### Steps to Reproduce

You could try this code :

`
require('sendgrid-7.3.0/vendor/autoload.php');

    $from = 'from@test.com';

    $mail=new SendGrid\Mail\Mail();

    $mail->setFrom(new \SendGrid\Mail\From($from, "Your Name"));

    $subject = 'Test Subject',
   
    $plainTextContent = new \SendGrid\Mail\PlainTextContent(
        $body_text
    );
    $htmlContent = new \SendGrid\Mail\HtmlContent(
        $body
    );

    $mail->addContent('Test Text');
    $mail->addContent('<b>Test Text</b>');   

    $recipients = array('test@test.com', 'test@test2.com'); 
    $subject = 'Test';
    $recp_cnt = count($recipients);
    $personalization_array = array();

    for ($i = 0; $i < $recp_cnt; $i++) {
        $personalization[$i] = new \SendGrid\Mail\Personalization();
        $personalization[$i]->addTo(new \SendGrid\Mail\To($recipients[$i]));
        
        $personalization[$i]->setSubject(
            new \SendGrid\Mail\Subject($subject)
        );

        $personalization_array[$i] = $personalization[$i];
    }

    $mail->addPersonalization($personalization_array);
    
        $mail->setReplyTo(new \SendGrid\Mail\ReplyTo($from, "Your Name"));

    $apiKey = 'YOUR_KEY';
    $sg = new \SendGrid($apiKey);

    $response = $sg->send($mail);

    if ($response->statusCode() < 200 || $response->statusCode() >= 300) {

        $arr = array ('response'=>'error','comment'=>$response->statusCode());
        header('Content-Type: application/json');
        echo json_encode($arr);
        echo $response->statusCode();
        print_r($response->headers());
        echo $response->body();

        print_r( json_decode(json_encode($mail), true));
        die(); // we stop here as it seems that we are having some issues

    }`

You should get the same error we did: **The personalization block may not be null.**

The only workaround we found was to change the function `function addPersonalization($personalization)` and replaced:

`public function addPersonalization($personalization)
    {
        $this->personalization[] = $personalization;
    }`

by:

`public function addPersonalization($personalization)
    {
        $this->personalization = $personalization;
    }`

Are we safe to use this workaround? 

Thanks

#### Technical details:

* sendgrid-php Version: 7.03
* PHP Version:  7.2

**Comment by lode** [comment]
I'm encountering the same issue. Working with Personalization objects breaks.

```php
$from    = new From("test@example.com", "Foo Bar");
$to      = new To("test@example.com", "Bar Foo");
$subject = "Bazzz";
$content = new Content('text/plain', "Baf!");

$mail = new Mail();
$mail->setFrom($from);
$mail->setSubject($subject);
$mail->addContent($content);

$personalisation = new Personalization();
$personalisation->addTo($to);
$mail->addPersonalization($personalisation);
 
$sendGrid = new SendGrid('...');
$sendGrid->send($mail);
```

That returns a 400 with

```json
{
    "errors": [
        {
            "message": "The personalization block may not be null.",
            "field": "personalizations.0",
            "help": null
        }
    ]
}
```

Where as the same code but with `Mail->addTo()` instead of Personalization objects does work:

```php
$from    = new From("test@example.com", "Foo Bar");
$to      = new To("test@example.com", "Bar Foo");
$subject = "Bazzz";
$content = new Content('text/plain', "Baf!");

$mail = new Mail();
$mail->setFrom($from);
$mail->setSubject($subject);
$mail->addContent($content);

$mail->addTo($to);
 
$sendGrid = new SendGrid('...');
$sendGrid->send($mail);
```

It seems the same features can be reached, for example by adding substitutions to the `To` object, but for me the `Personalization` object feels nicer to work with.

The example code (https://github.com/sendgrid/sendgrid-php/blob/master/examples/helpers/mail/example.php#L37) also contains something simular. That example does work, but it is only because when constructing the `Mail` object a first `To` is passed.

For my use case I have a list of people to email, so it is way easier to loop over that and add them, then to add the first one by passing it to the Mail constructor, and then loop over the others.

**Comment by thinkingserious** [comment]
Fixed by https://github.com/sendgrid/sendgrid-php/pull/705
