### ISSUE TITLE
Subject and content not working in Transactional templates.

### ISSUE THREAD

**Issue by Graloth** [sendgrid/sendgrid-php#889]
#### Issue Summary

I have set the mail subject using `setSubject('Just a test email')`, and added both plain text and html content using `addContent`.

Yet when then send the mail, I notice that neither work:

- Subject doesn't get overwritten with the subject I defined.
- Subject also isn't available in tag-form (tried `<%subject%>` and `{{subject}}`)
- Content isn't shown, tried using several different tags (`<%body%>`, `<%content%>`, `{{body}}` and `{{content}}`)

Having searched and read several documentations about the API and the subject/body, I haven't found any clear documentation that explains how to get them to work, only that "for transactional templates they work a bit differently".

Any and all help is greatly appreciated.

#### Steps to Reproduce

I have just followed the guide here: [Sending an Email to a Single Recipient](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#send-an-email-to-a-single-recipient)
With the only changes being different emails and names, and that I've added a template using `setTemplateId`.

It works fine if I don't include a template, since it just sends the mail without one, but I need to be able to use it with a template wrapper around.

The mail I receive if I use a template is the correct template, just without the content and with the default template subject (not what I defined).

#### Technical details:

* sendgrid-php Version: 7.3.0 (installed via composer)
* PHP Version: 7.2.20

**Comment by oscarpropify** [comment]
I´m suffering exactly the same issue

**Comment by Robin-the-Frog** [comment]
Hi both
I'm a total newbie here, having just spent 5 days trying to get SG working at all!
I have a template (Transactional email) working just fine, maybe I was just lucky?!
I don't have `setSubject` or `addContent` specified in my code at all, they're both handled by the template.
So here is an excerpt (not the whole coding) of my email.

Some notes:
1. I'm using $variables
2. The values `first_name`, `main_loc_display`, `user_username`, `temp_password_plain` and `encoded_url`
relate to the {{...}} variables set in the Template. e.g. {{first_name}} is on my Template somewhere. etc 

```
require("sendgrid/sendgrid-php.php");  // I'm not using Composer

$email = new \SendGrid\Mail\Mail(); 

$email->setFrom("info@mydomain.co.uk", "MyXXXXX");

$email->addTo(
				$test_to_email,
				$test_to_name,
				[
					'first_name' => $test_first_name,
					'main_loc_display' => $test_main_loc_display,
					'user_username' => $test_user_username,
					'temp_password_plain' => $test_temp_password_plain,
					'encoded_url' => $test_encoded_url
				]
			);
						
$email->setTemplateId("d-1bedXXXXXXX");
					
$sendgrid = new \SendGrid($test_api_key);

etc
etc
```

I don't know if this helps at all? Sorry if not, this is all new to me as well

Robin

**Comment by thinkingserious** [comment]
Hello @Graloth, @oscarpropify,

Please review the example [here](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#transactional-templates). I hope that helps!

With best regards,

Elmer

**Comment by thinkingserious** [comment]
Thanks for helping out @Robin-the-Frog!
