### ISSUE TITLE
Uncaught Error: Call to undefined method SendGrid\\Mail\\Mail::setFromName()

### ISSUE THREAD

**Issue by clickbid** [sendgrid/sendgrid-php#892]
Hello,

I just upgraded my sendgrid api to 7.3 from 1.x. I have everything working except this one error, so far. Is the setFromName no longer used in 7.3? If not is there a way to set this in the email. We were using it quite a bit in our application and now it appears as though I'm going to have to go through and remove it. Is that correct?

Thanks.

**Comment by jlapitan** [comment]
@clickbid 

Try this approach

`
$email = new \SendGrid\Mail\Mail();
$email->setFrom("test@example.com", "Example User");
`

**Comment by thinkingserious** [comment]
Thanks for helping out @jlapitan!

@clickbid,

Please let us know if you are still experiencing any difficulty.

With best regards,

Elmer
