### ISSUE TITLE
Unable to fetch template IDs from the new Email Designs section

### ISSUE THREAD

**Issue by edi** [sendgrid/sendgrid-php#893]
#### Issue Summary

So, while this is not an issue but more of a missing feature, it's quite weird as we can fetch a list of mostly anything we want ( marketing campaigns, single sends, contact lists, transactional templates, etc ) but not a list of templates for the new "Marketing" feature ( via the Email Designs ).

#### Steps to Reproduce

1. Go inside Email Designs
2. Create a random design
3. Look for the template's ID -- no way to get it ... unless you tap "Edit" and copy it from the within the address URL at the top.
4. Then .. look within the API, search for anything related to that kind of templates, how can you fetch them, or maybe remove ? Nothing.

It feels like a half baked solution, being able to do everything via the API ( that you'd do via the UI ), but not within the new email designs feature.

I've spent an hour with "R. Deonte" in the API Support live chat, trying to explain him how you can create a template before creating single sends ( in my case ). 

As an use case, my client has a dashboard, in which I want to be able to fetch the designs he creates ( just like you would fetch the transactional templates ), then use those design IDs, to create new "single sends" ( given they accept a parameter called template, which is optional ).

Point for him using the dashboard is that I'm creating the contact lists on the fly, directly from our end, pushing them to Sendgrid's API, get a new ID for them, alongside the template's ID that he chose, we go on and create a new single send.

Regards!

**Comment by thinkingserious** [comment]
Hello @edi,

I believe [this documentation](https://sendgrid.api-docs.io/v3.0/designs-api) (see **GET List Designs** header) is what you may be looking for.

With best regards,

Elmer
