### ISSUE TITLE
sendgrid php api not sending emails

### ISSUE THREAD

**Issue by Yoshik18** [sendgrid/sendgrid-php#894]
Im working on an application where I've created a user registration system. So when a user registers an email is sent to the account, Im using an email class to send email. Before using sendgrid I was using phpmailer and it was working perfectly fine in this format, but it doesn't works with sendgrid.

This is the code
```
<?php

class email {
   public function sendEmail($name, $email, $url, $type, $subject){
    require '../../vendor/autoload.php'; // If you're using Composer (recommended)
    $email = new \SendGrid\Mail\Mail(); 
    $email->setFrom("mymail@gmail.com", "Example User");
    $email->setSubject($subject);
    $email->addTo($email, $name);
    if($type === "CONFIRM"){
      $email->addContent(
        'text/html', 'CONFIRM MESSAGE'
    );

    } else if($type === "FORGOT"){
      $email->addContent(
        'text/html', 'FORGOT MESSAGE'
      );
}
    $apiKey = 'api_key';
    $sendgrid = new \SendGrid($apiKey);
    try {
        $response = $sendgrid->send($email);
        print $response->statusCode() . "\n";
        print_r($response->headers());
        print $response->body() . "\n";
    } catch (Exception $e) {
        echo 'Caught exception: '. $e->getMessage() ."\n";
    }
   }
}
?>
```
So when i use this code without if and else for '$type', it works completely fine, but does not works with if else and the page loading never ends!

Some help would be appreciated!!

**Comment by childish-sambino** [comment]
Could you post the request body for an email that's not working?

https://github.com/sendgrid/sendgrid-php/blob/master/TROUBLESHOOTING.md#viewing-the-request-body
