### ISSUE TITLE
SG Support says the devs are in here... Where are you devs!!

### ISSUE THREAD

**Issue by Robin-the-Frog** [sendgrid/sendgrid-php#902]
#### Issue Summary

Customer support from SG is, quite frankly, shocking and seriously lacking!!

**Comment by childish-sambino** [comment]
@Robin-the-Frog We're taking steps to improve response times here. Is there an issue in particular that you need help with?

**Comment by Robin-the-Frog** [comment]
Just the fact that my comment was made on 3rd November and it's taken until 17th March for a response says it all!
I had posted about 3 or 4 different questions around that time, none got any response for months. So long, that I worked them all out for myself by pure trial and error, and in fact I even helped some other posters with their questions from what I'd learnt myself...

**Comment by childish-sambino** [comment]
Understood. Appreciate your help in assisting others in the community. As I said, we're taking steps to improve response times while at the same time working through the large backlog of open issues (over 1k in total). It's a slow process, but we're committed to it.
