### ISSUE TITLE
Duplicate emails when sending once

### ISSUE THREAD

**Issue by crimson-med** [sendgrid/sendgrid-php#904]
#### Issue Summary

A few of the emails we are sending get sent twice. They even arrive at the exact same time. However we don't have any loops and there is no reasons for the email to be sent twice.

#### Steps to Reproduce

```php
public function sendMail($model) {
    $email = new \SendGrid\Mail\Mail(); 
    $email->setFrom(Yii::$app->params['supportEmail']);
    $email->setSubject("Feedback");
    $email->addTo($model->email);
    $email->addContent("redacted");
    $sendgrid = new \SendGrid(getenv(Yii::$app->params['apiKey']));
    try {
        $response = $sendgrid->send($email);
        print $response->statusCode() . "\n";
        print_r($response->headers());
        print $response->body() . "\n";
    } catch (Exception $e) {
        echo 'Caught exception: '. $e->getMessage() ."\n";
    }
}
$feedbacks = Feedback::find()->all();
foreach ($feedbacks as $feedback) {
    sendMail($feedback->giver);
}
```

This executes well and we get the emails sent to the clients with no issues however sometimes the clients receive two emails with exact same timestamp.

#### References:

This duplicate issue is not the first and it seems to be a problem that has been going on for a while. Would their be any solutions?

#538
#589
#870

#### Technical details:

* sendgrid-php Version: composer 7.3.0
* PHP Version: 7.1

#### Screeenshot: 

Two emails received by client at 20:58. I have redacted the information that is sensitive.

![duplicate](https://image.noelshack.com/fichiers/2019/45/5/1573191134-image.png)

**Comment by thinkingserious** [comment]
Hello @crimson-med,

Thanks for taking the time to report this and for your patience.

Using similar code, I can not duplicate the behavior you are describing. 

I would suggest adding some logging within the `foreach` to be sure that `sendMail` is not being called on the same email twice. I'm thinking that perhaps your `Feedback::find()->all()` may be returning duplicates.

When you say "A few of the emails we are sending get sent twice.", could you please provide further detail? (e.g. X emails out of X sent). 

Finally, I would suggest that you collect the headers of the two emails that were duplicated and provide them to our support team at https://support.sendgrid.com for further investigation.

Thanks!

With best regards,

Elmer

**Comment by xlcrr** [comment]
We had the same problem but found a solution [here](https://github.com/sendgrid/sendgrid-php/issues/538#issuecomment-376740281) when adding personalisation, the original "addTo" was redundant
