### ISSUE TITLE
Filtering messages stats using unique_args query

### ISSUE THREAD

**Issue by NikoNar** [sendgrid/sendgrid-php#909]
Hi,
I'm tying to filter my messages stats using unique_args query like example bellow:
(unique_args["email_type"]="welcome").
It's returns me right stats, but I can't find a way how to make a query with more then one unique args for get exact stats like  example bellow: (unique_args["email_type"]="welcome") && (unique_args["user_id"]="123").

I'm using php GuzzleHttp Client, and my code looks this way.
```
$response = $client->request('GET', $endpoint, ['query' => [
            'limit' => 99,
            'start_date' => '2019-11-15',
            'offset' => 0,
            'query' => '(unique_args["email_type"]="welcome")',
        ]]);
```
What I want to do is add one more unique_args, like this
```
$response = $client->request('GET', $endpoint, ['query' => [
            'limit' => 99,
            'start_date' => '2019-11-15',
            'offset' => 0,
            'query' => '(unique_args["email_type"]="welcome" && unique_args["user_id"]="123")',
        ]]);
```
but this not works for me. Any recommendation?

**Comment by childish-sambino** [comment]
Try using the keyword `AND`. Reference: https://sendgrid.com/docs/for-developers/sending-email/getting-started-email-activity-api/#keywords-and-operator-reference
