### ISSUE TITLE
Contact ID after insertion

### ISSUE THREAD

**Issue by xeux** [sendgrid/sendgrid-php#912]
#### Issue Summary

What would be the best way to get Contact ID after insertion? In my case Contact is in my database and I need to update the Sendgrid Contact ID field for further use.

#### Steps to Reproduce

1. Insert Contact using API and PUT. (/contacts)
2. Search for Contact if contains email. (/contacts/search)

What method should be used instead of the previous step 1 and 2.

#### Technical details:

* sendgrid-php Version: master (latest commit: [commit number])
* PHP Version: 7.2 (as of May 17, 2018)

**Comment by childish-sambino** [comment]
The steps you've listed are correct. Adding/updating contacts is an async process so contact IDs are not returned in the response.
