### ISSUE TITLE
401 Missing JSON  Body

### ISSUE THREAD

**Issue by justageek** [sendgrid/sendgrid-php#916]
#### Issue Summary

I have just upgraded my integration code to use the latest 7.x branch of this library.  I am getting the error 401 Missing JSON Body when I try to send my messages, I have confirmed in the library Client::createCurlOptions() that the $encodedBody is non-empty JSON.  Can you help me know where to look for this issue.

#### Technical details:

* sendgrid-php Version: 7.3.0 from packagist.org
* PHP Version: 5.6 (as of May 17, 2018)

**Comment by justageek** [comment]
To follow up, it appears the my json body is not empty in the library code that sets the body for the curl operation.

**Comment by childish-sambino** [comment]
Could you post an example that can be used to recreate the issue?
