### ISSUE TITLE
Sending mail to multiple recipients without them seeing each other using php Note: To address fetched from CSV file

### ISSUE THREAD

**Issue by adhiarunkumar** [sendgrid/sendgrid-php#921]
I need to send the multiple mail from single recipients
**Note**: The "To" address is fetched from CSV file through the local folder
     Please let me help in this situation.
      Thanks.

      require 'vendor/autoload.php'; 
      $API_KEY = "xxxxxxxxxxx";
      if(isset($_POST['submit_mail'])){
        $from_user_name = $_POST['name'];
        $from_user_mail = $_POST['from_addr'];
        $subject = $_POST['subject'];
        $email = new \SendGrid\Mail\Mail(); 
        $email->setFrom($from_user_mail, $from_user_name);
        $email->setSubject($subject);
        $email->addContent("text/plain", "and easy to do anywhere, even with PHP");
        $email->addContent(
        "text/html", "Test"
      );
      $to = $_POST['to_addr'];
      $start_row = 1; //define start row
      $i = 1;
      $the_big_array = [] ;
      if (($handle = fopen("info.csv", "r")) !== FALSE) {
        while (($row = fgetcsv($handle)) !== FALSE) {
            if($i >= $start_row) {
                // print_r($row);
                $the_big_array[] = $row[0];
                for($c=0; $c<count($the_big_array); $c++){
                    $email->addTo($the_big_array[$c], "User");
                    
                }
            }
            
            $i++;
        }
        fclose($handle);
    }

    try {
        $sendgrid = new \SendGrid($API_KEY);
        $response = $sendgrid->send($email);
        print $response->statusCode() . "\n";
        print_r($response->headers());
        print $response->body() . "\n";
    } catch (Exception $e) {
        echo 'Caught exception: '. $e->getMessage() ."\n";
    }

**Comment by kampalex** [comment]
This can be done by using `Personalization`. See method 'helloEmail' in [this example](https://github.com/sendgrid/sendgrid-php/blob/master/examples/helpers/mail/example.php#L37).

But because that example isn't perfect I'll write one below. It also includes some decision points to consider.
```php
use Exception;
use SendGrid;
use SendGrid\Mail\Subject;
use SendGrid\Mail\From;
use SendGrid\Mail\Content;
use SendGrid\Mail\Mail;
use SendGrid\Mail\TypeException;
use SendGrid\Mail\Personalization;
use SendGrid\Mail\To;
use SendGrid\Response;

//  Define API key first (must be a string) - or quit if you don't have the API key for SendGrid
$apiKey = "FooBar";

//  This collection is for email addresses
//  Maybe better to verify entries first
$emailAddresses = ["foobar@bad.user", "happy-user@sendgrid.com"];

//  Verify first if you really have addresses!
if (count($emailAddresses) === 0) {
    die("Nope");
}

//  Create the initial mail to send to every recipient
try {
    $mailFrom = new From("unknown@sendgrid.com");
    $mailSubject = new Subject("This is my subject");
    $mailContent = new Content("text/plain", "My contents are in plain text!");

    //  Create the message
    $mail = new Mail($mailFrom);
    $mail->setSubject($mailSubject);
    $mail->addContent($mailContent);
} catch (TypeException $e) {
    die("Your parameter is failing: " . $e->getMessage());
}

//  Iterate for every recipient
foreach ($emailAddresses as $address) {
    try {
        //  Create new Personalization instance
        $personalization = new Personalization();
        //  Append To recipient
        $personalization->addTo(new To($address));

        //  Append onto Mail
        $mail->addPersonalization($personalization);
    } catch (TypeException $e) {
        //  This address is failing!
        //  (Just ignore this address)
        echo "\nThis address is failing: " . $e->getMessage();
    }
}

//  Not having Personalizations added? Quit
if ($mail->getPersonalizationCount() === 0) {
    die("No recipients for your mail. Sorry");
}

try {
    //  Create SendGrid instance
    $client = new SendGrid($apiKey);

    //  Send the mail and fetch Response
    $response = $client->send($mail);

    //  Not having expected response?
    if (($response instanceof Response) === false) {
        //  Unknown response given
        die("Unclear response");
    }

    //  Review/evaluate response status and body (json formatted)
    echo "Got HTTP " . $response->statusCode() . ":\n" . $response->body();
} catch (Exception $e) {
    die("It failed! " . $e->getMessage());
}
```

**Comment by adhiarunkumar** [comment]
> This can be done by using `Personalization`. See method 'helloEmail' in [this example](https://github.com/sendgrid/sendgrid-php/blob/master/examples/helpers/mail/example.php#L37).
> 
> But because that example isn't perfect I'll write one below. It also includes some decision points to consider.
> 
> ```
> use Exception;
> use SendGrid;
> use SendGrid\Mail\Subject;
> use SendGrid\Mail\From;
> use SendGrid\Mail\Content;
> use SendGrid\Mail\Mail;
> use SendGrid\Mail\TypeException;
> use SendGrid\Mail\Personalization;
> use SendGrid\Mail\To;
> use SendGrid\Response;
> 
> //  Define API key first (must be a string) - or quit if you don't have the API key for SendGrid
> $apiKey = "FooBar";
> 
> //  This collection is for email addresses
> //  Maybe better to verify entries first
> $emailAddresses = ["foobar@bad.user", "happy-user@sendgrid.com"];
> 
> //  Verify first if you really have addresses!
> if (count($emailAddresses) === 0) {
>     die("Nope");
> }
> 
> //  Create the initial mail to send to every recipient
> try {
>     $mailFrom = new From("unknown@sendgrid.com");
>     $mailSubject = new Subject("This is my subject");
>     $mailContent = new Content("text/plain", "My contents are in plain text!");
> 
>     //  Create the message
>     $mail = new Mail($mailFrom);
>     $mail->setSubject($mailSubject);
>     $mail->addContent($mailContent);
> } catch (TypeException $e) {
>     die("Your parameter is failing: " . $e->getMessage());
> }
> 
> //  Iterate for every recipient
> foreach ($emailAddresses as $address) {
>     try {
>         //  Create new Personalization instance
>         $personalization = new Personalization();
>         //  Append To recipient
>         $personalization->addTo(new To($address));
> 
>         //  Append onto Mail
>         $mail->addPersonalization($personalization);
>     } catch (TypeException $e) {
>         //  This address is failing!
>         //  (Just ignore this address)
>         echo "\nThis address is failing: " . $e->getMessage();
>     }
> }
> 
> //  Not having Personalizations added? Quit
> if ($mail->getPersonalizationCount() === 0) {
>     die("No recipients for your mail. Sorry");
> }
> 
> try {
>     //  Create SendGrid instance
>     $client = new SendGrid($apiKey);
> 
>     //  Send the mail and fetch Response
>     $response = $client->send($mail);
> 
>     //  Not having expected response?
>     if (($response instanceof Response) === false) {
>         //  Unknown response given
>         die("Unclear response");
>     }
> 
>     //  Review/evaluate response status and body (json formatted)
>     echo "Got HTTP " . $response->statusCode() . ":\n" . $response->body();
> } catch (Exception $e) {
>     die("It failed! " . $e->getMessage());
> }
> ```

Great Thanks./ It works exactly as per my needs. You saved my days!!!

**Comment by adhiarunkumar** [comment]
Amazing!!!! Thank you. It works exactly as per my needs.
