### ISSUE TITLE
Send email via SendGrid 6.1.0

### ISSUE THREAD

**Issue by RenanSaia** [sendgrid/sendgrid-php#922]
Hi,
I am new to sendgrid v3 API. I am able to send simple email using version 5.6.0, but I am not getting the same result sending a simple email using version 6.1.0. And, for the future, how can I add a CSV file as an attachment on the same e-mail?? Please help me out to resolve my issue.

Thanking you in advance.

**Comment by kampalex** [comment]
Are you aware of breaking changes of [version 6.0.0 release](https://github.com/sendgrid/sendgrid-php/releases/tag/v6.0.0)?

Refer to the USE_CASES.md in your 6.1.0 installation for usage. It also shows how to add an attachment to a Mail - it's the very first example. For CSV, you can use `text/csv` as MIME type.

If it doesn't solve your issue, put the code into a comment so it can be reviewed.
