### ISSUE TITLE
How to call the mail address in dynamic html file?

### ISSUE THREAD

**Issue by adhiarunkumar** [sendgrid/sendgrid-php#923]
I need to include the **mail address** wherever I want in my HTML mail template. Please let me know how to do it? Thanks

    `<?php 
    require 'vendor/autoload.php'; 
    use Exception;
    use SendGrid;
    use SendGrid\Mail\Subject;
    use SendGrid\Mail\From;
    use SendGrid\Mail\Content;
    use SendGrid\Mail\Mail;
    use SendGrid\Mail\TypeException;
    use SendGrid\Mail\Personalization;
    use SendGrid\Mail\To;
    use SendGrid\Response;

    //  Define API key first (must be a string) - or quit if you don't have the API key for SendGrid
     $apiKey = "xxxxxxxx";

    //  This collection is for email addresses
    //  Maybe better to verify entries first
    $text= file_get_contents('design.html');
    $content =  $text;

    $file = 'info.csv';
    $content = file($file);

    $array = array();

    for($i = 0; $i < count($content); $i++) {
        $line = explode(',', $content[$i]);
        for($j = 0; $j < count($line); $j++) {
             $array[$i][$j + 1] = $line[$j];
         }
     }
     $emailAddresses = array_column($array, 1);
     $username = array_column($array, 2);

     //  Verify first if you really have addresses!
     if (count($emailAddresses) === 0) {
        die("Nope");
     }

     //  Create the initial mail to send to every recipient
     try {
         $mailFrom = new From("xxxxxxx);
         $mailSubject = new Subject("This is my subject");
         $mailContent = new Content("text/html", $text);

         //  Create the message
         $mail = new Mail($mailFrom);
         $mail->setSubject($mailSubject);
         $mail->addContent($mailContent);
         } catch (TypeException $e) {
        die("Your parameter is failing: " . $e->getMessage());
     }

     //  Iterate for every recipient
    foreach ($emailAddresses as $address) {
        try {
             //  Create new Personalization instance
             $personalization = new Personalization();
             //  Append To recipient
             $personalization->addTo(new To($address) ,
            [
                "name" => $username,
                "email" => $address
            ]);

             //  Append onto Mail
             $mail->addPersonalization($personalization);
             } catch (TypeException $e) {
             //  This address is failing!
            //  (Just ignore this address)
            echo "\nThis address is failing: " . $e->getMessage();
        }
    }

     //  Not having Personalizations added? Quit
     if ($mail->getPersonalizationCount() === 0) {
         die("No recipients for your mail. Sorry");
     }

     try {
         //  Create SendGrid instance
         $client = new SendGrid($apiKey);

         //  Send the mail and fetch Response
         // $response = $client->send($mail);

         //  Not having expected response?
         if (($response instanceof Response) === false) {
             //  Unknown response given
             die("Unclear response");
         }

         //  Review/evaluate response status and body (json formatted)
         echo "Got HTTP " . $response->statusCode() . ":\n" . $response->body();
        } catch (Exception $e) {
        die("It failed! " . $e->getMessage());
      }
      ?>`

design.html

      `<!DOCTYPE html>
       <html lang="en">
            <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <meta http-equiv="X-UA-Compatible" content="ie=edge">
            <title>Document</title>
            </head>
            <body>
                 <h1>{{email}}</h1>
            </body>
        </html>`

And how I got design in mail

      
![Selection_025](https://user-images.githubusercontent.com/51704182/70770965-806a3c80-1d95-11ea-943d-02729ea2f065.png)

**Comment by kampalex** [comment]
A solution may be adding replacements per `Personalization` entry, do it using substitutions:
```php
$personalization->addSubstitution("%email%", $address);
```
which is the same for
```php
use SendGrid\Mail\Substitution;
[...]
$personalization->addSubstitution(new Substitution("%email%", $address));
```
I'm using `%email%` as needle due to the fact I'm using Twig templates. When using `{{ email }}`, the placeholder will be removed (or replaced by other value) because Twig already renders it. This is unwanted, because SendGrid must replace this placeholder.

**Comment by adhiarunkumar** [comment]
Amazing!!. Thank you. It worked.
