### ISSUE TITLE
Single Send Issue

### ISSUE THREAD

**Issue by AttaurrehmaanBhatti687** [sendgrid/sendgrid-php#925]
I am creating single send from code and it is created. I have create contact list first and then add emails under list and then add list id to single send and run curl the single send is created but going to draft when i click on it on sendgrid dashboard it says unable to retrieve single send. I cannot preview single send which i have create and also cannot edit. Anybody help me?

**Comment by childish-sambino** [comment]
Can you post some sample code that you're running to help recreate issue?
