### ISSUE TITLE
Helper: The to email parameter is required.

### ISSUE THREAD

**Issue by clatteringmarion** [sendgrid/sendgrid-php#927]
#### Issue Summary

Email always return 400 when there's no customization object set. 

#### Steps to Reproduce

1. Use latest release
2. Click on send button (in my script)
3. Viola! Error occurred.

Since i haven't add any customization object in the array, it shouldn't report 
`{"errors":[{"message":"The to email parameter is required.","field":"personalizations.0.to.0.email","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.personalizations.to"}
`
I've tried to remove the personalizations, or hardcode the to address, but still received the error.

The function code is pasted below:
```
public function send($to_address, $subject_raw, $text, $files)
    {
        $from = new From($this->sender, $this->name);
        $subject = $subject_raw;
        $to = new To(null, $to_address);
        $content = new Content('text/html', $text);
        $mail = new Mail($from, $to, $subject, $content);	
		
		$mail->addTo($to);
		$mail->setSubject($subject);
		$mail->addContent($content);
		$content = new Content("text/html", $text);		   
        $mail->addContent($content);
		
        foreach ($files as $file) {
            $attachment = new Attachment();
            $attachment->setContent(base64_encode(file_get_contents($file)));
            $attachment->setType('application/octet-stream');
            $attachment->setFilename(basename($file));
            $attachment->setDisposition('attachment');
            $attachment->setContentId('backup');
            $mail->addAttachment($attachment);
        }
    	
		//$reply_to = new ReplyTo("test@example.com", "Optional Name");
        //$mail->setReplyTo($reply_to);		

		try {
        	$response = $this->sg->client->mail()->send()->post($mail);    
			print $response->statusCode() . "\n"; 
    		print_r($response->headers());
    		print $response->body() . "\n"; // Twilio SendGrid specific errors are found here
		} catch (Exception $e) {
    		echo 'Caught exception: ',  $e->getMessage(), "\n";
		}
    }
```

#### Technical details:

* sendgrid-php Version: master (latest commit: 96ae31d)
* PHP Version: 7.3.13

**Comment by clatteringmarion** [comment]
With Personalization:
```
    public function send($to_address, $subject_raw, $text, $files)
    {
        $from = new From($this->sender, $this->name);
        $subject = $subject_raw;
        $to = new To(null, "test1@example.com");
        $content = new Content('text/html', $text);
        $mail = new Mail($from, $to, $subject, $content);	
		
		$personalization = new Personalization();
        $personalization->addTo($to);
        $mail->addPersonalization($personalization);
		
        foreach ($files as $file) {
            $attachment = new Attachment();
            $attachment->setContent(base64_encode(file_get_contents($file)));
            $attachment->setType('application/octet-stream');
            $attachment->setFilename(basename($file));
            $attachment->setDisposition('attachment');
            $attachment->setContentId('backup');
            $mail->addAttachment($attachment);
        }
    	
		//$reply_to = new ReplyTo("test@example.com", "Optional Name");
        //$mail->setReplyTo($reply_to);		

		try {
        	$response = $this->sg->client->mail()->send()->post($mail);    
			print $response->statusCode() . "\n"; 
    		print_r($response->headers());
    		print $response->body() . "\n"; // Twilio SendGrid specific errors are found here
		} catch (Exception $e) {
    		echo 'Caught exception: ',  $e->getMessage(), "\n";
		}
    }
```
Exactly the same error message:
`
    Send daily mail to user: 1400 Array ( [0] => HTTP/1.1 100 Continue [1] => [2] => HTTP/1.1 400 Bad Request [3] => Server: nginx [4] => Date: Wed, 15 Jan 2020 16:31:07 GMT [5] => Content-Type: application/json [6] => Content-Length: 400 [7] => Connection: keep-alive [8] => Access-Control-Allow-Origin: https://sendgrid.api-docs.io [9] => Access-Control-Allow-Methods: POST [10] => Access-Control-Allow-Headers: Authorization, Content-Type, On-behalf-of, x-sg-elas-acl [11] => Access-Control-Max-Age: 600 [12] => X-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html [13] => [14] => ) {"errors":[{"message":"The to email parameter is required.","field":"personalizations.0.to.0.email","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.personalizations.to"},{"message":"The to email parameter is required.","field":"personalizations.1.to.0.email","help":"http://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/errors.html#message.personalizations.to"}]} 
`

**Comment by kampalex** [comment]
Did you verify the parameter order while constructing the `To` class? This line of code is failing:
`$to = new To(null, "test1@example.com");`

Constructor `EmailAddress` (parent class of `To`) expects an email address as first parameter - which you assigned with `null`, and second one as name.

You don't have to append an extra `Personalization` (second comment) - it's already done by the `Mail` class.

**Comment by clatteringmarion** [comment]
@kampalex  It's indeed working now... Feeling dumb for not trying to flip the position...

Thank you!
