### ISSUE TITLE
send email to list

### ISSUE THREAD

**Issue by MrApe** [sendgrid/sendgrid-php#929]
What is the right way to send emails to a contact list?

The new `marketing` API is restricted to 50 contacts, so manually adding them to a `Mail`-object will not work.

Creating a single send allows addressing a list but does not allow to add dynamic template data.

**Comment by childish-sambino** [comment]
I'm not aware of a contact limit of 50 for marketing campaigns. Does this link help? https://sendgrid.api-docs.io/v3.0/contacts/add-or-update-a-contact

**Comment by childish-sambino** [comment]
Or the standard mail send supports up to 1000 recipients: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html
