### ISSUE TITLE
email api integration error

### ISSUE THREAD

**Issue by VirtualGrinch** [sendgrid/sendgrid-php#932]
### Issue Summary
Hello, I'm trying to make the integration email api following the steps you suggest in your page https://app.sendgrid.com/guide/integrate/langs/php, but the system is giving me an error message.

In the chat service your team asked me to reinstall the libraries so I did it so, but the same result, so they asked me to write here for more help.
The code I used to install the libraries (composer.json file) was:
```
{
    "autoload": {
        "psr-4": {"Acme\\": "src/"}
    },
  "require": {
    "sendgrid/sendgrid": "~7"
  }
}
```

A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, or code examples.

### Steps to Reproduce
1. Install the composer packages related to the project
2. Create the php file as you suggest in the api page integration
3. Test the code in the page

### Code Snippet
```php
`<?php
	require 'vendor/autoload.php';
	$email = new \SendGrid\Mail\Mail(); 
	$email->setFrom("contacto@vivoplay.net", "VIVOplay");
	$email->setSubject("Sending with SendGrid is Fun");
	$email->addTo("william.mazo@gmail.com", "William Mazo");
	$email->addContent("text/plain", "and easy to do anywhere, even with PHP");
	$email->addContent(
		"text/html", "<strong>and easy to do anywhere, even with PHP</strong>"
	);
	$sendgrid = 'Bearer API KEY';
	try {
		$response = $sendgrid->send($email);
		print $response->statusCode() . "\n";
		print_r($response->headers());
		print $response->body() . "\n";
	} catch (Exception $e) {
		echo 'Caught exception: '. $e->getMessage() ."\n";
	}
?>`
```

### Exception/Log
```
[22-Jan-2020 15:11:52 UTC] PHP Fatal error: Uncaught Error: Call to a member function send() on string in /home/vivoplayadmin/public_html/m_mails/send_mail.php:13
```

### Technical details:
* sendgrid-php version: 7 (I guess because of the code "sendgrid/sendgrid": "~7")
* php version: 7.3.7
* Composer version: 1.9.2

**Comment by childish-sambino** [comment]
In your code snippet, you're assigning a string to the `sendgrid` var:
```
$sendgrid = 'Bearer API KEY';
```

Instead, you should be constructing a new `SendGrid` instance and pass it the API key value:
```
$sendgrid = new \SendGrid(getenv('SENDGRID_API_KEY'));
```

**Comment by VirtualGrinch** [comment]
Thank you for your response Childish-sambino, that was my first code test, but that is giving me a _"Permission denied, wrong credentials"_

> 401 Array ( [0] => HTTP/1.1 401 Unauthorized [1] => Server: nginx [2] => Date: Thu, 05 Mar 2020 20:20:35 GMT [3] => Content-Type: application/json [4] => Content-Length: 88 [5] => Connection: keep-alive [6] => Access-Control-Allow-Origin: https://sendgrid.api-docs.io [7] => Access-Control-Allow-Methods: POST [8] => Access-Control-Allow-Headers: Authorization, Content-Type, On-behalf-of, x-sg-elas-acl [9] => Access-Control-Max-Age: 600 [10] => X-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html [11] => [12] => ) {"errors":[{"message":"Permission denied, wrong credentials","field":null,"help":null}]}

Regards

**Comment by childish-sambino** [comment]
Recommend verifying that your API key is properly setup in the env var. Try just logging the value to make sure it's correct:
```
print getenv('SENDGRID_API_KEY');
```

**Comment by VirtualGrinch** [comment]
That gives me the message 

> bash: syntax error near unexpected token `('

The .env file has:
`export SENDGRID_API_KEY='SENDGRID_API_KEY'`

**Comment by VirtualGrinch** [comment]
Yes, the `SENDGRID_API_KEY` have my api key:
`export SENDGRID_API_KEY='_here_my_api_key_'`

I followed the steps that Sendgrid give us in their api integration documentation in their webpage

`echo "export SENDGRID_API_KEY='YOUR_API_KEY'" > sendgrid.env
echo "sendgrid.env" >> .gitignore
source ./sendgrid.env`

I'm runing that on PHP 7.3.13 and Composer 1.9.3

**Comment by childish-sambino** [comment]
Ah, I understand you're bash error now. The command I gave was not for running in the terminal; it's for running in your PHP code. Run this in your PHP code and make sure the output matches your API key. If it doesn't, then there's an issue with your env.
```
print getenv('SENDGRID_API_KEY');
```

**Comment by VirtualGrinch** [comment]
Well, that doesn't give me any result. The env file is on the same location that the php file, in terminal I read the env file and I see the follow:

`export SENDGRID_API_KEY='here_is_my_api_key'`

**Comment by childish-sambino** [comment]
Sourcing the `.env` file only applies to the context you're in. Are you running the PHP app in the same context?

**Comment by VirtualGrinch** [comment]
Yes, all the files are in the same folder

**Comment by childish-sambino** [comment]
It's not about the location of the files; it's about the context. For instance, if you're sourcing the file in one terminal and then launching your app from another, the contexts are different and the env var may not be set.

**Comment by VirtualGrinch** [comment]
Ah, no, I'm sourcing the `.env` in terminal but runing via website
