### ISSUE TITLE
Single send for lists

### ISSUE THREAD

**Issue by soorajop** [sendgrid/sendgrid-php#935]
### Issue Summary
I created the single send from code and it is created. I have added list id to single send and run curl the single send is created but going to draft when i click on it on sendgrid dashboard it says, unable to retrieve single send. 

### Steps to Reproduce
1. Created a list using php and added contacts to the list
2. Added the list id, sender id, and template id in json format and passed that to api in json format
3. api url : https://api.sendgrid.com/v3/marketing/singlesends

### data passed
{
	"name":"Test New",
	"sender_id":"698XXX",
	"status":"scheduled",
	"custom_unsubscribe_url":"https://www.testing.com",
	"filter":{
			   "list_ids":["66adfd57-c8f3-4d48-9788-03b06ef1XXXX"],
                           "send_to_all": false
			},
"send_at": "now",
	"template_id":"fccf3490-832d-4ab4-a7fe-f0ed308XXXX"
}

### Exception/Log
[{"messageType":"error","text":"{\n  \"context\": \"response.400.body\",\n  \"description\": \"Endpoint Response not defined for this content type of application/json.\",\n  \"type\": \"error\"\n}","createdAt":"2020-02-04T06:20:27.342651398Z"},{"messageType":"info","text":"{\n  \"context\": \"response.headers\",\n  \"description\": \"Object has no key 'custom-fields-values'\",\n  \"type\": \"lib\"\n}","createdAt":"2020-02-04T06:20:27.342666422Z"}]

### Technical details:
* sendgrid-php version: v3 api
* php version: 5.6

**Comment by childish-sambino** [comment]
Could you post a code sample that illustrates this issue?
