### ISSUE TITLE
Sender name has extra whitespace symbol

### ISSUE THREAD

**Issue by allok** [sendgrid/sendgrid-php#936]
### Issue Summary
If send email with russian letters in the sender name we have extra whitespace symbol.

### Steps to Reproduce
1. Send email with sender name 'Веселые.Приключения'
2. In the received email we have extra whitespace symbol in the sender name.
<img width="326" alt="Снимок экрана 2020-02-05 в 15 42 57" src="https://user-images.githubusercontent.com/561064/73842832-68131d00-482e-11ea-8ed3-0c42aa7a032b.png">

Below a raw from original source email:
`From: "Веселые.При ключения" <triptest@test.ru>`

### Technical details:
* sendgrid-php version: 7.4.0
* php version: 7.3

**Comment by childish-sambino** [comment]
Just tried this out locally using the Node and PHP libs and not seeing a space in the received email. Could you share sample code that illustrates the issue?

**Comment by allok** [comment]
Send email with sender name  'Веселые.Приключения' and open email on Mac.
I forget to say about the problem is on mac os.

**Comment by childish-sambino** [comment]
Tried this a couple times on my Mac mail app and still not able to recreate. One thing I did notice was that if the sender was in my Mac contacts, that name showed up on the mail and not the name that I sent it with. Just something to check.

**Comment by allok** [comment]
Gime me your email I sent you a mail you will see that it is bug.

**Comment by childish-sambino** [comment]
@allok Should be in my profile.

**Comment by yamelkaya** [comment]
Hi! We have the same issue with sendgrid-csharp

**Comment by allok** [comment]
Hello! Re-open please, the issue still exists

**Comment by childish-sambino** [comment]
As it last stood that I've been unable to recreate this issue, recommend contacting [support](https://support.sendgrid.com/hc/en-us) for investigation.
