### ISSUE TITLE
Change the error message in function [setEmailAddress] of class [EmailAddress]

### ISSUE THREAD

**Issue by BRBProg** [sendgrid/sendgrid-php#942]
### Issue Summary
In using the SendGrid-PHP library, I have a change request in function [setEmailAddress] of class [EmailAddress] (See sendgrid-php\lib\mail\EmailAddress.php file) because when I use a wrong e-mail address I get this error: $emailAddress must be valid and of type string.
It would be better to get the error message with the wrong e-mail address like this: test1@gmail.com must be valid and of type string.

I suggest the following change:
By replacing the error string ['$emailAddress must be valid and of type string.'] with the use of double quotes like this ["$emailAddress must be valid and of type string."] or [$emailAddress . ' must be valid and of type string.'] to allow the variable [$emailAddress] to be replaced by its value.

### Steps to Reproduce
1. Introduce a wrong e-mail address into your code

### Code Snippet
The old code is:
```php
public function setEmailAddress($emailAddress)
{
	if (!(is_string($emailAddress) &&
		filter_var($emailAddress, FILTER_VALIDATE_EMAIL))
	) {
		throw new TypeException(
			'$emailAddress must be valid and of type string.'
		);
	}
	$this->email = $emailAddress;
}
```
it should become:
```php
public function setEmailAddress($emailAddress)
{
	if (!(is_string($emailAddress) &&
		filter_var($emailAddress, FILTER_VALIDATE_EMAIL))
	) {
		throw new TypeException( 'The e-mail address ['
			$emailAddress . '] must be valid and of type string.'
		);
	}
	$this->email = $emailAddress;
}
```

### Exception/Log
With the old code:
```
$emailAddress must be valid and of type string
```

### Technical details:
* sendgrid-php version: last version
* php version: 7.1

**Comment by childish-sambino** [comment]
Fixed by https://github.com/sendgrid/sendgrid-php/pull/841
