### ISSUE TITLE
Get raw request when sending a email

### ISSUE THREAD

**Issue by pritamgb** [sendgrid/sendgrid-php#943]
### Issue Summary
One of the SendGrid support people was requesting me to share with him a raw JSON request when sending an email using SendGrid PHP library. Is there a way to get it?

### Code Snippet
```php
$email = new \SendGrid\Mail\Mail();
$email->setFrom(email id,send name);
$email->setSubject(subject);
$email->addTo(recepients email, recepients name);
$emailBody = view('emails.customerTemplate', $data)->render();
$email->addContent(
	"text/html",
	$emailBody
);
$sendgrid = new \SendGrid(sendgrid subuser api key);
$response = $sendgrid->send($email);
```

### Technical details:
* sendgrid-php version: ~7
* php version: 7.3

**Comment by childish-sambino** [comment]
Troubleshooting guide here: https://github.com/sendgrid/sendgrid-php/blob/master/TROUBLESHOOTING.md#viewing-the-request-body

```
echo json_encode($email, JSON_PRETTY_PRINT)
```
