### ISSUE TITLE
Unsubscribe group API command

### ISSUE THREAD

**Issue by mgrevtech** [sendgrid/sendgrid-php#944]
### Issue Summary
I would like to verify the curl command that I am using to remove multiple email addresses from the Unsubscribe Groups.

### Steps to Reproduce

This is command I used:

```
curl -X "DELETE" "https://api.sendgrid.com/v3/asm/groups/Email News Unsubscribe/suppressions/search" -H "accept-language: application/json" -H "authorization: Bearer SG.JvxARe" -H "cache-control: no-cache" -H "content-type: application/json" -d "@stafflist.json"
```

As per the sendgrid documentation here - https://sendgrid.com/docs/API_Reference/Web_API_v3/Suppression_Management/suppressions.html

Just want to make sure if that is right command to use, especially the group_id parameter. I have replaced "group_id" with the group name "Email News Unsubscribe" (the default & only unsubscribe group in our account). Is that the right way to do it?

### Code Snippet
```
DELETE https://api.sendgrid.com/v3/asm/groups/:group_id/suppressions/:email_address HTTP/1.1
```

**Comment by childish-sambino** [comment]
The command you've provided is not correct.  The `group_id` is not the name of the group; it's the ID of the group. I don't see an API for deleting multiple emails from a suppression group. You'll need to run something like this for each email address to remove:

```
curl -X "DELETE" "https://api.sendgrid.com/v3/asm/groups/{group_id}/suppressions/{email}" -H "authorization: Bearer SG.JvxARe"
```

Use this command to help determine the ID of the group:
```
curl "https://api.sendgrid.com/v3/asm/groups" -H "authorization: Bearer SG.JvxARe"
```

**Comment by mgrevtech** [comment]
Yes, i figured that out by this time. But now the issue is that it actually deletes the Unsubscribe group, when I mention the correct 'group_id' in the command. Which is not what I need.
I am trying to delete a list of emails/recipients from the group, picked up from json file the command is pointing to, as per below.

curl -X "DELETE" "https://api.sendgrid.com/v3/asm/groups/3333" -H "authorization: Bearer SG.JvxARegdTg" -d "@recipientfile.json"

And if I use it with the {email} paramater, the command does not work/does nothing. What am I doing wrong?

**Comment by childish-sambino** [comment]
The delete API does not take a payload so you're example command will delete the group itself. There is not an API to delete multiple emails from the suppression group at once so you'd need to iterate over the emails and call the API for each.

I just tested deleting an email from a group and got back the proper 204 response code. In my case:
```
DELETE https://api.sendgrid.com/v3/asm/groups/14500/suppressions/test1@example.com
```

Please post the command you're using to delete an email from the group for further debugging.
