### ISSUE TITLE
Get Message History

### ISSUE THREAD

**Issue by elysiopires** [sendgrid/sendgrid-php#948]
THIS IS A QUESTION!

### Issue Summary
Hello, I would like to know how can I retrieve the information contained on the Activity dashboard Menu by API. Is it possible?

Basically I would like to store the X-Message-Id on my side and then I would like to have the email activity data from an API endpoint.

I read all the documentation and didn't found a way to get this by a specific message.

Is there a way?

### Code Snippet
```php
# paste code here
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* sendgrid-php version:
* php version:

**Comment by childish-sambino** [comment]
Does querying the activity API by `msg_id` satisfy your use case? https://sendgrid.com/docs/for-developers/sending-email/getting-started-email-activity-api/#query-reference

**Comment by medbak** [comment]
I want to use the message_id but it wasn't clear for me, I am using this format :+1: 
"https://api.sendgrid.com/v3/messages/?msg_id=123456"

It is ok like that or not ? ( I am using the api key in header and I can retrieve template details) 
I just didn't know how to call api with message id and what i must put in the header ? 

Thanks,

**Comment by childish-sambino** [comment]
Better like this which will match messages where the message ID starts with `12345`:
```
https://api.sendgrid.com/v3/messages?query=msg_id LIKE "12345%"
```

**Comment by elysiopires** [comment]
Hello Guys!

Thank you for your responses... I really appreciate...

I have 2 questions:
1) How can I get my api key permission to run messages endpoint?

2) Is this message ID the same of X-Message-Id param that you receive when
you send a message using v3/mail/send endpoint? If not, how can I get this
message Id?


Have a great day and stay safe!

Best regards,
Elysio Pires

**Comment by childish-sambino** [comment]
1. Firstly, in order to gain access to the Email Activity Feed API, you must purchase [additional email activity history](https://app.sendgrid.com/settings/billing/addons/email_activity).

2. Yes, it's the same, but longer. The `X-Message-Id` returned header value is the prefix so I included an example that searches by prefix.

**Comment by elysiopires** [comment]
Awesome Childish!

Thx so much.

Have a great day!
