### ISSUE TITLE
resource not found after addAttachment

### ISSUE THREAD

**Issue by faiwiz** [sendgrid/sendgrid-php#953]
Email was sent from same code, now I am getting "resource not found" error from sandgrid api after adding attachment code,"sendgrid/sendgrid": "~6.0"

	$from = new SendGrid\Email($data['from_name'], $data['from']);
	$subject = $data['subject'];
	$to = new SendGrid\Email("user","user.name@domain.name");

	$content = new SendGrid\Content("text/html", $data['view']);

	$mail = new SendGrid\Mail($from, $subject, $to, $content);

	$apiKey = getenv('SENDGRID_API_KEY');
	$sg = new \SendGrid($apiKey);

	$response = $sg->client->mail();

	//Attachment code start
	if(isset($data['attach_files']) && is_array($data['attach_files']) && count($data['attach_files'])>=1){
		foreach($data['attach_files'] as $attach_files_i=>$attach_files_path){
			$filename = basename($attach_files_path);
			$file_encoded = base64_encode(file_get_contents($attach_files_path));
	        //echo '<pre>--$filename';print_r($filename);echo '</pre>'; //working fine
	        //echo '<pre>--$file_encoded';print_r($file_encoded);echo '</pre>'; //working fine
	        //echo '<pre>--mime_content_type($attach_files_path)';print_r(mime_content_type($attach_files_path));echo '</pre>'; //working fine
			$attachment = new SendGrid\Attachment();
			$attachment->setType(mime_content_type($attach_files_path));
			$attachment->setContent($file_encoded);
			$attachment->setDisposition("attachment");
			$attachment->setFilename($filename);
			$response->addAttachment($attachment);
		}
	}
	//Attachment code end

	$response = $response->send()->post($mail);

	echo "<pre>"; print_r($response); die;
	
	
Response from sendgrid

	SendGrid\Response Object
	(
		[statusCode:protected] => 404
		[body:protected] => {"errors":[{"field":null,"message":"resource not found"}]}
		[headers:protected] => Array
			(
				[0] => HTTP/1.1 404 NOT FOUND
				[1] => Server: nginx
				[2] => Date: Wed, 15 Apr 2020 18:43:55 GMT
				[3] => Content-Type: application/json
				[4] => Content-Length: 58
				[5] => Connection: keep-alive
				[6] => 
				[7] => 
			)

	)

I have double check is file exist =TRUE, is email sent without attachment code = EMAIL SENT

**Comment by faiwiz** [comment]
Replace 
$file_encoded = base64_encode(file_get_contents($attach_files_path));
with 
$file_encoded = file_get_contents($attach_files_path);

base64_encoded cause the problem, it works with other versions.

**Comment by childish-sambino** [comment]
v6 is bit old, but I just tried on v7 without issue. Are you able to upgrade?
