### ISSUE TITLE
Getting Error - Permission denied, wrong credentials 

### ISSUE THREAD

**Issue by upendraalwafaa** [sendgrid/sendgrid-php#954]
Hii im getting this error when i try to send email.
can u help me ??
![Capture1](https://user-images.githubusercontent.com/32842147/79637020-d4928c80-818c-11ea-8a7e-b68e544392af.PNG)

**Comment by childish-sambino** [comment]
Recommend double-checking your API key is correct. Try logging the value to make sure it's being loaded properly. Should start with `SG.`
