### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by s-ohnishi** [sendgrid/sendgrid-php#955]
### Issue Summary
I am using PhpStorm and the warnings are very annoying when using this library.
What is presented as input assistance is different from the one shown in the sample.
I think the cause is that the thing shown in PHPDoc is incorrect.

### Steps to Reproduce
1. This is the first step
2. This is the second step
3. Further steps, etc.
no steps

### Code Snippet
```php
// see: https://github.com/sendgrid/sendgrid-php#user-content-general-v3-web-api-usage-with-fluent-interface
    $response = $sg->client->suppression()->bounces()->get();

// vender/sendgrid/php-http-client/lib/Client.php
/**
 *
 * Class Client
 * @package SendGrid
 * @version 3.9.5
...
 * Supressions
 * @method Client suppressions()
 * @method Client global()

maybe
suppressions() --> suppression()
```

### Exception/Log
```
# paste exception/log here
```

### Technical details:
* sendgrid-php version: 3.9.5
* php version: 7.3.14

**Comment by childish-sambino** [comment]
Not really anything we can/should do here. The name of the endpoint is plural: [suppressions](https://sendgrid.com/docs/API_Reference/Web_API_v3/Suppression_Management/suppressions.html). Should be able to add it to your IDE's dictionary.

**Comment by childish-sambino** [comment]
Ah, looks like both are valid:
* https://sendgrid.com/docs/API_Reference/Web_API_v3/bounces.html
* https://sendgrid.com/docs/API_Reference/Web_API_v3/Suppression_Management/suppressions.html

I'll look into adding the other.

**Comment by childish-sambino** [comment]
Just upgraded to 75.0 on my Windows machine and not seeing any issues. Could you open an issue here with more details about your setup? https://github.com/sendgrid/docs

**Comment by s-ohnishi** [comment]
I have tried. Currently it seems to be displayed without problems.
I don't know what happened, but the tab displaying the faulty page was still there, so I saved it and tried a diff.

There seems to be a difference between the two files SendGrid.htm and SendGrid_files\a.
However, I was able to view the saved file locally without any problems.

I don't know if it will be helpful, but I will attach some files.
The file a is not clear in the diff, so rename it OK_a.txt, NG_a.txt.

[diff.txt](https://github.com/sendgrid/sendgrid-php/files/4515941/diff.txt)
[NG_a.txt](https://github.com/sendgrid/sendgrid-php/files/4515966/NG_a.txt)
[OK_a.txt](https://github.com/sendgrid/sendgrid-php/files/4515969/OK_a.txt)

**Comment by childish-sambino** [comment]
Best to add the details to a new issue here:  https://github.com/sendgrid/docs

**Comment by s-ohnishi** [comment]
sorry.
I don't reproduce the situation right now, just provide information.
