### ISSUE TITLE
addCc and addBcc not working while sending a mail

### ISSUE THREAD

**Issue by papnoisanjeev** [sendgrid/sendgrid-php#956]
### Issue Summary
We want to use addCc and addBcc but mail not going in these case but addTo working perfectly and receiving mails.
so how we can make addCc and addBcc working.

### Code Snippet

use SendGrid;
use SendGrid\Mail\Mail as SendgridMail;

$email = new SendGridMail(); 
$sendgrid = new SendGrid($this->container->getParameter('sendgrid_api'));

$email->addCc($ccEmail);
$email->addBcc($bccEmail);
$email->setSubject("subject");
$email->addContent("text/html",  $emailTemplate);

$sendgrid->send($email);

**Comment by childish-sambino** [comment]
What version of this library are you using? Can you post the request body? https://github.com/sendgrid/sendgrid-php/blob/master/TROUBLESHOOTING.md#viewing-the-request-body

This may be resolved by https://github.com/sendgrid/sendgrid-php/pull/952

**Comment by judyanndixon** [comment]
I could not get bcc to work today using 9.9.0.  I did however get cc working.
