### ISSUE TITLE
Please can you explain how am i going to setup the environment variable for php.

### ISSUE THREAD

**Issue by ike-njoku** [sendgrid/sendgrid-php#957]
Please can you explain how am i going to setup the environment variable for php.

What does these lines mean;

Update your development environment with your SENDGRID_API_KEY. Run the following in your shell:

echo "export SENDGRID_API_KEY='YOUR_API_KEY'" > sendgrid.env
echo "sendgrid.env" >> .gitignore
source ./sendgrid.env

_Originally posted by @akoladesam in https://github.com/sendgrid/sendgrid-php/issues/338#issuecomment-483755502_

**Comment by ike-njoku** [comment]
i am experiencing this same issue. I tried runnig this code on a Windows OS. Please help?

**Comment by childish-sambino** [comment]
### Windows
Temporarily set the environment variable (accessible only during the current CLI session):
```
set SENDGRID_API_KEY=YOUR_API_KEY
```

Or permanently set the environment variable (accessible in all subsequent CLI sessions):
```
setx SENDGRID_API_KEY "YOUR_API_KEY"
```

**Comment by kampalex** [comment]
Please discard the C# examples in the initial post - these don't work for PHP.

Best way is to use an environmental variables file loader like [php dotenv](https://github.com/vlucas/phpdotenv).

You can also assign an environmental variable in PHP by `putenv`.
```php
$sgApiKey = 'Key goes here';
putenv("SENDGRID_API_KEY=" . $sgApiKey);
```
