### ISSUE TITLE
Space in Subject above 50 characters

### ISSUE THREAD

**Issue by drimlike** [sendgrid/sendgrid-php#962]
### Issue Summary
Hello, we are experiencing a weird issue where the API is adding space to our subject as soon as the subject is over 50 characters.

### Steps to Reproduce
1. Run the code below
2. Remove characters from the subject and try again, until the space is not visible anymore

### Code Snippet
```php
<?php
include get_template_directory() .'/assets/sendgrid-7.3.0/vendor/autoload.php';
    $mail=new \SendGrid\Mail\Mail();    
    $mail->setFrom(new \SendGrid\Mail\From('contact@mydomain.com', "Citylive"));
    $htmlContent = new \SendGrid\Mail\HtmlContent(
        '<strong>I\'m testing it!</strong>'
    );
        $mail->addContent($htmlContent);
   

    $recipients = array('test@test.com');
    $recp_cnt = count($recipients);
    $personalization_array = array();

    for ($i = 0; $i < $recp_cnt; $i++) {
        $personalization[$i] = new \SendGrid\Mail\Personalization();
        $personalization[$i]->addTo(new \SendGrid\Mail\To($recipients[$i]));
        $personalization[$i]->setSubject(
            new \SendGrid\Mail\Subject('Votre sélection personnalisée Citylive du 12 Mai 2020')
        );
        $personalization_array[$i] = $personalization[$i];
    }

    $mail->addPersonalization($personalization_array);

    $apiKey = 'YOUR_KEY';
    $sg = new \SendGrid($apiKey);

    $response = $sg->client->mail()->send()->post($mail);
```

I did a few test by removing characters see when the space doesn't show anymore:

![image](https://user-images.githubusercontent.com/4152261/81724779-d8a88600-947c-11ea-969b-22d4cde542af.png)

And as you can see under 51 characters the subject is fine, over a weird space is added in the word **Mai**

### Technical details:
* sendgrid-php version: 7.3.0
* php version: 7.2.21

**Comment by kampalex** [comment]
You have an issue in your code - it's reported immediately after copy-pasting:
`addPersonalization` expects a `Personalization` instance, not an array.

Use next lines instead for adding Personalizations to `$mail`:
```
$recipients = ['test@test.com'];

foreach ($recipients as $recipient) {
    $personalization = new \SendGrid\Mail\Personalization();
    $personalization->addTo(new \SendGrid\Mail\To($recipient));
    $personalization->setSubject(
        new \SendGrid\Mail\Subject('Votre sélection personnalisée Citylive du 12 Mai 2020')
    );
    $mail->addPersonalization($personalization);
}
```

If you still have the weird space, the issue may be in the Sendgrid API itself. Look inside the message source code for `Subject: ` header and post it as comment.
I see you're using web based Gmail. To find the source: while viewing the message, click on the '3 dot' icon right (labeled 'More') and click 'Show original'. Source is shown below the evaluated headers.

**Comment by drimlike** [comment]
@kampalex ,

I just tried your code and I am getting : 

`"message":"Invalid type. Expected: array, given: object.","field":"personalizations",`

My code works as the email are sent properly, only the subject is getting that weird spacing. I am using this on some other projects and I just noticed that this spacing happens too. It looks like it was a bug in 2017 [here](https://github.com/sendgrid/sendgrid-python/issues/302) it's either the bug has resurfaced or not completely fixed. 

@thinkingserious do you have any feedback on this by any chance? 

Thanks,

**Comment by kampalex** [comment]
Please update SendGrid library due to implemented fixes of `Personalization` (see release notes of 7.4.0).

Executing your source code - including my fix applied - on version 7.4.2:
`Message-ID: [...]
Subject: Votre =?UTF-8?Q?s=C3=A9lection_personnalis=C3=A9e?= Citylive du 12
 Mai 2020
X-SG-EID: [...]`
Length of line: 76 chars + \r\n

Subject text is just 'cut' (like using PHP `wordwrap` method) and doesn't have tailing 'continue on next line' ending chars (like `?=`), as found in different message I tested containing simular chars.
This really is a SendGrid API thing.

**Comment by drimlike** [comment]
@kampalex ,

Upgraded to 7.4.6 and used your code, the subject is still having that weird space added. Does it mean there is nothing I can do as it looks like it's from the API itself? 
It also looks like it comes from the fact that I have special characters in the subject. As soon as I remove 1 `é` from the subject the space is not there anymore. 

Do you have any other idea I could try? 

Thanks,

**Comment by childish-sambino** [comment]
Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at https://support.sendgrid.com.
