### ISSUE TITLE
Composer autoloader unnecessarily includes files

### ISSUE THREAD

**Issue by SamMousa** [sendgrid/sendgrid-php#963]
### Issue Summary
Most of the files are autoloaded by composer via PSR-4 autoloading, however 3 classes that live in the global namespace are not:
- `lib/BaseInterface.php`
- `lib/SendGrid.php`
- `lib/TwilioEmail.php`

These are added to the composer autoloader via the `files` directive (https://getcomposer.org/doc/04-schema.md#autoload), causing them to be included on every request.

Composer has a different directive `classmap` that can scan the files for class definitions to allow them to be lazily included instead.

### Steps to Reproduce
1. Install the package via composer
2. Check the generated `autoload_files.php` that includes 3 files that are loaded on every request.

### Proposed solution
Change the `files` directive to the `classmap` directive should fix this issue without any work required on the library consumers.

**Comment by kampalex** [comment]
Good find, Sam.
(Introduced by #951)

**Comment by childish-sambino** [comment]
Fine by me.
