### ISSUE TITLE
Class BaseInterface in global namespace

### ISSUE THREAD

**Issue by kampalex** [sendgrid/sendgrid-php#964]
Issue #963 triggers my attention due to the existence of class `BaseInterface`. It's introduced in #951, version 7.5.0.

For local repository use, this is understandable. But using such a class name in a global namespace is highly risky. It may collide in other projects if this name is used/referred.

I suggest a more detailed class name which covers the meaning of the interface/client, like `BaseSendgridApiClientInterface`. Optionally, store it in different namespace.

**Comment by childish-sambino** [comment]
Works for me. I'll work on a fix.
