### ISSUE TITLE
using smtp not work, using curl not work. no error. and no response.

### ISSUE THREAD

**Issue by erlangp** [sendgrid/sendgrid-php#970]
using smtp not work, using curl not work. no error. and no response.

**Comment by erlangp** [comment]
disappointed

**Comment by erlangp** [comment]
the curl return empty response. how to solve this problem?

**Comment by kampalex** [comment]
We definitely want to help you, but we really need more details to give you a good answer.

- Do you use this library? If so, which version?
- Can you post your (anonymized) code sample?
- What PHP version do you use? (I expect you've verified extension `curl` was loaded)

Can you test your code locally using the PHP development `php.ini` configuration?

**Comment by childish-sambino** [comment]
Thanks @kampalex 👍   (I forgot to hit the comment button when I added the labels 🤦 )

**Comment by talovicnedim** [comment]
The same thing happens to me. Status code I get is 202 (Accepted).

Here is my CURL:

```
curl --request POST \
  --url https://api.sendgrid.com/v3/mail/send \
  --header 'authorization: Bearer [TOKEN]' \
  --header 'content-type: application/json' \
  --data '{"personalizations": [{"to": [{"email": "john.doe@example.net"}]}],"from": {"email": "john.doe@example.net},"subject": "Hello World!","content": [{"type": "text/plain", "value": "Hello World!"}]}'
```

Sendgrid returns nothing, but I always receive an email.

Note that I have downloaded CA Root Certificate from https://curl.haxx.se/docs/caextract.html and implemented it in the loaded php.ini file.

**Comment by childish-sambino** [comment]
@talovicnedim Please open a new issue if you've having a problem. But it sounds like you're getting back the expected 202 response code.

**Comment by talovicnedim** [comment]
@childish-sambino 
Ok, thanks! I will open a new issue. Yes, I'm getting the expected 202 status code. The body is empty and I'd like to store a message ID in my database.

**Comment by kampalex** [comment]
> The body is empty and I'd like to store a message ID in my database.

According to [Response Example](https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html#-Response-Example), the message identifier `X-Message-Id` is in the response **headers**, not the response body.
