### ISSUE TITLE
Docs/Examples: reduce excessive comment headings

### ISSUE THREAD

**Issue by kampalex** [sendgrid/sendgrid-php#981]
While working on docs improvement/suggestion, a lot of examples do start the next way:
```php
<?php
require 'vendor/autoload.php'; // If you're using Composer (recommended)
// Comment out the above line if not using Composer
// require("<PATH TO>/sendgrid-php.php");
// If not using Composer, uncomment the above line and
// download sendgrid-php.zip from the latest release here,
// replacing <PATH TO> with the path to the sendgrid-php.php file,
// which is included in the download:
// https://github.com/sendgrid/sendgrid-php/releases
```
Almost a quarter of my screen is eaten up by these comment headings. For example, see [USE_CASES](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#send-an-email-to-multiple-recipients).

It's hard to create a single line comment which covers all those instructions, but I gave it a try:
`Uncomment next line if you're not using a dependency loader (such as Composer)`
I'm open for improvement!

**Which file to load?**
The `sendgrid-php.php` will load the Composer `vendor/autoload.php`, which is also present in the releases ZIP file. I think this is the suggested starting point due to the included dependency `sendgrid/http-php-client`. If you decide to create a Composerless package (packed `sendgrid-php` and `http-php-client` together using combined loader), you don't have to change all the file references of `vendor/autoload.php`.

**For docs/md files:**
Change comments to minimums to make clear this library doesn't run without loader, but this is also applicable for all other packages. Therefore, leaving it out completely is also an option.
```php
<?php
// Uncomment next line if you're not using a dependency loader (such as Composer)
// require_once '<PATH TO>/sendgrid-php.php';
```

**For example files:**
They can be called directly (like [this file](https://github.com/sendgrid/sendgrid-php/blob/master/lib/mail/README.md) suggests), we can use next scenario:
```php
<?php
// If you're using Composer or have load the dependencies earlier, comment line below
require_once __DIR__ . '/../../../sendgrid-php.php';
```

**Comment by eshanholtz** [comment]
This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by kampalex** [comment]
If you would like to give a suggestion which text should be used in both scenarios, I can create a PR. 
(My English level isn't that worse - hopefully not _Dunglish_ yet - but I prefer a _perfect_ text.)

I was already thinking/working on improvement, but to prevent excessive/long review I think splitting the PR is better.

**Comment by childish-sambino** [comment]
+1 to smaller PRs. Recommend submitting the PR and we can adjust from there.
