### ISSUE TITLE
getting authorization key for subuser

### ISSUE THREAD

**Issue by curious-webs** [sendgrid/sendgrid-php#982]
Hi I have successfully created the subuser using api. Now when creating list or adding contact to subbsuer account, it ask for api key. Requirement is I dont want subbuser to create api key and then enter into application. Is there any possible way to login user automatically using bearer authentication.

**Comment by thinkingserious** [comment]
Hello @curious-webs,

Can you please try setting the `On-Behalf-Of` header [like so](https://github.com/sendgrid/sendgrid-php/blob/master/test/unit/SendGridTest.php#L45)? Thanks!

With best regards,

Elmer

**Comment by curious-webs** [comment]
> 
> 
> Hello @curious-webs,
> 
> Can you please try setting the `On-Behalf-Of` header [like so](https://github.com/sendgrid/sendgrid-php/blob/master/test/unit/SendGridTest.php#L45)? Thanks!
> 
> With best regards,
> 
> Elmer

Thanks, It Worked
