### ISSUE TITLE
Set from email incorrect error message

### ISSUE THREAD

**Issue by oleddzo** [sendgrid/sendgrid-php#987]
Hello, I've found an issue, when I set incorrect email to FROM get an error  '$email must be valid and of type string.', but $email in the string should be a value that I try to set. I figured out why it happened, in this function SendGrid\Mail\Mail::setFrom you should replace single-quotes to double-quotes in the error message. Thank you.

**Comment by childish-sambino** [comment]
Nice find. Working on a fix ...

**Comment by kampalex** [comment]
Similar to issue #841.
Fixing the `$email in the string should be a value that I try to set` may be simple, but this only works if an invalid string is provided. Also mentioned [during review](https://github.com/sendgrid/sendgrid-php/pull/841#discussion_r300320454).

I think a more durable solution is needed like already contributed #762.

**Comment by childish-sambino** [comment]
@kampalex Good call. Slowly working through old PRs but Octobers get crazy. I'll probably fix up that PR to resolve this issue.
