### ISSUE TITLE
Custom unsubscribe link

### ISSUE THREAD

**Issue by NgaiWeiLun** [sendgrid/sendgrid-php#991]
How to use custom unsubscribe link for campaign. Then the global unsubscribe will increase after users click the custom unsubscribe link from the email?

**Comment by eshanholtz** [comment]
I'm not sure I fully understand the second part of your question, but there is some documentation for [adding a custom unsubscribe link for your emails](https://sendgrid.com/docs/ui/sending-email/create-and-manage-unsubscribe-groups/#using-a-custom-unsubscribe-link). Is this what you were looking for?
