### ISSUE TITLE
Different attachments for different emails in bulk sending

### ISSUE THREAD

**Issue by BooleanType** [sendgrid/sendgrid-php#994]
### Issue Summary
Related to issue #352, but my question concerns exactly sendgrid-php.

I have 2 options for defining multiple recipients during bulk sending:

1. As described in example here [here](https://github.com/sendgrid/sendgrid-php/blob/d3cb8ee054446deaa91f6904a41be9b0ab1d8481/USE_CASES.md#send-multiple-emails-to-multiple-recipients), ie using `$tos = [new \SendGrid\Mail\To(...), new \SendGrid\Mail\To(...), ...]`.

2. With `Personalization` object (create new personalization for every recipient)

**My question is**: is it possible to send _different_ attachments to _multiple_ recipients in _one_ bulk request? Or should I do standalone request for every recipient? I'm asking, 'cause I haven't found any example that allows me to do that.

### Technical details:
* sendgrid-php version: 7.8.1
* php version: 7.4.1

**Comment by eshanholtz** [comment]
This functionality is not currently supported by the API, and is not a change that can be made in the library. An internal ticket has been filed against the relevant product team (reference ID CL-3265).
