### ISSUE TITLE
Clear addresses from Mail (Personalization) object

### ISSUE THREAD

**Issue by a61829437** [sendgrid/sendgrid-php#998]
I have a scenario where I would like to re-use the a Mail object but change the subject and to address. 

I only see methods for adding to already set emails. I do not see any methods for replacing or clearing the already set email addresses. 

It would be nice if there was a way to modify the addressees so that a Mail object could be reused.

**Comment by thinkingserious** [comment]
Hello @a61829437,

If you are comfortable, could you please share your use case? Perhaps there is a work around.

Also, this issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

Thanks!

With best regards,

Elmer

**Comment by a61829437** [comment]
In my case I need to send the same email with same content and same attachment to multiple users but with a modified subject per user. 

I was wanting to create a Mail object I could re-use with set content and attachment. Then loop a list of users and set unique subject per user and send to that user.

**Comment by childish-sambino** [comment]
Are you using dynamic templates for this? And can you share sample code of what you're trying to accomplish? There may be a solution already.

**Comment by a61829437** [comment]
Not using templates. 

Something along the lines of 
```
$mail = new \SendGrid\Mail\Mail();
$mail->setFrom(...)
$mail->addContent(...)
$mail->addAttachment(...)
...
...
...
foreach( $users as $user )
{
    //  clear previous "to" email in mail object...

    $mail->addTo( $user->email )
    $mail->setSubject( $this->getSubject( $user ) );

    $sendgrid = new \SendGrid(...api key...);
    $sendgrid->send( $this->mail )
}
```

**Comment by a61829437** [comment]
Thanks. 

This way puts all the to email addresses in the to field for each recipient though. I am needing to send individual email to a user without them knowing about the other users or seeing other email addresses it was sent to. I don't  think I clarified that part. 

Users receive an individual email (unaware other users it was sent to) with personalized subject, but the content and attachments are the same for all emails.

**Comment by childish-sambino** [comment]
Yup, I understood the use case; just the code didn't do exactly what I expected (I don't really like that way it's set up and will probably fix it all later).  This should work though:
```
$mail = new \SendGrid\Mail\Mail();
$mail->setFrom(...)
$mail->addContent(...)
$mail->addAttachment(...)
...
...
...
foreach( $users as $user )
{
    // $mail->addTo(new To($user->email, null, null, $this->getSubject($user)), null, null, null, new Personalization());
    // or easier to read:
    $personalization = new Personalization();
    $personalization->addTo($user->email);
    $personalization->setSubject($this->getSubject($user));
    $mail->addPersonalization($personalization);
}

$sendgrid = new \SendGrid(...api key...);
$sendgrid->send($this->mail)
```

**Comment by a61829437** [comment]
Thanks, that works. The first one ``` $mail->addTo( $user->email ....``` still had all recipients in the to field of the email. But the second way with a To object worked: 
```
foreach( $users as $user )
{	
    $to = new To( $user->email );
    $personalization = new Personalization();
    $personalization->addTo( $to );
    $mail->addPersonalization( $personalization );   
}

$sendgrid->send( $mail )
```
I didn't read the API documentation fully before using this library so missed part on personalizations... 

I think this seems like a better solution than my thought of clearing the to addresses from the Mail object. 

Maybe it would work to just add an example of this to the use cases https://github.com/sendgrid/sendgrid-php/blob/main/USE_CASES.md ?

**Comment by childish-sambino** [comment]
After reviewing the code this appears to really be a bug in that 'to' addresses with subjects are not placed in separate personalizations. The example linked above would work but only when the 'tos' had substitutions as well.

I've submitted #1001 to fix this.
