### ISSUE TITLE
SDK not able to send dynamic template email while responding message id

### ISSUE THREAD

**Issue by najm-allshorestaffing** [sendgrid/sendgrid-php#999]
### Issue Summary
I am trying to send the dynamic template that I have already created and template id is embeded to code, code seems working and responding the success message id but querying the report of that message id reveals the to_email is not set and status not_delivered, I have debug multiple time and added multiple Tos but result is same, success message id means the to_email is set.
### Steps to Reproduce
1. This is the first step ( execute following code)
```
        $oEmail = new Mail();
        $oEmail->setFrom(getenv("NOTIFICATION_FROM_EMAIL"), "Your Agent Services Support");
        $oEmail->addTo($sEmailAddress, $sName);
        $oEmail->addTo("myemail@gmail.com", "Najm GM");
        $oEmail->setSubject($sSubject);
        $oEmail->setTemplateId($sTemplateId);
        $oB2 = $oEmail->getPersonalizations();
         $oB2[0]->setHasDynamicTemplate(true);
         $oB2[0]->setSubject(new Subject($sSubject));
         $oB2[0]->addTo(new To("mythirdemail@gmail.com","Najm Again"));
        $oEmail->addDynamicTemplateDatas([
            'name'     => 'Some stuff',
            'entity_name' => 'Data here'
          ]);
        $oSendgrid = new SendGrid(getenv('SENDGRID_API_KEY'));
        try {
            $response = $oSendgrid->send($oEmail);
            $aHeaders = $response->headers();
              print $response->statusCode() . "\n";
              print_r($aHeaders);
              print $response->body() . "\n";
        } catch (Exception $e) {
            $sMessage = 'Caught exception: '. $e->getMessage() ."\n";
            debug($e);
        }
```
2. This is the second step (API response following)

> 202
> Array
> (
>     [0] => HTTP/1.1 202 Accepted
>     [1] => Server: nginx
>     [2] => Date: Tue, 18 Aug 2020 15:57:00 GMT
>     [3] => Content-Length: 0
>     [4] => Connection: keep-alive
>     [5] => X-Message-Id: Co3qJ7QoQyeRcIWeFGVIRw
>     [6] => Access-Control-Allow-Origin: https://sendgrid.api-docs.io
>     [7] => Access-Control-Allow-Methods: POST
>     [8] => Access-Control-Allow-Headers: Authorization, Content-Type, On-behalf-of, x-sg-elas-acl
>     [9] => Access-Control-Max-Age: 600
>     [10] => X-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html
>     [11] => 
>     [12] => 
> )

3. Further steps, etc. (Report API shows following result against the Message ID)

> stdClass Object
> (
>     [messages] => Array
>         (
>             [0] => stdClass Object
>                 (
>                     [from_email] => agentadmin@youragentservices.com
>                     [msg_id] => Co3qJ7QoQyeRcIWeFGVIRw.filterdrecv-p3mdw1-7fdf8bccc5-5v96p-20-5F3BFA4C-CD
>                     [subject] => Template loc available
>                     [to_email] => 
>                     [status] => not_delivered
>                     [opens_count] => 0
>                     [clicks_count] => 0
>                     [last_event_time] => 2020-08-18T15:57:00Z
>                 )
> 
>         )
> 
> )

### Code Snippet
```php
        $oEmail = new Mail();
        $oEmail->setFrom(getenv("NOTIFICATION_FROM_EMAIL"), "Your Agent Services Support");
        $oEmail->addTo($sEmailAddress, $sName);
        $oEmail->addTo("myemail@gmail.com", "Najm GM");
        $oEmail->setSubject($sSubject);
        $oEmail->setTemplateId($sTemplateId);
        $oB2 = $oEmail->getPersonalizations();
         $oB2[0]->setHasDynamicTemplate(true);
         $oB2[0]->setSubject(new Subject($sSubject));
         $oB2[0]->addTo(new To("mythirdemail@gmail.com","Najm Again"));
        $oEmail->addDynamicTemplateDatas([
            'name'     => 'Some stuff',
            'entity_name' => 'Data here'
          ]);
        $oSendgrid = new SendGrid(getenv('SENDGRID_API_KEY'));
        try {
            $response = $oSendgrid->send($oEmail);
            $aHeaders = $response->headers();
              print $response->statusCode() . "\n";
              print_r($aHeaders);
              print $response->body() . "\n";
        } catch (Exception $e) {
            $sMessage = 'Caught exception: '. $e->getMessage() ."\n";
            debug($e);
        }
```

### Exception/Log
```
> 202
> Array
> (
>     [0] => HTTP/1.1 202 Accepted
>     [1] => Server: nginx
>     [2] => Date: Tue, 18 Aug 2020 15:57:00 GMT
>     [3] => Content-Length: 0
>     [4] => Connection: keep-alive
>     [5] => X-Message-Id: Co3qJ7QoQyeRcIWeFGVIRw
>     [6] => Access-Control-Allow-Origin: https://sendgrid.api-docs.io
>     [7] => Access-Control-Allow-Methods: POST
>     [8] => Access-Control-Allow-Headers: Authorization, Content-Type, On-behalf-of, x-sg-elas-acl
>     [9] => Access-Control-Max-Age: 600
>     [10] => X-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html
>     [11] => 
>     [12] => 
> )

response of API status query
> stdClass Object
> (
>     [messages] => Array
>         (
>             [0] => stdClass Object
>                 (
>                     [from_email] => agentadmin@youragentservices.com
>                     [msg_id] => Co3qJ7QoQyeRcIWeFGVIRw.filterdrecv-p3mdw1-7fdf8bccc5-5v96p-20-5F3BFA4C-CD
>                     [subject] => Template loc available
>                     [to_email] => 
>                     [status] => not_delivered
>                     [opens_count] => 0
>                     [clicks_count] => 0
>                     [last_event_time] => 2020-08-18T15:57:00Z
>                 )
> 
>         )
> 
> )
```

### Technical details:
* sendgrid-php version: ~7
* php version: 7.1.8

**Comment by childish-sambino** [comment]
Could you post the request body here? That would make it easier to see if the payload is proper.

https://github.com/sendgrid/sendgrid-php/blob/main/TROUBLESHOOTING.md#viewing-the-request-body

**Comment by eshanholtz** [comment]
Closing due to extended inactivity.

**Comment by ValeSauer** [comment]
Perhaps same issue as https://github.com/sendgrid/sendgrid-php/issues/1008
